### ISSUE TITLE
示例有bug

### ISSUE THREAD

**Issue by liuyanchen1994** [antvis/L7#1]
http://antv.alipay.com/zh-cn/l7/1.x/demo/gallery/taxi.html
![image](https://user-images.githubusercontent.com/19524048/48891342-0e674280-ee76-11e8-88bc-98880462e54e.png)

**Comment by lzxue** [comment]
我这边测试没有报错，是偶发性的，还是你那边一直报这个错误看不了？

**Comment by liuyanchen1994** [comment]
突然就好了，前几天还是一直是这个错，好奇怪
