### ISSUE TITLE
点亮城市的例子中，如果替换为自己的geojson，由于坐标z值没有做特别处理，动画效果只是闪烁，不会出现有拖尾的效果

### ISSUE THREAD

**Issue by loverto** [antvis/L7#10]

**Comment by lzxue** [comment]
示例中的流动线，是特殊数据专门处理的所以效果比较好，L7是通用的可视化库，正在简化这个功能，传入一个路径数据就可以实现动画效果

**Comment by loverto** [comment]
这个功能啥时候上线啊

**Comment by lzxue** [comment]
> 这个功能啥时候上线啊
现在效果见这个文档，动画效果我们会继续优化
https://www.yuque.com/mo-college/beginner-tutorial/xy6hne
