### ISSUE TITLE
【bug】demo 中的航向图存在内存泄漏

### ISSUE THREAD

**Issue by AsakuraC** [antvis/L7#1002]
### demo 地址
https://l7.antv.vision/zh/examples/gallery/animate#plane_animate

### 设备
mac OS 12.2.1、M1 Max

**Comment by AsakuraC** [comment]
<img width="332" alt="image" src="https://user-images.githubusercontent.com/18549833/157845716-2ff0fbdb-6e12-47ae-a202-003e5cd12f57.png">

是这里导致的

**Comment by 2912401452** [comment]
收到，会尽快排查

**Comment by 2912401452** [comment]
先不要使用后处理
