### ISSUE TITLE
希望LineLayer可以增加一个增量更新数据的API

### ISSUE THREAD

**Issue by snowinszu** [antvis/L7#1003]
希望LineLayer可以增加一个增量更新数据的API，目前有一个常见的使用场景：通过Websocket源源不断的获取新的经纬度信息并追加到地球上，然而目前的 setData() 方法需要传递一个完整的数组并且会触发重新渲染，导致地球在自转的时候卡顿。

**Comment by 2912401452** [comment]
已经在计划中

**Comment by snowinszu** [comment]
期待！

**Comment by snowinszu** [comment]
请问增量更新什么时候增加，目前遇到卡顿问题，每次追加新数据都会导致3D地球卡一下，影响用户体验。

**Comment by 2912401452** [comment]
https://l7.antv.vision/zh/docs/api/base/#updatemodeldatadata-iattrubuteandelements
https://l7.antv.vision/zh/examples/gallery/animate/#timeline
可以使用 updateModelData 方法
