### ISSUE TITLE
使用geojson绘制3d地图，如何绘制行政区划边界？

### ISSUE THREAD

**Issue by brave1126** [antvis/L7#1006]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

使用geojson+PolygonLayer绘制3d地图：
<img width="639" alt="image" src="https://user-images.githubusercontent.com/34409806/158515782-dbb42f1f-55c0-4ba5-825f-de65b8e15e12.png">
现在想给地图绘制行政区划边界，尝试使用LineLayer，size设置线的高度，存在两个高度无法匹配的问题。
<img width="477" alt="image" src="https://user-images.githubusercontent.com/34409806/158515927-0190d14d-63c3-406d-8898-5c52de67b64f.png">
请问应该如何解决？

**Comment by lzxue** [comment]
高度不匹配应该是角度的问题吧

**Comment by brave1126** [comment]
项目需要有一个角度
