### ISSUE TITLE
关于L7离线加载mbtiles 格式的地图

### ISSUE THREAD

**Issue by zy135516** [antvis/L7#1008]
官方文档中关于离线化使用mapBox的介绍，给出了一个示例，请问如何使用 mbtiles 格式的地图瓦片渲染地图，而不请求mapBox的地址。因为是内网使用。

const scene = new Scene({
  id: 'map',
  map: new Mapbox({
    style: {
        "version": 8,
          "name": "blank",
          "sprite": "https://lzxue.github.io/font-glyphs/sprite/sprite",
          "glyphs": "https://gw.alipayobjects.com/os/antvdemo/assets/mapbox/glyphs/{fontstack}/{range}.pbf",
           "sources": {},
           "layers": [
             {
               id: 'background',
               type: 'background',
               paint: {
                 'background-color': 'white',
               },
             },
           ]
         },
    center: [ 103.83735604457024, 1.360253881403068 ],
    pitch: 4.00000000000001,
    zoom: 10.210275860702593,
    rotation: 19.313180925794313,
    token:'xxxx'
  })
});

**Comment by lzxue** [comment]
跟使用mapbox 绘制地图一样可以在使用自己的数据配置地图样式。

**Comment by zy135516** [comment]
@lzxue 感谢，已解决
