### ISSUE TITLE
Windows 下开发项目问题

### ISSUE THREAD

**Issue by xiaoiver** [antvis/L7#101]
需要在 `CONTRIBUTING.md` 中补充 Windows 环境下开发项目的内容。

1. 由于使用了 Yarn workspace，首先需要安装 Yarn：https://yarnpkg.com/en/docs/install#windows-stable
2. `yarn install` 安装依赖，完成 workspace 链接
3. [测试方案](https://github.com/antvis/L7/blob/master/dev-docs/%E8%87%AA%E5%8A%A8%E5%8C%96%E6%B5%8B%E8%AF%95%E6%96%B9%E6%A1%88.md)依赖 [headless-gl](https://github.com/stackgl/headless-gl#windows)，因此需要 `node-gyp` 编译本地依赖，[这一步](https://github.com/nodejs/node-gyp#on-windows)是 Windows 下出现问题最多的。
  a. 首先以管理员身份启动 PowerShell

<img width="408" alt="屏幕快照 2019-11-28 下午3 59 13" src="https://user-images.githubusercontent.com/3608471/69788332-3b70d280-11f9-11ea-839d-7da4553ea1f1.png">

  b. 运行 `npm install --global --production windows-build-tools`，安装 Microsoft's windows-build-tools 。这一步会安装 Python 2.7

<img width="529" alt="屏幕快照 2019-11-28 下午4 49 47" src="https://user-images.githubusercontent.com/3608471/69791299-2bf48800-11ff-11ea-85d3-dc6dcba968e5.png">

  c. [参考](https://github.com/imagemin/imagemin-pngquant/issues/46#issuecomment-515808859)，需要下载 Visual C++ Build Tools 并安装。Win7 以下安装 [2013](https://www.microsoft.com/en-us/download/details.aspx?id=40760)，Win10 及以上安装 [2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159)
  d. 重启

**Comment by xiaoiver** [comment]
`yarn install` 过程中出现如下问题：
<img width="605" alt="屏幕快照 2019-11-28 下午3 50 10" src="https://user-images.githubusercontent.com/3608471/69788375-53e0ed00-11f9-11ea-9cfa-0d7e00a5fac2.png">

解决方法是：
  1. 以管理员身份启动 PowerShell
<img width="408" alt="屏幕快照 2019-11-28 下午3 59 13" src="https://user-images.githubusercontent.com/3608471/69788332-3b70d280-11f9-11ea-839d-7da4553ea1f1.png">

  2. 运行 `npm install --global --production windows-build-tools`
  3. 重新安装依赖 `yarn install`

**Comment by xiaoiver** [comment]
安装 Visual C++ Build Tools 时可能出现如下问题：
<img width="457" alt="屏幕快照 2019-11-29 上午11 33 22" src="https://user-images.githubusercontent.com/3608471/69841978-6e1fd700-129c-11ea-8e62-bc76e2669b1e.png">

需要先下载并安装 [.NET 4.5.1](https://www.microsoft.com/en-us/download/details.aspx?id=40779)

**Comment by lijingyu1538** [comment]
有没有 macos 的环境配置呢

**Comment by guoliangli123** [comment]
yarn install 的过程就失败了，提示sharp安装失败。
![image](https://user-images.githubusercontent.com/12670391/79707690-e6407500-82ef-11ea-854e-08e8c4938579.png)

**Comment by yeastone** [comment]
Mac 怎么装有教程吗？ QAQ

**Comment by Binks123** [comment]
根据[贡献文档](https://github.com/Binks123/L7/blob/master/.github/CONTRIBUTING.md#windows-%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE)指引,在使用`npm install --global --production windows-build-tools`命令时，出现如下报错，排查了很久未能找到解决方法😭，请问如何解决
![image](https://github.com/antvis/L7/assets/103343025/19503b4c-71d5-4f1f-9236-533ac04bdab1)

**Comment by zheyi420** [comment]
> 根据[贡献文档](https://github.com/Binks123/L7/blob/master/.github/CONTRIBUTING.md#windows-%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE)指引,在使用`npm install --global --production windows-build-tools`命令时，出现如下报错，排查了很久未能找到解决方法😭，请问如何解决 ![image](https://user-images.githubusercontent.com/103343025/268948535-19503b4c-71d5-4f1f-9236-533ac04bdab1.png)

作者说新的 Node for Windows 包含了要用来构建的工具了。
我没有下载 windows-build-tools，更新 Node 版本，`yarn test` 和 `yarn coveralls` 都可以成功运行通过的，

我的配置 node v16.16.0

> Please note that the official [Node.js for Windows installer](https://nodejs.org/en/download/) can now automatically install the required tools.


参考 https://github.com/felixrieseberg/windows-build-tools#readme

**Comment by code-maker-code** [comment]
> > 根据[贡献文档](https://github.com/Binks123/L7/blob/master/.github/CONTRIBUTING.md#windows-%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE)指引,在使用`npm install --global --production windows-build-tools`命令时，出现如下报错，排查了很久未能找到解决方法😭，请问如何解决 ![image](https://user-images.githubusercontent.com/103343025/268948535-19503b4c-71d5-4f1f-9236-533ac04bdab1.png)
> 
> 作者说新的 Node for Windows 包含了要用来构建的工具了。 我没有下载 windows-build-tools，更新 Node 版本，`yarn test` 和 `yarn coveralls` 都可以成功运行通过的，
> 
> 我的配置 node v16.16.0
> 
> > Please note that the official [Node.js for Windows installer](https://nodejs.org/en/download/) can now automatically install the required tools.
> 
> 参考 https://github.com/felixrieseberg/windows-build-tools#readme

我在管理员权限下运行
`npm install --global windows-build-tools`
安装的是2.7版本的python，而现在需要的python版本是>=3.6.0
![image](https://github.com/antvis/L7/assets/73650835/a0ef92ec-37e0-40cc-98cc-8f3166506463)

**Comment by code-maker-code** [comment]
配置：Windows11系统下 node v16.16.0版本（用nvm安装，未尝试更高版本）
首先安装3.6.0版本以上的python，找出python安装路径，如`C:\Users\42297\anaconda3\python.exe`
在L7项目安装路径terminal下运行 `npm config set python "C:\Users\42297\anaconda3\python.exe"`
然后运行`yarn install`即可

**Comment by lzxue** [comment]
> 配置：Windows11系统下 node v16.16.0版本（用nvm安装，未尝试更高版本） 首先安装3.6.0版本以上的python，找出python安装路径，如`C:\Users\42297\anaconda3\python.exe` 在L7项目安装路径terminal下运行 `npm config set python "C:\Users\42297\anaconda3\python.exe"` 然后运行`yarn install`即可

能否写个完整的版的 Window 开发环境按照教程？

**Comment by code-maker-code** [comment]
> > 配置：Windows11系统下 node v16.16.0版本（用nvm安装，未尝试更高版本） 首先安装3.6.0版本以上的python，找出python安装路径，如`C:\Users\42297\anaconda3\python.exe` 在L7项目安装路径terminal下运行 `npm config set python "C:\Users\42297\anaconda3\python.exe"` 然后运行`yarn install`即可
> 
> 能否写个完整的版的 Window 开发环境按照教程？

可以，我是直接修改.github\CONTRIBUTING.md和.github\CONTRIBUTING_ENGLISH.md这两个文档里[Windows 环境配置](https://github.com/antvis/L7/blob/master/.github/CONTRIBUTING.md#windows-%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE)这部分然后提pr吗

**Comment by lzxue** [comment]
> > > 配置：Windows11系统下 node v16.16.0版本（用nvm安装，未尝试更高版本） 首先安装3.6.0版本以上的python，找出python安装路径，如`C:\Users\42297\anaconda3\python.exe` 在L7项目安装路径terminal下运行 `npm config set python "C:\Users\42297\anaconda3\python.exe"` 然后运行`yarn install`即可
> > 
> > 
> > 能否写个完整的版的 Window 开发环境按照教程？
> 
> 可以，我是直接修改.github\CONTRIBUTING.md和.github\CONTRIBUTING_ENGLISH.md这两个文档里[Windows 环境配置](https://github.com/antvis/L7/blob/master/.github/CONTRIBUTING.md#windows-%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE)这部分然后提pr吗

可以的
