### ISSUE TITLE
L7 中使用 GaodeMapV2 点漂移 

### ISSUE THREAD

**Issue by zhouyinchi** [antvis/L7#1012]
* **L7 Version**: 2.7.20
* **Platform**: Window 10
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

底图用GaodeMapV2的情况下， L7 的热力图Heatmap 以及 PointLayer，缩放到一定级别，点会来回跳动
![image](https://user-images.githubusercontent.com/38196296/159216197-c91799be-e0b7-48f7-846d-c0ccd7047543.png)
![微信图片_20220321144922](https://user-images.githubusercontent.com/38196296/159216445-dfd1a1c8-ed90-41f8-8069-92da715db4be.png)

**Comment by 2912401452** [comment]
没有发现你说的情况，可以提供一下在线的 demo 吗？

**Comment by zhouyinchi** [comment]
> 没有发现你说的情况，可以提供一下在线的 demo 吗？

似乎是电脑的问题，我换了一个电脑，就没有这个问题了呢

**Comment by 2912401452** [comment]
请问出问题的是什么电脑环境呢？
