### ISSUE TITLE
mapbox加载地图会出现经纬度偏差

### ISSUE THREAD

**Issue by zy135516** [antvis/L7#1029]
使用mapbox记载地图，按照官方demo （ https://antv-l7.gitee.io/zh/examples/gallery/animate#animate_path ） 
会出现经纬度偏差问题，而官方使用的是高德并不会出现此问题，请问有什么方式可以修改偏差吗

**Comment by lzxue** [comment]
偏移坐标系的问题，需要进行坐标转换 https://github.com/wandergis/coordtransform
