### ISSUE TITLE
amap创建的polygon无法叠加在polygonLayer上面

### ISSUE THREAD

**Issue by fullonce** [antvis/L7#1031]
无法让 amap创建的polygon，置于 polygonLayer上面，怎么设置zIndex值都没用（无论怎么设置zindex值，polygonLayer总是在amap创建的polygon上层）
）

**Comment by lzxue** [comment]
L7 只支持高德地图当底图使用，所以高德绘制的图层会在L7的下层，建议使用L7绘制
