### ISSUE TITLE
高德地图 V2 的实例似乎不能正常销毁

### ISSUE THREAD

**Issue by fanck0605** [antvis/L7#1034]
* **L7 Version**: 2.8.18

* **Platform**: l7-react

* **Mini Showcase(like screenshots)**:

  反复点击 show 按钮，即可复现
  ![image](https://user-images.githubusercontent.com/28819315/161294251-d170977d-000b-4779-a2df-dcb048479b79.png)

* **CodePen Link**:
  https://codesandbox.io/s/dazzling-frog-e6ubkc?file=/index.tsx

使用 l7-react 的 AMapSenceV2 时，在组件卸载后，高德地图 V2 的实例似乎不能被正常卸载。

l7-react 在[清除 Effect ](https://github.com/antvis/L7-react/blob/f7da92ee92b46755190d7e4ab6ca0c7022026fdf/src/component/MapScene/AMapSceneV2.tsx#L26)时，使用 了 `sence.destroy()` , 所以应该不是 **l7-react** 的问题。

主要是因为调用 `sence.destroy()` 后不能正常销毁 `GaodeMap` 实例导致的。

**Comment by fanck0605** [comment]
看了一下内存，确实泄漏了，确实没被销毁
![image](https://user-images.githubusercontent.com/28819315/161296987-1f082838-9ebd-4f16-be1c-065eb7e6557f.png)

**Comment by 2912401452** [comment]
感谢反馈问题！
目前问题正在修复，关于 L7 部分导致的 webgl 实例未正常销毁已经修复完成，会在 L7 新版本发布。
目前高德地图 2.0 的地图底图本身存在 webgl 实例未销毁的问题，已经反馈官方，请等高德官方修复！
发布新版本后 高德地图 1.x、Mapbox、Map 等其他地图可以正常使用

**Comment by 2912401452** [comment]
关于高德修复这边也会关注的，有进展会同步

**Comment by 2912401452** [comment]
目前高德地图 2.0 版本本身存在内存泄漏，会在新的版本修复，到时候 L7 也会及时更新，也会在这里同步

**Comment by fanck0605** [comment]
新版本已经修复
