### ISSUE TITLE
scene.setZoomAndCenter 和 scene.setZoom 的实际缩放效果不一致

### ISSUE THREAD

**Issue by ChenLittleBlack** [antvis/L7#1035]
scene.setZoomAndCenter(11, [lng, lat]) 和 scene.setZoom(11) 实际效果的缩放级别是不一样的，setZoomAndCenter总是要缩放得少一些。
![image](https://user-images.githubusercontent.com/38807067/161357773-001d47bf-7c27-4cd4-9982-ef5320044a3c.png)
![image](https://user-images.githubusercontent.com/38807067/161357777-cea9879f-45cf-4d58-898b-bff6eceecf6f.png)

**Comment by 2912401452** [comment]
会在 v2.8.22 版本修复
