### ISSUE TITLE
antv/l7如何实现中国地图的七大地理分区，并在分区上面显示分区名字和数据

### ISSUE THREAD

**Issue by SomethingInterstring** [antvis/L7#1036]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

效果图：
![企业微信截图_16487295967435](https://user-images.githubusercontent.com/102840115/161360884-d34e0e73-24fc-4c00-8e88-d248066219b2.png)

**Comment by lzxue** [comment]
实现这个主要是需要对省份数据处理一下，多个省份合成大区，数据处理可以使用turf  https://psilocine.github.io/turfjs-docs-Zh-CN/transformation/#union.
或者在 在线工具收到合成 http://datav.aliyun.com/portal/school/atlas/area_generator#3.78/111.038775/31.084790
