### ISSUE TITLE
是否支持矢量瓦片渲染？

### ISSUE THREAD

**Issue by Yuki-Zhao** [antvis/L7#1037]
用哪个图层可以渲染矢量瓦片吗？

**Comment by lzxue** [comment]
目前 L7 自身还不支持，不够预计今年上半年可以支持，如果目前需要使用可以使用mapbox vector 图层，离线使用需要自己提供瓦片服务

**Comment by Yuki-Zhao** [comment]
好的，谢谢啦。预期是否会支持多种坐标系的矢量瓦片图层？

**Comment by 2912401452** [comment]
在 v2.9.x 版本已经支持点、线、面、文字的矢量瓦片渲染
https://l7.antv.vision/zh/docs/api/tile/tile_layer
