### ISSUE TITLE
PointLayer setData报错

### ISSUE THREAD

**Issue by Yuki-Zhao** [antvis/L7#1040]
https://codesandbox.io/s/serene-fermi-j9jb80?file=/index.js

想更新点图层上的数据，通过setData方法，但是控制台报错。如果用source方法。不报错但是也不会更新

**Comment by lzxue** [comment]
初始化没有调用source 方法，可以设置为数据 
 .source({
    type: "FeatureCollection",
    features:[]
  })

@2912401452  setData 方法可以升级一下支持这样的写法
