### ISSUE TITLE
将来会支持微信小程序嘛

### ISSUE THREAD

**Issue by XiaoGongxs** [antvis/L7#1049]
![Snipaste_2022-04-11_16-44-47](https://user-images.githubusercontent.com/84717874/162700499-deb00949-0492-441e-885c-223bd6d2d0e9.png)
我安装L7-MINI的时候使用微信小程序点击构建NPM的时候出现了这个错误，想问一下是因为不支持微信小程序造成的，还是说我安装构建方法错误造成的问题，如果是因为不支持微信小程序将来有机会支持微信小程序嘛

**Comment by lzxue** [comment]
不支持微信小程序，目前只支付宝的，微信用H5
