### ISSUE TITLE
MarkerLayer管理的Marker标注add后没有显示

### ISSUE THREAD

**Issue by ChenLittleBlack** [antvis/L7#1053]
#### 1. 问题：
- [ ] 问题1：MarkerLayer有没有更新Marker的方法？我先调用MarkerLayer.clear再调用MarkerLayer.addMarker是否是当前L7版本下正确的使用方式？
- [ ] 问题2：多次addMarker后addMarkerLayer，地图上无法展示除第一次addMarkerLayer以外的其他数据点，必须要放大地图后才会正常显示

#### 2. 相关组件版本：
```json
"@antv/l7": "2.8.24",
"@antv/l7-district": "2.3.12",
"@antv/l7-maps": "2.8.24"
```

#### 3. 示例代码：
[示例代码](https://codesandbox.io/s/cranky-goldberg-4h6qmg?file=/index.js)

**Comment by 2912401452** [comment]
L7 新版本已经修复 v2.8.29
