### ISSUE TITLE
首次渲染PointLayer的source为空时，然后再使用setData去更新数据，会导致point点变得很奇怪

### ISSUE THREAD

**Issue by ChenLittleBlack** [antvis/L7#1054]
* **L7 Version**: 2.8.24
* **Platform**: pc chrome browser，version 99.0.4844.51
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/38807067/163307074-ce5bcd5f-fb76-4a3e-8628-8daa3d633811.png)
* **codesandbox Link**: https://codesandbox.io/s/naughty-alex-wzn365?file=/index.js

**Comment by 2912401452** [comment]
收到

**Comment by 2912401452** [comment]
https://codesandbox.io/s/beautiful-davinci-rcfvbe
在初始化的时候可以指定 blend 为 normal
