### ISSUE TITLE
使用 markerLayer聚合marker点时，是否提供有单个marker的点击事件

### ISSUE THREAD

**Issue by zy135516** [antvis/L7#1055]
现在有这种的需求：
1.使用markerLayer聚合marker点，目前是否支持单个marker的点击事件，文档中并未找到说明，只有scene.addMarker(marker)才有事件。
2.使用markerLayer聚合marker点，能否提供单个marker的更新方法（比如更新element或 extData）

**Comment by zy135516** [comment]
> 可以获取到 marker 的 dom 后单独绑定

感谢，是的，已经通过这个方法实现事件绑定和dom修改，但是这种实现方式在dom修改的时候随着缩放会一直来回替换，需要自己优化，建议提供类似功能，而且此功能是比较常用的功能

**Comment by 2912401452** [comment]
好的，感谢反馈，后面会对 Marker/MarkerLayer 进行优化
