### ISSUE TITLE
面图层在zoom13前后会发生偏移

### ISSUE THREAD

**Issue by fullonce** [antvis/L7#1063]
官方例子https://l7.antv.vision/zh/examples/geometry/geometry#plane 便有这个问题 所有polygon layer都存在该问题，在缩放地图（zoom 13）前后图形会发生偏移，想知道这是新bug吗 当前新版本使用会有问题，旧版本是否也存在该问题

**Comment by fullonce** [comment]
线图层也同样存在该问题 ，例子https://l7.antv.vision/zh/examples/line/path#road_light 中

![image](https://user-images.githubusercontent.com/39945052/163955619-61990909-98b1-4c69-86a6-66de29a8d345.png)
![image](https://user-images.githubusercontent.com/39945052/163955672-6570103b-359b-4112-a92d-318894fb555f.png)
可以两图前后对比，地图只是稍微缩放了一点，就产生了便宜

**Comment by 2912401452** [comment]
在测试的时候没有出现你说的情况，请问是在什么环境出现的问题呢？

**Comment by fullonce** [comment]
> 在测试的时候没有出现你说的情况，请问是在什么环境出现的问题呢？

用的是mac电脑 谷歌浏览器，官网的例子就会出现这个问题 而且是百分百复现

**Comment by fullonce** [comment]
> 在测试的时候没有出现你说的情况，请问是在什么环境出现的问题呢？

![image](https://user-images.githubusercontent.com/39945052/165016923-5f1e7b50-3f37-4b81-ad99-c71c20da4901.png)

**Comment by lvisei** [comment]
fixed https://github.com/antvis/L7/pull/2416
