### ISSUE TITLE
CanvasLayer的CanvaModel 调用 clearModels() 报错

### ISSUE THREAD

**Issue by BeDay** [antvis/L7#1073]
![image](https://user-images.githubusercontent.com/9448445/164681586-d90b4134-a294-49da-805d-62f2167a8f9c.png)
![image](https://user-images.githubusercontent.com/9448445/164681639-0b14b20c-6568-498b-b571-4254e967a98a.png)
![image](https://user-images.githubusercontent.com/9448445/164681716-e3a8006e-8b5c-4a5f-ace3-8ff18a891250.png)

**Comment by 2912401452** [comment]
收到
