### ISSUE TITLE
I7/component的库中lodash与项目中的lodash冲突，导致运行失败

### ISSUE THREAD

**Issue by lkxing** [antvis/L7#1085]
问题原因：I7/component库中使用了lodash/merge的方法，但是package.json中没有添加lodash的依赖，项目中使用的lodash的版本为3.几，导致运行失败。

修改方法：建议在package.json中添加lodash的依赖
<img width="960" alt="wecom-temp-a3df39cf9eaa7dfd2a28322ee443a94a" src="https://user-images.githubusercontent.com/43607327/165489335-69dcfdfe-110f-41c9-87dd-dca078c1969a.png">

**Comment by lzxue** [comment]
项目可以先统一锁定一下lodash 依赖，我们会新升级一个版本
