### ISSUE TITLE
CanvasLayer 调用hide() 缩放地图会再次显示，L7plot flow.getScene().addLayer(CanvasLayer) 后调用hide() 报错

### ISSUE THREAD

**Issue by BeDay** [antvis/L7#1090]
![image](https://user-images.githubusercontent.com/9448445/165712910-7701d46c-e1e1-4f13-a4d1-4b6377f0df64.png)
l7plot Flow 添加 CanvasLayer 调用 hide() 报错 this.layerModel is undefined
```
//@antv/l7@2.8.34
//@antv/l7plot@0.0.3

const flow = new Flow()
const canvasLayer = new CanvasLayer
flow.getScene().addLayer(canvasLayer)；
canvasLayer.hide();
```
![image](https://user-images.githubusercontent.com/9448445/165715501-33aa99a8-9687-4451-9049-566090848a5b.png)
![image](https://user-images.githubusercontent.com/9448445/165715632-e877643a-9288-476a-a163-fc9a86f920c2.png)

**Comment by 2912401452** [comment]
在执行 style 方法后就会重新执行绘制方法。
L7plot 暂时未做对 CanvasLayer 的适配，我们会尽快完成
