### ISSUE TITLE
地图贴图有的分辨率下会出现问题

### ISSUE THREAD

**Issue by jiaicon** [antvis/L7#1110]
![image](https://user-images.githubusercontent.com/34124517/168304204-c5957340-abc0-450e-9268-e42f60c5c1b6.png)

**Comment by 2912401452** [comment]
请问是在什么屏幕分辨率呢？
是在什么电脑、浏览器中出现的呢？
最好可以提供复现的demo（codesandbox）

**Comment by jiaicon** [comment]
> 请问是在什么屏幕分辨率呢？ 是在什么电脑、浏览器中出现的呢？ 最好可以提供复现的demo（codesandbox）

我看的官方的例子：https://l7.antv.vision/zh/examples/polygon/3d#texture3D
我自己电脑是没问题的，同事有的就是上面的样子。
windows  1920x1080   谷歌v96.0

**Comment by augustanamo** [comment]
> > 请问是在什么屏幕分辨率呢？ 是在什么电脑、浏览器中出现的呢？ 最好可以提供复现的demo（codesandbox）
> 
> 我看的官方的例子：https://l7.antv.vision/zh/examples/polygon/3d#texture3D 我自己电脑是没问题的，同事有的就是上面的样子。 windows 1920x1080 谷歌v96.0

请问解决了没？
