### ISSUE TITLE
未提供对于高德地图密钥的配置项

### ISSUE THREAD

**Issue by gaoshunpeng** [antvis/L7#1113]
* **L7 Version**: 2.8.35
* **Platform**: PC
* **Mini Showcase(like screenshots)**: 
* **CodePen Link**:

如下图：官网文档在配置高德地图作为底图时，只有对于token即高德地图key的配置，并没有密钥的配置，而高德地图官方要求必须加载密钥，否则很多功能没法使用
![image](https://user-images.githubusercontent.com/81577740/168784740-7f00a345-7a0f-46c5-8b63-4733cf1db726.png)

**Comment by Guard-233** [comment]
![image](https://user-images.githubusercontent.com/35839602/169690234-92ce28a2-dfa8-493d-831b-d478f46505ad.png)

加载地图之前把你的安全密钥配置在
window._AMapSecurityConfig. securityJsCode 属性中，就可以正常使用了（建议仅在开发时使用）

![image](https://user-images.githubusercontent.com/35839602/169690205-7d79d7a8-cf78-4d94-888b-64de1b301572.png)

**Comment by ChangYanwei** [comment]
> 需要在服务端配置安全密钥，和 L7 无关

有两个问题：
1、请问怎么在服务端配置高德地图的安全密钥？

2、在生产环境下，前端这样配置密钥不可以吗？
![image](https://user-images.githubusercontent.com/48378463/199498397-5920cc48-3e96-43df-b604-d5dbfea17d50.png)

**Comment by ChangYanwei** [comment]
> ![image](https://user-images.githubusercontent.com/35839602/169690234-92ce28a2-dfa8-493d-831b-d478f46505ad.png)
> 
> 加载地图之前把你的安全密钥配置在 window._AMapSecurityConfig. securityJsCode 属性中，就可以正常使用了（建议仅在开发时使用）
> 
> ![image](https://user-images.githubusercontent.com/35839602/169690205-7d79d7a8-cf78-4d94-888b-64de1b301572.png)


在生产环境下这样配置密钥会有什么问题吗
