### ISSUE TITLE
Add maplibre support

### ISSUE THREAD

**Issue by Carlos-Carreno-Berlanga** [antvis/L7#1121]
Hi,

I am a big fan of this library.  Would it be possible to add maplibre support since mapbox is no longer open source, and many people are using maplibre? 

I think the changes required can be very small. 

Thanks in advance.

**Comment by 2912401452** [comment]
We will consider, thanks

**Comment by lvisei** [comment]
https://l7.antv.antgroup.com/api/map/maplibre
