### ISSUE TITLE
L7 使用高德地图多次初始化地图 会导致页面崩溃

### ISSUE THREAD

**Issue by zy135516** [antvis/L7#1132]
在Vue 3 onMounted 生命周期初始化高德地图时，退出页面然后再次进入页面会导致浏览器直接崩溃（即使离开页面调用了scene.destroy( )）。而使用 setTimeout 不会出现这样的问题

**Comment by 2912401452** [comment]
scene 不应该被重复创建，初始化 scene 会创建 webgl 实例，浏览器有 webgl 实例数量的限制，超过数量会直接丢失

**Comment by zy135516** [comment]
@2912401452 那有什么解决办法吗？scene.destroy( ) 不会销毁webgl实例吗？
