### ISSUE TITLE
BUG：PointLayer 等面积点unit:'meter'不支持mapbox

### ISSUE THREAD

**Issue by sinkingstones** [antvis/L7#1139]
* **L7 Version**: 2.8.41
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

BUG：PointLayer 等面积点unit:'meter' 不支持mapbox，但是文档中说已支持。

![image](https://user-images.githubusercontent.com/13111410/171573731-dee5a4cd-df4b-4a16-943d-f374626a77f9.png)

**Comment by tagore-cai** [comment]
https://codesandbox.io/s/crazy-moore-4kchhu?file=/src/index.js

**Comment by 2912401452** [comment]
问题在 v2.9.11 版本已经修复
