### ISSUE TITLE
@antv/l7-source depends on @mapbox/geojson-rewind which has a vulnerability with 

### ISSUE THREAD

**Issue by johnjiang** [antvis/L7#1140]
* **L7 Version**: 2.5.23
* **Platform**: all

@antv/l7-source depends on `@mapbox/geojson-rewind` <= 0.4.1 which has a vulnerability. If we upgraded to latest version of `@mapbox/geojson-rewind` to 0.5.2 I believe we would be able to address this vulnerability issue.

Untested PR: https://github.com/antvis/L7/pull/1141

```
node_modules/sharkdown/node_modules/minimist
  sharkdown  *
  Depends on vulnerable versions of minimist
  node_modules/sharkdown
    @mapbox/geojson-rewind  <=0.4.1
    Depends on vulnerable versions of sharkdown
    node_modules/@mapbox/geojson-rewind
      @antv/l7-source  *
      Depends on vulnerable versions of @mapbox/geojson-rewind
```

CVEs
* https://github.com/advisories/GHSA-xvch-5gv4-984h
* https://github.com/advisories/GHSA-vh95-rmgr-6w4m

**Comment by johnjiang** [comment]
As a workaround, I added the following to my `package.json`

```
    "overrides": {
        "@mapbox/geojson-rewind": "^0.5.2"
    },
```

**Comment by yiiiiiiqianyao** [comment]
done
