### ISSUE TITLE
pointLayer使用图片显示，如果一开始载入未显示图片，则后续使用setData时，两个点的经纬度重合显示的图片就会有问题

### ISSUE THREAD

**Issue by Benjamin369** [antvis/L7#1144]
问题代码
```
import { Scene, PointLayer, Popup } from '@antv/l7';
import { GaodeMap } from '@antv/l7-maps';

const scene = new Scene({
  id: 'map',
  map: new GaodeMap({
    style: 'dark',
    center: [ 120.5969, 29.7918 ],
    zoom: 7,
  })
});
scene.on('loaded', () => {
  scene.addImage(
    '01',
    'https://tianyue369.oss-cn-shanghai.aliyuncs.com/testimage/icon-001.png'
  );
  let data = []
  const imageLayer = new PointLayer()
    .source(data,{parser: {
            type: 'json',
            x: 'lon',
            y: 'lat',
        }})
    .shape('w', function(w) {
      return w;
    })
    .size(15)
    .on('click', e => {
      const popup = new Popup({
          offsets: [ 0, 0 ],
          closeButton: true
      })
      .setLnglat(e.lngLat)
      .setHTML("ceshi")
      .setMaxWidth('300px');
      scene.addPopup(popup);
    });
  scene.addLayer(imageLayer);
  setTimeout(() => {
    let newdata = [
      {lon:120.5969, lat: 29.7918, w:"01" },
      {lon:120.5969, lat: 29.7918, w:"01" },
    ]
    imageLayer.setData(newdata)
  }, 1000);
});

```
关键点
![image](https://user-images.githubusercontent.com/31198310/172518730-105a1b8c-3967-4ad3-a489-ab81e8e682dc.png)
效果
![image](https://user-images.githubusercontent.com/31198310/172518764-7f2f77b3-8516-4a1b-896d-6ec5d2d157ae.png)
有可能是自定义图片的问题，因为使用官方demo（https://l7.antv.vision/zh/examples/point/image#weather）中的图片是没有问题的。
如果一开始是在data就将所有的图片显示出来，后续更改就没有任何问题，更改如下：
```
// 原代码
  let data = []
// 更改后，就是将所有的图片都显示出来
let data = [
  {lon:120.5969, lat: 29.7918, w:"01" }
]
```

**Comment by Benjamin369** [comment]
不知道是不是我写的有问题，我找到的临时的解决方法就是在最开始的data中显示出所有的图片，不想在地图上显示，设置的经度是181，纬度是91，地图上经度范围是[-180,180]，纬度范围是[-90,90]，只要不是这个范围内就行

**Comment by Benjamin369** [comment]
又重新翻了几遍文档，发现应该是没有设置blend的问题，两个解决方案，任选其一，当然两个都用也行。
<img width="706" alt="image" src="https://user-images.githubusercontent.com/31198310/172523847-4bb7fef9-27b6-441c-b8ff-98da97ae134c.png">

**Comment by Benjamin369** [comment]
不过，如果不设置的话，这个是会动态变化的，希望作者还是看一下，就是如果我一开始显示图片了，后续就是normal，如果一开始没有显示图片，后续好像就是additive

**Comment by 2912401452** [comment]
目前是这样的，空数据的时候 blend 为 additive，这个后续优化一下默认值吧，感谢反馈
