### ISSUE TITLE
希望LineLayer的线路围墙能支持光源强弱的动画

### ISSUE THREAD

**Issue by jinxiangqiang** [antvis/L7#1154]
现在的效果只要动画修改透明度效果会很好，可以支持传入opacity: [0,1]
https://antv-l7.gitee.io/zh/examples/line/wall#hangzhou_wall

**Comment by 2912401452** [comment]
会考虑加入呼吸动效

**Comment by yiiiiiiqianyao** [comment]
推荐使用自定义图层实现
https://github.com/antvis/L7-CustomLayer-Template
