### ISSUE TITLE
聚合图问题

### ISSUE THREAD

**Issue by l13537061051** [antvis/L7#1165]
需求：点击聚合图定位并放大；
问题：调用setZoomAndCenter方法会导致部分标注不显示，手动放缩地图则不存在该问题；
复现：在官网图表演示《充电桩分布聚合图》底部代码第58行插入以下代码，并点击地图上的聚合图；
pointLayer.on('click', ({feature}) => {
  let zoom = scene.getZoom();
  scene.setZoomAndCenter(zoom >= 9 ? 12 : zoom >= 6 ? 10 : 7, feature.coordinates); 
}); 
![image](https://user-images.githubusercontent.com/53296880/174241811-03549135-d4f6-4c85-8e2f-c5b2d04581aa.png)
目前折中的临时替补方案是在调用setZoomAndCenter方法之后，使用显隐方式；
pointLayerText.hide()
setTimeout(() => {
  pointLayerText.show()
}, 200)
![image](https://user-images.githubusercontent.com/53296880/174241846-bcf9f77c-75f0-4a4b-8eb3-9ba452a3364f.png)
希望能得到解决

**Comment by 2912401452** [comment]
收到

**Comment by lzxue** [comment]
新版 2.11.1 已解决
