### ISSUE TITLE
[QUESTION] 钻取功能只支持中国地区吗？

### ISSUE THREAD

**Issue by zsj621** [antvis/L7#1173]
🐛 Question description
如何钻取非中国地区的世界其他国家行政地图？试了joinBy名称匹配渲染和joinBy行政编码匹配渲染，都无法正确钻取。应该需要一个adcode去访问接口：
https://gw.alipayobjects.com/os/alisis/geo-data-v0.1.2/choropleth-data/country/100000_country_province.topo.json
来获取钻取后的topoJson数据。
但[官方codepen](https://codesandbox.io/s/men2gn?file=/index.ts)中，hover中国地区，可以显示adcode为100000，hover其他国家，只显示name，不显示adcode。

🏞 Expected result
hover非中国地区时，可以显示adcode，并且可以根据该adcode正确钻取其他国家的'province'及以下level的地图。或者提供一个全世界各个国家的adcode对照表。

🚑 Any additional [like screenshots]
@antv/l7plot Version:0.0.7
@antv/l7 Version:2.7.20
Platform:macos 12.4 Monterey

**Comment by zsj621** [comment]
https://gw.alipayobjects.com/os/alisis/geo-data-v0.1.2/administrative-data/area-list.json
文档里的这份行政名称数据，其他国家的adcode和name相同，但根据该adcode取不到${adcode}_country_province.topo.json的数据。

**Comment by 2912401452** [comment]
目前只支持中国地图
