### ISSUE TITLE
L7 + 高德地图，层级缩放问题

### ISSUE THREAD

**Issue by siluozhang516** [antvis/L7#1195]
使用 L7 + GaodeMap   会存在地图缩放问题，设置了地图层级最大19，但是在地图缩放到 17层的时候，偶尔就无法在缩放到更大层级了，偶尔又能缩放到19层级

**Comment by lzxue** [comment]
需要设置高德地图的zoom 范围吧

**Comment by zy135516** [comment]
@lzxue 最大层级设置的19，而且这个问题出现的几率是比较大的，来回缩放，通过 zoomchange 事件观察，有时能展示到最大层级19级，有时会一直停留到17级。mapbox不存在此问题，目前仅在 GaodeMap 上出现

**Comment by 2912401452** [comment]
暂时没有支持

**Comment by lvisei** [comment]
一般这个地方没有高层级的地图，比如海外
