### ISSUE TITLE
circle()固定为30是否合理？

### ISSUE THREAD

**Issue by lucifer1004** [antvis/L7#123]
https://github.com/antvis/L7/blob/42c48301a3ce9f04b210ad39b03f4dd791d9c1ab/packages/layers/src/point/shape/Path.ts#L39

`circle()` 固定为30是否合理？是不是应该允许用户自定义？

**Comment by lzxue** [comment]
确实是很好的提议
circle 主要用于3D圆柱的绘制，平面circle绘制不是采用该方案。
3D场景减少点个数据性能会提高，这块需要修改你主要是什么场景？

**Comment by lucifer1004** [comment]
谢谢说明。看了下用户可以通过`polygonPath`来自定义顶点数，`circle`当成常量来使用的话确实是不需要参数的。

另外咨询个问题：3D场景绘制柱体，支持任意多边形作为底面吗？支持带孔的多边形吗？

**Comment by lzxue** [comment]
> 谢谢说明。看了下用户可以通过`polygonPath`来自定义顶点数，`circle`当成常量来使用的话确实是不需要参数的。
> 
> 另外咨询个问题：3D场景绘制柱体，支持任意多边形作为底面吗？支持带孔的多边形吗？

如果是具有实际经纬度多边形可以认为是polygon 图层 extrude是可以的。
如果作为标注是不支持的。

欢迎为L7贡献代码
