### ISSUE TITLE
加载坐标系为4490的栅格影像时，栅格影像会随着地图的移动而移动

### ISSUE THREAD

**Issue by zhanghjtx** [antvis/L7#1234]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by yiiiiiiqianyao** [comment]
L7 使用的是 GCJ-02 坐标系，暂时不支持 CGCS2000（EPSG 4490）

**Comment by yiiiiiiqianyao** [comment]
L7 使用的是 GCJ-02 坐标系，暂时不支持 CGCS2000（EPSG 4490）

**Comment by wangjiahao123456** [comment]
老哥这个问题你解决没呀？
