### ISSUE TITLE
【BUG】航向图，长时间停留在界面，会出现报错，导致地图崩溃

### ISSUE THREAD

**Issue by a717822** [antvis/L7#1239]
![image](https://user-images.githubusercontent.com/31062855/179441494-cf9fa0ab-181f-441c-ba6b-1f5636c40c9a.png)

demo地址：https://antv-l7.gitee.io/zh/examples/gallery/animate#plane_animate

**Comment by zwh0711** [comment]
遇到了同样的问题

**Comment by yiiiiiiqianyao** [comment]
context lost 这是 页面上的 webgl 实例超出浏览器限制，需要销毁
```js
scene.destroy()
```
