### ISSUE TITLE
地球模式下添加 PointLayer 无效

### ISSUE THREAD

**Issue by Reinhard2019** [antvis/L7#1240]
* **L7 Version**: 2.9.14
* **Platform**: 
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/13881726/179451002-abaa046f-0c67-4808-b530-87c448c0d759.png)

* **CodePen Link**: https://codesandbox.io/s/7sm002

**Comment by yiiiiiiqianyao** [comment]
试试 L7 j新版本就可以了
