### ISSUE TITLE
代码实例中的文件地址无法访问

### ISSUE THREAD

**Issue by AtroxEzerel** [antvis/L7#1245]
![sBPYerPcUP3P9cFuUWky$w==](https://user-images.githubusercontent.com/55567122/179718885-74aaa5a4-0b42-46f7-a5a1-0dba92faddbb.png)

**Comment by AtroxEzerel** [comment]
或者是否能提供要生成这样的图标需要什么样结构的数据

**Comment by yiiiiiiqianyao** [comment]
这是 mapbox 标准的矢量数据，可以用 mapbox 对应工具生产
https://github.com/mapbox/tippecanoe
