### ISSUE TITLE
如何使用wms瓦片？

### ISSUE THREAD

**Issue by FA93vHWS** [antvis/L7#1248]
使用wms格式的瓦片时，bbox的参数应该用什么占位符替代？

这种的https://a.basemaps.cartocdn.com/rastertiles/dark_nolabels/{z}/{x}/{y}.png，请求时坐标信息会被带入

用mapbox的方式&bbox={bbox-epsg-3857}无法对参数进行坐标替换，请求url直接就是https://XXXXXX/wms?CQL_FILTER=DLDM_2021=%27340%27&bbox={bbox-epsg-3857}&crs=EPSG:3857

**Comment by zwh0711** [comment]
请问下这个问题是如何解决的？我也有这样的困惑，非常感谢

**Comment by FA93vHWS** [comment]
> 请问下这个问题是如何解决的？我也有这样的困惑，非常感谢

可以参照这段代码
`scene.setMapStyle({
            version: 8,
            sources: {
                'wms': {
                    type: 'raster',
                    tiles: [
                        'https://img.nj.gov/imagerywms/Natural2015?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&transparent=true&width=256&height=256&layers=Natural2015'
                    ],
                    tileSize: 256,
                },
            },
            layers: [
                this.baseLayer.layer,
                {
                    id: 'wms',
                    type: 'raster',
                    source: 'wms',
                },
            ]
        });`

**Comment by zwh0711** [comment]
> > 请问下这个问题是如何解决的？我也有这样的困惑，非常感谢
> 
> 可以参照这段代码 `scene.setMapStyle({ version: 8, sources: { 'wms': { type: 'raster', tiles: [ 'https://img.nj.gov/imagerywms/Natural2015?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&transparent=true&width=256&height=256&layers=Natural2015' ], tileSize: 256, }, }, layers: [ this.baseLayer.layer, { id: 'wms', type: 'raster', source: 'wms', }, ] });`

非常感谢，如果我理解的没有错，这是一种将wms瓦片叠加为底图的写法？直接叠加为图层的时候也可以用这种格式写吗？我的代码里可能是需要叠加多个wms图层的

**Comment by FA93vHWS** [comment]
> > > 请问下这个问题是如何解决的？我也有这样的困惑，非常感谢
> > 
> > 
> > 可以参照这段代码 `scene.setMapStyle({ version: 8, sources: { 'wms': { type: 'raster', tiles: [ 'https://img.nj.gov/imagerywms/Natural2015?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&transparent=true&width=256&height=256&layers=Natural2015' ], tileSize: 256, }, }, layers: [ this.baseLayer.layer, { id: 'wms', type: 'raster', source: 'wms', }, ] });`
> 
> 非常感谢，如果我理解的没有错，这是一种将wms瓦片叠加为底图的写法？直接叠加为图层的时候也可以用这种格式写吗？我的代码里可能是需要叠加多个wms图层的

是的，这是叠加为底图的写法，很遗憾我也想叠加多个wms图层，但是目前没有发现其他有效的方法
