### ISSUE TITLE
Angular 6 error: regeneratorRuntime is not defined.

### ISSUE THREAD

**Issue by ParryQiu** [antvis/L7#125]
* **L7 Version**: 2.0.0-beta.20
* **Platform**: mac + Angular 6

Angular 6 以 npm 包的形式引用 2.0.0-beta.20 版本，编译后控制台输出错误。

> zone.js:682 Unhandled Promise rejection: regeneratorRuntime is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: regeneratorRuntime is not defined
>     at Scene.render (SceneService.js:218)
>     at Scene.addLayer (SceneService.js:213)
>     at Scene.addLayer (index.js:52)
> 

![错误截图](https://image.devopen.club/WX20191217-111324@2x.png)

**Comment by ParryQiu** [comment]
**解决方案**
手动在 Angular 6 项目的 /src/polyfills.ts 文件中添加 babel-polyfill 包。

`import 'babel-polyfill';`

即可。

类似问题可参见
https://github.com/retejs/examples/issues/16

**Comment by lzxue** [comment]
regeneratorRuntime is not defined 都可以通过引入 polyfill解决
https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.7.0/polyfill.js
