### ISSUE TITLE
🐛 [BUG]使用L7draw绘制的多边形层级放大后有坐标偏移

### ISSUE THREAD

**Issue by MarkLei7** [antvis/L7#1254]
### 🐛 mapbox作为地图实例时，绘制多边形，放大至22级屏幕坐标有偏移，但是导出的geojson数据正确

> https://codesandbox.io/s/eloquent-sanne-i31q3e?file=/src/App.tsx

- _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]
16级时候正常
<img width="394" alt="image" src="https://user-images.githubusercontent.com/33211377/180355122-b0af4c37-ec2b-4f06-8812-379ccd945584.png">
22级有偏差
<img width="510" alt="image" src="https://user-images.githubusercontent.com/33211377/180355170-846da321-1af3-4748-85e2-43bb920e7034.png">

**Comment by lzxue** [comment]
升级新版 L7Draw 3.0

**Comment by MarkLei7** [comment]
> 升级到L7Draw 3.0还是存在这个BUG
