### ISSUE TITLE
RasterLayer引入天地图标注出现锯齿模糊现象

### ISSUE THREAD

**Issue by adntian** [antvis/L7#1279]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

* **L7 Version**:2.9.23
* **Platform**:MacOS Chrome
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/2285733/183636926-06a4c905-380b-4a1c-88be-59497b7f5268.png)

* **CodePen Link**: [codesandbox](https://codesandbox.io/s/l7-tianditu-v8bcr4)

引入天地图的标注后，查看请求资源图片中文字是正常的，应该是进行了缩放，同时做了png处理导致出现锯齿，还是我引入的方式有问题？目前在文档中没有找到配置项目，尝试了scene和layer的配置，均没有效果，麻烦帮忙看下是哪里的问题，谢谢

**Comment by yiiiiiiqianyao** [comment]
收到

**Comment by lzxue** [comment]
zoomOffset: 1 先调整一下，看一下效果

**Comment by yiiiiiiqianyao** [comment]
会在新版本修复问题

**Comment by yiiiiiiqianyao** [comment]
已经在新版修复 v2.9.24
