### ISSUE TITLE
Extrude图层数据源为矢量切片时，无法挤出图层。

### ISSUE THREAD

**Issue by xiaowate** [antvis/L7#1289]
* **L7 Version**:2.9.16
* **Platform**:all
* **Mini Showcase(like screenshots)**:
import { Scene, PolygonLayer } from '@antv/l7';
import { GaodeMap } from '@antv/l7-maps';

const scene = new Scene({
  id: 'map',
  map: new GaodeMap({
    style: 'dark',
    center: [116.27361, 39.989267],
    zoom: 16,
    pitch: 30,
  }),
});

let data =
  'https://geoserver.citydnatech.com/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=city_scanner:beijing_haidian_building&STYLE=&TILEMATRIX=EPSG:900913:{z}&TILEMATRIXSET=EPSG:900913&FORMAT=application/vnd.mapbox-vector-tile&TILECOL={x}&TILEROW={y}';

let option = {
  sourceLayer: 'beijing_haidian_building',
  minZoom: 12,
  maxZoom: 19,
};
let sourceOption = {
  parser: {
    type: 'mvt',
    tileSize: 256,
    zoomOffset: 0,
  },
};
const provincelayer = new PolygonLayer(option)
  .source(data, sourceOption)
  .size(150000)
  .shape('extrude')
  .color('#FFFF00')
  .style({
    heightfixed: true,
    pickLight: true,
    raisingHeight: 200000,
    sourceColor: '#333',
    targetColor: '#fff',
  });

scene.addLayer(provincelayer);

<img width="993" alt="image" src="https://user-images.githubusercontent.com/38240441/184277548-1977759a-da27-44cb-995d-5e8803045376.png">

* **CodePen Link**:

**Comment by yiiiiiiqianyao** [comment]
polygon 挤出图层暂时不支持瓦片形式

**Comment by xiaowate** [comment]
> polygon 挤出图层暂时不支持瓦片形式
