### ISSUE TITLE
markerLayer在GaodeMapV2做底图时removeMarkerLayer视图图层层级改变时会复原被删除的图层

### ISSUE THREAD

**Issue by choumai555** [antvis/L7#1306]
markerLayer在GaodeMapV2做底图时removeMarkerLayer视图图层层级改变时会复原被删除的图层
dome地址：https://codesandbox.io/s/blazing-sky-lt49vk?file=/index.js

**Comment by Dreammy23** [comment]
![0908B111-FEF4-4905-8D8C-7076C37D9995](https://user-images.githubusercontent.com/18047832/186843872-b10798af-0dd9-427e-9092-60199dfa72d9.gif)

**Comment by Dreammy23** [comment]
![0908B111-FEF4-4905-8D8C-7076C37D9995](https://user-images.githubusercontent.com/18047832/186843958-3a0741f5-9ce9-4987-8191-42b0831fa423.gif)

**Comment by Dreammy23** [comment]
已修复 https://github.com/antvis/L7/pull/1324
