### ISSUE TITLE
setZoomAndCenter 设置地图缩放等级和中心点时是否可以提供飞入动画

### ISSUE THREAD

**Issue by zwh0711** [antvis/L7#1317]
场景设置中心点和zoomlevel的方法，如setZoomAndCenter 或setCenter等，是否可以提供类似mapbox flyto的效果，有缓慢飞入的动画？
非常感谢

**Comment by yiiiiiiqianyao** [comment]
后续会考虑，感谢提出需求

**Comment by caisheng-0304** [comment]
2024年了还没有提供这个方法吗
