### ISSUE TITLE
markerLayer 执行 markerLayer.clear() 后， 重新加入 marker 丧失聚合能力

### ISSUE THREAD

**Issue by wangxingkang** [antvis/L7#1320]
* **L7 Version**: latest
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

复现 demo

https://codesandbox.io/embed/magical-margulis-6li3be?fontsize=14&hidenavigation=1&theme=dark

**Comment by MarkLei7** [comment]
clear函数还是有BUG啊 @lvisei 
这样可以规避
<img width="483" alt="image" src="https://user-images.githubusercontent.com/33211377/187828498-ebe11b49-8081-4476-85b3-3540d4e6c7cd.png">

https://codesandbox.io/s/jovial-architecture-sc1ts5?file=/index.js

**Comment by Dreammy23** [comment]
已修复 https://github.com/antvis/L7/pull/1324

**Comment by Dreammy23** [comment]
原来在markerLayer的clear函数中，将viewChange的监听函数一并清除了，因此执行了clear后再添加，图层失去监听容器变化的能力，已在2.9.27-alpha.2版本上修复。

**Comment by luoxiao-supermap** [comment]
2.17.7版本 忍让有同样的问题
