### ISSUE TITLE
样例图表中的填充地图地理位置标注有偏差的问题

### ISSUE THREAD

**Issue by EricHan0723** [antvis/L7#1327]
* **L7 Version**: 2.9.24
* **Platform**: Windows
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

请问样例图表中的填充地图的中，香港和澳门的标注位置和实际位置有很大偏差，我在用到这部分json的时候要自己手动调一下位置，请问这个能不能同步一下行政区划中的省级地图的位置数据？

**Comment by yiiiiiiqianyao** [comment]
这个自己调整就可以了
