### ISSUE TITLE
使用L7/plot绘制湖南省的市级地图时，株洲市的label不显示

### ISSUE THREAD

**Issue by shinyruo-nmsl** [antvis/L7#1337]
<img width="471" alt="image" src="https://user-images.githubusercontent.com/76041600/189824749-865076f6-e116-41d3-acdd-ba5dc76a8653.png">
<img width="667" alt="image" src="https://user-images.githubusercontent.com/76041600/189824868-649d3885-f678-4ca4-ba80-8cc168211406.png">

**Comment by lvisei** [comment]
@shinyruo-nmsl 放大会出来吗，看是不是文字碰撞的原因

可以去 L7Plot 提一个 issue 带上复现的 codesanbox 地址
