### ISSUE TITLE
行政地区数据更新

### ISSUE THREAD

**Issue by HXJian** [antvis/L7#1339]
在使用l7-boundary的区县级行政数据有发现部分数据存在更新，例如：江苏省-南通市-海门市。在目前的geojson数据上并不存在对应的海门市以及邮编，对应区域现名称叫做海门区。
这类数据更新是否还会同步到l7-boundary上，我看都已经9个月没有进行过更新了，或者这个数据能不能通过其他方式进行更新数据

**Comment by HXJian** [comment]
本地是下载了省市区的fill.bin文件进行使用的，这个数据能本地维护吗

**Comment by yiiiiiiqianyao** [comment]
目前行政地图以经不再维护 L7-boundary，使用 L7Plot 的行政区划图进行替换
https://l7plot.antv.vision/zh/docs/api/plots/choropleth
