### ISSUE TITLE
使用L7Plot时候左下角Antv logo如何去除

### ISSUE THREAD

**Issue by gabrielpondc** [antvis/L7#1341]
* **L7 Version**:
* **Platform**:HTML
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/26787778/190346518-eef69334-0afb-4e74-b122-38957e44d9d4.png)

* **CodePen Link**:

**Comment by lolarun** [comment]
[参见Scent的配置项：logoVisible](https://antv-l7.gitee.io/en/docs/api/scene#logovisible-logo-%E6%98%AF%E5%90%A6%E5%8F%AF%E8%A7%81)
