### ISSUE TITLE
@antv/l7-three可以提供一个umd包吗？

### ISSUE THREAD

**Issue by xiao252** [antvis/L7#1352]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lzxue** [comment]
@yiiiiiiqianyao

**Comment by yiiiiiiqianyao** [comment]
后续会提供

**Comment by yiiiiiiqianyao** [comment]
https://unpkg.com/browse/@antv/l7-three@2.9.31/dist/l7-three.min.js
