### ISSUE TITLE
line线图层出现虚线断裂的情况

### ISSUE THREAD

**Issue by zwh0711** [antvis/L7#1359]
L7 Version**:2.9.29

线图层出现虚线断裂的情况。
代码示例：
fetch(
    'https://gw.alipayobjects.com/os/bmw-prod/0290a972-eedd-42f6-b69e-50a35e8a0824.json'
  )
    .then(res => res.json())
    .then(data => {
      const layer = new LineLayer({})
        .source(data, {
          parser: {
            type: 'json',
            coordinates: 'coordinates'
          }
        })
        .size(0.5)
        .shape('line')
        .active(true)
        .color('length', [
          '#0A3663',
          '#1558AC',
          '#3771D9',
          '#4D89E5',
          '#64A5D3',
          '#72BED6',
          '#83CED6',
          '#A6E1E0',
          '#B8EFE2',
          '#D7F9F0'
        ]);
      scene.addLayer(layer);
    });

在antv图表示例中显示如下：
![image](https://user-images.githubusercontent.com/16575345/192769616-5d8024ae-f7a0-476a-ba94-93d78b02447f.png)

在我本地项目中显示如下：
![image](https://user-images.githubusercontent.com/16575345/192769698-280e0ae2-7625-4fc0-bcaa-138e331fb890.png)

同样的代码，在我本地的项目中，所有的line类型的图层都会变成虚线，请教

**Comment by yiiiiiiqianyao** [comment]
收到

**Comment by yiiiiiiqianyao** [comment]
是不是线图层太细了呢？太细的时候由于分辨率的原因很容易出现你说的情况，尤其是在大倾角的时候，可以调整粗细看看
