### ISSUE TITLE
No such file /@antv/l7-renderer/node_modules/inversify/src/utils/serialization.ts

### ISSUE THREAD

**Issue by iplash** [antvis/L7#1362]
* **L7 Version**: 2.9.20
* **Platform**: Mac OS
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: 无

![image](https://user-images.githubusercontent.com/5343414/192960726-f4d33e43-69f0-4b2f-9a0c-0ebe1e8ad3ee.png)

`
WARNING in ./node_modules/@antv/l7-renderer/node_modules/inversify/lib/utils/serialization.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/wujun/github/iplash/my-app/node_modules/@antv/l7-renderer/node_modules/inversify/src/utils/serialization.ts' file: Error: ENOENT: no such file or directory, open '/Users/wujun/github/iplash/my-app/node_modules/@antv/l7-renderer/node_modules/inversify/src/utils/serialization.ts'
`

**Comment by yiiiiiiqianyao** [comment]
Seems to be `source map` error, Try to ignore `node_modules` at `webpack.config.js`
```js
rules : [
 {
 enforce: 'pre', 
 exclude: [/node_modules/],
 test: /\.(js|mjs|jsx|ts|tsx|css)$/,
 loaded: require.resolve('source-map-loader'),
 }
]
```

**Comment by iplash** [comment]
🥰 thank you, the following are the configurations to resolve the issue.
`
{
  enforce: 'pre',
  exclude: [/@babel(?:\/|\\{1,2})runtime/, /node_modules/],
  test: /\.(js|mjs|jsx|ts|tsx|css)$/,
  loader: require.resolve('source-map-loader'),
}
`
