### ISSUE TITLE
论文项目使用Antv-l7，需要对Antv作引用是否有引用的模板

### ISSUE THREAD

**Issue by gabrielpondc** [antvis/L7#1366]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: 最好为APA7样式的bib格式引用模板

**Comment by yiiiiiiqianyao** [comment]
看你论文是学校项目还是投稿给期刊、会议，不同的期刊或会议有自己的论文以及引用的模版。
或者可以看看这个回答 https://www.wikihow.com/Cite-a-GitHub-Repository ，希望对你有帮助
