### ISSUE TITLE
栅格瓦片用做底图时，3d弧线会出现颜色失效问题

### ISSUE THREAD

**Issue by suzukaovo** [antvis/L7#1374]
`const layer = new LineLayer({
        zIndex: 2,
      })
        .source(data, {
          parser: {
            type: "json",
            x: "lng1",
            y: "lat1",
            x1: "lng2",
            y1: "lat2",
          },
        })
        .size(4)
        .shape("arc3d")
        .color("#333")
        .style({
          sourceColor: "#333",
          targetColor: "#333",
        });`

![image](https://user-images.githubusercontent.com/109931363/194793156-e6d6ea10-dc7b-4524-b17d-f784c946fd97.png)

**Comment by yiiiiiiqianyao** [comment]
混合模式改一下
blend: 'normal'
