### ISSUE TITLE
https://l7.antv.vision/zh/examples/engine/three#amap_ant    将这个案例中的地图改为mapbox，无法显示旁边的立方体，高德地图是正常显示

### ISSUE THREAD

**Issue by chenshuqun** [antvis/L7#1377]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by yiiiiiiqianyao** [comment]
不同地图需要调整参数

**Comment by chenshuqun** [comment]
@yiiiiiiqianyao 不同地图调整参数的规则是什么呢，文档上有这说明不

**Comment by chen-min** [comment]
> @yiiiiiiqianyao 不同地图调整参数的规则是什么呢，文档上有这说明不

你好，你的参数调整好了吗？ 我也遇到这个问题了

**Comment by chen-min** [comment]
> @yiiiiiiqianyao 不同地图调整参数的规则是什么呢，文档上有这说明不

你好，你的参数调整好了吗， 我也遇到这个问题了
