### ISSUE TITLE
Zoom 组件放大按钮不会置灰

### ISSUE THREAD

**Issue by Randysheng** [antvis/L7#139]
* **L7 Version**: 2.0.0-beta.25+
* **Platform**: 
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/11868294/71584888-aa6e7d80-2b4f-11ea-9d5d-88c8467581d3.png)

* **CodePen Link**:
https://codesandbox.io/s/base-2fyis

高德地图放大到最大级别后，放大按钮未置灰。

**Comment by Randysheng** [comment]
AMapService 中 getZoom 从beta.25后改为了
```JavaScript
public getZoom(): number {
  // 统一返回 Mapbox 缩放等级
  return this.map.getZoom() - 1;
}
```

Zoom 组件中 updateDisabled 方法判断如下：
```JavaScript
if (this.disabled || mapsService.getZoom() >= mapsService.getMaxZoom()) {
   DOM.addClass(this.zoomInButton, className);
}
```
现在的 zoom 应该是达不到 maxZoom 了吧

**Comment by lzxue** [comment]
新版本已修复
