### ISSUE TITLE
1.x版本会实现 2.0beta中的示例气泡动画水波纹效果么

### ISSUE THREAD

**Issue by doublenian** [antvis/L7#140]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

2.0的示例是这个 https://l7.antv.vision/zh/examples/point/bubble#scatter

**Comment by lzxue** [comment]
不会的，正式版本很快就发布，届时希望大家升级的2.0
