### ISSUE TITLE
请问什么时候可以在Maker中支持raisingHeight属性，或者PointLayer可以自定义Shape？

### ISSUE THREAD

**Issue by Longder** [antvis/L7#1429]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by yiiiiiiqianyao** [comment]
Marker 是 DOM 节点，不支持 raisingHeight属性
PointLayer 需要自定义的话可以暂时考虑使用 L7-CustomLayer-Template（https://github.com/antvis/L7-CustomLayer-Template）
