### ISSUE TITLE
报错：浏览器不支持

### ISSUE THREAD

**Issue by masoncat** [antvis/L7#144]
* **L7 Version**:  1.4.12
* **Platform**: macOS
* **Mini Showcase(like screenshots)**:  
1.4.12版本引入了一个Error检测，导致页面白屏。部分浏览器检测报错了，目前已知的浏览器版本为：版本 78.0.3904.108（正式版本） （64 位）
![image](https://user-images.githubusercontent.com/30170642/71655302-10861b00-2d71-11ea-9606-169556c17e99.png)

具体代码commit在这里：
![image](https://user-images.githubusercontent.com/30170642/71655332-2a276280-2d71-11ea-894a-3f259f1e27d6.png)

**Comment by lzxue** [comment]
在引入L7脚本的前面增加
```
<script>
window.forceWebGL =true
</script>
````

**Comment by masoncat** [comment]
请问具体是什么原因呢？我看到AMap的getCameraState方法中，this.view.type = 2D
