### ISSUE TITLE
使用高德地图情况下 scene.panTo方法不生效

### ISSUE THREAD

**Issue by liuhuo-qiu** [antvis/L7#1445]
* **L7 Version**: 官网demo
* **Platform**: windows11
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:  https://l7.antv.vision/zh/examples/gallery/animate#turin
在官网demo  高德地图做地图情况下 scene.panTo方法不生效
![image](https://user-images.githubusercontent.com/29687128/198509412-c7e810a3-588a-4fa0-a8e4-250edcb0796e.png)

**Comment by lvisei** [comment]
最新版本没有问题的
