### ISSUE TITLE
聚合图初始化时设置不可见，之后设置显示，缩放后点图层消失

### ISSUE THREAD

**Issue by wangkeyu** [antvis/L7#1446]
![截图_16669398819001](https://user-images.githubusercontent.com/76460377/198522344-bb86a1a7-76b3-4ee1-92e1-aad1dbcee3f3.png)
聚合图中先设置不可见,addLayer之后设置显示,然后缩放地图之后点图层就消失了

**Comment by lzxue** [comment]
2.11.1应该已经解决了
