### ISSUE TITLE
windows下PolygonLayer shape 使用extrude，纹理贴图渲染花屏

### ISSUE THREAD

**Issue by PeopleMountain** [antvis/L7#1457]
1. 部分windows电脑使用官网案例就能复现
[https://antv-l7.gitee.io/zh/examples/polygon/3d#texture3D](url)
2. 问题已经查到，webgl顶点着色器使用的数据没处理成浮点数
例：l7-layers/es/core/shape/extrude.js 下的extrude_PolygonNormal():{positions,index,normals}
positions 的数据是小数和整数混合的,当我把positions的数统一处理成小数时问题被解决。

ps：这样的问题可能在多处存在，希望能尽快修复。

**Comment by chenshuqun** [comment]
我也是偶尔会，偶尔又正常，是电脑配置问题吧

**Comment by yiiiiiiqianyao** [comment]
L7 新版本已经处理过这个问题
