### ISSUE TITLE
上线之后报错_this2.map.getOverlayContainer is not a function

### ISSUE THREAD

**Issue by fit2cloud-chenyw** [antvis/L7#1459]
[本地运行没有问题，上线之后就报错。开始怀疑是token问题，换了token依然报错。]

SceneService.js:252 Uncaught (in promise) TypeError: _this2.map.getOverlayContainer is not a function
    at _callee2$ (SceneService.js:252:46)
    at tryCatch (regeneratorRuntime.js:72:17)
    at Generator.eval [as _invoke] (regeneratorRuntime.js:55:24)
    at Generator.eval [as next] (regeneratorRuntime.js:97:21)
    at asyncGeneratorStep (asyncToGenerator.js:3:24)
    at _next (asyncToGenerator.js:22:9)
    at eval (asyncToGenerator.js:27:7)
    at new Promise (<anonymous>)
    at eval (asyncToGenerator.js:19:12)
    at AsyncSeriesHook.eval (index.js:1606:43)
![image](https://user-images.githubusercontent.com/67260074/199657241-946e203f-8d48-4743-8dcf-8ab6d9ff1547.png)

**Comment by lzxue** [comment]
解决了吗，地图是不是没有初始化？

**Comment by slobber** [comment]
修改 node_modules/@antv/l7-core/es/services/SceneService.js 对应行，改为

renderContainer = undefined; 

即可

**Comment by SituC** [comment]
没有更新g7/maps

**Comment by hopperhuang** [comment]
同一问题。

**Comment by lzxue** [comment]
地图没有初始化完成导致的

**Comment by hopperhuang** [comment]
> 地图没有初始化完成导致的

1. 请问大佬，地图初始化是指 没有调用地图进行初始化，还是地图没有初始化完成就调用了对应的api？
这是我们的代码，我们是有对地图进行初始化的，并且地图相关调用相关代码是在加载后的。为啥还会出这问题，能指引一下吗。<img width="705" alt="image" src="https://github.com/antvis/L7/assets/20254356/232bc9d5-0233-464d-a080-9ae478bf6375">

**Comment by hopperhuang** [comment]
请问这个问题应该如何解决呢。

**Comment by hopperhuang** [comment]
@fit2cloud-chenyw  请问这个问题解决了吗？

**Comment by lzxue** [comment]
可以看一下的的 地图实例化的 dom 有没有给高度，最好提供一个 在线可运行 codesanbox demo

**Comment by hopperhuang** [comment]
> 可以看一下的的 地图实例化的 dom 有没有给高度，最好提供一个 在线可运行 codesanbox demo

没法解决，现在暂时是通过 @slobber 的提议来解决。看过你们的源代码，getOverlaycontainter 方法本来就是返回undefined ，按照这个大佬提议的方法修改也不是问题。 具体是什么问题导致这个报错，要你们自己打包试下，自己排查了。。。
