### ISSUE TITLE
两个PolygonLayer 3D 填充图之间的zIndex遮挡问题

### ISSUE THREAD

**Issue by Znonymous29** [antvis/L7#1461]
* **L7 Version**:  "@antv/l7": "2.10.1"
* **Platform**:  Win10
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/19743142/199933952-1fd31db1-dd0c-4dbd-ad5f-92a0af86d71a.png)

* **CodePen Link**: https://stackblitz.com/edit/react-qbdr6s?file=index.js

两个PolygonLayer的3D图层A和B，如果A图层的zIndex高于另一个图层B的话，A应该是在B图层之前，不应该被B所遮挡。如果B图层为透明图层，也应显示出A图层。但是，示例中A图层仍被B图层遮挡，且不能全部显现。

**Comment by Znonymous29** [comment]
为了完整显示A图层，目前找到一个比较tricky的解决方案是，将B图层使用`地理围墙`进行构建，使用`LineLayer({}).shape('wall')`color采用rgba颜色。A图层仍旧使用PolygonLayer

**Comment by yiiiiiiqianyao** [comment]
zIndex 越大渲染顺序越靠后，同时要考虑深度检测，上图的 demo 中通过 zIndex 固定了渲染顺序，先绘制了透明的 polygon 再绘制不透明的 polygon，所以不透明 polygon 的像素没有通过深度检测被舍弃，在这个场景中应该先绘制不透明的 polygon。
![image](https://user-images.githubusercontent.com/42212176/208141593-2fa5b5a6-c014-4707-9995-3b9dc8b1a212.png)

**Comment by Znonymous29** [comment]
@yiiiiiiqianyao 谢谢开发人员拨冗解惑，调整了一下A和B图层的zIndex大小，A图层可以完整显示了
