### ISSUE TITLE
用高德2.x版实例化地图，执行高德jssdk，marker正常显示，但是监听‘click’事件不能正常触发

### ISSUE THREAD

**Issue by guozhenqianga** [antvis/L7#147]
* **L7 Version**:2.0.0-beta.26
* **Platform**:
创建scene之后，用scene.map来执行高德jssdk，来渲染marker，能正常渲染，但是marker的监听‘click’事件不能正常触发，
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
https://codesandbox.io/s/nervous-kapitsa-2h5hg

**Comment by lzxue** [comment]
2.0版本已经修复
