### ISSUE TITLE
2.x版本显示maxZoom为22，但是报错

### ISSUE THREAD

**Issue by guozhenqianga** [antvis/L7#148]
* **L7 Version**:2.0.0-beta.26
* **Platform**:
![image](https://user-images.githubusercontent.com/23112360/71716852-0dfaf280-2e51-11ea-9dd6-d65c55948053.png)
![image](https://user-images.githubusercontent.com/23112360/71716854-105d4c80-2e51-11ea-911f-34ed9196e3a6.png)

* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lzxue** [comment]
已修复
