### ISSUE TITLE
这个react组件中的Layer组件没有VUE版本的实现么

### ISSUE THREAD

**Issue by ztyhal** [antvis/L7#1486]
![image](https://user-images.githubusercontent.com/39219035/202629924-1c25af47-bcd2-4309-89ea-1bcae4a0d96d.png)
这个react组件中的Layer组件没有VUE版本的实现么

**Comment by lzxue** [comment]
没有Vue版本， 新版 React 组件 升级为 LarkMap  https://larkmap.antv.antgroup.com/  能力更丰富
