### ISSUE TITLE
PointLayer.shape 动态设置类型只会生效一次

### ISSUE THREAD

**Issue by Viin-zx** [antvis/L7#1502]
通过PointLayer.shape(field, function) 这个方式修改数据对应的图片，只能生效一次。
版本引用最新版本就行。

`
        import { Scene, PointLayer } from "@antv/l7";
        import { GaodeMap } from "@antv/l7-maps";
        
        const scene = new Scene({
          id: "map",
          map: new GaodeMap({
            style: "light",
            center: [121.434765, 31.256735],
            zoom: 14.83,
          }),
        });
        scene.addImage(
          "00",
          "https://gw.alipayobjects.com/zos/basement_prod/604b5e7f-309e-40db-b95b-4fac746c5153.svg"
        );
        scene.addImage(
          "01",
          "https://gw.alipayobjects.com/zos/basement_prod/30580bc9-506f-4438-8c1a-744e082054ec.svg"
        );
        scene.addImage(
          "02",
          "https://gw.alipayobjects.com/zos/basement_prod/7aa1f460-9f9f-499f-afdf-13424aa26bbf.svg"
        );
        
        const list = [];
        const imageLayer = new PointLayer()
          .source(
            [
              {
                id: "5011000000404",
                type: "00",
                longitude: 121.4316962,
                latitude: 31.26082325,
              },
              {
                id: "5011000002716",
                type: "01",
                longitude: 121.3810096,
                latitude: 31.25302026,
              },
              {
                id: "5011000003403",
                type: "01",
                longitude: 121.4086229,
                latitude: 31.25291206,
              },
            ],
            {
              parser: {
                type: "json",
                x: "longitude",
                y: "latitude",
              },
            }
          )
          .shape("type", (type) => {
            return type;
          })
          .size(25);
        // 点击的时候动态设置图形，这个shape只会生效一次。
        imageLayer.on("click", (e) => {
          list.push(e.feature.id);
        
          imageLayer.shape("id*type", (id, type) => {
            if (list.includes(id)) {
              return "02";
            }
            return type;
          });
        });
        scene.addLayer(imageLayer);
`

**Comment by lzxue** [comment]
什么场景要这样操作？

**Comment by Viin-zx** [comment]
> 

我这边场景是这样的， 一个点图层有多种类型的数据，例如3个，有个编辑修改类型的功能，把其中一个点改成另一种类型，这个时候要在地图上体现出来，我就重新shape一次

**Comment by lzxue** [comment]
新版的应该已经解决了，可以试一下
