### ISSUE TITLE
layer.active(true)开启时，layer.setSeleted()设置的高亮，鼠标移动就会被取消；只有设置为.active(false)时，setSeleced()的才会常亮

### ISSUE THREAD

**Issue by chenshuqun** [antvis/L7#1506]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lzxue** [comment]
@yiiiiiiqianyao  这个原来支持吗？

**Comment by lzxue** [comment]
目前这两个互斥的，建议高亮新加个图层做高亮图层
