### ISSUE TITLE
使用GaodeV1作为底图，加载LineLayer，缩放地图会线图层会有明显抖动，底图和叠加图层不同步。 

### ISSUE THREAD

**Issue by qxang** [antvis/L7#1509]
L7 Version：2.11.1；
demo： https://stackblitz.com/edit/react-szmuuw?file=index.js

**Comment by lzxue** [comment]
能用高德V2先使用V2，V1 的问题这边排查一下

**Comment by lzxue** [comment]
已修复  2.11.4
