### ISSUE TITLE
layer 相关方法需要初始完成后，才能加载

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#151]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by photino** [comment]
有时开启动画，它就报` Uncaught (in promise) TypeError: Cannot read property 'getZoom' of undefined`，取消动画它就正常，不知道是不是和这个issue有关？

![image](https://user-images.githubusercontent.com/3446306/72432302-b1dd8a00-37d1-11ea-82e2-4c5b817a0893.png)

**Comment by lzxue** [comment]
scene是异步加载,推荐Loaded完成之后进行图层加载的逻辑。
```javascript
scene.on('loaded',()=>{
})
```
