### ISSUE TITLE
国际化

### ISSUE THREAD

**Issue by AlwaysMing** [antvis/L7#1525]
* **L7 Version**:2.11.4
* **Platform**:安卓
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

请问支持国际化吗？文档里没看到，要怎么配置？

**Comment by lzxue** [comment]
你说的国际化是指什么，国外底图吗？

**Comment by AlwaysMing** [comment]
> 你说的国际化是指什么，国外底图吗？

是的，比如切到英文，地图上显示的地名都换成英文。

**Comment by AlwaysMing** [comment]
自己加的覆盖物可以自己翻译，但是底图能切语言吗？
