### ISSUE TITLE
 [QUESTION] Popup在父级有缩放的情况下会出现定位偏移的问题，该问题有处理方法吗？

### ISSUE THREAD

**Issue by vobile-wangzhenfeng** [antvis/L7#1526]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

## 复现
进入这个例子  https://l7.antv.antgroup.com/examples/component/popup#layerpopup
![image](https://user-images.githubusercontent.com/111114334/205798138-f7f14196-9b0e-451a-9700-ab7a59864441.png)
![image](https://user-images.githubusercontent.com/111114334/205799073-d0421cdf-01c0-4bec-b9a8-4141171b940c.png)

## 期望
希望在父容器缩放的情况下正确定位

我看有人提出过相似的问题，并提出了解决方案
https://github.com/antvis/L7Plot/issues/180

**Comment by heiyexing** [comment]
会在下一个版本修复

**Comment by heiyexing** [comment]
目前 LayerPopup 展示的为止是依靠鼠标事件拾取到的经纬度来控制的，因此如果你地图缩放层级过大的情况下，拾取到的经纬度肯定和图层元素真实坐标有很大出入的，这个问题目前没有比较标准的解法
