### ISSUE TITLE
地图模式支持在球面上画点或者画dom吗？

### ISSUE THREAD

**Issue by AlwaysMing** [antvis/L7#1527]
* **L7 Version**:2.11.4
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

L7支持在地球模式的球面上画点或者画dom吗？看文档（https://l7.antv.antgroup.com/api/experiment/earth/point）这里的意思应该是可以的，但是试了下，点并没有画出来。下面是例子代码：

import React, {
  useEffect
} from 'react';
import { Earth, GaodeMap } from '@antv/l7-maps';
import { EarthLayer, PointLayer } from '@antv/l7-layers';
import { Scene } from '@antv/l7-scene';

export default function WDMEarth(props) {

  useEffect(() => {
    HWH5.navTitle({ title: '地图' });
    initPage();
  }, []);

  const initPage = async () => {
    const scene = new Scene({
      id: 'wdmMap',
      logoVisible: false,
      preserveDrawingBuffer: true,
      map: new Earth({})
    });

    const earthlayer = new EarthLayer()
      .source(
        // 地球表面的纹理
        'https://gw.alipayobjects.com/mdn/rms_23a451/afts/img/A*3-3NSpqRqUoAAAAAAAAAAAAAARQnAQ',
        {
          parser: {
            type: 'image',
            extent: [121.168, 30.2828, 121.384, 30.421],
          },
        },
      )
      .color('#f00')
      .shape('base')
      .style({
        opacity: 1.0,
        radius: 40,
        globalOptions: {
          ambientRatio: 0.6, // 环境光
          diffuseRatio: 0.4, // 漫反射
          specularRatio: 0.1, // 高光反射
          earthTime: 0.1,
        },
      });

    const points = new PointLayer({}).source({
        "type": "FeatureCollection",
        "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
        "features": [
          { "type": "Feature", "properties": { "id": "ak16994521", "mag": 2.3, "time": 1507425650893, "felt": null, "tsunami": 0 }, "geometry": { "type": "Point", "coordinates": [ -151.5129, 63.1016, 0.0 ] } },
          { "type": "Feature", "properties": { "id": "ak16994519", "mag": 1.7, "time": 1507425289659, "felt": null, "tsunami": 0 }, "geometry": { "type": "Point", "coordinates": [ -150.4048, 63.1224, 105.5 ] } },
          { "type": "Feature", "properties": { "id": "ak16994517", "mag": 1.6, "time": 1507424832518, "felt": null, "tsunami": 0 }, "geometry": { "type": "Point", "coordinates": [ -151.3597, 63.0781, 0.0 ] } },
          { "type": "Feature", "properties": { "id": "ci38021336", "mag": 1.42, "time": 1507423898710, "felt": null, "tsunami": 0 }, "geometry": { "type": "Point", "coordinates": [ -118.497, 34.299667, 7.64 ] } }
        ]
    }).shape('simple').size(25).color('mag', mag => {
      return mag > 4.5 ? '#5B8FF9' : '#5CCEA1';
    })
    .active(true)
    .style({
      opacity: 0.6,
      strokeWidth: 3
    });

    scene.on('loaded', async () => {
      scene.addLayer(earthlayer);
      scene.addLayer(points);
    });
  };

  return (
      <div id='wdmMap' style={{ width: '100%', height: '100%' }}>
      </div>
  )
}

球面上什么都没有：
![image](https://user-images.githubusercontent.com/12559180/205926997-352c900f-a5d8-4a53-8fb7-8ac2d31a6692.png)

**Comment by heiyexing** [comment]
目前 L7Draw 仅支持在平面地图（高德地图/Mapbox）中使用，并不支持在 Earth 地图上使用，主要是因为底层对 Earth 地图中鼠标事件无法与平面地图打平造成的
