### ISSUE TITLE
popup的内容可以是一个React的组件吗？

### ISSUE THREAD

**Issue by tanglm4346** [antvis/L7#153]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by tanglm4346** [comment]
目前 popup提供了两个添加content的方法 ：setText和setHtml.
setText过于简单，而setHtml需要拼接html的字符串用起来很不方便。希望popup能够接受React组件

**Comment by ParryQiu** [comment]
组件渲染后的本质也还是 HTML 啊。
https://stackoverflow.com/questions/48916901/possible-to-render-react-component-within-mapboxgl-popup-in-sethtml-or-setdo

**Comment by lzxue** [comment]
你可以看一下这个 https://github.com/lzxue/l7-react/blob/master/src/component/popup.js#L33
