### ISSUE TITLE
语法错误？为什么是removeAllMakers

### ISSUE THREAD

**Issue by CJuNing** [antvis/L7#1538]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

`scene`的关于标签的api都是 `marker`

- `scene.addMarker()`

- `scene.addMarkerLayer()`

- `scene.addMarkerLayer()`

只有一个移除所有标签是 `maker`

- `scene.removeAllMakers()`

是手抖了导致语法错误？ （X

**Comment by lzxue** [comment]
你需要什么接口？

**Comment by Dreammy23** [comment]
是想问为什么只有removeAllMakers中使用了marker的复数形式吗？

**Comment by lzxue** [comment]
拼写错误
