### ISSUE TITLE
pointLater uses the png tag, which has a chance of blurring the image instead of displaying the original image.

### ISSUE THREAD

**Issue by Liang-Ben** [antvis/L7#1542]
* **L7 Version**:
@2.10.1
* **Platform**:
Vue3
* **Mini Showcase(like screenshots)**:

* **CodePen Link**:
    initIconLayer() {
      let zoom = scene.getZoom();
      scene.addImage("marker4", "/static/img/busStop4.png");
      pointIconFontLayer = new PointLayer({ zIndex: 11 })
        .source(JSON.parse(JSON.stringify(this.busStationData)), {
          parser: {
            type: "json",
            coordinates: "position",
          },
        })
        .size(15)
        .shape("marker4")
        .color("#fff")
        .style({
          offsets: [0, -10]
        });
      scene.addLayer(pointIconFontLayer);
    }

使用一张png给点图层做标记，有时候可以加载出原图，也有时候加载的不是原图，而是加载了一个相对于原图边界模糊了很多，只有纯色的图片（能看出是基于原图加载的，但效果差很多）。

**Comment by yiiiiiiqianyao** [comment]
去掉 color 方法，color 的颜色值会覆盖贴图
