### ISSUE TITLE
图层反选

### ISSUE THREAD

**Issue by lyydhy** [antvis/L7#1543]
使用

data = {
    type: 'FeatureCollection',
   features: [{
type: 'Feature',
        geometry: {
          type: 'Polygon',
          coordinates: [
            [
              [-180, 90],
              [180, 90],
              [180, -90],
              [-180, -90],
            ],
            ...coord
          ]
        }
}
   ]
}
这样的数据来进行反选图层 出现图层不正确

复现地址  
https://vue-d246t1.stackblitz.io

**Comment by lzxue** [comment]
坐标范围超出了吧

**Comment by lyydhy** [comment]
没有超出范围  这串geojson数据 我在mapbox上是ok的  但是用l7 的图层添加就不行
