### ISSUE TITLE
scene.exportPng 未能成功导出 renderCanvas 上的图片

### ISSUE THREAD

**Issue by heiyexing** [antvis/L7#1546]
* **L7 Version**:
2.12.0
* **Platform**:
chrome
* **Mini Showcase(like screenshots)**:
https://codesandbox.io/s/pensive-grass-rk7vb4?file=/App.tsx:0-2070
* **CodePen Link**:
-

scene.exportPng 未能成功导出 renderCanvas 上的图片

https://github.com/antvis/L7/blob/55ae0001c92b2400b193ca05da127bb989a20565/packages/core/src/services/scene/SceneService.ts#L341-L349

**Comment by lzxue** [comment]
this.render 方法目前是异步方法，导致没有渲染完成就导出了。exportMap 也应该是异步，新的版本修改，同样使用时按照异步方法使用。

![image](https://user-images.githubusercontent.com/4366658/208665105-100d441d-bd24-4e23-866f-46148e2e4956.png)

**Comment by heiyexing** [comment]
ok
