### ISSUE TITLE
L7 2.0事件监听报错

### ISSUE THREAD

**Issue by photino** [antvis/L7#155]
* **L7 Version**: 2.0
* **Platform**: Win 10
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

`scene.on('mapmove', () => ())` 报错：`TypeError: Cannot read property 'on' of undefined`

**Comment by lzxue** [comment]
scene 初始化是异步操作，scene的交互方法需要loaded完成后执行
```javascript
scene.on('loaded',()=>{
}) 
```
