### ISSUE TITLE
L7 2.0生产环境输出Log

### ISSUE THREAD

**Issue by photino** [antvis/L7#156]
* **L7 Version**: 2.0.0.min.js
* **Platform**: Windows
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/3446306/72236706-ea833500-3612-11ea-933d-676d22cd9a79.png)

* **CodePen Link**:

生产环境下console.log的内容不需要输出

**Comment by lzxue** [comment]
2.0.2版本已修复
