### ISSUE TITLE
scene 的 selectend 事件期望也返回像数坐标

### ISSUE THREAD

**Issue by lvisei** [antvis/L7#1560]
## 期望 selectend 事件期望也返回像数坐标
```ts

this.scene?.on('selectend', (bbox, pxBbox) => {
  this.layer.boxSelect(pxBbox, (features: Record<string, any>[]) => {
    console.log('features: ', features);
  });
})
```

**Comment by heiyexing** [comment]
![image](https://user-images.githubusercontent.com/29321750/211449248-42d4432c-6718-49ec-82fe-bb38dccdae60.png)
![image](https://user-images.githubusercontent.com/29321750/211449293-c422e143-8406-41d0-afff-0be3abc93380.png)

当前 `selectend` 是会把两个事件对外透出的

**Comment by lvisei** [comment]
xy 是 boxSelect 方法要的参数吗 @heiyexing

**Comment by heiyexing** [comment]
https://codesandbox.io/s/4ez9ym?file=/App.tsx YJGB

**Comment by heiyexing** [comment]
x,y 是鼠标以地图左上角为原点的坐标，可以直接传入 layer.boxSelect 的第一个参数中使用
