### ISSUE TITLE
[Bug] 图标图层在不同 ratio 的屏幕下，图标大小不一致

### ISSUE THREAD

**Issue by heiyexing** [antvis/L7#1567]
* **L7 Version**: 2.13.1
* **Platform**: macos + chrome
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/29321750/211446660-45ed1f63-1bab-4423-8abd-44360a24c4a1.png)
![image](https://user-images.githubusercontent.com/29321750/211446683-6da34f14-2e03-4fe6-92dc-7e41f059692a.png)

* **CodePen Link**:

**Comment by lzxue** [comment]
验证后没有问题
