### ISSUE TITLE
请问AntV l7交流钉钉群在哪里，实在找不到

### ISSUE THREAD

**Issue by jingyun6** [antvis/L7#1570]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by heiyexing** [comment]
![original](https://user-images.githubusercontent.com/29321750/212226590-2ce95665-83b2-49dc-b4aa-0576f0be0d7d.png)

**Comment by jingyun6** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/L7"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月13日(星期五) 上午10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/L7] 请问AntV l7交流钉钉群在哪里，实在找不到 (Issue #1570)
