### ISSUE TITLE
Map 底图情况下 Draw 不能正常绘制

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#1571]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lzxue** [comment]
已在 L7Draw 修复

**Comment by fatesq** [comment]
> 已在 L7Draw 修复

 version: 'SIMPLE',的时候依然不能正常绘制

**Comment by muyu66** [comment]
> > 已在 L7Draw 修复
> 
> version: 'SIMPLE',的时候依然不能正常绘制



> 已在 L7Draw 修复

希望l7draw能 支持simple坐标系
