### ISSUE TITLE
官网某些重要模块404

### ISSUE THREAD

**Issue by elias4ty** [antvis/L7#1585]
L7官网（http://antv.antfin.com/zh-cn/l7/1.x/index.html）的“API 教程“（https://www.yuque.com/antv/l7/vgo25g）和“开始使用“、“使用教程“（https://www.yuque.com/antv/l7/wyb66y），点击跳转后显示语雀 404

**Comment by lzxue** [comment]
为什么还在使用 1.x 版本的文档

https://l7.antv.antgroup.com/

**Comment by elias4ty** [comment]
antv 官网跳转L7就是1.x版本
