### ISSUE TITLE
shape参数使用函数时，imageId为空的图标渲染有误

### ISSUE THREAD

**Issue by qiulinFV** [antvis/L7#1588]
问题描述：
1）地图上先添加"arrBlue"图片，再添加"arrRed"图片时，
2）设置layer.shape("name", (v) => {
      if (v === "test1") return "arrRed";
      return "";
    })
问题：函数中return ""的点显示为"arrBlue"图标；
（如果先添加"arrRed"图片，再添加"arrBlue"图片，则所有点都显示为"arrRed"符号）

问题预期：
函数中return ""的点应该不显示任何符号；

CodePen Link: 
https://codesandbox.io/s/youthful-buck-lmop21?file=/index.ts

**Comment by lzxue** [comment]
shape 目前支持空，可以过滤一下数据
```ts
   .size(30)
    .filter('name',(v)=>v === "test1")
    .shape("name", (v) => {
      if (v === "test1") return "arrRed";
    })
```

https://codesandbox.io/s/hardcore-breeze-gch48z

**Comment by qiulinFV** [comment]
你说的方法可以绕过这个问题；但这个问题仍然存在，
请问是否有计划按照，函数中return ""的情况的不显示任何符号，的预期处理这个问题呢。

**Comment by lzxue** [comment]
> 感谢回复，你说的方法可以绕过这个问题； 但这个问题仍然存在，请问是否有计划按照，函数中return ""的情况的不显示任何符号，的预期处理这个问题呢。

可以的，会考虑如何处理
