### ISSUE TITLE
Feature: Shape 为‘text'的 PointLayer 不能设置字体的 fontStyle: 'normal/italic'

### ISSUE THREAD

**Issue by seanzb1985** [antvis/L7#1602]
Feature需求： Shape 为‘text'的 PointLayer文字图层， Sytle 不支持设置字体的 fontStyle: 'normal/italic'
期望： 文字PointLayer图层Style支持 "正常、斜体"。

**Comment by lzxue** [comment]
L7 字体绘制使用了Canvas 绘制模板，L7 fontsyle 只要canvas 支持，就都支持

 ctx.font = `${fontWeight} ${fontSize}px ${fontFamily}`;

**Comment by lzxue** [comment]
看你提了不少有建设性的issue，可以在钉钉群找到我联系我

**Comment by seanzb1985** [comment]
好的，请问钉钉群号是什么，怎么能加到你？

**Comment by lzxue** [comment]
> 好的，请问钉钉群号是什么，怎么能加到你？
可加微信 think-gis
