### ISSUE TITLE
Feature: 对于Shape为Text的文字Layer的Style包含的所有属性都可以支持数据映射 

### ISSUE THREAD

**Issue by seanzb1985** [antvis/L7#1606]
目前对于文字Layer(shape="text" 的PointLayer), style中fontFamily， fontWeight 等不支持数据映射
需求： 我们对一些地图的Datalabel设置条件格式化，某些特殊的文字提供特殊的数据标签字体样式，包括文字大小，字体样式等，如首都“北京”想应用一个特殊的字体来标识。
期望： style中的所有属性都能支持数据映射， 如下：
`style: {
   fontFamily: (prop) => {return props.fontFamaily;}
}`

**Comment by lzxue** [comment]
这种粒度的支撑复杂度有点高，建议单独加个图层。
