### ISSUE TITLE
请问为什么L7的layer要单独画在一个canvas上面， 而不是画在地图的canvas上面

### ISSUE THREAD

**Issue by YOUYOUNG** [antvis/L7#1611]
* **L7 Version**: 任意
* **Platform**:  windows 10
* **Mini Showcase(like screenshots)**: 无
* **CodePen Link**: 无

请问为什么L7要单独画在一个canvas上面， 而不是画在地图的canvas上面

**Comment by lzxue** [comment]
L7 渲染和地图渲染是独立的WebGL上下文

**Comment by YOUYOUNG** [comment]
那L7如果使用地图的WebGL上下文渲染， 会有什么问题吗
设计两个独立的WebGL上下文的原因是什么呢
像是mapbox有个customLayer, 可以叠加用户自定义的图层（例如：three）

**Comment by lzxue** [comment]
> 那L7如果使用地图的WebGL上下文渲染， 会有什么问题吗 设计两个独立的WebGL上下文的原因是什么呢 像是mapbox有个customLayer, 可以叠加用户自定义的图层（例如：three）

首先底图需要支持，比如mapbox提供了customlayer,
