### ISSUE TITLE
setData方法使用时产生报错，显示BaseLayer的log为undefined

### ISSUE THREAD

**Issue by PiKesi522** [antvis/L7#1628]
* **L7 Version**:  2.13.7
* **Platform**: Chrome 100.0.4896.88
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/73263112/221881706-d814f3ae-1a1d-44b4-b012-bbf8c9cce1f3.png)

* **CodePen Link**:

当scene加载完成之后，使用useEffect在对其中的Layer进行更新数据。但是使用setData方法会产生上述报错，其中data为geoJson格式数据，应该可以排除数据格式问题

dataSource结构和setData的Layers如下：
![image](https://user-images.githubusercontent.com/73263112/221883432-8b5294cd-fc62-4c78-8e7e-b7b70f85dd96.png)

**Comment by lzxue** [comment]
@yiiiiiiqianyao

**Comment by yiiiiiiqianyao** [comment]
新版本已经修复这个问题，升级版本即可

**Comment by PiKesi522** [comment]
> 新版本已经修复这个问题，升级版本即可

![image](https://user-images.githubusercontent.com/73263112/222165330-9e73fcad-4e6d-4df3-9589-51ae7d91b290.png)
更新到2.13.9版本后出现这个报错
