### ISSUE TITLE
需求：可否增加文字标注的背景颜色设置

### ISSUE THREAD

**Issue by bigfacewo** [antvis/L7#1653]
需求描述：

在使用文字标注时，文字颜色存在和地图背景文字难以区分，并且可能存在重叠的情况：
![image](https://user-images.githubusercontent.com/31603897/225541020-3840c767-b402-490b-9759-d91ebabd086e.png)

如果此时增加一个文字背景，那么就好区分了，如：
![image](https://user-images.githubusercontent.com/31603897/225541273-2b126fe2-5e51-4c93-9fb0-e34ce11ffa2a.png)

**Comment by lzxue** [comment]
stroke 、strokewidth 参数设置，可以实现
