### ISSUE TITLE
在使用stroke 、strokewidth来模拟文字背景颜色时，出现了文字模糊的问题

### ISSUE THREAD

**Issue by bigfacewo** [antvis/L7#1654]
问题：

在使用stroke 、strokewidth来模拟文字背景颜色时，出现了文字模糊的情况：

![image](https://user-images.githubusercontent.com/31603897/225549283-3458c0b1-7c27-44b7-91cf-6fadf8b20181.png)

核心代码如下：

```
  const pointLayer = new PointLayer({})
    .source(data)
    .shape('类别', 'text')
    .size(60)
    .color('细分', [ '#1e1030', '#2e2030', '#3e3030' ])
    .style({
      stroke: '#fff',
      strokeWidth: 100
    })
  scene.addLayer(pointLayer);
  const layerPopup = new LayerPopup({
        items: [
          {
            layer: pointLayer,
            fields: ['类别','细分'],
          },
        ],
      });
  scene.addPopup(layerPopup) 
```

效果复现；https://codesandbox.io/s/02uowv

L7：2.14.5
L7-maps: 2.14.5

**Comment by lzxue** [comment]
strokeWidth 可以设置的小一点，文字一般绘制描边当背景，文字也不需要太大

**Comment by bigfacewo** [comment]
这个主要是考虑将大小编码也应用到文字标记上，参考tableau的效果做的。在tableau中，如果将size最大值设置得较大，确实会出现文字较大得情况。
