### ISSUE TITLE
问题：请问点图层中的scala是否可以将数据映射到形状？

### ISSUE THREAD

**Issue by bigfacewo** [antvis/L7#1655]
我在文档https://l7.antv.antgroup.com/api/polygon_layer/scale中看到：

> scale 方法设置数据字段映射方法，用于设将地图数据值（数字、日期、类别等数据）转成视觉值（颜色、大小、形状）。尺度 Scale 是数据可视化的基本组成部分，因为它们决定了视觉编码的性质。

看上去该方法应该支持将数据映射到形状，但是文档中没有给出例子。

请问scala是否可以将数据映射到形状呢？如果不可以，是否有其他方法？

L7: 2.14.5

**Comment by lzxue** [comment]
https://l7.antv.antgroup.com/examples/point/bubble/#color  颜色和shape 映射demo

https://l7.antv.antgroup.com/tutorial/scale scale

**Comment by bigfacewo** [comment]
看了例子明白了。

之前主要看文档，发现好像没有shape(fieldName, [shap1,shap2,...])这个用法。

非常感谢。
