### ISSUE TITLE
LayerPopup 图层气泡能够和面图层一起使用么？

### ISSUE THREAD

**Issue by bigfacewo** [antvis/L7#1660]
LayerPopup 图层气泡能够和面图层一起使用么？

LayerPopup 能够和pointLayer一起使用，但是似乎不能面图层一起使用，官方示例https://l7.antv.antgroup.com/zh/examples/polygon/fill/#usa 中是自定义Popup来实现的。

l7：2.14.5

**Comment by heiyexing** [comment]
可以和 PolygonLayer 一起使用的，只是示例中没有演示。
