### ISSUE TITLE
Marker在移动端不能被点击

### ISSUE THREAD

**Issue by xunzhaoliuxingluo** [antvis/L7#1689]
* **L7 Version**:2.15.2
* **Platform**:windows11 chrome 112.0.5615.138
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://react-yahjwh.stackblitz.io

在移动端浏览器点击Marker无效，Popup也不行。

**Comment by lzxue** [comment]
如果只是移动端使用，可以监听 touchend 事件
