### ISSUE TITLE
邮箱绑定有点问题

### ISSUE THREAD

**Issue by afc163** [antvis/L7#17]
<img width="296" alt="图片" src="https://user-images.githubusercontent.com/507615/63639561-534f2c80-c6c7-11e9-82f7-d4004effa95c.png">

**Comment by lzxue** [comment]
内部gitlab项目，直接提交山来的，会有内部账户，或者直接master分支提交都会是象数账户，后面GitHub账户 pr 的形式提交就没问题了

**Comment by lzxue** [comment]
已解决
