### ISSUE TITLE
L7-darw 改变地图时报错： Error: (regl) invalid render buffer format

### ISSUE THREAD

**Issue by zhang5530** [antvis/L7#1705]
应业务需求，绘图页增加全屏、展开显示侧栏功能，当地图尺寸发生变化时，就会报这个错误。

![QQ截图20230517093731](https://github.com/antvis/L7/assets/133831271/ae19a3bc-4974-4867-894d-e037349bea37)

**Comment by lzxue** [comment]
提供一下复现 Demo
