### ISSUE TITLE
mapbox实例如何添加指北针

### ISSUE THREAD

**Issue by zwh0711** [antvis/L7#1707]
* **L7 Version**:2.15.4
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
 scene = new Map.Scene({
        id: "map",
        logoVisible: false,
        map: new Mapbox({
          style: config.value.baseMapStyle,
          center: [config.value.center_lng, config.value.center_lat],
          pitch: config.value.pitch,
          zoom: config.value.zoom_level,
          token: process.env.VUE_APP_MAPBOX_TOKEN,
        }),
      })
实例化了一个mapbox地图，应该如何添加指北针？谢谢，官方文档中并没有提供指北针的组件

**Comment by lzxue** [comment]
如果mapbox 有指北针方法可以直接调用，map 的方法。

**Comment by zwh0711** [comment]
map.addControl(new mapboxgl.NavigationControl(), "bottom-left")
这是mapbox调用指北针的方法 
但如果我在l7中直接调用map执行addControl，会出现报错
scene.map.addControl(new mapboxgl.NavigationControl(), "bottom-left")
![image](https://github.com/antvis/L7/assets/16575345/ab4773a6-7908-48ca-a951-cb085ea18279)
调用map的写法应该没有问题，因为我在类似的调用map的其他方法如scene.map.queryRenderedFeatures(bbox);就可以获得正确的结果，只有addControl这个方法会这样
