### ISSUE TITLE
地图点击事件触发时，如何判断当前的点击位置是否有图层要素？

### ISSUE THREAD

**Issue by zwh0711** [antvis/L7#1713]
scene.on('click', (ev) => {});
我在使用地图点击事件是，希望获取当前点击位置上加载的图层要素，l7是否有类似于mapbox中根据范围获取feature的方法map.queryRenderedFeatures(bbox)？
这样就不必给每个layer都注册点击事件，而是可以在地图上进行统一处理

**Comment by lzxue** [comment]
目前没有可以考虑增加
