### ISSUE TITLE
升级最新版本后，mapTexture不生效

### ISSUE THREAD

**Issue by jiaicon** [antvis/L7#1719]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

eg: https://codesandbox.io/s/upbeat-archimedes-oz9h26?file=/index.js:731-741

之前使用mapTexture有个显卡下会出现花屏的问题，可以看这两个issue：
https://github.com/antvis/L7/issues/1127
https://github.com/antvis/L7/issues/1127
今天升级到最新版本不能使用了。

**Comment by lzxue** [comment]
mapTexture 纹理这块有什么诉求，这块功能计划升级

**Comment by jiaicon** [comment]
> mapTexture 纹理这块有什么诉求，这块功能计划升级

新版本中mapTexture不生效，可以看上面的例子

**Comment by LaraineR** [comment]
> mapTexture 纹理这块有什么诉求，这块功能计划升级

请问目前新版本的L7还是不支持mapTexture是吗？

**Comment by lzxue** [comment]
https://codesandbox.io/s/cranky-elion-4sd4hf 最新版本的已经支持了，感谢关注
