### ISSUE TITLE
自定义图标模糊且不规则问题

### ISSUE THREAD

**Issue by kenary** [antvis/L7#172]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

使用PointLayer自定义图标问题
1.图标压缩模糊
2.最好能使用图标原始默认尺寸
![1](https://user-images.githubusercontent.com/43365633/72769915-4ebb7f80-3c37-11ea-8c57-75bf18bd719c.png)
![2](https://user-images.githubusercontent.com/43365633/72769917-4f541600-3c37-11ea-8bf9-61a5a007510f.png)

**Comment by LiuJianhuo** [comment]
> * **L7 Version**:
> * **Platform**:
> * **Mini Showcase(like screenshots)**:
> * **CodePen Link**:
> 
> 使用PointLayer自定义图标问题 1.图标压缩模糊 2.最好能使用图标原始默认尺寸 ![1](https://user-images.githubusercontent.com/43365633/72769915-4ebb7f80-3c37-11ea-8c57-75bf18bd719c.png) ![2](https://user-images.githubusercontent.com/43365633/72769917-4f541600-3c37-11ea-8bf9-61a5a007510f.png)

你解决了最后
