### ISSUE TITLE
显示点聚合的数量时，过滤为point_count为1的点，文字会重影

### ISSUE THREAD

**Issue by zhouyinchi** [antvis/L7#1723]
* **L7 Version**:最新
* **Platform**:
* **Mini Showcase(like screenshots)**:<img width="616" alt="image" src="https://github.com/antvis/L7/assets/38196296/91786703-038c-4df5-8f78-80ba4506645c">
* **CodePen Link**: https://codesandbox.io/s/suspicious-murdock-38khi6

地图缩放，就能复现这个问题

**Comment by zhouyinchi** [comment]
<img width="539" alt="image" src="https://github.com/antvis/L7/assets/38196296/dbdcd7d4-90da-4b3d-9a19-6817a6a424f1">
需求是过滤为聚合数量为1 的用其他PointLayer 展示，但是过滤了就会出现上面重影的问题

**Comment by lzxue** [comment]
好像是只有filter 的时候会有问题

**Comment by lzxue** [comment]
临时解决办法, 允许文本覆盖

```ts
style({
 textAllowOverlap: true
})

```

**Comment by zhouyinchi** [comment]
> 临时解决办法, 允许文本覆盖
> 
> ```ts
> style({
>  textAllowOverlap: true
> })
> ```

试过这个办法；但是这个办法会隐藏掉一部分的数字，即导致部分聚合的数字不显示，就失去了聚合的意义
