### ISSUE TITLE
行政区域的经纬度,比如某省省会的经纬度,有方便的方法获取吗

### ISSUE THREAD

**Issue by KuduroJS** [antvis/L7#1736]
数据来自l7的地图工具
https://l7.antv.antgroup.com/custom/tools

期望通过adcode获取某省/市/区的经纬度

因为name或adcode和各开源数据未必完全匹配,想咨询一下官方的方案.

谢谢

**Comment by lzxue** [comment]
中心经纬度还是围栏坐标

**Comment by KuduroJS** [comment]
> 中心经纬度还是围栏坐标

中心呢

**Comment by lzxue** [comment]
目前可以自己通过围栏经纬度前端计算中心点

**Comment by KuduroJS** [comment]
了解 谢谢
