### ISSUE TITLE
l7 destory 有概率  (regl) buffer must not be deleted already

### ISSUE THREAD

**Issue by adolfheir** [antvis/L7#1742]
昨天更新了下依赖包
<img width="422" alt="image" src="https://github.com/antvis/L7/assets/26828649/e3ae88d7-7260-4200-b964-81f68a6e70ba">
然后在快速切换页面的时候l7有概率报错导致白屏
这是报错日志
![image](https://github.com/antvis/L7/assets/26828649/34883d16-87bf-408a-afbb-c2ef3a749fb1)

[127.0.0.1-1687141796964.log](https://github.com/antvis/L7/files/11783518/127.0.0.1-1687141796964.log)

**Comment by adolfheir** [comment]
我调了下 buffer must not be deleted already这个报错是因为buffer destory 调了2次 导致的 
![image](https://github.com/antvis/L7/assets/26828649/10610ba1-cadb-4d34-8630-b7f8775251cb)
调2次应该是
![image](https://github.com/antvis/L7/assets/26828649/bd43582b-0174-4106-bd0b-269743fc1b74)
![image](https://github.com/antvis/L7/assets/26828649/b9dab000-2fe0-4391-b904-c6b2aff35227)
这2个函数都调了style 的clearAllAttributes
![image](https://github.com/antvis/L7/assets/26828649/7428f6ee-4b6a-4a5c-91f8-8137620c2847)
怀疑中间哪里有异步竞争或者一个buffer给了不同的styleAttributeService不然clearAllAttributes本身是同步的 不应该会有竞争

调试代码
<img width="828" alt="image" src="https://github.com/antvis/L7/assets/26828649/609877fa-ba16-4aa8-9bd6-c95ec994f362">

调试日志

[127.0.0.1-1687167562507.log](https://github.com/antvis/L7/files/11786945/127.0.0.1-1687167562507.log)

**Comment by Vincent-bin** [comment]
我也遇上了同样的问题，尤其是我使用L7Plot上添加多个Plot再removeAllPlots的时候，可以稳定复现。

**Comment by adolfheir** [comment]
> 我也遇上了同样的问题，尤其是我使用L7Plot上添加多个Plot再removeAllPlots的时候，可以稳定复现。

我没去定位具体发生原因 不过临时处理方案挺简单的。可以先手动给l7regl 做个防护 打个补丁  
[l7regl@0.0.20.patch](https://github.com/antvis/L7/files/11859238/l7regl%400.0.20.patch)

**Comment by qxz123456** [comment]
2.15.5版本的问题，暂时回退到2.15.4就行，啥时候这个问题解决了，再升上来

**Comment by qxz123456** [comment]
> > 我也遇上了同样的问题，尤其是我使用L7Plot上添加多个Plot再removeAllPlots的时候，可以稳定复现。
> 
> 我没去定位具体发生原因 不过临时处理方案挺简单的。可以先手动给l7regl 做个防护 打个补丁 [l7regl@0.0.20.patch](https://github.com/antvis/L7/files/11859238/l7regl%400.0.20.patch)

2.15.5版本的问题，暂时回退到2.15.4就行，啥时候这个问题解决了，再升上来

**Comment by qxz123456** [comment]
> > 我也遇上了同样的问题，尤其是我使用L7Plot上添加多个Plot再removeAllPlots的时候，可以稳定复现。
> 
> 我没去定位具体发生原因 不过临时处理方案挺简单的。可以先手动给l7regl 做个防护 打个补丁 [l7regl@0.0.20.patch](https://github.com/antvis/L7/files/11859238/l7regl%400.0.20.patch)

为啥你这版本都导2.16了，我这最新install的版本才是2.15.5，同样是这个问题，我回退到2.15.4就好了

**Comment by adolfheir** [comment]
> > > 我也遇上了同样的问题，尤其是我使用L7Plot上添加多个Plot再removeAllPlots的时候，可以稳定复现。
> > 
> > 
> > 我没去定位具体发生原因 不过临时处理方案挺简单的。可以先手动给l7regl 做个防护 打个补丁 [l7regl@0.0.20.patch](https://github.com/antvis/L7/files/11859238/l7regl%400.0.20.patch)
> 
> 为啥你这版本都导2.16了，我这最新install的版本才是2.15.5，同样是这个问题，我回退到2.15.4就好了

你锁大版本号了呗

**Comment by qxz123456** [comment]
> > > > 我也遇上了同样的问题，尤其是我使用L7Plot上添加多个Plot再removeAllPlots的时候，可以稳定复现。
> > > 
> > > 
> > > 我没去定位具体发生原因 不过临时处理方案挺简单的。可以先手动给l7regl 做个防护 打个补丁 [l7regl@0.0.20.patch](https://github.com/antvis/L7/files/11859238/l7regl%400.0.20.patch)
> > 
> > 
> > 为啥你这版本都导2.16了，我这最新install的版本才是2.15.5，同样是这个问题，我回退到2.15.4就好了
> 
> 你锁大版本号了呗

 "@antv/l7": "^2.15.4",  锁的是主版本

**Comment by xiaomoziyi** [comment]
2.17.2版本同样复现，能尽快修复吗 @Vincent-bin
