### ISSUE TITLE
线图层，漂移

### ISSUE THREAD

**Issue by QLLNNH** [antvis/L7#1744]
* **L7 Version**:2.16.1
* **Platform**:Chrome 114
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

在渲染线图层时，部分线段发生浮动，漂移，渲染结果与QGIS或者geojson.io不符。
图1是geojson.io的渲染。
图2是L7maobox的渲染（高德情况一样）。
附件是出错的geojson文件。
![1](https://github.com/antvis/L7/assets/9846330/d15db898-45a0-4ec1-93cf-51e5a4b1da87)
![2](https://github.com/antvis/L7/assets/9846330/eae4635e-571e-4e1b-a645-e5aeb623bf23)

[11C.zip](https://github.com/antvis/L7/files/11796398/11C.zip)

**Comment by lzxue** [comment]
![image](https://github.com/antvis/L7/assets/4366658/bd00f220-ebec-470a-a9c3-851b289eaa66)
线坐标里面高度导致的
