### ISSUE TITLE
用mapbox加载EPSG：4326的地图后，移动地图图层会上下移动

### ISSUE THREAD

**Issue by hchaoe** [antvis/L7#1747]
用mapbox加载EPSG：4326的地图后，用layer标绘图层后在移动地图时标绘图层会上下移动，如果用marker加载的标绘图层就不会有这个问题，请问要如何解决？
vue2
antvl7 2.16.1

**Comment by hchaoe** [comment]
![cdbc7af4fe35cced84e0bd036a336c5](https://github.com/antvis/L7/assets/138205319/1a754921-8f74-48b2-b59d-1b76e8d81a3c)
![fdb6675f98feb9af828c3d8fd8ff49a](https://github.com/antvis/L7/assets/138205319/2b6df9c4-4f53-424d-9762-8f4c4ee96586)

**Comment by lzxue** [comment]
目前还不支持 4326 底图
