### ISSUE TITLE
将地图保存为图片时出现问题

### ISSUE THREAD

**Issue by zhaojiuyi123** [antvis/L7#1756]
这是我完成的绘制
![image](https://github.com/antvis/L7/assets/136292153/5f60af89-2323-4b71-95f6-6f8aefef7522)
当我使用htmlToCanvas.toPng保存为图片后，标注的圆点消失了，效果如下
![image](https://github.com/antvis/L7/assets/136292153/4810de6e-5c97-4d56-b4b2-0b9f6484dc0b)

**Comment by lzxue** [comment]
建议使用 L7 自带导出方法
 https://l7.antv.antgroup.com/api/scene#exportmaptype-iimage-string-%E5%AF%BC%E5%87%BA
