### ISSUE TITLE
打包错误

### ISSUE THREAD

**Issue by xiaochong44** [antvis/L7#1759]
* **L7 Version**:2.17.4
* **Platform**:vite
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

node_modules/@antv/l7-component/es/index.js:3:7: error: Could not resolve "./assets/iconfont/iconfont.js"
    3 │ import "./assets/iconfont/iconfont.js"; // 引入样式
      ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 1 error:
node_modules/@antv/l7-component/es/index.js:3:7: error: Could not resolve "./assets/iconfont/iconfont.js"
    at failureErrorWithLog

**Comment by lzxue** [comment]
@heiyexing
