### ISSUE TITLE
LineLayer.style 动态改变线形为虚线设置不生效

### ISSUE THREAD

**Issue by KelseyYau** [antvis/L7#1761]
* **L7 Version**: 2.17.4
* **Platform**: windows 10
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

先创建一个实线的LineLayer 并添加到地图上，然后动态修改为虚线
import { Scene, LineLayer } from '@antv/l7';
import { GaodeMap } from '@antv/l7-maps';

const scene = new Scene({
  id: 'map',
  map: new GaodeMap({
    center: [ 116.3956, 39.9392 ],
    pitch: 20,
    zoom: 10,
    style: 'dark'
  })
});
scene.on('loaded', () => {
  fetch(
    'https://gw.alipayobjects.com/os/basement_prod/0d2f0113-f48b-4db9-8adc-a3937243d5a3.json'
  )
    .then(res => res.json())
    .then(data => {
      const layer = new LineLayer({})
        .source(data)
        .size(2)
        .shape('line')
        .color('标准名称', [ '#5B8FF9', '#5CCEA1', '#F6BD16' ])
        .style({
          borderWidth: 0.4,
          borderColor: '#fff'
        });
      scene.addLayer(layer);

      // 延时3秒改为虚线
      setTimeout(() => {
        layer.style({
          lineType: 'dash',
          dashArray: [5, 5]
        })
        scene.render()
      }, 3000)
    });
});
并不能生效

**Comment by lzxue** [comment]
今天会修复
