### ISSUE TITLE
网格世界地图demo报错

### ISSUE THREAD

**Issue by riluo** [antvis/L7#1767]
案例地址是这个https://l7.antv.antgroup.com/zh/examples/heatmap/grid#grid_world，已经安装后对应js组件，执行的时候报错
“Uncaught Error: Invalid Object: LngLat(NaN, NaN)”，

并且有提示“您正在使用 Demo 测试 Token, 生产环境务必自行注册 Token 确保服务稳定!_”

文档写的不太清楚，应该有所遗漏，查看帮助文档也没有找到方法，只好来此求助。

**Comment by lzxue** [comment]
token 的问题，使用高德需要自己申请token的

**Comment by lzxue** [comment]
使用高德地图需要自己申请token，L7提供的试用token
