### ISSUE TITLE
通过 click 方式创建 Popup 同时触发 closeOnClick 问题   该问题依旧存在

### ISSUE THREAD

**Issue by nanvon** [antvis/L7#1771]
* **L7 Version**:^2.17.4
* **Platform**:Chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://codesandbox.io/s/amazing-meadow-g6rfc4?file=/index.ts

使用官网的样例（见上述 CodeSandbox 链接），手动改为 click 触发 Popup，无法显示 Popup 层，并且控制台显示触发了 hide 事件。

https://github.com/antvis/L7/pull/1479 我发现这个问题曾被修复过，但依旧存在这个问题。

**Comment by lzxue** [comment]
这边排查一下

**Comment by heiyexing** [comment]
之前的 PR 修复的是 Popup + click + closeOnClick 的 Bug ，LayerPopup 这边比较特殊，先不要开启 clickOnClick

**Comment by nanvon** [comment]
> 之前的 PR 修复的是 Popup + click + closeOnClick 的 Bug ，LayerPopup 这边比较特殊，先不要开启 clickOnClick

@heiyexing 这个 Bug 先不修复吗？还是说后续会修复？
