### ISSUE TITLE
线设置为虚线后不支持抬高

### ISSUE THREAD

**Issue by szygiser** [antvis/L7#1774]
![e067ac65d123cf0ae0b5859bd8ddfbc2](https://github.com/antvis/L7/assets/15412933/7689ec3d-31b4-4392-8aaa-64c14d573e11)
//具体复现代码如下：
import { Scene, LineLayer } from '@antv/l7';
import { GaodeMap } from '@antv/l7-maps';

const scene = new Scene({
  id: 'map',
  map: new GaodeMap({
    center: [ 116.3956, 39.9392 ],
    zoom: 10,
    style: 'dark'
  })
});
scene.on('loaded', () => {
  fetch(
    'https://gw.alipayobjects.com/os/basement_prod/0d2f0113-f48b-4db9-8adc-a3937243d5a3.json'
  )
    .then(res => res.json())
    .then(data => {
      const layer = new LineLayer({})
        .source(data)
        .size(1.5)
        .shape('line')
        .color('标准名称', [ '#5B8FF9', '#5CCEA1', '#F6BD16' ])
        .style({
          lineType: 'dash',
          dashArray: [ 5, 5 ],
          raisingHeight: 142000
        })
      ;
      scene.addLayer(layer);
    });
});
![50c26746f6dd4cb3ff98962587996c98](https://github.com/antvis/L7/assets/15412933/691429b3-c2ae-4dbe-95fd-ccc787bda0b7)

**Comment by lzxue** [comment]
已记录

**Comment by szygiser** [comment]
这个问题何时修复啊，测试了下仍然不好使
