### ISSUE TITLE
mapbox的流向图显示异常

### ISSUE THREAD

**Issue by wqh81615429** [antvis/L7#1777]
**mapbox的流向图显示异常**

**Comment by lzxue** [comment]
应该官网异常，提issue 尽量明确什么问题，便于排查

**Comment by wqh81615429** [comment]
这是基于mapbox的流向图：





这是基于高德的流向图：





基于mapbox的流向图显示的样式与基于高德的差异太大，是否不正常？或者说基于mapbox的流向图还需要做其他的配置项才能正常显示？
望回复，谢谢！


_此时此刻。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/L7"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月23日(星期三) 上午10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/L7] mapbox的流向图显示异常 (Issue #1777)





 
应该官网异常，提issue 尽量明确什么问题，便于排查

**Comment by wqh81615429** [comment]
这是基于mapbox的流向图：





这是基于高德的流向图：





基于mapbox的流向图显示的样式与基于高德的差异太大，是否不正常？或者说基于mapbox的流向图还需要做其他的配置项才能正常显示？
望回复，谢谢！





_此时此刻。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/L7"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月8日(星期二) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/L7] mapbox的流向图显示异常 (Issue #1777)





 
麻烦截个图 + 提供一下代码

**Comment by lzxue** [comment]
已修复
