### ISSUE TITLE
style配置动态参数时报错

### ISSUE THREAD

**Issue by tsuyoii** [antvis/L7#1779]
例如
<img width="879" alt="image" src="https://github.com/antvis/L7/assets/49632080/e1f6f431-0219-467b-9b95-f80c8035231e">

报错
<img width="989" alt="image" src="https://github.com/antvis/L7/assets/49632080/46bcac68-f2ef-4a54-9a6e-fb8ebd1523b0">

**Comment by lzxue** [comment]
textOffset：{
field:'name',
value:()=>{
 }
}

换个写法看看

**Comment by tsuyoii** [comment]
> textOffset：{ field:'name', value:()=>{ } }
> 
> 换个写法看看

这样写没有报错，但是没展示出文字，试了一下console也没打印出来

**Comment by lzxue** [comment]
最新版本修复了bug 2.17.8

**Comment by tsuyoii** [comment]
> 最新版本修复了bug 2.17.8

终于成功了，感谢大佬
