### ISSUE TITLE
OpenGL, Performance, GL_CLOSE_PATH_NV, High

### ISSUE THREAD

**Issue by wangjiale7** [antvis/L7#1781]
在无头浏览器打开网页，使用到Mapbox-gl-js 地图底图 和 L7 的lineLayer图层，导致服务器报错
[.WebGL-0x322800306200]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels', 'source': 'rendering', 'timestamp': 

* **L7 Version**: 2.17.5
* **Platform**: 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lzxue** [comment]
应该不支持服务端渲染，什么场景使用
