### ISSUE TITLE
scene.removeLayer概率出现buffer must not be deleted already

### ISSUE THREAD

**Issue by 13554599576** [antvis/L7#1782]
* **L7 Version**:2.17.4
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://github.com/antvis/L7/assets/34908374/e9a29896-8dd0-4c94-9f8c-07103feed83d)
`scene.removeLayer` 此方法概率出现 `buffer must not be deleted already`

**Comment by lzxue** [comment]
升级到最新的已经解决了
