### ISSUE TITLE
使用iconFont标注时刷新页面无法渲染出来，只能渲染出普通的文本标注

### ISSUE THREAD

**Issue by tsuyoii** [antvis/L7#1783]
<img width="822" alt="image" src="https://github.com/antvis/L7/assets/49632080/3eb328dd-fb18-4a09-bf1c-7e5ff5a3ce09">

<img width="753" alt="image" src="https://github.com/antvis/L7/assets/49632080/44fd31ae-1466-49bd-ba65-6c491a1bae4d">

<img width="862" alt="image" src="https://github.com/antvis/L7/assets/49632080/a1cbe403-66ab-4da9-946a-7bf0078639f8">

如图，只渲染出了文本，未渲染出iconFont
但是如果我跳转到其他页面再跳转回来(未经过刷新时)，可以展示出iconFont
<img width="596" alt="image" src="https://github.com/antvis/L7/assets/49632080/110f1f62-fbd7-46a1-9735-9eeb7334a90f">

**Comment by tsuyoii** [comment]
解决了

**Comment by lzxue** [comment]
> 

什么原因，或者怎么解决的？

**Comment by tsuyoii** [comment]
加个scene.once('fontloaded', async (e) => {})
 https://blog.csdn.net/weixin_44258574/article/details/132238638

**Comment by lzxue** [comment]
感谢分享
