### ISSUE TITLE
some report

### ISSUE THREAD

**Issue by deyihu** [antvis/L7#18]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

1. demos/01_circle.html 里脚本名字有误，导致非windows平台会出现404

```html
<script src="../build/l7.js"></script>
```

2. demos/01_point_circle.html 里代码直接有误

```js
 $.get('https://gw.alipayobjects.com/os/rmsportal/epnZEheZeDgsiSjSPcCv.json', data => {
    console.log(data);
    const circleLayer = = scene.PointLayer({
      zIndex: 0,
    })
    .source(data,{
       isCluster:true
    })
```

```js
    const circleLayer = = scene.PointLayer
```
3.整个项目我刚才打包编译了一下，在sourcemap里只看到三个文件（不知是不是我运行的命令有问题,还是怎们的   ? build-dev : dist)
![5R1D3K`QLG902$T}NSW)(}1](https://user-images.githubusercontent.com/25998927/63661436-209f5400-c7ed-11e9-98f3-6212c315df4f.png)

![1ZDBI%YQ0OV$8S(I$APO@_K](https://user-images.githubusercontent.com/25998927/63661227-319b9580-c7ec-11e9-84c9-29740d47e588.png)

导致debug的时候非常困难，单个js脚本太大，浏览器容易死掉，希望可以对src整个目录下的文件进行调试,例如这样子的:

![QT $Q`4CBQMXCFD3F9`)J_V](https://user-images.githubusercontent.com/25998927/63661605-d8ccfc80-c7ed-11e9-8728-d8e8fa6eab4a.png)

4.在源码里看到了mapbox的相关MapProvider，能否提供一个简单的例子？

**Comment by lzxue** [comment]
1.问题 mac 下查看有问题
2.尽快修复
3.打包问题我们会尽快解决
4.mapbox支持问题在于高缩放等会有抖动的问题，为了兼容高德和mapbox我们下一版本重构会支持mapbox，当前版面下mapbox没有最佳实践。

多谢关注L7，希望多提PR
