### ISSUE TITLE
Point Layer 是否支持自定义的shape？

### ISSUE THREAD

**Issue by seanzb1985** [antvis/L7#1803]
目前 PointLayer 只支持一些内置的shape 类型，如
// shape 支持的各种形状
type IFillShape =
  | 'circle'
  | 'square'
  | 'hexagon'
  | 'triangle'
  | 'pentagon'
  | 'octogon'
  | 'hexagram'
  | 'rhombus'
  | 'vesica';

请问Point Layer是否可以支持自定义的Shape 类型，如果支持，请给一个参考示例。

**Comment by lzxue** [comment]
完全自定义可以使用 Marker,如果希望基于 Pointlayer 自定义可以说一下详细需求，我看看有什么方案

**Comment by seanzb1985** [comment]
Marker 是可以自定义，但是需要完全自定义dom, 不宜使用，数据量大时，可能出现性能问题，最重要的是，集成的时候，想获得和PointLayer 一样的使用体验，所以，有这样的需求：
1. 提供一个svg 的path, 这个path 描述一个自定义的几何图形，且保证这个图形是封闭的，用户可以注册这个svg icon 作为内置形状的扩展。
2 可以在PointLayer中使用这个新注册的自定义shape。 
3. 设置size属性时，可以改变大小；设置color属性时，可以对自定义shape进行颜色填充。

**Comment by lzxue** [comment]
这种两种方式实现：

- 如果是单色的图标可以使用 iconfont ,可以做支持数据映射。
-使用图片图层，但是需要先把 SVG 改成不同样式的图标，图片图层其实也可以跟进颜色映射，但是对普通要求可以试试。
