### ISSUE TITLE
传入中英文对照参数，地图没有显示中英文对照

### ISSUE THREAD

**Issue by hopperhuang** [antvis/L7#1805]
代码如下：
<img width="453" alt="image" src="https://github.com/antvis/L7/assets/20254356/cef82eb4-2d5f-4420-af0b-164be3afb2dc">
<img width="494" alt="image" src="https://github.com/antvis/L7/assets/20254356/07b56c22-1e80-4482-9955-fd605796b92d">

实际效果：
<img width="706" alt="image" src="https://github.com/antvis/L7/assets/20254356/8af84f41-8b49-421e-b143-dc29414e204d">

依赖版本：
    "@antv/l7": "^2.17.11",
    "@antv/l7-maps": "^2.17.11",

**Comment by lzxue** [comment]
这个是高德底图的配置，L7 透传的，看一下高德地图有没有生效。

**Comment by hopperhuang** [comment]
> 这个是高德底图的配置，L7 透传的，看一下高德地图有没有生效。

亲自在高德的平台上试了一下，发现他们的是可以的。但是，我发现按照这个写法，传给l7的组件是不行的。
又偷偷看了一下大佬们定义的组件，好像没有定义lang这个字段呢。大佬帮忙看看为啥呗。

大佬： 注意一下画红圈的地方。![image](https://github.com/antvis/L7/assets/20254356/b2c4a83c-eb96-4cd5-94c4-69ac1447c362)

**Comment by lzxue** [comment]
直接给个链接吧，没找到你这个demo

**Comment by hopperhuang** [comment]
https://lbs.amap.com/demo/javascript-api/example/map/map-english

**Comment by hopperhuang** [comment]
> 直接给个链接吧，没找到你这个demo

https://lbs.amap.com/demo/javascript-api/example/map/map-english

**Comment by lzxue** [comment]
试了一下高德地图 V2  不支持，你给的demo 是高德 1.4 的  

https://codesandbox.io/s/relaxed-banzai-fn98xl?file=/index.js
