### ISSUE TITLE
线图层的箭头为什么加载出来很奇怪

### ISSUE THREAD

**Issue by daiguamm** [antvis/L7#1806]
官网的demo看着也是，为什么会这样？https://l7.antv.antgroup.com/examples/line/path#arrow

**Comment by lzxue** [comment]
这个箭头有些问题，先看一下这个 https://l7.antv.antgroup.com/examples/line/flow/#flow

**Comment by daiguamm** [comment]
> 这个箭头有些问题，先看一下这个 https://l7.antv.antgroup.com/examples/line/flow/#flow

thanks
