### ISSUE TITLE
点图层pointLayer 使用自定义字体

### ISSUE THREAD

**Issue by ivan0827** [antvis/L7#1808]
L7地图的点图层中有一个API：addFontFace(fontFamily: string, fontPath: string): void 添加字体文件; 
```let fontFamily = 'iconfont';
let fontPath =
  '//at.alicdn.com/t/font_2534097_iiet9d3nekn.woff2?t=1620444089776';
scene.addFontFace(fontFamily, fontPath)
```
其中fontPath为导入的文件地址，疑惑的是下载到本地的字体文件如何在这里使用？

**Comment by lzxue** [comment]
本地路径,打包时候拷贝到本地静态路径，或者上传cdn

**Comment by ivan0827** [comment]
> 本地路径,打包时候拷贝到本地静态路径，或者上传cdn

本地路径这样用吗？ let fontPath =  ‘@/assets/font_2534097_iiet9d3nekn.woff2';还是需要import 或者 require ；

另外再插一嘴，如果想用自己切的图片是不是还是marker好扩展一点。

**Comment by lzxue** [comment]
let fontPath = ‘@/assets/font_2534097_iiet9d3nekn.woff2'; 这一种确保你的路径能访问的，这个是前端问题。

数据量不大，自定义强调使用marker 好
