### ISSUE TITLE
现象咨询---给多个相邻PolygonLayer设置active(true)，鼠标从一个面移动到另一个面，颜色不消失

### ISSUE THREAD

**Issue by GitHumburger** [antvis/L7#1809]
如下图所示
鼠标从区域1移动到区域2时，区域1的颜色不消失
![微信截图_20230830171451](https://github.com/antvis/L7/assets/49260937/1939d7ee-eaa5-43ec-b7f0-fda1cb835285)
![微信截图_20230830171523](https://github.com/antvis/L7/assets/49260937/eb8c6276-17a7-4512-ad84-1400d113269b)

**Comment by GitHumburger** [comment]
[test.zip](https://github.com/antvis/L7/files/12481278/test.zip)
请用附件本地启动查看。

**Comment by lzxue** [comment]
> [test.zip](https://github.com/antvis/L7/files/12481278/test.zip) 请用附件本地启动查看。

提供在线demo吧，如何提供在线demo https://l7.antv.antgroup.com/tutorial/demo

**Comment by GitHumburger** [comment]
额，只是一个html文件和一个json文件

**Comment by GitHumburger** [comment]
codesandbox请求同级json文件不生效

**Comment by GitHumburger** [comment]
> > [test.zip](https://github.com/antvis/L7/files/12481278/test.zip) 请用附件本地启动查看。
> 
> 提供在线demo吧，如何提供在线demo https://l7.antv.antgroup.com/tutorial/demo
额，只是一个html文件和一个json文件
codesandbox请求同级json文件不生效

**Comment by GitHumburger** [comment]
> > [test.zip](https://github.com/antvis/L7/files/12481278/test.zip) 请用附件本地启动查看。
> 
> 提供在线demo吧，如何提供在线demo https://l7.antv.antgroup.com/tutorial/demo

额，只是一个html文件和一个json文件
codesandbox请求同级json文件不生效

**Comment by lzxue** [comment]
确实发现有这个问题，我这边排查一下，你可以先关闭默认的 active 方法，添加一个高亮图层来实现
https://l7.antv.antgroup.com/examples/tutorial/layer/#layer_highlight

**Comment by lzxue** [comment]
> > > [test.zip](https://github.com/antvis/L7/files/12481278/test.zip) 请用附件本地启动查看。
> > 
> > 
> > 提供在线demo吧，如何提供在线demo https://l7.antv.antgroup.com/tutorial/demo
> 
> 额，只是一个html文件和一个json文件 codesandbox请求同级json文件不生效

仔细看了一下代码，你的实现有问题，你每个地区是独立的 layer 是互不干扰的。你仔细看下L7 demo

**Comment by GitHumburger** [comment]
> > > > [test.zip](https://github.com/antvis/L7/files/12481278/test.zip) 请用附件本地启动查看。
> > > 
> > > 
> > > 提供在线demo吧，如何提供在线demo https://l7.antv.antgroup.com/tutorial/demo
> > 
> > 
> > 额，只是一个html文件和一个json文件 codesandbox请求同级json文件不生效
> 
> 仔细看了一下代码，你的实现有问题，你每个地区是独立的 layer 是互不干扰的。你仔细看下L7 demo


之前想过是数据结构的原因。
除了重新组织数据外，有其他方式可以实现这种多个独立layer的hover效果吗？
自己试过添加事件监听
geoLayer.on('mousemove', e => {
	geoLayer.color('#0F75FA');
});
geoLayer.on('mouseout', e => {
	geoLayer.color(colorBy[item.regionCompaniesName]);
});
但还是会出现颜色不消失的问题。
