### ISSUE TITLE
h5 在微信浏览器或者作为webview 在小程序中显示出现问题

### ISSUE THREAD

**Issue by qinpengsen** [antvis/L7#1811]
我用的地图是高德地图
在微信开发者工具中没有问题，在微信中打开的时候或者作为h5在微信小程序中显示的时候，地图区域的名字聚集到左上角了，
[
![image](https://github.com/antvis/L7/assets/25683149/16ea37aa-b476-486a-9b2e-e5e7aa3fda3c)
](url)

**Comment by lzxue** [comment]
名字是什么图层，最后贴一下代码实现

**Comment by qinpengsen** [comment]
<template>
  <div>
    <div>
      <div id="mapContainer" style="height:500px;width: 100%; justify-content: center;position: relative;"></div>
    </div>
  </div>
</template>

<script>
import { Scene } from "@antv/l7";
import { GaodeMap } from "@antv/l7-maps"; //引入高德2
export default {
  mounted() {
    let me = this;
    let scene = new Scene({
      id: "mapContainer",
      map: new GaodeMap({
        style: "amap://styles/light",
        center: [117, 36],
        zoom: 2.5,
        minZoom: 2,
        token: "440b5018425628c30d479a1e3493dfbc",
      }),
    });
  },
};
</script>

**Comment by qinpengsen** [comment]
> 名字是什么图层，最后贴一下代码实现

`<template>
  <div>
    <div>
      <div id="mapContainer" style="height:500px;width: 100%; justify-content: center;position: relative;"></div>
    </div>
  </div>
</template>

<script>
import { Scene } from "@antv/l7";
import { GaodeMap } from "@antv/l7-maps"; //引入高德2
export default {
  mounted() {
    let me = this;
    let scene = new Scene({
      id: "mapContainer",
      map: new GaodeMap({
        style: "amap://styles/light",
        center: [117, 36],
        zoom: 2.5,
        minZoom: 2,
        token: "440b5018425628c30d479a1e3493dfbc",
      }),
    });
  },
};
</script>`

**Comment by lzxue** [comment]
还是不清楚的问题是啥，你干了啥，加了什么图层，地图区域的名字是高德地图和L7绘制的都没表示清楚。另外贴代码请排一版，问题描述清楚节约大家时间。

**Comment by qinpengsen** [comment]
> 还是不清楚的问题是啥，你干了啥，加了什么图层，地图区域的名字是高德地图和L7绘制的都没表示清楚。另外贴代码请排一版，问题描述清楚节约大家时间。
<template>
  <div>
      <div id="mapContainer" style="height:500px;width: 100%;"></div>
  </div>
</template>
`<script>
   import { Scene } from "@antv/l7";
   import { GaodeMap } from "@antv/l7-maps"; 
   export default { 
     mounted(){ 
         let scene = new Scene({ 
           id: "mapContainer", 
          map: new GaodeMap({
            style: "amap://styles/light", 
            center: [117, 36], 
            zoom: 2.5, 
           minZoom: 2, 
           token: "440b5018425628c30d479a1e3493dfbc", 
       }), 
      }); 
    }, 
  }; 
</script>`

**Comment by herryle** [comment]
手机应该是曲面屏吧？  曲面屏上面会有这个问题

**Comment by lzxue** [comment]
地图本身的问题。
