### ISSUE TITLE
文档修复 

### ISSUE THREAD

**Issue by DreamNO1** [antvis/L7#1818]
一.  Problem Link      https://l7.antv.antgroup.com/tutorial/map/offline
二. Repair location   
       操作步骤：
            1.打开problem Link   
            2. 地图使用：离线地图   3.在线雪碧图服务地址:  Click Link Error   404    github服务：URL Link 和  蚂蚁CDN：URL Link    Click  Error 404

**Comment by lzxue** [comment]
Mapbox 离线地图资源是 URL模板，不能直接访问的，可以搜索一下 mapbox 离线方案
