### ISSUE TITLE
🐛 [BUG]客流聚合图层当底图换成mapbox时，图层显示异常

### ISSUE THREAD

**Issue by xhy1286** [antvis/L7#1822]
### 🐛 Bug description [Please make everyone to understand it]

> Please provide a link by forking these links [L7Plot](https://codesandbox.io/s/l7plot-issue-template-ckpvq?file=/src/index.ts) or GitHub repo, a minimal reproduction.

- _Required_ **Link to minimal reproduction**:

### 🚑 Any additional [like screenshots]

- **L7Plot Version**:
- **Platform**:
- 
![1693907771173](https://github.com/antvis/L7Plot/assets/43475616/5ef442c1-2133-49a3-8f14-edec29f8312e)

**Comment by lzxue** [comment]
已修复
