### ISSUE TITLE
3D热力图的高度映射

### ISSUE THREAD

**Issue by xhy1286** [antvis/L7#1825]
3D热力图的高度映射具体是如何映射的呢?是否支持等分位、等间距、枚举等其他类型映射？
![1693965431860](https://github.com/antvis/L7/assets/43475616/9dd70838-f36c-46be-9b67-61ea6399e2e9)

**Comment by lzxue** [comment]
支持的，设置scale 就可以了 https://l7.antv.antgroup.com/tutorial/scale

**Comment by xhy1286** [comment]
好的，我试试，谢谢
