### ISSUE TITLE
请问适配 uniapp 了吗

### ISSUE THREAD

**Issue by xIongEr1213** [antvis/L7#1828]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by xIongEr1213** [comment]
在 uniapp 中使用地图缩小的时候会出现定位偏移，vue2中不会出现，引用的官网点图层案例

**Comment by lzxue** [comment]
这个是 H5 的问题，跟 L7 关系不大吧

**Comment by xIongEr1213** [comment]
> 这个是 H5 的问题，跟 L7 关系不大吧

有什么解决方案吗   好像图层都会偏移

**Comment by xIongEr1213** [comment]
> 这个是 H5 的问题，跟 L7 关系不大吧

我找到了  给那个图层元素加上 top0 left0 就好了
