### ISSUE TITLE
如何给point图层集合点分别添加旋转值？

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#1844]
### Discussed in https://github.com/antvis/L7/discussions/1841

<div type='discussions-op-text'>

<sup>Originally posted by **liuminglhd** September  7, 2023</sup>
rotate()方法无法生效</div>

**Comment by MacJayLee** [comment]
同问 求解答

**Comment by lzxue** [comment]
> 同问 求解答

你提供个demo 吧，按照上面模板

**Comment by lzxue** [comment]
> 同问 求解答

你提供个demo 吧，按照上面模板

**Comment by MacJayLee** [comment]
`import { Scene, PointLayer } from "@antv/l7";
import { GaodeMap } from "@antv/l7-maps";

const scene = new Scene({
  id: "map",
  map: new GaodeMap({
    pitch: 0,
    style: "light",
    center: [121.435159, 31.256971],
    zoom: 3
  })
});
const fontFamily = "iconfont";
const fontPath =
  "//at.alicdn.com/t/font_2534097_fcae9o2mxbv.woff2?t=1622200439140";
scene.addFontFace(fontFamily, fontPath);
scene.addIconFont("icon1", "&#xe6d4;");

var data = [
  {
    lng: 121.435159,
    lat: 31.256971
  }
];

const pointLayer = new PointLayer({})
  .source(data, {
    parser: {
      type: "json",
      x: "lng",
      y: "lat"
    }
  })
  .shape("icon1", "text") // 指定需要映射字段为 icon、shape 类型和普通的文字标注一样为 text
  .size(50)
  .color("red")
  .style({
    textAnchor: "center", // 文本相对锚点的位置 center|left|right|top|bottom|top-left
    padding: [0, 0], // 文本包围盒 padding [水平，垂直]，影响碰撞检测结果，避免相邻文本靠的太近
    stroke: "#ffffff", // 描边颜色
    fontFamily,
    iconfont: true // 开启 iconfont 映射
  });
scene.addLayer(pointLayer);`

![1694144174773](https://github.com/antvis/L7/assets/38428395/bb02403b-57ee-4e0f-a2c2-1fa343ce0ec1)



如代码所示 在地图上生成了一个icon 现在我希望让icon旋转90度  怎么实现？？

> > 同问 求解答
> 
> 你提供个demo 吧，按照上面模板

**Comment by lzxue** [comment]
目前应该是有bug，需要支持，提供demo 最好提供在线访问的demo, codesanbox

**Comment by MacJayLee** [comment]
> 目前应该是有bug，需要支持，提供demo 最好提供在线访问的demo, codesanbox

sandbox 链接

https://codesandbox.io/s/l7-demo-forked-xjfdtp
