### ISSUE TITLE
The zIndex of legend need to be decreased

### ISSUE THREAD

**Issue by DawnLck** [antvis/L7#1845]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

Current zIndex of legends is 1000, which is equal to antd@5.x modal, and this will cause some problems.

**Comment by heiyexing** [comment]
https://github.com/antvis/L7/pull/1849

可以等 @antv/l7 2.18.0 发布之后再试一下
