### ISSUE TITLE
弹窗无法监听close,弹窗关闭重新设置html后自动打开

### ISSUE THREAD

**Issue by szygiser** [antvis/L7#1846]
import { Scene, GaodeMap, Popup } from '@antv/l7';

const scene = new Scene({
  id: 'map',
  map: new GaodeMap({
    pitch: 0,
    style: 'normal',
    center: [120.154672, 30.241095],
    zoom: 12,
  }),
  logoVisible: false,
});
scene.on('loaded', () => {
  const popup = new Popup({
    title: '自定义标题',
    html: '<p>Popup 示例的自定义内容</p>',
    lngLat: {
      lng: 120.154672,
      lat: 30.241095,
    },
  });

  scene.addPopup(popup);
  popup.on('close',()=>{
    alert('关闭')
  })
  setInterval(()=>{
    popup.setHTML('<p>Popup 示例的</p>');
  },10000)
});
_______________________________________________________________________________________________________

* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by heiyexing** [comment]
1.Popup 隐藏对应的是 `hide` 事件
2.`setHTML` 方法设计上就是会打开 `Popup` 的，不是 bug
