### ISSUE TITLE
LayerPopup 如何避免超出地图被遮挡?

### ISSUE THREAD

**Issue by warryy** [antvis/L7#1847]
* **L7 Version**: 2.17.4
* **Platform**: pc
* **Mini Showcase(like screenshots)**: https://l7.antv.antgroup.com/zh/examples/component/popup#customContent
* **CodePen Link**: https://l7.antv.antgroup.com/zh/examples/component/popup#customContent

如下图, LayerPopup 在边缘时, 显示会被截断一部分, 请问有办法去规避这个问题吗?
<img width="1672" alt="image" src="https://github.com/antvis/L7/assets/22448081/a0f15a47-10c9-4649-bbd9-e05ab51f3ddb">
示例截图自官网demo

**Comment by lzxue** [comment]
@heiyexing

**Comment by heiyexing** [comment]
![image](https://github.com/antvis/L7/assets/29321750/510055f7-055c-4a24-811f-9bf4094390a4)

LayerPopup 超出展示可能会导致一些 Bug，建议你这边可以改成移动地图的中心点至  LayerPopup 所在经纬度的方式 `scene.setCenter(...)` ，如果硬要让 LayerPopup 溢出部分展示的话，可以尝试通过样式覆盖的方式把以下两个 DOM 样式表中的 `overflow: hidden;` 给覆盖掉

![image](https://github.com/antvis/L7/assets/29321750/d70614ef-e88c-4bd0-b553-f9cbd8391cf1)
