### ISSUE TITLE
BUG 着色器精度不足导致L7+maoboxapi时渲染线出现扭曲

### ISSUE THREAD

**Issue by Thor5233** [antvis/L7#1850]
* **L7 Version**:2.16.1
* **Platform**:  开发者自研
* **Mini Showcase(like screenshots)**:
![image](https://github.com/antvis/L7/assets/144661915/62a7b1a6-c3cd-4500-a0b0-5ac2eea3c044)

* **CodePen Link**:https://codesandbox.io/s/9pp2t8

实例化底图为mapbox时绘制线出现异常扭曲，高德地图时渲染正常
![image](https://github.com/antvis/L7/assets/144661915/fb6d6714-67f9-4b46-93b3-b885ed51dd0e)
![image](https://github.com/antvis/L7/assets/144661915/7c2d425c-a8bc-4594-b0fb-9a1a4566cb51)

**Comment by Thor5233** [comment]
感谢回复，不过能否再确认一下？
1. 这个数据，并不是与经度完全垂直的数据，它是个斜线，所以只是把数据改成经度一致这个方法并不是解决方案
2. 如果数据本身渲染就会有折线，L7+高德为底图时为什么没有出现波折？
3. 目前用其他gis软件/webgis引擎渲染包括mapboxgljs本身渲染也都是一条直线，确实也没有办法向上反馈说是数据问题。

麻烦再看一下呢？

**Comment by lzxue** [comment]
1.如果不少完全垂直的，说明显示没问题，我改成一致只是说明，数据显示没问题。
2.高德坐标处理的时候会有四舍五入

**Comment by lzxue** [comment]
感谢的你反馈，我看一下不同平台差异

**Comment by lzxue** [comment]
排查确实是精度的问题，如需修复需要较长时间，短时间内不能够解决，主要什么场景使用mapbox ?

**Comment by Sh1-5** [comment]
> 
目前我们业务上有两个功能L7暂时还实现不了：

1.fill-extrusion，https://docs.mapbox.com/style-spec/reference/layers/#fill-extrusion，通过图层的叠加实现室内地图效果，大致效果是这样
![image](https://github.com/antvis/L7/assets/48705798/299faed2-cb57-4847-a16f-6935cea70077)

2.标注功能，目前L7的标注是基于点图层的，但是在某些情况下，需要根据线图层加标注，所以有点不方便，大致效果是这样
![image](https://github.com/antvis/L7/assets/48705798/ba000988-6cef-48c7-bd06-e339233e0ece)

因为这两点，还不能完全弃用mapbox，一般两个都会用

**Comment by Sh1-5** [comment]
> 排查确实是精度的问题，如需修复需要较长时间，短时间内不能够解决，主要什么场景使用mapbox ?

之前业务一直用的是mapbox，后面因为老项目用了你这个库https://github.com/lzxue/echartsLayer，后面因为模块化规范的问题用不了想联系你才了解到L7的，现在日常使用的添加图层工具函数已经大部分转向L7了

**Comment by lzxue** [comment]
> > 
> 
> 目前我们业务上有两个功能L7暂时还实现不了：
> 
> 1.fill-extrusion，https://docs.mapbox.com/style-spec/reference/layers/#fill-extrusion 通过图层的叠加实现室内地图效果，大致效果是这样 ![image](https://user-images.githubusercontent.com/48705798/267274858-299faed2-cb57-4847-a16f-6935cea70077.png)
> 
> 2.标注功能，目前L7的标注是基于点图层的，但是在某些情况下，需要根据线图层加标注，所以有点不方便，大致效果是这样 ![image](https://user-images.githubusercontent.com/48705798/267275974-ba000988-6cef-48c7-bd06-e339233e0ece.png)
> 
> 因为这两点，还不能完全弃用mapbox，一般两个都会用

提个新 issue 吧，这个功能开发成本不高

**Comment by Thor5233** [comment]
我们需要叠加很多比较细节的3D要素到底图上，用户要求可以精确到1m级别（22级），高德除了标准底图，其他的在超过一定层级时都会出现缩放抖动/卫星底图19级以后就没有影像了

**Comment by lvisei** [comment]
数据精度问题已经修复 https://github.com/antvis/L7/pull/2416
