### ISSUE TITLE
关于官方文档 PointLayer的 示例代码fillImage rotate不生效 BUG  

### ISSUE THREAD

**Issue by MacJayLee** [antvis/L7#1854]
这个是官方文档的演示界面   https://l7.antv.antgroup.com/zh/examples/point/image#monsoon 

在这个示例代码中  rotate方法不起任何作用    季风的箭头方向永远不变

原因就在于    PointLayer初始化的时候 必须要先声明  largeLayer：'fillImage '   

而并非案例中在style方法中去声明   largeLayer：'fillImage ' 

正确代码sandbox如下 

https://codesandbox.io/s/practical-mclean-9hkqcy?file=/index.js

这个文档我试了半天才发现是这个问题 在文档的上方关于fillImage作了专门的陈述 

![1694492449752](https://github.com/antvis/L7/assets/38428395/145956b1-c09e-435f-9f15-b46d7ac972c6)

而这个这个是对的 

希望和下面的rotate方法在线示例代码结合起来  不然容易误导新手

**Comment by lzxue** [comment]
感谢反馈，本周 rotate 方法，配置和demo 会重新升级，能力会更完善。

**Comment by lzxue** [comment]
https://codesandbox.io/s/currying-cache-c4zkzc
