### ISSUE TITLE
Feature: fill-extrusion

### ISSUE THREAD

**Issue by Sh1-5** [antvis/L7#1860]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

面图层可根据自身高度和基准高度实现叠加
实现如下效果：
![image](https://github.com/antvis/L7/assets/48705798/8e3e1065-6773-4b12-ba75-656657ac8b0f)

**Comment by lzxue** [comment]
Polygon Exture 核心逻辑这里，可以看一下 shader 代码，进行一些改造和重构, 实现够示例代码，在style 进行配置

### 常量高度
```ts
 const layer = new PolygonLayer({})
        .source(data)
        .shape('extrude')
        .size('h20', [ 100, 120, 160, 200, 260, 500 ])
        .color( '#816CAD')
        .style({
           extrusion-base: 10
          }
   )

```

### 数据映射高度
```ts
 const layer = new PolygonLayer({})
        .source(data)
        .shape('extrude')
        .size('h20', [ 100, 120, 160, 200, 260, 500 ])
        .color( '#816CAD')
        .style({
           extrusion-base: {
                field:'baseHeight',
                value: [10,30]
              }
          }
   )

```

**Comment by Sh1-5** [comment]
[indoor-3d-map.geojson.zip](https://github.com/antvis/L7/files/12697459/indoor-3d-map.geojson.zip)

**Comment by Sh1-5** [comment]
![image](https://github.com/antvis/L7/assets/48705798/35aeaefd-b1b1-47d1-a12f-8032a12f15c6)

**Comment by Sh1-5** [comment]
height为高度，base_height为抬升高度（离地面）

**Comment by Sh1-5** [comment]
const layer = new PolygonLayer({})
  .source(data)
  .shape('extrude')
  .size('height')
  .style({
    raisingHeight: 'base_height'
  })
scene.addLayer(layer)
