### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by DreamNO1** [antvis/L7#1863]
1.  链接  https://l7.antv.antgroup.com/examples#tutorial-map
2.  error的具体位置：
   图标演示 ----> 高德地图插件----->   图层 ----->click 框选图层 ---->【什么都没有，报错误】

**Comment by lzxue** [comment]
具体哪个demo,报什么错误

**Comment by DreamNO1** [comment]
https://geo.datav.aliyun.com/areas_v3/bound/330100_full.json    403

**Comment by DreamNO1** [comment]
链接     https://l7.antv.antgroup.com/examples/tutorial/layer/#layer_boxselect
  自己打开看得到

**Comment by lzxue** [comment]
应该还是服务跨域问题，感谢反馈

**Comment by zuoyifeng** [comment]
这个API在说明里面都没有scene.enableBoxSelect(false);
也是这个示例
