### ISSUE TITLE
在使用ImageLayer时，layer.source传入svg格式的图片时，这个图片图层展示不出来，png的可以。

### ISSUE THREAD

**Issue by zimutao** [antvis/L7#1865]
问题描述：在使用ImageLayer时，layer.source传入svg格式的图片时，这个图片图层展示不出来，png的可以。

https://codesandbox.io/s/xenodochial-cartwright-jqlqfj?from-embed
代码：
```javascript
 const scene = new Scene({
      id: "map",
      map: new GaodeMap({
        pitch: 0,
        style: "light",
        center: [121.168, 30.2828],
        zoom: 14.89,
        minZoom: 10
      })
    });
    fetch(
      "https://gw.alipayobjects.com/os/basement_prod/893d1d5f-11d9-45f3-8322-ee9140d288ae.json"
    )
      .then((res) => res.json())
      .then((data) => {
        const layer = new ImageLayer({});
        layer.source(
          "1.svg",
          {
            parser: {
              type: "image",
              extent: [121.168, 30.2828, 121.384, 30.4219]
            }
          }
        );

        scene.addLayer(layer);
      });
```

**Comment by lzxue** [comment]
支持 SVG 的，访问的你的图片链接访问不了

**Comment by zimutao** [comment]
我没描述清楚，png和svg都是本地文件，直接引入后，png可以展示。这种场景，用这个api或者其他api可以实现吗？

**Comment by zimutao** [comment]
> 支持 SVG 的，访问的你的图片链接访问不了

我没描述清楚，png和svg都是本地文件，直接引入后，png可以展示。这种场景，用这个api或者其他api可以实现吗？

**Comment by lzxue** [comment]
可能是打包的问题，你可以尝试 实例化成 image 对象看看

**Comment by zimutao** [comment]
> 可能是打包的问题，你可以尝试 实例化成 image 对象看看

初始化可以加载出来，之后的热更新或者再次添加一个图层会出现错误。
<img width="823" alt="image" src="https://github.com/antvis/L7/assets/20102205/efc82f69-c0b7-4e97-a69f-70337b1fc9df">
![image](https://github.com/antvis/L7/assets/20102205/d10776aa-c817-40ec-8fb9-f4dd3168a8b7)

**Comment by zimutao** [comment]
> > 可能是打包的问题，你可以尝试 实例化成 image 对象看看
> 
> 初始化可以加载出来，之后的热更新或者再次添加一个图层会出现错误。 <img alt="image" width="823" src="https://user-images.githubusercontent.com/20102205/267837005-efc82f69-c0b7-4e97-a69f-70337b1fc9df.png"> ![image](https://user-images.githubusercontent.com/20102205/267836507-d10776aa-c817-40ec-8fb9-f4dd3168a8b7.png)

**Comment by zimutao** [comment]
> 可能是打包的问题，你可以尝试 实例化成 image 对象看看

实例化就好了，上个问题是图片没加载完成我就传入了，加上img.onload就好了。
感谢回复。
