### ISSUE TITLE
图片图层引入svg图片后，放大失真，展示效果和png的差不多。

### ISSUE THREAD

**Issue by zimutao** [antvis/L7#1869]
<img width="460" alt="image" src="https://github.com/antvis/L7/assets/20102205/aa21c285-ff4d-4ef6-98da-8ca56a0115ba">

**Comment by zimutao** [comment]
> Hello @zimutao. Please provide a online reproduction by forking codesandbox of [@antv/l7 demo template](https://codesandbox.io/s/l7-demo-w4v6pr?file=/index.js) Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.
> 
> 你好 @zimutao, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 [@antv/l7 demo 模板](https://codesandbox.io/s/l7-demo-w4v6pr?file=/index.js) 3 天内未跟进此 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ![68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966) [ ](https://camo.githubusercontent.com/3f51b5a32e6e5d5adabdebc5ef968150bdabc8d17a8dc1a535b8fb255d2165d0/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/l7-demo-forked-sx2cmj?file=/index.js
模糊了。

**Comment by adtkcn** [comment]
可以加一个宽高解决
`    const imgs = new Image();
      imgs.width= 10000;
      imgs.height= 10000;
`
