### ISSUE TITLE
Provide SVG Download Resources

### ISSUE THREAD

**Issue by helloworq** [antvis/L7#1877]
I have read the download page but not found the url of download all of the svg data of china region.but it provides geojson,json,csv format and so on. and it now only provides the url for download single province or city or country. will you consider provide the url for download all the svg data ?
![微信截图_20230918180452](https://github.com/antvis/L7/assets/26016637/9fe21d11-8b32-4784-929b-81fa7dd90e50)

**Comment by lzxue** [comment]
![image](https://github.com/antvis/L7/assets/4366658/ea3829b1-cc29-4abe-84b1-93a2dcbe807a)

Does the svg download here not meet your needs?

**Comment by helloworq** [comment]
> ![image](https://user-images.githubusercontent.com/4366658/268692196-ea3829b1-cc29-4abe-84b1-93a2dcbe807a.png)
> 
> Does the svg download here not meet your needs?

Thanks for replying, i tried it again, it works well.thank you .
