### ISSUE TITLE
请教一下，使用Dot创建的散点图，在添加token后，map中的style 无效是什么情况

### ISSUE THREAD

**Issue by tpc-ht** [antvis/L7#1879]
设置token后 dark 和 light样式无效
![image](https://github.com/antvis/L7/assets/59469126/965c8dbf-9162-49d5-8ce8-795303fa7cae)

添加主题工具 MapTheme 同样也是这两个样式无效
![image](https://github.com/antvis/L7/assets/59469126/0074e3c7-4445-4573-8e52-47ff5012db3b)

https://github.com/antvis/L7/assets/59469126/ee96b446-0dd8-4c84-b746-0b30af474a3e

**Comment by lzxue** [comment]
不生效的两个样式 L7 官方的提供，高德新的 token 机制下不支持，共享样式，我们会将 maptheme 中的样式替换成官方的

**Comment by lzxue** [comment]
我们本地验证了一下，设置Token 没问题的，是不是你token 使用有问题报错了 

Token 使用：

https://lbs.amap.com/api/javascript-api/guide/abc/prepare
