### ISSUE TITLE
scene.on('click', (ev) => {}); 这个方法中的ev中的哪些属性我可以确定该点击的地方是属于那个省份的，谢谢

### ISSUE THREAD

**Issue by DreamNO1** [antvis/L7#1881]
我想问的 问题是 

URL:    https://l7.antv.antgroup.com/examples/choropleth/administrative/#zhejiang-province
  scene.on('click', (ev) => {}); // 鼠标左键点击事件
这个鼠标点击事件中的ev ,我可以通过ev的属性中哪些参数可以知道这个位置是属于那个省/获取省的名字?   谢谢

**Comment by lvisei** [comment]
事件是绑定到图层上的

```js
choropleth.once('loaded',() => {
  choropleth.on('fillAreaLayer:click', (ev) => {
    console.log(ev)
  })
})
```

**Comment by DreamNO1** [comment]
好的，谢谢，可以啦
