### ISSUE TITLE
scene + Choroplet dblclick error

### ISSUE THREAD

**Issue by Peter-FrontEnd** [antvis/L7#1884]
this.ChoroplethDom.on('loaded',()=>{

          this.ChoroplethDom.on('fillAreaLayer:click',(e)=>{
            console.log(e,'e');
          })
          this.ChoroplethDom.on('fillAreaLayer:dblclick',(e)=>{
            console.log(e,'e dblclick');
          })
})

辛苦帮忙看下 这个双击时间有什么问题吗? 不知道为啥不可以像click事件一样返回feature

**Comment by lzxue** [comment]
@lvisei 看一下

**Comment by lvisei** [comment]
升级 L7Plot 至 0.5.6 @Peter-FrontEnd

**Comment by Peter-FrontEnd** [comment]
@lvisei  好了 谢谢
