### ISSUE TITLE
geojson位置偏移

### ISSUE THREAD

**Issue by wy2123726** [antvis/L7#1890]
请问L7如何对已经写好了的geojson数据进行位置偏移的操作？

**Comment by wy2123726** [comment]
比如：
import { Scene, PointLayer } from "@antv/l7";
import { GaodeMap } from "@antv/l7-maps";

const scene = new Scene({
  id: "map",
  map: new GaodeMap({
    pitch: 0,
    style: "dark",
    center: [114.30, 30.50],
    zoom: 9,
  })
});

// 标准的geojson数据
const data = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [114.30, 30.50]
      },    
      properties: {
        name: '武汉'
      }
    }
  ]
}

scene.on('loaded', () => {

    let point_layer = new PointLayer()
    point_layer.source(data)
      .size(30)// size相当于半径
      .color('#ff2d51')
      .shape('circle')
    scene.addLayer(point_layer)

})

地图会出现一个红点，我如何不改变data值，只操作L7让这个红点往右偏移0.1°？

**Comment by lzxue** [comment]
更新一下经纬度，setdata 更新图层

**Comment by wy2123726** [comment]
就是说还是得对data进行操作，并不能用L7的API函数进行操作，因为这是一个简单的例子，如果是大量数据的整体偏移，如果遍历data会造成浏览器卡顿，L7有没有API函数进行偏移操作并且不卡顿？
