### ISSUE TITLE
请问怎么使地图到合适的中心点和缩放大小呢

### ISSUE THREAD

**Issue by KuduroJS** [antvis/L7#1891]
比如点状地图，但是点的位置和数量是不确定的，这些点可能集中在某市，也可能集中在某省，也可能遍布全国。
所以中心点和zoom大小要根据实际数据来确定。
中心点是比较容易计算的，但缩放大小该如何计算呢，我并不知道zoom对应的比例尺，该怎么处理呢，zoom不需要很精确。
官方这边有什么建议吗？
谢谢。

**Comment by heiyexing** [comment]
PointLayer options 中的 `autoFit` 配置传 `true`，后续给 PointLayer 设置数据的时候，地图会自动移动和缩放。
如果需要更自由操作地图移动和缩放，可以使用 `Scene` 的 `fitBounds` 方法。

**Comment by KuduroJS** [comment]
@heiyexing 非常感谢
