### ISSUE TITLE
引入高德插件能不能使用自己的key

### ISSUE THREAD

**Issue by zhuhai-1999** [antvis/L7#1909]
项目中引入的GaodeMap可不可以使用自己的开发者的key,能修改吗

* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lzxue** [comment]
必须使用的 token,官网默认token 仅供测试。map 初始化可配置自己的Token
https://l7.antv.antgroup.com/api/map/map

**Comment by zhuhai-1999** [comment]
谢谢，找到了
