### ISSUE TITLE
L7 支持百度地图

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#1924]
### Issue 难度

中等难度

### 任务介绍

L7  接入百度地图技术方案已经走通，需要进行完善，主要需要完成

### 1. 初始化方式统一，完善地图初始化化方法：
  
https://github.com/antvis/L7/blob/master/packages/maps/src/bmap/map.ts#L65

需要实现两种地图初始化方式
 
  方法一： 参数初始化

- 需要支持动态引入 百度地图 API，已经传入token,可参考高德地图实现 https://github.com/antvis/L7/blob/master/packages/maps/src/amap2/map.ts#L262

```ts
const scene = new Scene({
  id: 'map',
  map: new BMap({
    pitch: 35.210526315789465,
    style: 'dark',
    center: [ 104.288144, 31.239692 ],
    zoom: 4.4
  })
});

```
  方法二： 支持传入百度地图实例
 ```ts
const scene = new Scene({
    id: 'map',
    map: new GaodeMap({
      mapInstance: map
    })
  });
```

### 2. 地图接口统一

 不同地图厂商的接口并不完全一致，但是 L7 是对外统一的接口，这样就能实现不同底图之间的切换，要将 L7 的通用接口对应到三方地图的不同接口

https://github.com/antvis/L7/blob/master/packages/core/src/services/map/IMapService.ts#L52

需要实现 IMAPService 里面的接口定义

### 3. 补充文档
   补充如何使用的文档

### 4. 补充demo.使用教程
  增加demo 实例

### 5. 功能发布
  对外宣发，发布稿件

### 详细介绍

可多人认领，有兴趣可直接回复。

**Comment by KipSong** [comment]
cc

**Comment by lzxue** [comment]
> cc

感谢参与
