### ISSUE TITLE
希望能新加arcgis地图支持

### ISSUE THREAD

**Issue by GemT27** [antvis/L7#1934]
### 问题描述

希望能新加arcgis地图SceneView支持

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
可以详细描述一下业务场景

**Comment by GemT27** [comment]
> 可以详细描述一下业务场景

不知道将来会不会支持arcgis地图接入联动，政府国土设计院就爱用arcgis， 领导爱看炫酷的🤯

**Comment by lzxue** [comment]
> > 可以详细描述一下业务场景
> 
> 不知道将来会不会支持arcgis地图接入联动，政府国土设计院就爱用arcgis， 领导爱看炫酷的🤯

回评估一下可行性
