### ISSUE TITLE
类型为simple的线图层配置渐变样式shader报错。

### ISSUE THREAD

**Issue by IveChen** [antvis/L7#1936]
### 问题描述

![image](https://github.com/antvis/L7/assets/1736282/0ff50e7a-80a0-42aa-b695-d9d947d04898)

### 重现链接

如图

### 预期行为

api文档中的线图层在类型simple中支持渐变，但实际不支持，配置后会报错。

### 平台

- 操作系统: macos
- 网页浏览器: Google Chrome

**Comment by lzxue** [comment]
感谢反馈
