### ISSUE TITLE
高德地图token

### ISSUE THREAD

**Issue by qq9321** [antvis/L7#1938]
为啥我加载高德地图出来是空白的，token从哪获取，我看高德地图只有key 和密钥啊，写了也没作用

**Comment by lzxue** [comment]
提供一下复现demo，如何提供看一下 https://l7.antv.antgroup.com/tutorial/demo

**Comment by qq9321** [comment]
我在你那个上面是可以出现高德地图的，在我的项目上面是一片空白

![1697701486856](https://github.com/antvis/L7/assets/32297011/860decf8-e1bd-450c-b8cc-656b84add5d1)
![1697701516159](https://github.com/antvis/L7/assets/32297011/8eb4cada-248b-4f50-9385-6f771a7291f8)

**Comment by lzxue** [comment]
看一下控制有没有提醒，了解一下高德地图Token的配置

**Comment by qq9321** [comment]
没有提醒，但是我用了GaodeMapV1 就可以出现了

**Comment by lzxue** [comment]
> 没有提醒，但是我用了GaodeMapV1 就可以出现了

https://lbs.amap.com/api/javascript-api-v2/guide/abc/jscode 看下这个

**Comment by qq9321** [comment]
用了，密钥也设置了，key 值也写了，我就想问下这个token 代表的是啥，高德地图控制台里面有token 么，只要key 和密钥

**Comment by lzxue** [comment]
token 就是key

**Comment by lzxue** [comment]
高德地图白屏一般是自己没有注册

**Comment by lzxue** [comment]
> 没有提醒，但是我用了GaodeMapV1 就可以出现了

高德V1 的key 不需要设置密钥，V2 升级了需要key加密钥双重验证，具体可以看

https://lbs.amap.com/api/javascript-api-v2/guide/abc/jscode

**Comment by qq9321** [comment]
我写了密钥也没用作用。

**Comment by yeyunwen** [comment]
> 我写了密钥也没用作用。
你好请问解决了吗，我也不会设置token

**Comment by lzxue** [comment]
> > 我写了密钥也没用作用。
> > 你好请问解决了吗，我也不会设置token

https://github.com/antvis/L7/discussions/1112  这个里面写的已经很详细了
