### ISSUE TITLE
新增 JSON 瓦片支持

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#1947]
### AntV Open Source Contribution Plan（可选）

- [X] 我同意将这个 Issue 参与 OSCP 计划

### Issue 难度

中等难度

### 任务介绍

目前 L7 瓦片仅仅支持 MVT 矢量瓦片格式，很多场景不支持 MVT 格式，提供一种更便捷的，通过的数据 JSON，即可实现瓦片可视化。

### 详细介绍

新增 JSONTile parse 支持JSON 瓦片数据

**Comment by KipSong** [comment]
cc
