### ISSUE TITLE
控件均无法显示

### ISSUE THREAD

**Issue by xujiahe** [antvis/L7#1949]
### 问题描述

按照最基础的demo加载后，L7提供的控件均无法显示。

### 重现步骤

vue组件代码如下：
 ![image](https://github.com/antvis/L7/assets/21364066/ed35b212-da49-4b2c-883e-4e7ff26e5d61)
版本vue3+vite+@antv/l7最新版本

### 预期行为

出现zoom组件

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/L7/assets/21364066/7f7495f2-afea-4a41-aab2-8ddeaca3d7a7)

### 补充说明（可选）

由vite'创建的最基础的demo，直接 helloworld 组件

**Comment by lzxue** [comment]
看一下是不是样式的问题，提供一个codesandbox 在线demo

**Comment by xujiahe** [comment]
没有加其他的样式我这里代码初始化结束后，我看整个dom里面没有生成L7-control-container容器，所以后面的control都无法add进去。

**Comment by lzxue** [comment]
搞个复现demo 看一下吧

**Comment by xujiahe** [comment]
我这个是vue3项目中使用，在线的都是提供的react版本吧。我看你们线上也是好的，我就是直接vite4脚手架创建了个demo工程，然后新建一个helloworld文件，逻辑复制的你们官网上的代码。 地图和其他layer都可以出现，但是就控件无法出现。

**Comment by heiyexing** [comment]
你把 new Scene 的操作放到 mounted 声明周期里试一下，我这边是 ok 的，如果还不行的话麻烦吧你的项目 push 到 Github 上 ，我这边再去验证

```vue
<template>
  <div class="app" id="map"></div>
</template>

<script setup>
import { onMounted, ref } from "vue";
import { Scene, GaodeMap, Zoom } from "@antv/l7";

onMounted(() => {
  const scene = new Scene({
    id: "map",
    map: new GaodeMap({
      pitch: 0,
      style: "normal",
      center: [118, 24.8],
      zoom: 6,
    }),
  });
  scene.on("loaded", async () => {
    const zoom = new Zoom({});
    scene.addControl(zoom);
  });
});
</script>

<style scoped>
.app {
  height: 100vh;
}
</style>

```

![image](https://github.com/antvis/L7/assets/29321750/628eee64-3e04-47e9-98a7-5807fc89b7cd)

**Comment by xujiahe** [comment]
嗯嗯额。可以了。
