### ISSUE TITLE
L7的点地图引用了iconfont的话，或自带一圈内发光效果，调节参数无法去掉或隐藏啊

### ISSUE THREAD

**Issue by nalameiko** [antvis/L7#1954]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![企业微信截图_16982128723176](https://github.com/antvis/L7/assets/148941597/9637d0a2-c2f5-45e9-aa47-c9dcb7909ea9)

**Comment by lzxue** [comment]
提供一个在线复现demo 吧

**Comment by qtj4js** [comment]
https://l7.antv.antgroup.com/zh/examples/point/text/#iconfonts
官网示例即可看到
![企业微信截图_16983052894819](https://github.com/antvis/L7/assets/47909978/a9690551-287a-4d45-aa18-fe99cae9c426)
将size调大就可明显看到iconfont 提供的图标周围有一圈白色光圈,调高strokeWidth会更明显,但是设置为0依然存在

**Comment by lzxue** [comment]
这个应该是 storke 的样式，尝试设置 strokeOpacity:0 好像没剩下，我排查一下
