### ISSUE TITLE
高德地图加载

### ISSUE THREAD

**Issue by qq9321** [antvis/L7#1958]
我配置了高德地图的key 和密钥，为啥高德地图还是加载不出来。
![image](https://github.com/antvis/L7/assets/32297011/1ac924f8-703c-45ae-ae83-b9e2f56917af)
![image](https://github.com/antvis/L7/assets/32297011/ad3a1fc8-8090-4116-8e8f-17a74d135b96)

**Comment by lzxue** [comment]
提供一个在线复现demo

**Comment by lzxue** [comment]
一般是先后顺序的问题

参考 #1112
