### ISSUE TITLE
MarkerLayer 下的 cluster 点，在 -180 处的异常问题

### ISSUE THREAD

**Issue by ParryQiu** [antvis/L7#196]
* **L7 Version**: 待 merge 的 PR
* **Platform**: macOS
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

发现不管是高德还是使用 mapbox 的 getBounds 方法，进行 cluster 按照视野加载的时候，都会出现穿越 -180 经度的时候计算错误的问题。

具体的解决方案应该是这个 issue: https://github.com/mapbox/supercluster/issues/41
待讨论后进行理解并实现。

**Comment by lzxue** [comment]
2.0.19修复完成
