### ISSUE TITLE
渲染的线都断了，不连续

### ISSUE THREAD

**Issue by szygiser** [antvis/L7#1968]
![image](https://github.com/antvis/L7/assets/15412933/fc9d440e-9692-47fe-9c9f-6e9aa8f34253)

测试数据和代码如下：

[test.txt](https://github.com/antvis/L7/files/13183936/test.txt)

**Comment by szygiser** [comment]
https://codesandbox.io/s/l7-demo-forked-n6msr7?file=/index.js


测试了下一部分数据好像是正常的，下图的弯曲线也能生成。但是我用那个大数据量生成的话就不行。那个数据量比较大，传到sandbox里面执行比较费劲。能用我github上发的那个txt里面的代码给看下吗？







zy.S
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/L7"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月27日(星期五) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/L7] 渲染的线都断了，不连续 (Issue #1968)





 
Hello @szygiser. Please provide a online reproduction by forking codesandbox of @antv/l7 demo template Issues labeled by Need Reproduce will be closed if no activities in 3 days.
 
你好 @szygiser, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 @antv/l7 demo 模板 3 天内未跟进此 issue 将会被自动关闭。

**Comment by szygiser** [comment]
https://codesandbox.io/s/l7-demo-forked-zz2qr9?file=/index.js









zy.S
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/L7"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月27日(星期五) 上午10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/L7] 渲染的线都断了，不连续 (Issue #1968)





 
Hello @szygiser. Please provide a online reproduction by forking codesandbox of @antv/l7 demo template Issues labeled by Need Reproduce will be closed if no activities in 3 days.
 
你好 @szygiser, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击这里创建一个 @antv/l7 demo 模板 3 天内未跟进此 issue 将会被自动关闭。

**Comment by lzxue** [comment]
你这个数据是不是本身就是线段

**Comment by szygiser** [comment]
每个Feature都是LineString。本身就是线段是什么意思？




zy.S
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/L7"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 下午5:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/L7] 渲染的线都断了，不连续 (Issue #1968)





 
你这个数据是不是本身就是线段

**Comment by lzxue** [comment]
你的LineString 是也是两个点的线段，建议你先用一下本地软件查看一下数据：比如QGIS 、ArcGiS先预览一下数据

**Comment by lzxue** [comment]
数据本身就是这样，使用QGIS 打开数据
![image](https://github.com/antvis/L7/assets/4366658/3caab5c4-275a-427a-a1ac-66e2cd57b539)

放大

![image](https://github.com/antvis/L7/assets/4366658/cf93e542-9817-4966-9dd5-42ea9e54a693)

**Comment by szygiser** [comment]
您是把我发您的geojson转换成shp，在QGIS里面打开？


我原始数据是没问题的：

，

发您的是经过GeoServer矢量切片之后的geojson格式的数据，在GeoServer里面预览也是没问题的。









zy.S
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/L7"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月1日(星期三) 晚上11:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/L7] 渲染的线都断了，不连续 (Issue #1968)





 
数据本身就是这样，使用QGIS 打开数据
 
 
放大

**Comment by lzxue** [comment]
QGIS 可以直接打开GeoJSON、数据本身就不连续的线段
