### ISSUE TITLE
地图蓝色地图：style:normal   但是测试下来的结果是 地图没有蓝色底图

### ISSUE THREAD

**Issue by DreamNO1** [antvis/L7#1973]
### 问题描述

1.原始的code：  https://l7.antv.antgroup.com/examples/choropleth/administrative/#zhejiang-province-district
2. 官网编辑测试的链接  https://c6kk3z.csb.app/
1和2 测试的结果底图是不同的？   这是什么情况
三次运行的底图结果：第一次为什么和第二次运行的底图效果不同？  相同的code

### 重现链接

https://codesandbox.io/s/c6kk3z?file=/index.ts

### 预期行为

我期望  第一次和第二次运行的底图效果是相同的

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]
window10   google

### 屏幕截图或视频（可选）

![1](https://github.com/antvis/L7/assets/42691915/3cdd45e1-28e2-4de9-b42b-454b1ac274c5)
![2](https://github.com/antvis/L7/assets/42691915/da3c1f48-fca7-492b-b4ca-836ff47e6e87)
![3](https://github.com/antvis/L7/assets/42691915/95863fcb-f4cd-45e8-83ad-4ca1d15af063)
三次运行的底图结果：第一次为什么和第二次第三次运行的地图效果不同？  相同的code

**Comment by lzxue** [comment]
L7 默认 Token 设定了域名白名单，只能官网访问，请使用自己的token，多了解一下 高德的地图token 机制

**Comment by DreamNO1** [comment]
好的，谢谢
