### ISSUE TITLE
自定义悬浮提示和图例

### ISSUE THREAD

**Issue by qq9321** [antvis/L7#1995]
这边自定义悬浮提示和图例能给个示例么，到底要怎么实现才能显示，怎么样才能在自定义的里面取到值呢。

**Comment by heiyexing** [comment]
Popup：https://l7.antv.antgroup.com/examples/component/popup#popup2
Legend：可以看一下 LarkMap 上图例的实现代码 https://github.com/antvis/LarkMap/blob/main/src/components/Legend/LegendCategories/index.tsx
