### ISSUE TITLE
https://codesandbox.io/s/gsvnyq，经典热力图这个演示地址。地图背景颜色不显示，显示空白。

### ISSUE THREAD

**Issue by SuHang-Java** [antvis/L7#1996]
https://codesandbox.io/s/gsvnyq，经典热力图这个演示地址。地图背景颜色不显示，显示空白。
请打开上述地址，查看便知。

![image](https://github.com/antvis/L7/assets/62089815/b7bc319b-5544-4c4b-b79c-e9317177a951)

**Comment by lzxue** [comment]
高德底图token问题，需要自注册token 并配置 token 参考 #1112

**Comment by SuHang-Java** [comment]
收到，谢谢！
















在 2023-10-30 ***@***.***" ***@***.***> 写道：

高德底图token问题，需要自注册token 并配置 token 参考 #1112
