### ISSUE TITLE
新bug：点击 layer 之后，调用 scene.render 报错

### ISSUE THREAD

**Issue by JackieLs** [antvis/L7#200]
代码实现：
```js
polygonLayer.on('click', () => {
      polygonLayer.color('red');
      scene.render();
});
```
如果就是这么设计的话，我觉得不太合理，我们的业务需求是，点击一个省份，然后这个省份和其他几个有业务联系的省份会高亮，那么我就应该去调用这个 color 方法，通过回调函数去判断，哪几个省份的颜色变为不同的颜色。

![image](https://user-images.githubusercontent.com/14228179/74097054-59847880-4b42-11ea-834b-b7e2b986ff3c.png)

**Comment by lzxue** [comment]
这样有业务需求，应该用的一个新的图层作为高亮图层，而不是修改原图层
