### ISSUE TITLE
L7 实现地图卷帘 demo 

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#2002]
### AntV Open Source Contribution Plan（可选）

- [ ] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

高级任务

### 任务介绍

使用 L7 实现 卷帘效果 Demo

![image](https://github.com/antvis/L7/assets/4366658/95cfa0ea-8267-4cb2-a244-b68591a459c6)

方案建议：

### 方案一
 双地图实现，上下两个 L7 地图实例，使用 css clip 属性实现

### 方案二
 单个地图实现，使用 L7 mask 能力实现图层之间的 clip

https://l7.antv.antgroup.com/examples#Mask-basic

**Comment by code-maker-code** [comment]
【code-maker-code 认领】

**Comment by hcfq1999** [comment]
【hcfq1999 认领】

**Comment by lzxue** [comment]
感谢认领两位可各自开发或者相互交流开发

**Comment by hcfq1999** [comment]
您好，我们对题目和项目有一些困惑，可否留个联系方式交流一下

> 感谢认领两位可各自开发或者相互交流开发

**Comment by lzxue** [comment]
> 您好，我们对题目和项目有一些困惑，可否留个联系方式交流一下
> 
> > 感谢认领两位可各自开发或者相互交流开发

加 AntV2030 微信助手，备注 L7 共建
