### ISSUE TITLE
2.19.0 ie存在兼容问题,会报错

### ISSUE THREAD

**Issue by qtj4js** [antvis/L7#2003]
### 问题描述

L7 Version: 2.19.0
Platform:
Mini Showcase(like screenshots):
CodePen Link:
项目中的依赖包从2.17.0升级至2.19.0后,ie下出现报错
他会报es6语法错误,包是regl的包
但是如果我在babel中把这个regl包编译为es5的话,又会报错:无法设置未定义或 null 引用的属性“createREGL”
并且此时我所有浏览器都会有createRegl的报错
从2.17.0升级至2.19.0确实存在regl包的变更

### 重现步骤

进入ie下的相关工程即可复现

### 预期行为

期望能正常显示但是却出现报错

### 平台

ie浏览器

### 屏幕截图或视频（可选）

![1698826651965_A7A5A8D0-9F22-4cc1-9DCC-F737A0FC4C2F](https://github.com/antvis/L7/assets/47909978/70b84ebd-682c-427d-94da-d3b6fe8be436)
![1698826651965_A7A5A8D0-9F22-4cc1-9DCC-F737A0FC4C2F](https://github.com/antvis/L7/assets/47909978/a04cf4fc-025e-4a14-8991-e3e3814f7b07)

**Comment by qtj4js** [comment]
![ed084ec458d77783da7bf8f00084b26e](https://github.com/antvis/L7/assets/47909978/f095dbfc-7f1f-432b-8b51-0bec4b1d0b54)

**Comment by lzxue** [comment]
你尝试一下，把 regl 版本全局锁定 1.3.1 看看IE 可不行
