### ISSUE TITLE
当一个vue 项目中有多个页面时会造成API加载方式混用

### ISSUE THREAD

**Issue by qq9321** [antvis/L7#2027]
我有两个页面，一个页面是使用的你们的L7，一个页面是使用的高德的官方地图（2.0），当我在L7地图使用GaodeMap的时候，我有些面图层数据无法加载出来，但是如果我使用GaodeMapV1的时候，是可以加载出来，但是当我如果点击另外一个使用高德地图的页面时，在点击L7的页面的时候，所有的图层都加载不出来了，我打了断点也没有进入load 函数里面，并且报错 “ 禁止多种API加载方式混用”。我想问你们有没有像高德那样有AMapLoader.reset()方法重置地图。

**Comment by lzxue** [comment]
正常现象 GaodeMapV1, GaodeMapV2 不能存在，如果希望存在两个版本需求,需要动态移除不同的版本的 API。

V2 加载不出来的问题，可以单独提ISSUE
