### ISSUE TITLE
提供 window 环境下，主要提供相关依赖如何安装，能指导 windows 用户进行 L7 研发

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#2028]
### AntV Open Source Contribution Plan（可选）

- [ ] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

中级任务

### 任务介绍

window 环境一般比较难按照，在Window 下安装成功的同学可以写份完整的文档，
- 可以写在 https://github.com/antvis/L7/blob/master/.github/CONTRIBUTING.md 这个 文件提交 PR
- 也可以写在 知乎、语雀、CSDN 等三方平台，这里回复链接既可。

**Comment by xuqwCloud** [comment]
报名

**Comment by wsqstar** [comment]
【wsq_star 认领】https://github.com/wsqstar

**Comment by code-maker-code** [comment]
【code-maker-code 认领】

**Comment by hcfq1999** [comment]
【hcfq1999+认领】
