### ISSUE TITLE
地图放大之后出现异常

### ISSUE THREAD

**Issue by vellengs** [antvis/L7#204]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/5743338/74325223-35839a00-4dc3-11ea-8c73-ea507aca4f85.png)

重现问题：
https://lzxue.github.io/yiqingditu/

**Comment by lzxue** [comment]
2.0.24已修复
