### ISSUE TITLE
新增可视化 demo

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#2042]
### AntV Open Source Contribution Plan（可选）

- [X] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

中级任务

### 任务介绍

使用 L7 复刻 demo 原demo 地址： https://observablehq.com/@neocartocnrs/ridge-lines

![image](https://github.com/antvis/L7/assets/4366658/8fc96615-7cfe-49f9-835b-53dd56ed2716)

数据地址：
https://static.observableusercontent.com/files/c517bc4710d3a5daf34549dde51fd3a0e457a62ce3113847cf804dd21b78a95dd0ecc0b975455c4c162f87e74e665e6994bb9bbd457a420e46d6b6179200b47d

![image](https://github.com/antvis/L7/assets/4366658/533512b7-1fbf-4640-946f-0a76313f3761)
源数据为点数据，可以把相同纬度的点连接成线，value 为线的 z 字段
L7示例 ： https://l7.antv.antgroup.com/examples/line/isoline/#ele

L7 代码地址：https://github.com/antvis/L7/tree/master/packages/site/examples/line/isoline/demo，该目录下添加一个demo

**Comment by taiyuanhy** [comment]
我认领
