### ISSUE TITLE
官方示例L7 Editor 里面的官方图层是怎么实现的

### ISSUE THREAD

**Issue by qq9321** [antvis/L7#2050]
![image](https://github.com/antvis/L7/assets/32297011/da9c761a-b0c8-4690-b0d3-ddde637aaabf)
这个官方的示例图层是怎么实现的，怎么样然他默认不选择呢。

**Comment by heiyexing** [comment]
这个是高德地图的官方图层，可以自行看下高德的官方 API，另外 [L7Editor](https://github.com/antvis/L7Editor) 是开源的，也可以自行看下具体的实现方式。
