### ISSUE TITLE
Mapbox  zoom为22级时，l7图层有偏移

### ISSUE THREAD

**Issue by luoxiao-supermap** [antvis/L7#2052]
### 问题描述

Mapbox （传入map实例） zoom为22级时，l7图层有偏移

下图中红点 为l7 layer;    蓝色marker为mapbox原生marker图层, 使用的同一个坐标
![image](https://github.com/antvis/L7/assets/97505033/72a52f62-4dda-4820-970d-ff4c7c70f3d5)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
为什么关闭了？

**Comment by luoxiao-supermap** [comment]
我重新打开了

**Comment by luoxiao-supermap** [comment]
在线示例
https://codesandbox.io/s/practical-johnson-xn295s?file=/index.js

**Comment by lvisei** [comment]
fixed https://github.com/antvis/L7/pull/2416
