### ISSUE TITLE
L7  Window 系统下 webGL2 转 webgl1 问题

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#2067]
### AntV Open Source Contribution Plan（可选）

- [ ] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

高级任务

### 任务介绍

window 系统启动 L7 项目，不能正常使用demo，原因是 glsl 版本转换问题，猜测代码编译不兼容问题

https://github.com/antvis/L7/blob/master/packages/renderer/src/regl/ReglModel.ts#L93

**Comment by taiyuanhy** [comment]
申请认领
