### ISSUE TITLE
高德地图的简介为什么没了

### ISSUE THREAD

**Issue by JUNHAN12138** [antvis/L7#2071]
### 问题描述

![image](https://github.com/antvis/L7/assets/65531323/d8773688-8772-463a-8dc5-aad8adcecebe)

### 重现链接

https://l7.antv.antgroup.com/api/map/gaode

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
https://l7.antv.antgroup.com/api/map/map 

最新的官网还没推上来，先看这个

**Comment by JUNHAN12138** [comment]
> https://l7.antv.antgroup.com/api/map/map
> 
> 最新的官网还没有推上来，先看这个

本地运行没有地图了，是不是必须加上token才行，
![image](https://github.com/antvis/L7/assets/65531323/f0df4d54-8e4b-4261-aeb1-71c528d77aa7)
我用的是const scene = new Scene({
        id: "map",
        map: new GaodeMap({
          pitch: 0,
          style: "light", // 可根据需求调整地图样式
          zoom: 10,
          center: [Number(lng), Number(lat)], // 设置地图中心点坐标
        }),
      });

**Comment by lzxue** [comment]
是的，必须有 Token  https://github.com/antvis/L7/discussions/1112

**Comment by lzxue** [comment]
https://l7.antv.antgroup.com/api/map/gaode
