### ISSUE TITLE
无法加载mapbox地球

### ISSUE THREAD

**Issue by maxueli** [antvis/L7#2083]
### 问题描述

new l7.Scene({
      id,
      map: new l7.Mapbox({
        container: id, // container id
        style: 'mapbox://styles/mapbox/streets-v12', // stylesheet location
        center: [-74.5, 40], // starting position [lng, lat]
        zoom: 9, // starting zoom
        projection: 'globe',
        token: accessToken,
      }),
    });

无法加载地球，怎么写，急急急

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
现在支持是 Mapbox 1.x  版本地球 版本应该不支持

**Comment by MarkLei7** [comment]
你可以用V2版本生成Mapbox实例后再挂到L7上，注意在低层级下L7的坐标和Mapbox坐标不一致。

**Comment by Sh1-5** [comment]
我的建议是反过来，L7挂到mapbox上
