### ISSUE TITLE
枚举 scale 映射自定义配置需求

### ISSUE THREAD

**Issue by lvisei** [antvis/L7#2086]
### 问题描述

图标图层使用自定义 scale 映射自定义配置

1. domain 可支持更新
2. 未在 domain 内的值，可配置 unknown 不在地图上显示

### 重现链接

https://riddle.alibaba-inc.com/riddles/f7fada99

**Comment by lzxue** [comment]
这个应该是通过数据更新解决吗？scale 的 unknown 是指数据为定义，不是domain 未定义。

**Comment by lvisei** [comment]
按理说可以这样用

![image](https://github.com/antvis/L7/assets/26923747/79dec021-daaa-46e1-887a-656743d8a60b)

**Comment by lvisei** [comment]
在自定义映射枚举的时候，不宜提前处理数据更新数据来解决

![image](https://github.com/antvis/L7/assets/26923747/f9e91cf5-cf6b-4b9e-bfb6-6c54a2816c93)

**Comment by lzxue** [comment]
- scale domain 没更新，不符合预期应该是bug
 - 未在domain里面的数值，设置成 unknown 对应的图片的是符合预期的，如果不显示这个目前可以使用透明图片。增加一个配置目前看有点复杂、

**Comment by lvisei** [comment]
注册透明的图片在也是这样做的，设置一个透明的背景图片。另外发现了一个其他问题

- 未注册 unknown 对应的图片
- domain 设置数据中，按顺序的前几条数据
- 地图上 unknown 不会显示，取的逻辑没有看太明白

https://riddle.alibaba-inc.com/riddles/8bbbac42
