### ISSUE TITLE
does it support angular 8?

### ISSUE THREAD

**Issue by petitlen** [antvis/L7#209]
My project is angular 8 and typescript 3.4.5.
The code is below:
import * as L7 from '@antv/l7/dist/l7';
import { Scene, PointLayer } from '@antv/l7';
import { Mapbox } from '@antv/l7-maps';
@Component({
  selector: 'app-mapmain2',
  templateUrl: './mapmain2.component.html',
  styleUrls: ['./mapmain2.component.scss']
})
export class Mapmain2Component implements OnInit {
  constructor() { }
  ngOnInit() {
    const scene = new Scene({
      id: 'map',
      map: new Mapbox({
        style: 'dark',
        pitch: 0,
        center: [104.288144, 31.239692],
        zoom: 2.632456779444394,
      }),
    });
  }
}

In the end, It show the error:
import EventEmitter from 'eventemitter3';
         ~~~~~~~~~~~~
../node_modules/@antv/l7-core/es/services/camera/ICameraService.d.ts:23:41 - error TS2304: Cannot find name 'Omit'.

23 export interface ICameraService extends Omit<IViewport, 'syncWithMapCamera'> {
                                           ~~~~
../node_modules/@antv/l7-core/es/services/config/IConfigService.d.ts:1:8 - error TS1192: Module '"/Users/linjiang/Documents/workspace/ng-uikit-pro-standard-6.2.1/node_modules/@antv/l7-core/node_modules/ajv/lib/ajv"' has no default export.

1 import Ajv from 'ajv';
         ~~~
../node_modules/@antv/l7-core/es/services/layer/IStyleAttributeService.d.ts:73:53 - error TS2304: Cannot find name 'Omit'.

**Comment by petitlen** [comment]
if use L7.Scene instend,i show another error.

ERROR in ./node_modules/@antv/l7/dist/l7.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.fill' in '/Users/petitlen/Documents/workspace/ng-uikit-pro-standard-6.2.1/node_modules/@antv/l7/dist'

**Comment by lzxue** [comment]
please ensure  node_modules install  successed.

here is a angular demo ,you can download this project to local.

https://codesandbox.io/s/angulartest-chpff

**Comment by petitlen** [comment]
"@angular/cli": "1.6.6",
你使用的是小于angular 6的版本（angular-cli.json），但是angular 8（angular.json）编译报错
