### ISSUE TITLE
L7 3.0 引擎升级-点图层-多人认领

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#2093]
### AntV Open Source Contribution Plan（可选）

- [ ] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

中级任务

### 任务介绍

方案介绍： https://www.yuque.com/antv/l7/fa6mytdksh9v1qtm

技术交流欢迎加入 https://discord.gg/jvRWGXgSbN  L7 DIscord 频道

![image](https://github.com/antvis/L7/assets/4366658/19a7ea63-ff3f-43fd-a64f-bdd57b2d99a2)

- [x] normal
- [x] fill
- [x] extrude
- [x] billboard ⭐️
- [x] earthExtrude ⭐️
- [x] earth fill ⭐️
- [x] fill image
- [x] image
- [x] radar
- [x] text  ⭐️⭐️⭐️

**Comment by taiyuanhy** [comment]
我来领一个试试

**Comment by zhnny** [comment]
认领

**Comment by Pureblackkk** [comment]
111

**Comment by Knight-wh** [comment]
认领

**Comment by lzxue** [comment]
大家可以备注一下认领那个 model,不要重复领取，已领取的可以加我微信 qqlzxue

**Comment by hustcc** [comment]
认领一个简单，不知道哪个比较简单~

**Comment by Knight-wh** [comment]
> 认领

image
