### ISSUE TITLE
L7 3.0 引擎升级-线图层-多人认领

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#2094]
### AntV Open Source Contribution Plan（可选）

- [X] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

中级任务

### 任务介绍

目录路径：packages/layers/src/line

方案介绍： https://www.yuque.com/antv/l7/fa6mytdksh9v1qtm

修改 model，认领需要备注model 名称不要重复领取

- [x] arc3d
- [x] arc
- [x] flow
- [x] earth_arc_3d
- [x] greate_circle
- [x] line
- [x] linearline
- [x] simpleline
- [x] wall

技术交流欢迎加入 https://discord.gg/jvRWGXgSbN  L7 Discord 频道

![image](https://github.com/antvis/L7/assets/4366658/58f49da3-5248-4444-b9a0-7fdff9664c44)

**Comment by taiyuanhy** [comment]
认领

**Comment by Nullaha** [comment]
认领greate_circle
