### ISSUE TITLE
官网的图层高亮例子，需要鼠标点击两次才会高亮，这是什么原因呢

### ISSUE THREAD

**Issue by wlfei0502** [antvis/L7#2100]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by wlfei0502** [comment]
https://l7.antv.antgroup.com/examples/tutorial/layer/#layer_highlight

**Comment by lzxue** [comment]
感谢反馈，应该setdata 没有触发重新渲染
