### ISSUE TITLE
 scene.off

### ISSUE THREAD

**Issue by ChimKoNight** [antvis/L7#2126]
### 问题描述

使用 scene.off方法无法移除事件

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by ChimKoNight** [comment]
使用了 scene.on 监听 mousemove事件，但是使用scene.off 无法移除

**Comment by lzxue** [comment]
提供一下示例demo吧

**Comment by ChimKoNight** [comment]
![1701853451435](https://github.com/antvis/L7/assets/41896810/cee5a471-a1a1-4d18-b04c-de4bdab6dea1)
正常来说，移除事件执行后，应该打印出字符，但是并没有。同时zoomchange还是依然能在执行。

**Comment by ChimKoNight** [comment]
scene.on("zoomchange", () => {
      this.zoomchange();
    }); // 地图缩放级别更改后触发
    scene.off("zoomchange", () => {
      console.log("zoomchangeOff");
    }); // 地图缩放级别更改后触发
    scene.on("mousemove", (ev) => {
      //
      console.log("scene.off11");
    });
    scene.off("mousemove", (ev) => {
      //
      console.log("scene.off11");
    });

**Comment by lzxue** [comment]
给函数起个名字，在监听，这样写是两个函数了

**Comment by lzxue** [comment]
如果已解决star 一下再走
