### ISSUE TITLE
L7 3.0 引擎升级-geometry

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#2133]
### AntV Open Source Contribution Plan（可选）

- [ ] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

中级任务

### 任务介绍

需要升级 model，认领需要备注model 名称不要重复领取

技术交流欢迎加入 https://discord.gg/jvRWGXgSbN L7 DIscord 频道

![image](https://github.com/antvis/L7/assets/4366658/5e4733e0-2654-4152-9870-bfe0ed9d85de)

- [ ] billbord ⭐️⭐️
- [ ] plane⭐️ ⭐️
- [ ] sprite ⭐️ ⭐️

**Comment by MarkLei7** [comment]
认领billboard
