### ISSUE TITLE
项目执行`yarn start`时报错

### ISSUE THREAD

**Issue by zhnny** [antvis/L7#2156]
### 问题描述

执行`yarn start`时报错，报错详情如下图：
![cda6b2cc5db439a7010b44099686e20](https://github.com/antvis/L7/assets/58084743/36b29a65-64b8-4de7-8079-ebeb841c5bab)

### 重现步骤

1. 克隆项目
2. 执行`yarn install`
3. 执行`yarn start`

### 平台

- 操作系统: [Windows WSL]
- 网页浏览器: [Edge]

### 补充说明（可选）

看起来是因为webpack不能使用只有大小写区别的文件，例如下面这两个文件的文件名：
![e319b94aa39f165b999bf6d70d19ca0](https://github.com/antvis/L7/assets/58084743/cb35f07d-421b-4290-a1e0-830ea6fdbce1)

看上去这两文件几乎是一样的

**Comment by lzxue** [comment]
改一文件名，采用下划线分隔看看

**Comment by lzxue** [comment]
文件名称已修复
