### ISSUE TITLE
热力图无法渲染

### ISSUE THREAD

**Issue by Raymond1030** [antvis/L7#2160]
我只有一组点数据，我只是想单纯根据点密度进行热力图渲染，我是使用了我自己的Mapbox地图实例之后进行渲染，但是热力图格式一直在报错。我能确保底图是正常的，GetJson是正常读入的。
L7通过CDN引入

数据：[村子_new.json](https://github.com/antvis/L7/files/13650846/_new.json)
报错：l7:1  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'positions')
代码：
 const scene = new L7.Scene({
        id: 'map',
        map: new L7.Mapbox({
            mapInstance: map,
        }),
    });

    scene.on('loaded', async () => {
        // 异步获取数据
        const population = getJson('../data/人口/村子_new.json');
        const heatmapLayer = new L7.HeatmapLayer({})
        .source(population)
        .shape('heatmap')
        .size(1) // 固定大小
        .style({
            intensity: 1, // 热力强度
            radius: 20,   // 半径大小
            opacity: 1.0, // 不透明度
            // 其他样式设置
        });

    scene.addLayer(heatmapLayer);

**Comment by lzxue** [comment]
你 getjson 异步写法不需要写 await 吗

**Comment by Raymond1030** [comment]
我的getjson函数已经包含了，不用担心异步，数据已经成功读入
