### ISSUE TITLE
DrawCircle 画圆API

### ISSUE THREAD

**Issue by ChimKoNight** [antvis/L7#2166]
### 问题描述

我何如获取画出圆形的中心坐标和半径，有这种接口吗？该feature中coordinates有61个点迹数组，只能通过类似取第0个和第30个数组来计算中心坐标和半径吗？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
@heiyexing  看看要不要提供配置

**Comment by ChimKoNight** [comment]
还有就是请问下，我如果给定一个圆的中心位置和半径，可以在地图上初始化一个可编辑的圆形吗？

**Comment by heiyexing** [comment]
问题：我何如获取画出圆形的中心坐标和半径，有这种接口吗？该feature中coordinates有61个点迹数组，只能通过类似取第0个和第30个数组来计算中心坐标和半径吗？
答：可以去看一下 [turf](turfjs.org) 提供的 center 和 distance 方法，可以计算出圆 Feature 的中心点坐标和半径。

问题：还有就是请问下，我如果给定一个圆的中心位置和半径，可以在地图上初始化一个可编辑的圆形吗？
答：暂时不提供这种方式创建圆，但是你也可以通过 [turf](turfjs.org) 提供的方法计算出圆的 Feature 在传入 DrawCircle 的 initialData 中。
