### ISSUE TITLE
antv l7 使用内网的瓦片地图后可以设置地图主题为深色么

### ISSUE THREAD

**Issue by leidao** [antvis/L7#2170]
### 问题描述

我使用RasterLayer加载了内网的瓦片地图，但是地图的配色和项目主题不符，我想修改地图主题颜色为深色，请问有api可以实现么。如果暂不支持的话，我希望可以逐像素读取图层的rgb，然后在去修改像素颜色。请问图层实例上有提供对像素操作的能力么，或者我应该从哪方面去下手。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

黄色主题颜色改为深色主题颜色
<img width="653" alt="image" src="https://github.com/antvis/L7/assets/39399843/776065aa-0c3e-4a22-88e7-2af0da5851bd">
<img width="527" alt="image" src="https://github.com/antvis/L7/assets/39399843/aad4ee41-ae9f-4e4d-a224-bc13816c3abe">

**Comment by lzxue** [comment]
一种方法是 L7实现，对于图片瓦片，一般是将图片设置一下灰度，对比度等效果，需要  L7  支持，成本也不太高。

**Comment by leidao** [comment]
> 一种方法是 L7实现，对于图片瓦片，一般是将图片设置一下灰度，对比度等效果，需要 L7 支持，成本也不太高。

请问有文档链接么，我去研究下，如果没有文档的话能在详细指点下么，感激不尽！

**Comment by lzxue** [comment]
> > 一种方法是 L7实现，对于图片瓦片，一般是将图片设置一下灰度，对比度等效果，需要 L7 支持，成本也不太高。
> 
> 请问有文档链接么，我去研究下，如果没有文档的话能在详细指点下么，感激不尽！

L7  现在还不支持

**Comment by leidao** [comment]
> > > 一种方法是 L7实现，对于图片瓦片，一般是将图片设置一下灰度，对比度等效果，需要 L7 支持，成本也不太高。
> > 
> > 
> > 请问有文档链接么，我去研究下，如果没有文档的话能在详细指点下么，感激不尽！
> 
> L7 现在还不支持

关于把图片设置灰度和对比度等效果，我已经实现了，但是我不知道该怎么在l7中去进行，想请教下RasterLayer图层中是否有把瓦片图片进行转换处理的相关api暴露出来或者能提供下实现思路么。

**Comment by leidao** [comment]
> > > > 一种方法是 L7实现，对于图片瓦片，一般是将图片设置一下灰度，对比度等效果，需要 L7 支持，成本也不太高。
> > > 
> > > 
> > > 请问有文档链接么，我去研究下，如果没有文档的话能在详细指点下么，感激不尽！
> > 
> > 
> > L7 现在还不支持
> 
> 关于把图片设置灰度和对比度等效果，我已经实现了，但是我不知道该怎么在l7中去进行，想请教下RasterLayer图层中是否有把瓦片图片进行转换处理的相关api暴露出来或者能提供下实现思路么。

我在openlayers中找到tileLoadFunction函数可以操作瓦片图片以及在cesium中找到requestImage方法可以操作瓦片图片，l7有没有考虑过提供类似的api呢，或者有什么取巧的办法可以做到类似的效果么。
`
 const offlineMapLayer = new TileLayer({
        source: new XYZ({
          url: "https://webrd01.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=8&x={x}&y={y}&z={z}", // 设置本地离线瓦片所在路径,前面的地址是你输入http-server之后的服务地址
          tileLoadFunction: (imageTile, src) => {
            console.log(imageTile, src);
            // 使用滤镜 将白色修改为深色
            let img = new Image();
            // img.crossOrigin = ''
            // 设置图片不从缓存取，从缓存取可能会出现跨域，导致加载失败
            img.setAttribute("crossOrigin", "anonymous");
            (img.onload = () => {
              const canvas = theme.processImage(img);
              imageTile.getImage().src = canvas.toDataURL("image/png");
            }),
              (img.onerror = () => {
                imageTile.getImage().src = require("@/assets/logo.png");
              });
            img.src = src;
          }
`
`
const requestImage = layer.imageryProvider.requestImage;
imageryProvider.requestImage = function (x, y, level, request) {
  var promise = requestImage.bind(imageryProvider)(x, y, level, request);
  if (promise) {
    promise = promise.then((image) => {
      var imageProcessed = theme.processImage(image, layer);
      return imageProcessed || image;
    });
  }
  return promise;
};
`

**Comment by lzxue** [comment]
可以的

可以参照 这个demo:  https://github.com/antvis/L7/blob/master/dev-demos/tile/BaseMap/demos/customImage.tsx
