### ISSUE TITLE
ImageLayer 支持图片效果增强

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#2180]
### AntV Open Source Contribution Plan（可选）

- [x] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

中级任务

### 任务介绍

增强图图层的样式配置，目前只支持透明度 opacity 配置，需要新增一些配置增强图片的表达能力。

- saturation 饱和度
- contrast 对比度’
- brightness 亮度
- mixColor 颜色混合

可以参照 Mapbox的实现  https://docs.mapbox.com/style-spec/reference/layers/#paint-raster-raster-brightness-max

**Comment by taiyuanhy** [comment]
认领
