### ISSUE TITLE
layer.setData([])未能成功清除图层

### ISSUE THREAD

**Issue by wfJoanna** [antvis/L7#2189]
### 问题描述

想用layer的setData方法清空图层数据，结果发现图层并没有变化，直到鼠标拖动一下才消失

### 重现链接

https://codesandbox.io/p/sandbox/l7-setdata-demo-pm2t8k

### 预期行为

预期应该在 layer.setData([]) 的时候，图层立即消失

### 屏幕截图或视频（可选）

https://github.com/antvis/L7/assets/62973056/24859939-0b88-43b7-98c1-29314f76dbc4

### 补充说明（可选）

具体请看codesandbox里的代码。以下是我的一些发现：
1. 经过不断尝试，发现只有图层初始数据就为空时才能复现
2. 把空数组换成 { type: 'FeatureCollection', features: [] } 也一样

**Comment by wfJoanna** [comment]
我上面说错了一点，就是跟初始数据空不空无关，试了下即使不空也还是没法立即清除

**Comment by lzxue** [comment]
> 我上面说错了一点，就是跟初始数据空不空无关，试了下即使不空也还是没法立即清除

我看一下记得这个问题已经修复了

**Comment by lzxue** [comment]
最新版已修复
