### ISSUE TITLE
离线使用

### ISSUE THREAD

**Issue by ChimKoNight** [antvis/L7#2195]
### 问题描述

请问可以讲解下如何配合使用geoserver发布的离线地图进行使用吗？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by ChimKoNight** [comment]
需要加载WMS、WMTS、TMS等

**Comment by lzxue** [comment]
看一下 L7 的瓦片图层就开业了

**Comment by ChimKoNight** [comment]
使用antV7L访问我部署geoserver的wmts服务，访问时url中TILEMATRIX属性格式为TILEMATRIX=11，而我的geoserver服务的格式为TILEMATRIX=EPSG:3857:11，这个可以对TILEMATRIX属性进行格式化吗？

**Comment by lzxue** [comment]
核心还是x,yz 根据自己的url 拼接就可以，其他保持不变。
正常服务
'https://tiles{1-3}.geovisearth.com/base/v1/img/{z}/{x}/{y}?format=webp&tmsIds=w',

你的服务可以是
https://**TILEMATRIX=EPSG:3857:{z}***
