### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by oOBobbyOo** [antvis/L7#2198]
### 问题描述

Uncaught ReferenceError: process is not defined at l7-venders.8376c056.js

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by piece-Chao** [comment]
同样问题
![image](https://github.com/antvis/L7/assets/29347932/26a5f17f-67e1-484c-adbe-ac1d21fa46be)

**Comment by lzxue** [comment]
cdn 引用吗？

**Comment by lzxue** [comment]
已修复 2.20.8
