### ISSUE TITLE
使用mapTexture时纹理图和地图不能重合在一起

### ISSUE THREAD

**Issue by twosoy** [antvis/L7#2208]
### 问题描述

使用mapTexture时纹理图和地图不能重合在一起，对纹理图有什么要求吗？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by twosoy** [comment]
十分有用，已经⭐!!!

**Comment by lzxue** [comment]
复现demo 有没有
