### ISSUE TITLE
文本标注字体过大时色彩异常且模糊有锯齿

### ISSUE THREAD

**Issue by herofqy** [antvis/L7#2242]
### 问题描述

文本标注字体过大时色彩异常且模糊有锯齿.
官方文档：https://l7.antv.antgroup.com/tutorial/point/text

### 重现链接

https://l7.antv.antgroup.com/examples/point/text/#point_text

### 重现步骤

1. 打开页面
2. 修改size为122或其他大数字

### 预期行为

文字正常显示，但我看到文字色彩失真且模糊有锯齿
![image](https://github.com/antvis/L7/assets/23518758/df1df2d2-06ba-4c62-ad79-734605a4598f)

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/L7/assets/23518758/df1df2d2-06ba-4c62-ad79-734605a4598f)

**Comment by lzxue** [comment]
文本不需要设置太大，如果模糊的话，只能调整参数优化一下
