### ISSUE TITLE
windows环境 网格热力图发生偏移

### ISSUE THREAD

**Issue by JeffreyZhang96** [antvis/L7#2244]
* **L7 Version**: latest
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codesandbox.io/p/sandbox/heuristic-banach-p4n7c2?file=%2Findex.js%3A43%2C21

分别在macos和windows11的chrome浏览器打开，发现windows11上的网格热力图整体往上偏移了一部分
windows：
![img_v3_026p_849cfcc6-43e7-4be5-8515-0354998e9d2g](https://github.com/antvis/L7/assets/43950839/e613e9ea-4385-4605-b62b-6374f191e930)
macos：
![img_v3_026p_fc25594c-b21c-481e-9b0f-c8573ccde06g](https://github.com/antvis/L7/assets/43950839/5991089a-30e5-426e-937f-54e5841171c2)

**Comment by JeffreyZhang96** [comment]
有的macos电脑也会发生偏移

**Comment by lzxue** [comment]
感谢反馈，其他地图底图会有问题吗

**Comment by JeffreyZhang96** [comment]
没试过其他底图，只用了高德

**Comment by lzxue** [comment]
我在window 环境复现和 mac 表现一致

**Comment by lzxue** [comment]
> > 我在window 环境复现和 mac 表现一致
> 
> 可以多试几台设备（我这边的设备是macbook和thinkpad），有些设备示例里的热力图会整体发生偏移
有没有可能样式兼容性的问题，地图可视化的canvas 偏移导致的

**Comment by JeffreyZhang96** [comment]
> > > 我在window 环境复现和 mac 表现一致
> > 
> > 
> > 可以多试几台设备（我这边的设备是macbook和thinkpad），有些设备示例里的热力图会整体发生偏移
> > 有没有可能样式兼容性的问题，地图可视化的canvas 偏移导致的

正常：![image](https://github.com/antvis/L7/assets/43950839/600d7ad6-acf2-46f9-a93d-4a8e731cca9f)
不正常：![image](https://github.com/antvis/L7/assets/43950839/5a50ae93-4c00-4911-a0ad-c9b6b9bf6606)
我加了个线图层可以更直观看出问题，只有热力图在部分设备下发生了偏移

**Comment by JeffreyZhang96** [comment]
@lzxue 你好，请问这个后面有复现吗

**Comment by lzxue** [comment]
> @lzxue 你好，请问这个后面有复现吗

没有复现，如果线没有偏移就不是样式兼容性问题，使用其他底图有没有这样的问题？

**Comment by lvisei** [comment]
没有复现
