### ISSUE TITLE
PolygonLayer可否设置颜色为线性渐变或者镜像渐变

### ISSUE THREAD

**Issue by wuzf007** [antvis/L7#2246]
### 问题描述

https://l7.antv.antgroup.com/zh/examples/gallery/story/#yidaiyilu2
我把这个案例下载到本地修改使用，但实际要求是希望每个国家的颜色为渐变色填充的。
地图 Map 可否设置填充色为渐变色？

### 平台

操作平台：Windows
测试浏览器为：谷歌

**Comment by lzxue** [comment]
https://codesandbox.io/p/sandbox/naughty-franklin-f9cf2c


目前支持的比较简单，透明度的渐变
