### ISSUE TITLE
mapbox，加载三维模型，setObjectLngLat方法无法设置高度。

### ISSUE THREAD

**Issue by CjCjCjCj-Cj** [antvis/L7#2250]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by CjCjCjCj-Cj** [comment]
this.layerInfo.setObjectLngLat(gltfScene, g.lnglat, 0); 第三个参数如果输入除0以外的数字，模型会消失

**Comment by CjCjCjCj-Cj** [comment]
不光是模型，在mapbox地图下，元素都无法设置高度，比如threejs中的面板。setObjectLngLat第三个参数传入1时，面板消失。

textureLoader.load('/favicon.jpg', (texture: any) => {
  const panelMaterial = new THREE.MeshBasicMaterial({
    side: THREE.DoubleSide,
  });
  panelMaterial.map = texture;
  const panelGeometry = new THREE.PlaneGeometry(40, 20);
  const panelMesh = new THREE.Mesh(panelGeometry, panelMaterial);

  layer.adjustMeshToMap(panelMesh);
  layer.setObjectLngLat(panelMesh, [120.01752508825811, 30.278129509254377], 1);
  threeScene.add(panelMesh);
});

**Comment by lzxue** [comment]
感谢反馈，可以看一下 l7-three 的源码

**Comment by lzxue** [comment]
> 感谢反馈，可以看一下 l7-three 的源码

高度单位可以设置的大一些 10000 级别的
