### ISSUE TITLE
以高德地图为底图加入点图层时，北京动画不生效

### ISSUE THREAD

**Issue by binghuis** [antvis/L7#2253]
### 问题描述

使用高德地图卫星图为底图，加入点图层，如果点坐标不在具体城市，则正常显示，如果点坐标在具体城市，比如北京，点坐标动画不生效。看起来渲染逻辑是没问题的，是什么原因导致城市不能渲染点图层动画的呢。

<img width="692" alt="image" src="https://github.com/antvis/L7/assets/20395726/ecfeef35-070e-4c35-b9a7-139a81fa500d">

<img width="773" alt="image" src="https://github.com/antvis/L7/assets/20395726/68fa70c1-e9a4-4ea0-8d95-2be0de23cfc3">

<img width="408" alt="image" src="https://github.com/antvis/L7/assets/20395726/f2fbaaf1-5d0b-4183-97ca-5d59548c623c">

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
![image](https://github.com/antvis/L7/assets/4366658/c6ba7c71-2f4a-440c-82bf-4dec1782d3fa)

经纬度错了

**Comment by binghuis** [comment]
thks
