### ISSUE TITLE
使用高德地图并使用tif文件设置图层掩膜，位置偏移（与官方文档中注释的tiff文件效果类似，https://l7.antv.antgroup.com/examples/Mask/basic/#raster）

### ISSUE THREAD

**Issue by W-ang-nan** [antvis/L7#2266]
### 问题描述

使用高德地图并使用tif文件设置图层掩膜，位置偏移（与官方文档中注释的tiff文件效果类似，https://l7.antv.antgroup.com/examples/Mask/basic/#raster）

### 平台

- 操作系统: [Windows，Vue3]
- 网页浏览器: [Google Chrome]

### 屏幕截图或视频（可选）

![1705994433304](https://github.com/antvis/L7/assets/96137916/6786b506-43da-4ca8-9b72-6ed0740d44cf)

**Comment by lzxue** [comment]
你栅格数据必须是3857 坐标系的，目前看你是4326的
