### ISSUE TITLE
CityBuildingLayer不能设置偏移量

### ISSUE THREAD

**Issue by yong722** [antvis/L7#2267]
### 问题描述

CityBuildingLayer不能设置偏移量

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
你说的偏移量垂直上升？

**Comment by yong722** [comment]
> 你说的偏移量垂直上升？

导入的建筑位置与地图有差异（经纬度），期望能通过微调偏移量实现建筑与地图位置重合

**Comment by lzxue** [comment]
这个数据层处理就可以的，统一的处理不能解决问题。

**Comment by yong722** [comment]
可以调整建筑层buildingLayer.coordCenter的值实现

**Comment by lzxue** [comment]
> 可以调整建筑层buildingLayer.coordCenter的值实现

这算是魔改吧
