### ISSUE TITLE
高德地图联动升级

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#2269]
### AntV Open Source Contribution Plan（可选）

- [X] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

高级任务

### 任务介绍

目前高德地图与可视化引擎的联动是侵入式的，代码内部大量 if esle 条件判断，冗余的数据处理，升级为解耦的联动方式，
类似百度、腾讯地图的联动方式。

**Comment by KipSong** [comment]
let me do it

**Comment by lvisei** [comment]
> let me do it

有进展吗

**Comment by lvisei** [comment]
https://github.com/antvis/L7/issues/2411
