### ISSUE TITLE
热力图使用MVT Tiles时，部分参数设置不生效

### ISSUE THREAD

**Issue by MyShallowTime** [antvis/L7#2273]
### 问题描述

热力图使用MVT Tiles时，部分参数设置不生效：
 transforms: [
        {
          type: 'hexagon',
          size: 5 * 100000
        }
  ]
或者
shape('heatmap3D')；

### 重现步骤

1、进入官网示例：https://l7.antv.antgroup.com/examples/tile/vector#point
2、将PointLayer改为HeatMapLayer， 此时MVT可以正常出图
![image](https://github.com/antvis/L7/assets/20198963/cb0fb756-64f4-4a4e-a2fc-91cf459e6ba0)

3、添加 transforms: [
        {
          type: 'hexagon',
          size: 5 * 100000
        }
  ]， 地图不渲染
![image](https://github.com/antvis/L7/assets/20198963/4cb84269-cb5a-4898-ae2d-267f55d85fd9)

4、删除transforms， shape设置为heatmap3D， 出图效果是预期吗？
![image](https://github.com/antvis/L7/assets/20198963/74a51f8a-e9ad-4ea2-a00a-4228e53faba0)

**Comment by lzxue** [comment]
瓦片不支持热力图，建议使用非瓦片数据

**Comment by MyShallowTime** [comment]
> 瓦片不支持热力图，建议使用非瓦片数据

感谢回答，那请问 使用瓦片时，图层点击事件中e.features为空数组， 或者通过layer.getSource().getFeatureById()也不能拿到feature，也是预期吗？

**Comment by lzxue** [comment]
> > 瓦片不支持热力图，建议使用非瓦片数据
> 
> 感谢回答，那请问 使用瓦片时，图层点击事件中e.features为空数组， 或者通过layer.getSource().getFeatureById()也不能拿到feature，也是预期吗？

这个是不符合预期的，应该是bug
