### ISSUE TITLE
layerpopup无法弹出了，线上demo也不执行

### ISSUE THREAD

**Issue by mahsked** [antvis/L7#2293]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by heiyexing** [comment]
图层的  mousemove 事件失效了，转移到 https://github.com/antvis/L7/issues/2295 里跟踪

**Comment by zuoyifeng** [comment]
这个并没有解决啊！！！

**Comment by zuoyifeng** [comment]
线上的demo什么时候更新？

**Comment by zuoyifeng** [comment]
查了半天，线上的LayerPopup对象里面缺了属性传参
 trigger: 'click',//hover

> 线上的demo什么时候更新？
