### ISSUE TITLE
[Bug] 腾讯地图 setMapStatus 报错

### ISSUE THREAD

**Issue by heiyexing** [antvis/L7#2300]
### 问题描述

腾讯地图调用 scene.setMapStatus 方法时报错

![image](https://github.com/antvis/L7/assets/29321750/9b637ba1-2bf4-428c-a63a-3352bb0879c8)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
腾讯地图适配问题，感兴趣的同学，可以帮助实现该方法，并提交PR

**Comment by lvisei** [comment]
没有复现，方法里支持的参数可以的
