### ISSUE TITLE
bug：缩放效果不正确

### ISSUE THREAD

**Issue by wufenfen** [antvis/L7#231]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

问题1：Mapbox地图缩小到最小，然后放大，中心位置不正确，会向上偏移。

![image](https://user-images.githubusercontent.com/16536105/75446537-8ccc6180-59a2-11ea-82e2-97e5f71afa2f.png)

![image](https://user-images.githubusercontent.com/16536105/75446578-9fdf3180-59a2-11ea-8817-9a88426e258f.png)

问题2：切换区域之后，地图出现太慢。感觉从很远的地方出现。

![image](https://user-images.githubusercontent.com/16536105/75446657-c309e100-59a2-11ea-95eb-210d1a28e25e.png)

**Comment by thomaszdxsn** [comment]
+1

**Comment by lzxue** [comment]
问题1 ： mapbox可以的缩放等级可以小于0 ，最小的时候显示全图，中心点会发生改变。解决该问题可以将 scene  的 minZoom 设成成0

问题2 是mapbox 的fitbound的动画效果，可以通过设置动画参数解决
