### ISSUE TITLE
MarkerLayer 如何隐藏

### ISSUE THREAD

**Issue by ppdigger** [antvis/L7#233]
使用scene.removeMarkerLayer(layer)，MarkerLayer中的marker都清空了。在api中未看到可以隐藏/显示MarkerLayer的接口

**Comment by ParryQiu** [comment]
layer 是否可见是可以单独控制的。
https://l7.antv.vision/en/docs/api/layer/layer#isvisible

**Comment by lzxue** [comment]
目前Marker,MarkerLayer 没好隐藏方式，目前建议方案通过移除控制

**Comment by 2912401452** [comment]
目前提供了 hide/show 方法调整 marker 的透明度
