### ISSUE TITLE
如和创建有三维高度的标注点

### ISSUE THREAD

**Issue by zuoyifeng** [antvis/L7#2334]
### 问题描述

在场景内创建有高度的点，类似高德地图的创建文本标注点
var A = new AMap.Text({
      text: 'XX大厦A座',
      position: [116.472476, 39.991878],
      height: 650,
      verticalAlign: 'bottom',
      map: map,
      style: {
        'background-color': 'red',
        'border-color': 'white',
        'font-size': '12px'
      }
    })
以上代码里面height属性就是当前经纬度点位的三维空间高度，详细可见下面示例

### 预期行为

![Snipaste_2024-03-06_15-11-20](https://github.com/antvis/L7/assets/18437941/3fcff477-509c-47f3-bf06-b6d0276a09ab)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![Snipaste_2024-03-06_15-11-20](https://github.com/antvis/L7/assets/18437941/c8d21e40-e84f-43bd-a365-943e8b03cd68)

### 补充说明（可选）

高德地图有可实现的效果 [https://lbs.amap.com/demo/javascript-api/example/3d/3d-model](https://lbs.amap.com/demo/javascript-api/example/3d/3d-model)

**Comment by lzxue** [comment]
style 配置  raiseHeight 参数试试

**Comment by zuoyifeng** [comment]
> style 配置 raiseHeight 参数试试

怎样画一个三维的线连接到这个点呢？比如这个线起始位置高度为0 另一端高度为100 同时还有经纬度

**Comment by lzxue** [comment]
三维线，可以 coordinates 可以设置Z 值 [lng,lat,z]
