### ISSUE TITLE
Popup stopPropagation 无效

### ISSUE THREAD

**Issue by foxii-cn** [antvis/L7#2336]
### 问题描述

根据Popup文档（图一），默认阻止鼠标事件冒泡，但官网示例双击气泡边缘或者标题下内容上方空隙时地图照样响应

看了下原因是 .l7-popup 出现了一个 css属性（图二）`pointer-events: none;` 删掉就好了

### 重现链接

https://l7.antv.antgroup.com/examples/component/popup#popup

### 重现步骤

打开上述官网示例，双击气泡发现地图放大

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/L7/assets/38043552/b23d72fc-d013-4761-912e-5e8e80d89acf)

![image](https://github.com/antvis/L7/assets/38043552/80db597b-36a8-4fe7-b28a-3a718e2ac5d7)

**Comment by foxii-cn** [comment]
搜了一下之前也有人反馈过这个 stopPropagation 无效的问题，但是没有修复问题就关闭了
想知道 .l7-popup 的这行 `pointer-events: none;` 有什么作用？

**Comment by foxii-cn** [comment]
加了这行css popup 上注册的事件监听器会无效，应该没有理由同时这么写
![image](https://github.com/antvis/L7/assets/38043552/30cd21e4-348f-4267-a0a1-9f18b2d2facd)
![image](https://github.com/antvis/L7/assets/38043552/964c4303-45a3-400e-8e0d-83e30fc00200)

**Comment by heiyexing** [comment]
`pointer-events: none;` 的作用是：在有的场景下需要 Popup 只是纯信息展示，但不会影响地图交互。
`stopPropagation` 现在看起来有点鸡肋，后面会跟  `pointer-events: none;` 合并搞一个配置去解决此类问题。

**Comment by foxii-cn** [comment]
> `pointer-events: none;` 的作用是：在有的场景下需要 Popup 只是纯信息展示，但不会影响地图交互。 `stopPropagation` 现在看起来有点鸡肋，后面会跟 `pointer-events: none;` 合并搞一个配置去解决此类问题。

问题是，默认情况下内部的div `l7-popup-content__title` 和 `l7-popup-content__panel` 又加了 `pointer-events: initial;` 导致并不能达到你所说的效果，相反官网示例表现出很奇怪的行为：标题和内容部分双击地图不放大，而其余空白部分双击地图会放大

![image](https://github.com/antvis/L7/assets/38043552/db356729-5e47-431a-939c-df29bb99d478)

你也说了是有的场景下需要纯信息展示，这种情况用户只需要自行加上`pointer-events: none;`就可以，况且内部html能够自定义，这部分让用户自己去控制更加合适

**Comment by foxii-cn** [comment]
另外 stopPropagation 能不能把鼠标滚轮事件也加上
