### ISSUE TITLE
开发的过程中发现后台提示需要输入token。所以想确认下，如正式生产环境中，是否需要额外购买高德地图应用许可才能使用

### ISSUE THREAD

**Issue by 992572161** [antvis/L7#2339]
### 问题描述

目前不需要用到第三方地图的底图，但在开发的过程中发现后台提示需要输入token。所以想确认下，如正式生产环境中，是否需要额外购买高德地图应用许可才能使用

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
不需要底图可以使用 Map
