### ISSUE TITLE
想要一个禁用双指操作缩放

### ISSUE THREAD

**Issue by shiruicha** [antvis/L7#2349]
### 问题描述

在触摸屏中可以禁止双指缩放

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
这个跟地图底图相关，可以查看地图文档，
Map 和mapbox 应该地图可以使用 

```
{
touchZoomRotate:false
}
```

**Comment by shiruicha** [comment]
> 这个跟地图底图相关，可以查看地图文档， Map 和mapbox 应该地图可以使用
> 
> ```
> {
> touchZoomRotate:false
> }
> ```

感谢大佬指导
