### ISSUE TITLE
device 多层掩膜问题

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#2350]
### 问题描述

device 渲染模式下 设置多个掩膜图层不生效

错误
![image](https://github.com/antvis/L7/assets/4366658/d8f9d6f2-09a7-46f0-b4ef-6e19d2d9ef9f)

正确输出
![image](https://github.com/antvis/L7/assets/4366658/b81faf1e-3689-435c-a010-1db4cd68e5f3)

https://github.com/antvis/L7/blob/master/examples/demos/mask/multi.ts

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by xiaoiver** [comment]
升级到 `@antv/g-device-api@1.6.10` 即可
