### ISSUE TITLE
英文字体对齐bug什么时候更新解决啊？

### ISSUE THREAD

**Issue by Jerome-lara** [antvis/L7#2357]
### 问题描述

#2046 
我看已经推修复的代码了，但是一直没正式版发出来，导致l7和l7 Plot一直没办法对齐。

### 平台

- 操作系统: [macOS, ]
- 网页浏览器: [Google Chrome, Safari,]

**Comment by lvisei** [comment]
L7 fixd [2.20.1](https://github.com/antvis/L7/pull/2061) ，L7Plot 依赖 L7 升级项目 L7 版本就好。

**Comment by Jerome-lara** [comment]
@lvisei  2.20.1 还没发版本呀，一直在等

**Comment by lvisei** [comment]
> @lvisei 2.20.1 还没发版本呀，一直在等

现在版本都发到 [2.21.0](https://www.npmjs.com/package/@antv/l7/v/2.21.0) 了～
