### ISSUE TITLE
Animate line: unable to see line on map

### ISSUE THREAD

**Issue by lezan** [antvis/L7#236]
* **L7 Version**: 2.0.34
* **Platform**: ReactJS 16.13.0, Node.js v13.9.0, W10.

I am unable to see lines on Animate Line example ([here](https://l7.antv.vision/en/examples/gallery/animate#animate_line)). I tried with different broswer with no success.
If I try to use China mirror site, I can see lines ([here](https://antv-l7.gitee.io/zh/examples/gallery/animate#animate_line)).
When I try to use CodeSanbox example from both website, I am also unable to see lines (both are redirecting to the same codesanbox page).
When I try to use in ReactJS (in local) I am also unable to see lines.

If I try to switch to L7 2.0.0 version (for example) on CodeSanbox, I can see lines animated.

Could be some mismatch between all mirrors and a regression with 2.0.34?

Thanks for your answer.

**Comment by lzxue** [comment]
sorry   Update website delay

before
```
 layer..color('color', v => {
        return `rgb(${v[0]})`;
      })
```
now
```
layer .color('color', v => {
        return `rgb(${v})`;
      })
```
