### ISSUE TITLE
加载Geoserver的矢量瓦片不显示结果

### ISSUE THREAD

**Issue by szygiser** [antvis/L7#2362]
### 问题描述

加载了Geoserver的矢量瓦片地址，但是不显示。
矢量瓦片地址为：http://60.217.200.163:8995/geoserver/gwc/service/tms/1.0.0/ghgas%3Aghgas_pipesectionhpa@WebMercatorQuad@pbf/{z}/{x}/{y}.pbf。
咱们得矢量瓦片格式应该是什么样的？自己制作矢量瓦片的话，应该是什么格式和如何发布？

### 重现链接

https://codesandbox.io/p/sandbox/l7-demo-forked-n6msr7?file=%2Findex.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu46490a00074f6g8rcg7gjh%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu46490a00034f6gqr0k18k9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu46490a00044f6ghcx7ywuy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu46490a00064f6grhskluf9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu46490a00034f6gqr0k18k9%2522%253A%257B%2522id%2522%253A%2522clu46490a00034f6gqr0k18k9%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu46490a00064f6grhskluf9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu46490a00054f6g54j7cobe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu46490a00064f6grhskluf9%2522%252C%2522activeTabId%2522%253A%2522clu46490a00054f6g54j7cobe%2522%257D%252C%2522clu46490a00044f6ghcx7ywuy%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu46490a00044f6ghcx7ywuy%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lvisei** [comment]
采用了 Mapbox 标准的矢量瓦片，没有什么特殊性。重现示例中瓦片请求失败，检查服务可访问。

<img width="1424" alt="image" src="https://github.com/antvis/L7/assets/26923747/f52d3e6a-16b3-4737-bab4-55c05b51688a">

**Comment by szygiser** [comment]
> 采用了 Mapbox 标准的矢量瓦片，没有什么特殊性。重现示例中瓦片请求失败，检查服务可访问。
> 
> <img alt="image" width="1424" src="https://private-user-images.githubusercontent.com/26923747/316369745-f52d3e6a-16b3-4737-bab4-55c05b51688a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNDAxMTEsIm5iZiI6MTcxMTMzOTgxMSwicGF0aCI6Ii8yNjkyMzc0Ny8zMTYzNjk3NDUtZjUyZDNlNmEtMTZiMy00NzM3LWJhYjQtNTVjMDViNTE2ODhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA0MTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNDhkMDk5ZDhmMTY3MDU4ZGE3ZWM4MDYzNDcxNTBhYjZiZTViZDdjMjE4YmZhMGRjYjRiMjFlMjViYTI3YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2jhJ8stckYpbzd1exLQgzJC5kxGTRHSom_s2MaDjFRE">

示例代码中这个服务连接通过mapboxgl是能加载成功的，下面这个链接是Geoserver发布出来的，你可以浏览一些这个地址：http://60.217.200.163:8995/geoserver/gwc/service/tms/1.0.0/ghgas%3Aghgas_pipesectionhpa@WebMercatorQuad@pbf,
您可以看下这个服务连接

**Comment by lvisei** [comment]
服务没有数据，检查服务。mapboxgl 确保可以，贴一个复现链接
```
http://60.217.200.163:8995/geoserver/gwc/service/tms/1.0.0/ghgas%3Aghgas_pipesectionhpa@WebMercatorQuad@pbf/5/24/14.pbf
```

**Comment by szygiser** [comment]
> 服务没有数据，检查服务。mapboxgl 确保可以，贴一个复现链接
> 
> ```
> http://60.217.200.163:8995/geoserver/gwc/service/tms/1.0.0/ghgas%3Aghgas_pipesectionhpa@WebMercatorQuad@pbf/5/24/14.pbf
> ```
L7的复现连接为：https://codesandbox.io/p/sandbox/l7-demo-forked-n6msr7?file=%2Findex.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu46490a00074f6g8rcg7gjh%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu46490a00034f6gqr0k18k9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu46490a00044f6ghcx7ywuy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu46490a00064f6grhskluf9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu46490a00034f6gqr0k18k9%2522%253A%257B%2522id%2522%253A%2522clu46490a00034f6gqr0k18k9%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu46490a00064f6grhskluf9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu46490a00054f6g54j7cobe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu46490a00064f6grhskluf9%2522%252C%2522activeTabId%2522%253A%2522clu46490a00054f6g54j7cobe%2522%257D%252C%2522clu46490a00044f6ghcx7ywuy%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu46490a00044f6ghcx7ywuy%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D
mapboxgl的可记载html附件上传：

**Comment by lvisei** [comment]
> mapboxgl的可记载html附件上传：
> [testgeoserver.zip](https://github.com/antvis/L7/files/14739962/testgeoserver.zip)

```js
map.addSource('mapillary', {
'type': 'vector',
'scheme': 'tms',
'tiles': [
'http://60.217.200.163:8995/geoserver/gwc/service/tms/1.0.0/ghgas%3Aghgas_pipesectionhpa@WebMercatorQuad@pbf/{z}/{x}/{y}.pbf'
],
'minzoom': 1,
'maxzoom': 14,
'tileSize': 512
});
```

1. tileSize 需要一致
2. [scheme](https://docs.mapbox.com/style-spec/reference/sources/#vector-scheme)，L7 矢量瓦片只支持 xyz 的，不支持 tms，改下服务
