### ISSUE TITLE
百度地图加载问题

### ISSUE THREAD

**Issue by szygiser** [antvis/L7#2363]
### 问题描述

咱们引擎加载的百度地图是带偏移的吧？如何加载百度自定义样式的底图？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lvisei** [comment]
L7 没有做偏移处理，使用百度地图，数据应与百度的一致；样式参考百度地图文档，通过 style 设置。

**Comment by szygiser** [comment]
> L7 没有做偏移处理，使用百度地图，数据应与百度的一致；样式参考百度地图文档，通过 style 设置。

import { Scene } from '@antv/l7';
import { BaiduMap } from '@antv/l7-maps';

new Scene({
  id: 'map',
  map: new BaiduMap({
    center: [107.054293, 35.246265],
    zoom: 4.056,
    style: 'e0f462e654a12542b24c873b2b1db67a',
    // 百度地图的logo是否可见，默认true
    logoVisible: false,
    token: 'nZ4akGEGiIurz8A4r1kRwTGPCg03W810'
  })
});
设置了token和自定义的百度底图样式，不起作用

**Comment by lvisei** [comment]
token 和 style 是自己的吗，建议从百度地图的开发者文档看一下

**Comment by szygiser** [comment]
> token 和 style 是自己的吗，建议从百度地图的开发者文档看一下

token和style都是自己的，在百度API测试了，自定义的样式是能出来效果的
![image](https://github.com/antvis/L7/assets/15412933/1597956b-9c68-4f74-bbab-2b53a752c1a6)

**Comment by lvisei** [comment]
贴一个 codesanbox 上复现一下 L7 的使用不行的例子

**Comment by szygiser** [comment]
> 贴一个 codesanbox 上复现一下 L7 的使用不行的例子

https://codesandbox.io/p/sandbox/l7-demo-forked-n6msr7?file=%2Findex.js%3A11%2C47&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu46490a00074f6g8rcg7gjh%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu46490a00034f6gqr0k18k9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu46490a00044f6ghcx7ywuy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu46490a00064f6grhskluf9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B43.25142995523947%252C56.74857004476053%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu46490a00034f6gqr0k18k9%2522%253A%257B%2522id%2522%253A%2522clu46490a00034f6gqr0k18k9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu6jnvq70002536ebkphuka9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A47%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A47%257D%255D%257D%255D%252C%2522activeTabId%2522%253A%2522clu6jnvq70002536ebkphuka9%2522%257D%252C%2522clu46490a00064f6grhskluf9%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu46490a00054f6g54j7cobe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu46490a00064f6grhskluf9%2522%252C%2522activeTabId%2522%253A%2522clu46490a00054f6g54j7cobe%2522%257D%252C%2522clu46490a00044f6ghcx7ywuy%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu46490a00044f6ghcx7ywuy%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A10%257D

**Comment by lvisei** [comment]
> token和style都是自己的，在百度API测试了，自定义的样式是能出来效果的

没有看出现在是哪里不一致吗

![image](https://github.com/antvis/L7/assets/26923747/aaa6cc15-009b-40b0-b04e-01c6183f9fa6)

**Comment by lvisei** [comment]
官网上可能是 官网内置的  token与stye 不匹配的原因
