### ISSUE TITLE
removeLayer无法正确的移除多个layer

### ISSUE THREAD

**Issue by hsp-sz** [antvis/L7#2366]
### 问题描述

当我创建多个面图层layer，再通过某一事件逐个移除，发现无法完全移除，会遗留。我在用larkmap时，创建三个，移除的时候，会遗留2个。写最小demo的时候，遗留了一个。尝试removeAllLayer，可以完全移除。

### 重现链接

https://codesandbox.io/p/sandbox/sad-julien-kshfvv?file=%2Findex.js%3A298%2C32

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
@lvisei

**Comment by lvisei** [comment]
内部一个不好的编码习惯 mutable 引起的，可先这样使用解决你的问题，下一个版本修复

```js
const layers = scene.getLayers().slice();
for (const layer of layers) {
  scene.removeLayer(layer);
}
```
