### ISSUE TITLE
出现大概5px的空白区域导致页面出现滚动条

### ISSUE THREAD

**Issue by XYGR** [antvis/L7#2372]
### 问题描述

当容器高度为100%时出现大概5px的空白区域导致页面出现滚动条

### 重现链接

https://codesandbox.io/p/sandbox/peaceful-jerry-x8x7yv

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lvisei** [comment]
demo 上没有看到，检查是不是页面默认 margin 的原因

**Comment by XYGR** [comment]
> demo上没有看到，检查是不是页面默认margin的原因

![WX20240404-212318](https://github.com/antvis/L7/assets/43074851/3da4a645-3b28-49bf-bf11-9c1479a917f8)
qi请看demo截图，默认margin已清除，但右侧仍然有滚动条

**Comment by lvisei** [comment]
我这边没有，看下是不是系统环境不同 vh 表现不同

![image](https://github.com/antvis/L7/assets/26923747/f8e70947-bd98-4096-ade7-78bcb8c6a006)
