### ISSUE TITLE
CanvasLayer,鼠标交互相关的bug

### ISSUE THREAD

**Issue by hehuasa** [antvis/L7#2392]
### 问题描述

使用CanvasLayer，绘制了元素，添加到sence后，CanvasLayer所在的dom，覆盖在了map所在的dom元素上，导致底图无法进行鼠标交互，比例拖拽、点击等。

### 重现链接

https://codesandbox.io/p/sandbox/l7-demo-forked-xmlnq9?file=%2FCanvasLayer.js%3A111%2C36

### 重现步骤

1.  安装最新l7依赖，注册 CanvasLayer并添加到地图
2.  此时地图无法进行鼠标交互，但CanvasLayer本身的鼠标交互（例如点击）是可以的。
3.  控制台查看dom树，发现CanvasLayer所在的dom，覆盖在了map所在的dom元素上。CanvasLayer有一个样式类` .l7-canvas-layer`。但是搜了下源代码，没有发现定义这个样式类的地方。
4. 结合官网demo的dom样式，手动给CanvasLayer所在的dom添加了一个style：pointer-events: none。此时地图可以拖拽等鼠标交互，但是CanvasLayer本身的鼠标事件都不响应了。
![1](https://github.com/antvis/L7/assets/26007057/49af22dc-daf5-4456-9b67-16f6b31457c9)
![2](https://github.com/antvis/L7/assets/26007057/09c4598c-a010-4da4-a790-32b1a29620bf)

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome

### 补充说明（可选）

感觉是遗漏了`.l7-canvas-layer `这个 css样式类的定义。可否优先把这个css类发出来呢。
谢谢

**Comment by heiyexing** [comment]
https://github.com/antvis/L7/pull/2393
