### ISSUE TITLE
L7 官网工程 - 文档地址钉正

### ISSUE THREAD

**Issue by lvisei** [antvis/L7#2397]
### AntV Open Source Contribution Plan（可选）

- [ ] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

初级入门任务

### 任务介绍

官网示例的 API 文档地址错误，目前是错误路径，需要更新

### 解决以下问题

1.项目工程跑起来会提示错误路径

![image](https://github.com/antvis/L7/assets/26923747/7d93eff8-2317-4d1a-9b01-51da98637abb)

2. 案例 API 文档

![image](https://github.com/antvis/L7/assets/26923747/b6c2c565-b1bd-4551-a360-5be325691fbb)

### 怎么做

去 examples 目录，对错误的路径进行钉正

![image](https://github.com/antvis/L7/assets/26923747/7f5595da-1510-4f38-ae25-122bd02074ba)

**Comment by lzxue** [comment]
example 页面的 API 文档已经不需要显示了，关闭了 showAPIdoc 配置，并且移除了 API.*md  文件
