### ISSUE TITLE
官网demo「lerc 高程栅格」报错

### ISSUE THREAD

**Issue by Dreammy23** [antvis/L7#2418]
### 问题描述

链接：https://l7.antv.antgroup.com/zh/examples/tile/raster/#lerc
demo 演示代码报错
![image](https://github.com/antvis/L7/assets/18047832/579c25db-9cf4-4f69-89d3-5ef71124b368)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
刚才打开了一下正常显示
