### ISSUE TITLE
在事件中根据字段动态设置opacity时无效或报错

### ISSUE THREAD

**Issue by tsuyoii** [antvis/L7#2424]
### 问题描述

在事件中根据字段动态设置opacity时无效或报错
代码：
gw_layer.on('click', (e: any) => {
    scene?.getLayerByName('分组')?.style({
      opacity: {
        field: 'type',
        value: (type: any) => {
          return type === 'a' ? 0.1 : 1;
        }
      }
    });
})

效果：无效

另一种写法：
代码：
gw_layer.on('click', (e: any) => {
    scene?.getLayerByName('分组')?.style({
      opacity: {
        field: 'type',
        value: [0, 0.3, 1]
      }
    });
})
效果：第一次点击无反应，第二次点击后报错
<img width="728" alt="WeChat8d863f4fe6b7adbb6fbcbb993d6f7abe" src="https://github.com/antvis/L7/assets/49632080/f69597cc-6888-4664-872a-67141f41f8b7">

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

<img width="728" alt="WeChat8d863f4fe6b7adbb6fbcbb993d6f7abe" src="https://github.com/antvis/L7/assets/49632080/dce7a046-9005-4196-98f5-c0fd27690af9">

**Comment by lvisei** [comment]
codesanbox 复现一下～

**Comment by lzxue** [comment]
https://l7.antv.antgroup.com/zh/examples/polygon/3d/#polygon_stylemap   可以参照这个demo

**Comment by tsuyoii** [comment]
> https://l7.antv.antgroup.com/zh/examples/polygon/3d/#polygon_stylemap 可以参照这个demo

在scene.on('loaded', () => {})中可以生效，但是当我放到事件中(例如这里的click事件里)就不生效了

**Comment by tsuyoii** [comment]
> codesanbox 复现一下～

大佬应该怎么在codesanbox里复现呀😭

我在这个官方示例里改了一下，把这段代码替换一下这个例子，这样可以复现
[https://l7.antv.antgroup.com/zh/examples/polygon/3d/#polygon_stylemap](url)
```
import { PolygonLayer, Scene } from '@antv/l7';
import { GaodeMap } from '@antv/l7-maps';

const scene = new Scene({
  id: 'map',
  map: new GaodeMap({
    style: 'dark',
    pitch: 50,
    center: [118.8, 32.056],
    zoom: 8,
  }),
});
const colors = [
  '#87CEFA',
  '#00BFFF',

  '#7FFFAA',
  '#00FF7F',
  '#32CD32',

  '#F0E68C',
  '#FFD700',

  '#FF7F50',
  '#FF6347',
  '#FF0000',
];
scene.on('loaded', () => {
  fetch('https://gw.alipayobjects.com/os/bmw-prod/94763191-2816-4c1a-8d0d-8bcf4181056a.json')
    .then((res) => res.json())
    .then((data) => {
      const filllayer = new PolygonLayer({
        name: 'fill',
        zIndex: 3,
      })
        .source(data)
        .shape('extrude')
        .color('unit_price', colors)
        .size('unit_price')
        // .style({
        //   opacity: {
        //     field: 'unit_price',
        //     value: [0, 1],
        //   },
        // })
        .active(true);
      scene.addLayer(filllayer);

      filllayer.on('click',()=>{
        filllayer.style({
          opacity: {
            field: 'unit_price',
            value: [0, 1],
          }
        })
      })
    });
});

```

**Comment by lzxue** [comment]
初始化的会判断是 Opacity 是数据映射还是常量，开始没有设置 opacity ，初始化haul的任务是常量。

初始化时可以这样写
```ts
.style({
          opacity: {
            field: 'unit_price',
            value: 1,
          },
        })
```

**Comment by tsuyoii** [comment]
> 初始化的会判断是 Opacity 是数据映射还是常量，开始没有设置 opacity ，初始化haul的任务是常量。
> 
> 初始化时可以这样写
> 
> ```ts
> .style({
>           opacity: {
>             field: 'unit_price',
>             value: 1,
>           },
>         })
> ```

成功啦，感谢大佬

**Comment by chameleoncmw** [comment]
> 初始化的会判断是 Opacity 是数据映射还是常量，开始没有设置 opacity ，初始化haul的任务是常量。
> 
> 初始化时可以这样写
> 
> ```ts
> .style({
>           opacity: {
>             field: 'unit_price',
>             value: 1,
>           },
>         })
> ```

这种方式还是会有bug，如果初始化时设置opacity: {field: 'unit_price', value: 1}，之后再次用同样方式改变opacity时，比如 .style({opacity: {field: 'unit_price', value: 0.5}}) ， 是不起作用的
