### ISSUE TITLE
高德地图的语言可以修改为英文吗？

### ISSUE THREAD

**Issue by daiguamm** [antvis/L7#2425]
在高德地图的API中看到中、英文地图，在初始化时设置lang属性为"en"即可，Antv L7似乎没有支持这个属性？可以显示英文的高德地图吗？

**Comment by lvisei** [comment]
高德 [MAP](https://lbs.amap.com/api/javascript-api-v2/documentation#map)文档里没有 lang 属性

**Comment by daiguamm** [comment]
> 高德 [MAP](https://lbs.amap.com/api/javascript-api-v2/documentation#map)文档里没有 lang 属性

https://lbs.amap.com/demo/javascript-api/example/map/map-english这个是咋实现的？

**Comment by lvisei** [comment]
> https://lbs.amap.com/demo/javascript-api/example/map/map-english这个是咋实现的？

这是 amap V1 的示例，我们默认用的 V2，去看看 amap V2 支持 lang 设置不

**Comment by daiguamm** [comment]
> > [https://lbs.amap.com/demo/javascript-api/example/map/map-english这个是咋实现的？](https://lbs.amap.com/demo/javascript-api/example/map/map-english%E8%BF%99%E4%B8%AA%E6%98%AF%E5%92%8B%E5%AE%9E%E7%8E%B0%E7%9A%84%EF%BC%9F)
> 
> 这是 amap V1 的示例，我们默认用的 V2，去看看 amap V2 支持 lang 设置不

好的，谢谢
