### ISSUE TITLE
如何获取点图层内包含的每一个点的组件对象呢？

### ISSUE THREAD

**Issue by wushengyuan** [antvis/L7#2452]
我找不到途径反馈问题了，所以在这里像开发者问一下。
我目前创建了一个PointLayer，内部有5个点。但是，在我想实现“点击内部的某个点使其变色”的功能时却发现没有对应的api。请问该如何实现这个需求

**Comment by lzxue** [comment]
- 通过 active 或者 select 方法设置
- 或者自己监听点击事件，新增一个高亮图层
