### ISSUE TITLE
l7加载mapbox自定义地图报错

### ISSUE THREAD

**Issue by lxyzong** [antvis/L7#2479]
![微信图片_20240516210904](https://github.com/antvis/L7/assets/31872602/bd16cfe9-67da-4cbf-8e36-4de9c32d57a7)

**Comment by lvisei** [comment]
![image](https://github.com/antvis/L7/assets/26923747/f8f975ba-414d-4766-8453-a88f02e50d0b)

**Comment by lvisei** [comment]
https://l7.antv.antgroup.com/examples/map/map/#mapbox
