### ISSUE TITLE
源码运行报错

### ISSUE THREAD

**Issue by kkak1990** [antvis/L7#2481]
- **L7 Version**:
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

**Comment by kkak1990** [comment]
![image](https://github.com/antvis/L7/assets/108910910/553d5e37-6bbf-4694-9c40-13b32e424cc7)

**Comment by lvisei** [comment]
https://blog.csdn.net/qq_40085888/article/details/104253914
