### ISSUE TITLE
使用 MapLibre底图，新增marker 拖动报错

### ISSUE THREAD

**Issue by hehuasa** [antvis/L7#2487]
### 问题描述

使用 MapLibre底图,新增marker ,options 设置 `draggable:true,`，进行marker拖动时，会报错。
跟了下报错信息：拖动时，代码 使用 `e.lnglat` 获取当前坐标，但是实际返回的 坐标对象名为 `e.lngLat`；

### 重现链接

https://codesandbox.io/p/sandbox/l7-demo-forked-d5mgff?file=%2Findex.js%3A15%2C28

### 重现步骤

复现仓库见上方，最小复现步骤：

```
import { Scene, Marker } from "@antv/l7";
import {  MapLibre } from "@antv/l7-maps";


const scene = new Scene({
  id: "map",
  map: new MapLibre({
    pitch: 0,
    style:
      "https://api.maptiler.com/maps/3eb670bc-724c-46fc-adbc-48f2c5956bc8/style.json?key=mIkNLzkbhwfNopBXjt6d",
    center: [121.435159, 31.256971],
    zoom: 12,
  }),
});
const marker = new Marker({ draggable: true }).setLnglat([
  121.4316962, 31.26082325,
]);

scene.addMarker(marker);
```

### 平台

- 操作系统: Windows
- 网页浏览器: Chrome

**Comment by lvisei** [comment]
收到 MapBox/Map 也有这个问题

**Comment by lvisei** [comment]
[@antv/l7@2.22.0](https://github.com/antvis/L7/releases/tag/%40antv%2Fl7%402.22.0) 已修复
