### ISSUE TITLE
点层图-文本标注-内存不释放

### ISSUE THREAD

**Issue by ScOrPiOzzy** [antvis/L7#249]
* **L7 Version**: 2.0

* **Platform**: win7, 64位

* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/28925952/76379320-bfa32c00-638a-11ea-88b9-7ddb75042b7a.png)

* **CodePen**:https://codesandbox.io/s/1jkix

* **官方案例**:https://l7.antv.vision/zh/examples/point/text

地图在`移动`或`缩放`时候, 内存飙升.

**Comment by ScOrPiOzzy** [comment]
我好像找到导致内存不释放的原因了.

在`node_modules\@antv\l7-layers\es\point\models\text.js`的`getUninforms`方法中有这么一句
```
      if (Object.keys(mapping).length !== this.textCount) {
        this.updateTexture();
      }
```
暂时没明白意图是什么, 我只是粗暴地将其注释掉, 然后一切正常运行, 没有出现内存飙升的情况

**Comment by lzxue** [comment]
没有更新textCount 导致的，下一版本修复

**Comment by ScOrPiOzzy** [comment]
> 没有更新textCount导致的，下一版本修复

好的,期待新版本..
