### ISSUE TITLE
WMS服务加载GeoServer的图片类型会出现地图平铺的问题

### ISSUE THREAD

**Issue by aaa1729511481** [antvis/L7#2506]
根据官网例子：https://l7.antv.antgroup.com/examples/tile/basemap#wms  
copy到项目中，第37行WMS地址更换为公司地图服务器Geoserver导出的png数据（http://203.56.192.140/geoserver/sn2/wms?service=WMS&version=1.1.0&request=GetMap&layers=sn2%3Avegetable&bbox=105.6701407070002%2C30.31957705100018%2C105.76017704100018%2C30.44515179400018&width=550&height=768&srs=EPSG%3A4326&styles=&format=image%2Fpng）
，运行项目时出现地图被png数据平铺占满，地图缩放时会跟随铺满。使用OpenLayers格式时，提示：Could not load image because of The source image could not be decoded.. Please make sure to use a supported image type such as PNG or JPEG. Note that SVGs are not supported。

期望 ：能支持Geoserver导出的格式
@antv/l7": "^2.21.10
@antv/l7-maps": "^2.21.10
图一：使用png格式  图二：使用Openlayers格式  图三：代码
![1](https://github.com/antvis/L7/assets/132034539/e4cf40a9-ff48-4dca-8f51-b3298d276cfe)
![Uploading 2.png…]()
![3](https://github.com/antvis/L7/assets/132034539/c66f8ef4-a7e4-4afd-8d7c-82c1ef07178d)

**Comment by zhaokjun** [comment]
把url参数里的bbox参数删除就可以了，还有其他参数，保留基本的参数，其他都删了。
