### ISSUE TITLE
地图初始化不显示

### ISSUE THREAD

**Issue by taofeifanIT** [antvis/L7#2508]
- **L7 Version**: @antv/l7@2.21.10     @antv/larkmap@1.4.16
- **Platform**: win11
- **Mini Showcase(like screenshots)**:
`-import { PointLayer, Scene } from '@antv/l7';
import { GaodeMap } from '@antv/l7-maps';
import { useEffect } from 'react';

export default function OrderMap() {
    useEffect(() => {
        const scene = new Scene({
            id: 'map',
            map: new GaodeMap({
                pitch: 66.02383,
                center: [121.400257, 31.25287],
                zoom: 14.55,
                rotation: 134.95,
            }),
        });
        scene.on('loaded', () => {
            fetch('https://gw.alipayobjects.com/os/basement_prod/893d1d5f-11d9-45f3-8322-ee9140d288ae.json')
                .then((res) => res.json())
                .then((data) => {
                    const pointLayer = new PointLayer({})
                        .source(data, {
                            parser: {
                                type: 'json',
                                x: 'longitude',
                                y: 'latitude',
                            },
                        })
                        .animate(true)
                        .active(true)
                        .shape('name', ['cylinder', 'triangleColumn', 'hexagonColumn', 'squareColumn'])
                        .size('unit_price', (h) => {
                            return [6, 6, h / 500];
                        })
                        .color('name', ['#739DFF', '#61FCBF', '#FFDE74', '#FF896F']);

                    scene.addLayer(pointLayer);
                });
        });

    }, [])
    return <div style={{
        // background: 'white',
        boxShadow: '0 0 10px 0 rgba(0, 0, 0, 0.1)',
        borderRadius: '5px',
        height: '470px',
    }}>
        <div id='map' />
    </div>
}`
- **CodePen Link**:
![image](https://github.com/antvis/L7/assets/42193371/ebe10ed3-ab21-4dbe-ae69-8756ffce9bd0)

**Comment by lvisei** [comment]
代码块编辑一下，阅读起来方便些 @taofeifanIT 

https://docs.github.com/zh/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by lvisei** [comment]
配置高德地图作为底图时，需配置 key

- https://github.com/antvis/L7/discussions/1112
