### ISSUE TITLE
关于内网部署的功能限制

### ISSUE THREAD

**Issue by nanfb** [antvis/L7#2536]
### 问题描述

在内网环境使用L7有功能被限制吗，比如有些功能的缺失之类的

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lvisei** [comment]
L7 没有限制

**Comment by nanfb** [comment]
> L7 没有限制

回复好快，快男。了解，所以内网部署一般是第三方服务商有所限制是吗

**Comment by lvisei** [comment]
是的 底图是高德的话，需要能访问高德
