### ISSUE TITLE
底图使用Map时，点击地图的div，然后在浏览器中按F11全屏展示时，地图的div会出现一圈黑色的边框

### ISSUE THREAD

**Issue by aaa1729511481** [antvis/L7#2546]
### 问题描述

底图使用Map时，点击地图的div，然后在浏览器中按F11全屏展示时，地图的div会出现一圈黑色的边框，想要将该黑色边框隐藏

### 重现链接

https://codesandbox.io/p/sandbox/jolly-sound-c9w9t4

### 重现步骤

鼠标左键点击地图，然后按F11使浏览器全屏，地图的边框就会出现黑色边框。若底图为高德地图时，则不会出现（其他底图没试过）

### 预期行为

希望底图为Map时，不会出现黑色边框的情况

### 平台

- 操作系统: [Windows]
- 网页浏览器: [Google Chrome,]

### 屏幕截图或视频（可选）

![35d45bd1723e41e3e2f0b4f2b379651](https://github.com/antvis/L7/assets/132034539/9cfc6cee-ab93-474a-8658-ad5227a4dfa9)

### 补充说明（可选）

最新版本的L7也存在这个问题 （2024-06-21版本）

**Comment by lvisei** [comment]
Mac 上是蓝色，检查是不是浏览器默认自带样式

- https://stackoverflow.com/questions/26531663/how-to-change-a-divs-outline-color-when-selected

![image](https://github.com/antvis/L7/assets/26923747/3ae1e0ea-9b57-48db-98bc-d29e71d929ce)

**Comment by aaa1729511481** [comment]
确实是这样原因 ，加上 下面的代码就解决了 赞
:focus-visible {
    outline: 0;
  }
