### ISSUE TITLE
使用PointLayer添加点要素，点击事件触发位置不准确

### ISSUE THREAD

**Issue by a1329403800** [antvis/L7#2552]
### 问题描述

L7使用版本为：2.22.0,
加载点要素，后点击要素并不能弹出弹窗，需要点击要素靠上或者要素外上面一点才能触发点击事件。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

https://github.com/antvis/L7/assets/43359344/1244d27f-5872-4293-97ea-5f9cb06136ca

![代码截图](https://github.com/antvis/L7/assets/43359344/0c917334-455b-4825-a9fb-12ac853a749e)

**Comment by lvisei** [comment]
试试配置 [pickingbuffer](https://l7.antv.antgroup.com/api/base_layer/base#pickingbuffer) 属性。

**Comment by a1329403800** [comment]
![截图](https://github.com/antvis/L7/assets/43359344/39958515-ba5e-460c-a29d-72bef9c187cf)
不知配置是否正确    没有起作用

**Comment by lvisei** [comment]
关掉配置，加一个 renderer 配置试试

```js
const scene = new Scene({
		renderer: 'regl'
		...
});
```

**Comment by a1329403800** [comment]
我尝试建立一个模板，遇到点问题，如何使用上传的图片作为点要素的形状呢？
![代码截图 (2)](https://github.com/antvis/L7/assets/43359344/68b418f8-499c-4366-b462-2dc22b939091)

**Comment by a1329403800** [comment]
大概就是使用图片创建点要素会使，点击事件不准确，而且好像会根据设置的偏移量同样偏移

**Comment by lvisei** [comment]
> 我尝试建立一个模板，遇到点问题，如何使用上传的图片作为点要素的形状呢？

图片传 cdn 地址

**Comment by lvisei** [comment]
> 据设置的偏移量同样偏移


还可以试试 2.22.0 以前的版本有没有问题。

**Comment by a1329403800** [comment]
好像找到导致问题的原因了，使用高德地图作为地图时，没有问题，使用天地图时会出现上述问题

**Comment by shen-lan** [comment]
@a1329403800 兄弟你怎么弄的？必须使用天地图怎么解决  点击的位置确实是偏移的。
