### ISSUE TITLE
使用官方网站图层信息框实例，会报toFixed的错，改掉后就会拿不到数据显示undefind

### ISSUE THREAD

**Issue by li-wei99** [antvis/L7#2560]
官方文档首次加载会报错
![1](https://github.com/antvis/L7/assets/50743193/670db7bf-753d-4e30-8dd2-db2fc8731489)
不知道是电脑少什么配置之类的
修改后就会拿不到数据，显示undefind
![Uploading 2.jpg…]()

**Comment by lvisei** [comment]
图片未上传成功，不太明白什么情况 @li-wei99
