### ISSUE TITLE
使用了高德地图作为底图, 加载正常的geojson数据会和地图有偏移

### ISSUE THREAD

**Issue by outcast521** [antvis/L7#2564]
### 问题描述

怎么解决高德地图的偏移问题啊, API文档中没看到相关的解释, 有没有方法纠正高德地图的偏移问题?

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lvisei** [comment]
使用高德地图，检查是否为火星坐标数据
