### ISSUE TITLE
l7-draw 

### ISSUE THREAD

**Issue by shining-data** [antvis/L7#2565]
### 问题描述

"@antv/l7-draw": "^3.1.3",mapbox 为底图模式；这边我是用的离线地图；
绘制的时候，会发生偏移，估计是坐标系的区别。
![image](https://github.com/antvis/L7/assets/161019165/6c4ebee3-f17c-4a2d-bcf2-617b321a0f65)

### 预期行为

是否能根据地图的坐标系去做绘制，根据l7-editor一致支持可选择坐标系，或许能否提供一个入参，指定使用的坐标系是什么

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by heiyexing** [comment]
l7-draw 是根据鼠标事件反上来的坐标传给图层进行绘制的，建议看一下 click 这些鼠标事件的坐标是否正确
