### ISSUE TITLE
水波散点图 当地图缩放时 点位偏移

### ISSUE THREAD

**Issue by guzicheng90** [antvis/L7#2588]
官方示例“水波散点图” 在当地图缩放时 同一个点位会出现偏移
![image](https://github.com/user-attachments/assets/e102a1d6-a1c9-4a4c-8204-cddef2d2c106)
![image](https://github.com/user-attachments/assets/1049885c-6f1d-4a1f-8534-25f9547f830e)

**Comment by lvisei** [comment]
看下是不是像数单位，地图缩小的情况下，圆还是那么大，看上去会有有偏移

**Comment by guzicheng90** [comment]
我有相同猜测 但这里似乎没有设置渲染方式的地方？    
const pointLayer = new PointLayer({})
      .source(data, {
        parser: {
          type: 'csv',
          x: 'Longitude',
          y: 'Latitude',
        },
      })
      .shape('circle')
      .active(true)
      .animate(true)
      .size(40)
      .color('#ffa842')
      .style({
        offsets: [40, 40],
      });

**Comment by lvisei** [comment]
style 上

**Comment by guzicheng90** [comment]
啊 我把offsets:[40,40]去掉就正常了 谢谢
