### ISSUE TITLE
PolygonLayer 使用数据源 source(data,{parser:{type:'json'}})，不能渲染

### ISSUE THREAD

**Issue by amve** [antvis/L7#26]
* **L7 Version**:1.3.2
* **Platform**: Browser Chrome @76.0.3809.132
* **CodePen Link**:

data 数据为json
`
[{
        "label": "A1",
        "cat": "疯子",
        "lng": 102.5377969,
        "lat": 48.4715354,
        "to_lng": 92.59428911,
        "to_lat": 52.4991738,x
        "points": [
            [121.34349799968906, 31.512055999985392],
            [121.3622599998125, 31.506785999770123],
            [121.49426699962251, 31.417845999789357],
            [121.52123199989882, 31.394787999681277],
            [121.60304099969844, 31.37265800032847],
            [121.72251299966202, 31.303514000016172],
            [121.74374799977883, 31.283202000228304],
            [121.80981499979465, 31.196909000060938],
            [121.94679500025403, 31.065888000016056],
            [121.97755499992343, 31.016104000118997],
            [121.99093300039206, 30.968427000089903],
        ],
        "value": 33,
        "createDate": "2019/8/15 20:12"
}]
`
数据源配置(二级，数组，三级数组都试过)
` layer.source(data,{
      parser:{
        type:'json',
        coordinates:'points'
      }
})
`
代码 PolygonLayer 图形 怎么配置都无法显示。  是否必须使用geojson？
`    scene.PolygonLayer().source(data,{parser:{type:'json',coordinates:'points'}})      .shape('fill').color("#fff").active(true).style({opacity: 1}).render()`

明白数据流转模式，也理解概念，现正在做可视化平台，集成L7地图渲染，常用json数据模式

![QQ截图20190906151337](https://user-images.githubusercontent.com/16434725/64408569-ab1f6780-d0b9-11e9-960b-8d7d670eae37.png)

**Comment by lzxue** [comment]
我这边测试了一了一下 三级数组是可以的
`const data = [{ 
  "label": "A1", "cat": "疯子", "lng": 102.5377969, "lat": 48.4715354, 
  "to_lng": 92.59428911, "to_lat": 52.4991738,
  "points": [[ [121.34349799968906, 31.512055999985392], [121.3622599998125, 31.506785999770123], [121.49426699962251, 31.417845999789357], [121.52123199989882, 31.394787999681277], [121.60304099969844, 31.37265800032847], [121.72251299966202, 31.303514000016172], [121.74374799977883, 31.283202000228304], [121.80981499979465, 31.196909000060938], [121.94679500025403, 31.065888000016056], [121.97755499992343, 31.016104000118997], [121.99093300039206, 30.968427000089903 ] ] ], 
  "value": 33, "createDate": "2019/8/15 20:12" }]`

区域比较小注意缩放到区域中心点

**Comment by amve** [comment]
已解决，感谢，我数据有问题
