### ISSUE TITLE
l7引入有问题，L7.Scene在vs code中识别不出来

### ISSUE THREAD

**Issue by lz0728** [antvis/L7#2602]
### 问题描述

<script src="https://unpkg.com/@antv/l7"></script>时，浏览器网址的状态是
状态代码:
302 Found
怎么办

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lvisei** [comment]
应该是这个 CDN 的网络问题，网上找一下可替换的 CDN

**Comment by lz0728** [comment]
![image](https://github.com/user-attachments/assets/5fb9b0da-748e-48e6-b291-6a1a6a0cdbd1)

**Comment by lz0728** [comment]
<script src="https://cdn.jsdelivr.net/npm/@antv/l7@latest/dist/l7.js"></script>使用了这个新的CDN，网络没问题了，但是L7还是不认识
