### ISSUE TITLE
closeOnClick事件失效问题

### ISSUE THREAD

**Issue by lz0728** [antvis/L7#2608]
### 问题描述

popup信息框开启了closeOnClick，但是点击其他地图区域并消息框并没有消失

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![image](https://github.com/user-attachments/assets/47e0f74e-e710-4f00-866b-7c1531b8c1bd)

**Comment by heiyexing** [comment]
Popup 构造器只能传一个 Options 对象，你把参数拆成两个传递了

![image](https://github.com/user-attachments/assets/285abc78-ae47-460c-ba7a-af59a9ee5a58)

**Comment by lz0728** [comment]
> Popup 构造器只能传一个 Options 对象，你把参数拆成两个传递了
> 
> ![image](https://private-user-images.githubusercontent.com/29321750/364214034-285abc78-ae47-460c-ba7a-af59a9ee5a58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MjEwMzcsIm5iZiI6MTcyNTQyMDczNywicGF0aCI6Ii8yOTMyMTc1MC8zNjQyMTQwMzQtMjg1YWJjNzgtYWU0Ny00NjBjLWJhN2EtYWY1OWE5ZWU1YTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAzMzIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NDJiMTZlMjQwMTQwNzdlNTVmOTZhNzNjMTEyOTczNDJlOTk5MmYyNjk0YzA4NTc2MWRlMDBjMjBlYTU2MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g7tQatm-VfgCUH7pEHpIeW3EjsutaDgWbTBv_ku_1KQ)

![image](https://github.com/user-attachments/assets/aeb05849-b126-463a-8f00-5e62fe2f2005)
这样是吧
