### ISSUE TITLE
风场、暴雨点、暴雪点图层添加失败

### ISSUE THREAD

**Issue by lz0728** [antvis/L7#2609]
### 问题描述

风场、暴雨点、暴雪点图层添加失败，运行之后并没有显示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![image](https://github.com/user-attachments/assets/b8087c64-54db-4600-9713-b075104975b6)

**Comment by lz0728** [comment]
![image](https://github.com/user-attachments/assets/990c2350-0dcf-4cb7-8183-63b0629987e4)

**Comment by lvisei** [comment]
风场是实验性图层，目前不支持
