### ISSUE TITLE
地图平移时触发事件mapmove报错

### ISSUE THREAD

**Issue by lz0728** [antvis/L7#2611]
### 问题描述

l7.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'on')
    at r.value (l7.js:1:694456)
    at e.value (l7.js:1:1184570)
    at index.html:368:15

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![image](https://github.com/user-attachments/assets/af94cd6e-e41e-4de2-81b7-1b7868f5689c)

**Comment by lvisei** [comment]
复现在线案例，这里应该是没有风场这个图层报错

**Comment by lz0728** [comment]
> 复现在线案例，这里应该是没有风场这个图层报错

![image](https://github.com/user-attachments/assets/d45d167d-c1b6-43b5-9b19-d63b37c41609)
这里是有的，但是还是报错

**Comment by lz0728** [comment]
![image](https://github.com/user-attachments/assets/659f802b-cef7-4d82-81f3-b915dd4393a5)
效果已经出来了，但是浏览器还是有这个错误

**Comment by lvisei** [comment]
没有复现，codesanbox 复现在线示例
