### ISSUE TITLE
如何使用高德图层

### ISSUE THREAD

**Issue by annoyc** [antvis/L7#2618]
### 问题描述

如何使用高德图层以满足业务需求，比如高德AMap.Circle，在本仓库文档中未找到类似api，希望可以兼容高德图层，或者提供类似高德Circle接口

### 重现步骤

无

### 预期行为

无

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

无

### 补充说明（可选）

如何使用高德图层以满足业务需求，比如高德AMap.Circle，在本仓库文档中未找到类似api，希望可以兼容高德图层，或者提供类似高德Circle接口

**Comment by lvisei** [comment]
通过 Scene 拿到 map，map 是高德地图的实例

**Comment by lvisei** [comment]
const amap = scene.map
