### ISSUE TITLE
在高德底图的demo中 没有显示国外地区信息

### ISSUE THREAD

**Issue by Rose-wu** [antvis/L7#2620]
### 问题描述

demo中 在style = light下 不显示国外地区以及海洋名称等  并且在style = dark下显示了名称 但是缩小后也没有显示城市下具体地区名称

### 重现链接

https://l7.antv.antgroup.com/zh/examples/map/map/#gaodemap

### 预期行为

![image](https://github.com/user-attachments/assets/a8a2cf58-596a-4f3f-abec-5efc35ff57a2)
在百度的demo中可以看到详细的地区信息

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![image](https://github.com/user-attachments/assets/1ff91e1e-c303-4cbc-8ac4-fd46465a2147)
![image](https://github.com/user-attachments/assets/a7fd9a8b-e2b7-48a1-aeee-cb7336b3b8bb)

**Comment by lvisei** [comment]
高德地图的服务缺少海外的信息，去高德开发者平台能否配置出来 https://lbs.amap.com/product/geohub#mapstyle，海外可以用 mapbox
