### ISSUE TITLE
GaodeMap 添加样式不生效

### ISSUE THREAD

**Issue by zhangchengwen629** [antvis/L7#2650]
### 问题描述

	const scene = new Scene({
		id: "map",
		map: new GaodeMap({
			style: "amap://styles/5250e7f46f813282a5faf7c234254523", // 样式URL
			center: [120.19382669582967, 30.258134],
			pitch: 0,
			zoom: 12,
			token: "",
		}),
	});

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by wang1212** [comment]
检查 `securityJsCode`、`token`、`style` 是否来自于同一个开发者账户，这三个信息是必须的

**Comment by zhangchengwen629** [comment]
window._AMapSecurityConfig = {
    securityJsCode: "「你申请的安全密钥」",
  };
