### ISSUE TITLE
图层事件冒泡

### ISSUE THREAD

**Issue by YE-Fan** [antvis/L7#269]
* **L7 Version 2.1**:

Layer叠加之后，怎么让点击事件不冒泡
![图片](https://user-images.githubusercontent.com/25742666/77648753-9e098d80-6fa3-11ea-9668-9fad12dd1f56.png)
![图片](https://user-images.githubusercontent.com/25742666/77648911-e032cf00-6fa3-11ea-8ccb-87c237f80485.png)

点击这两个图层叠加的部分，会同时触发两个图层的click事件，怎么只触发最上层的图层的事件

**Comment by lzxue** [comment]
你是两个图层都需要监听是吧，但是希望只有最上面的响应用到事件？

**Comment by YE-Fan** [comment]
没错，就是这样

**Comment by lzxue** [comment]
现在还不支持，下一步会考虑增加冒泡机制

**Comment by lzxue** [comment]
目前已经开启了默认只拾取最上层元素
