### ISSUE TITLE
bug: 官网上图表演示中的经典热力3d 地图放大到最大再缩小之后，热力点消失，没有重新渲染

### ISSUE THREAD

**Issue by lijingyu1538** [antvis/L7#272]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lijingyu1538** [comment]
官网实例中的bug

**Comment by lijingyu1538** [comment]
国内镜像同样的问题，并且拖动过程热力点和地图不同步

**Comment by lzxue** [comment]
3d  热力图目前会有问题，正在修复

**Comment by lzxue** [comment]
同 issue #271
