### ISSUE TITLE
Bug: 网格热力图中方块中心点偏移

### ISSUE THREAD

**Issue by yuriholyhigh** [antvis/L7#273]
* **L7 Version**: unpkg引入最新版
* **Platform**: Windows 10, Chrome 75.0.3770.100（正式版本） （64 位）
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/26298552/78016567-90764e00-737d-11ea-9bc8-9ef99fae97fc.png)

* **CodePen Link**: https://codepen.io/yurizhang110/pen/vYOPYpK

网格热力图(Loca.GridLayer)渲染出的方块并没有以中心点经纬度为中心, 存在偏移的情况

**Comment by lzxue** [comment]
我跟进一下
