### ISSUE TITLE
添加飞线图demo

### ISSUE THREAD

**Issue by guoliangli123** [antvis/L7#281]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

查看了官方demo，有一些3d版本的线图，但是没有飞线图的demo。可否添加飞线图demo，或者告知如何实现一个简单的飞线图功能？

**Comment by lzxue** [comment]
https://l7.antv.vision/zh/examples/gallery/animate#world 这种不能不满足需求吗

**Comment by guoliangli123** [comment]
![wzz](https://user-images.githubusercontent.com/12670391/79106645-7852f580-7da5-11ea-8e7a-8817863fc112.gif)
我想实现这种效果

**Comment by likeswinds** [comment]
飞线和线条能否单独设置样式

**Comment by lzxue** [comment]
> 飞线和线条能否单独设置样式
不能是全局设置的

**Comment by lzxue** [comment]
> ![wzz](https://user-images.githubusercontent.com/12670391/79106645-7852f580-7da5-11ea-8e7a-8817863fc112.gif)
> 我想实现这种效果
demo
https://l7.antv.vision/zh/examples/line/animate

更新了动画参数
https://l7.antv.vision/zh/docs/api/layer/line_layer/arc/#%E8%AE%BE%E7%BD%AE%E5%8A%A8%E7%94%BB%E5%8F%82%E6%95%B0

**Comment by guoliangli123** [comment]
棒！
