### ISSUE TITLE
官网demo里一个疑问

### ISSUE THREAD

**Issue by mfoonirlee** [antvis/L7#284]
链接来自L7示例官网 https://codesandbox.io/s/w6ujq，打开页面后，只有图表视图的宽高发生变化，绘图容器的canvas的高度就会不断变大，且不再响应上/下移操作。。地图背景由原本的黑色变成白色。。
![image](https://user-images.githubusercontent.com/6947182/79226556-2edfd480-7e91-11ea-95e9-4f18f31fd332.png)
图例还有跟flyline会超出地图区域，不知道是不是设计是这样，视觉上看着有点奇怪
另外issue info里的文档好像是附的G2的链接。。

**Comment by lzxue** [comment]
超出是3D空间，是正常显示，
issue info 是和g2共用
demo问题好像遇到过，现在很难复现
