### ISSUE TITLE
可否添加canvas图层

### ISSUE THREAD

**Issue by guoliangli123** [antvis/L7#287]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

看了源代码和官方demo，每个layer都需要shader的编写，门槛比较高。可否提供canvas图层，使用起来更灵活，使用门槛也会降低。

**Comment by lzxue** [comment]
主要有哪些扩展需求？

**Comment by guoliangli123** [comment]
高德支持canvas图层，用高德实现也可以，比如绘制坐标网格等。
