### ISSUE TITLE
建议PointLayer增加更多3D型图层，支持高度参数 

### ISSUE THREAD

**Issue by jack3rpopov** [antvis/L7#289]
目前L7最新版本是2.1.15。PointLayer中的3d图层有圆柱和棱柱。其他的主要是点类型，如符号图、散点图、气泡图，这些都是平面型的图层。

我的建议是PointLayer增加更多的3D图层，如球体、圆锥体等。
球型支持高度参数，配合圆柱。组成有“高度的气球”。适合在立体视角中显示。

**Comment by 2912401452** [comment]
现在已经在规划中了

**Comment by zhuyuejiu** [comment]
> 现在已经在规划中了

有支持3D堆叠图，一条柱子支持多组数据的3D柱状图吗？

**Comment by 2912401452** [comment]
目前 3D 堆叠柱图还未支持，配置高度已经支持了
