### ISSUE TITLE
PolygonLayer  shape(type) 设置问题！

### ISSUE THREAD

**Issue by amve** [antvis/L7#29]
* **L7 Version**: 1.3.2
* **Platform**:Browser Chrome @76.0.3809.132

PolygonLayer 的shape  方法代码 中this.set('shape',type)，把shape方法改写

 shape(type) {
    this.shape = type;
    this.set('shape', type);
    this.set('shapeType', 'polygon');
    return this;
}

导致此方法只能执行一次，并且只能传入line,fill,extrude 三种shape，填写其他field映射都会导致draw时,getRender方法报错。

**Comment by lzxue** [comment]
目前polygon的shape不支持数据映射，只支持line,fill,extrude 常量设置

**Comment by amve** [comment]
多谢。
