### ISSUE TITLE
这个css selector 有问题

### ISSUE THREAD

**Issue by OuyangQianba** [antvis/L7#290]
https://github.com/antvis/L7/blob/master/packages/component/src/css/l7.css#L460

![image](https://user-images.githubusercontent.com/17270099/79679235-bd0fde00-8236-11ea-8a36-9cd65442a092.png)

所有type为checkbox的input 都会应用这段css。

我猜应该是这样的？
```
.l7-control-layers label input[type="radio"], 
.l7-control-layers label input[type="checkbox"]
```

**Comment by lzxue** [comment]
这两个写法效果应该一样吧，你在使用中出现了什么问题？

**Comment by OuyangQianba** [comment]
这两种写法不一样：

`.l7-control-layers label input[type="radio"],  input[type="checkbox"]` 逗号分开的是两个selector, 匹配的是
.l7-control-layers 这个class 的label后代的type为radio的input元素**或者** type 为checkbox的input元素。

而`.l7-control-layers label input[type="checkbox"]` 则进一步需要该input元素的label的后代，同时这个label 要是.l7-control-layers的后代。

出现的问题：
[这个](https://rmwc.io/switches) 组件的style 被意外更改了。

![image](https://user-images.githubusercontent.com/17270099/79757992-61854380-834f-11ea-818e-11f75eba9506.png)

如图，input[type="checkbox"]在这里起了作用。而这里的input元素其实和l7-component没得什么关系。

**Comment by lzxue** [comment]
方便的话你可以提个pr看一下

**Comment by lzxue** [comment]
已升级
