### ISSUE TITLE
轨迹图能否添加marker

### ISSUE THREAD

**Issue by guoliangli123** [antvis/L7#292]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

现在轨迹图不是很明显，只能看出流动，但是具体流动到哪里不是很清楚，能否在轨迹上添加marker，显示轨迹当前运行到哪里，在向哪里运行。

**Comment by lzxue** [comment]
轨迹图效果，可以调整动画参数设定效果

https://l7.antv.vision/zh/docs/api/layer/line_layer/arc/#%E8%AE%BE%E7%BD%AE%E5%8A%A8%E7%94%BB%E5%8F%82%E6%95%B0
