### ISSUE TITLE
layer图层的各个形状的style参数是否可支持更多属性？

### ISSUE THREAD

**Issue by wanjiaHuang** [antvis/L7#294]
目前文档中layer的[style属性](https://l7.antv.vision/zh/docs/api/layer/layer/#style)一共支持三个属性：
opacity   设置透明度
stroke 线填充颜色 仅点图层支持
strokeWidth 线的宽度 仅点图层支持

L7在数据可视化的应用场景是非常有竞争力的，但是数据可视化往往对设计样式要求比较多样化，目前的三种属性并无法满足设计的多样性
例如：
多边形的边框与填充的透明度不一样的时候
线条需要有阴影，需要可自定义阴影的颜色跟大小
线条或多边形的拐角处需要圆润光滑

**Comment by lzxue** [comment]
多边形的描边可以通过添加线图层实现
阴影，拐角圆滑这些功能由于webgl实现比较复杂，需要逐步新增

**Comment by xiaogaofudao** [comment]
style 配置参数可以暴漏  方法回调，比如
`
textAnchor(item) {
   if (item.direction === 1) {
      return "left";
  }
  return "center";
}
`
