### ISSUE TITLE
l7中引用的 Reflect-metadata 和 redux的connect 冲突。

### ISSUE THREAD

**Issue by jefferyssy** [antvis/L7#296]
相关的bug：https://github.com/rbuckton/reflect-metadata/issues/108

如果需要使用L7。在umi项目中，则必须要去改写 connect 方法，让代码不容易理解。
不知道，你们有没有遇到相关问题，有没有好的建议方案。

**Comment by lzxue** [comment]
有没有项目实例，我复现一下
