### ISSUE TITLE
bundle 命令无法执行

### ISSUE THREAD

**Issue by thomaszdxsn** [antvis/L7#299]
![image](https://user-images.githubusercontent.com/23616426/79851555-0d826980-83f8-11ea-9f88-caf30fa365ee.png)

clone了 L7 最新代码，运行 `yarn release` 出现这个错误。

网上搜索不到是什么原因，请问一下你们怎么解决的？

**Comment by lzxue** [comment]
@rollup/plugin-commonjs 版本升级问题，已经锁定到 11.0.2 ，拉去最新代码，更新node_modules
