### ISSUE TITLE
点亮城市示例中动态线的数据

### ISSUE THREAD

**Issue by githubhanjunjun** [antvis/L7#3]
我用pgis转线的geojson数据放到示例中，并没有动态效果，因为坐标中没有第三个值吗？

**Comment by lzxue** [comment]
是的,第三个值表示出现的时间，

**Comment by githubhanjunjun** [comment]
> 是的,第三个值表示出现的时间，

非常感谢您的回复，请问时间的单位是毫秒还是秒，还有每次重复显示一条线的时间是多久，可以设置吗？

**Comment by lzxue** [comment]
单位是毫秒， 速度是每帧率 50ms的步长 ，当前的周期是3.6秒，  目前还没有开放这块这块动画设置的接口，

**Comment by githubhanjunjun** [comment]
> 单位是毫秒， 速度是每帧率 50ms的步长 ，当前的周期是3.6秒， 目前还没有开放这块这块动画设置的接口，

请问我应该如何计算每个点的时间间隔，我用随机数生成了100-3000的数值，遍历每一条线，当随机数小于500，我设置这条线的第一个点时间为随机数，后面的点时间逐个加100。当随机数大于500小于1000，这条线的第一个点时间设置为随机数，后面的点时间逐渐加50。大于1000时时间间隔为10，展示效果并没有实例中的那么好，显示线很短，很稀少的感觉。这个时间间隔的计算方法是什么呢？

**Comment by swwwww** [comment]
> 我用pgis转线的geojson数据放到示例中，并没有动态效果，因为坐标中没有第三个值吗？

你是通过什么方式得到线的geojson数据呢？
