### ISSUE TITLE
IE11的地图显示位置和鼠标触碰位置不相符

### ISSUE THREAD

**Issue by thomaszdxsn** [antvis/L7#300]
谢谢 antv 团队的工作。最近我用 L7 做了一个下钻地图组件，有个问题只在 IE11 出现。详情见动图。

有个值得注意的是，那个返回按钮是 Control 对象，它的位置是准确的。但是地图的位置不是准确的。

请问有见过类似的情况吗？

![屏幕录制2020-04-22 下午2 40 27](https://user-images.githubusercontent.com/23616426/79952448-0701f980-84ad-11ea-9ca4-7ef917035044.gif)

**Comment by lzxue** [comment]
没有遇到过，方便不方便提供一个简单可复现的demo

**Comment by thomaszdxsn** [comment]
好的，我这两天整一个demo

**Comment by Davidyanlong** [comment]
是不是在body或者父元素上有transform相关的css变换？以前也发现过类似的问题不过不是l7

**Comment by MrGuoPF** [comment]
你好，这个问题解决了吗，我也遇到了
