### ISSUE TITLE
vue 中使用 散点地图，data对象传入为undefined

### ISSUE THREAD

**Issue by yqwoe** [antvis/L7#302]
* **L7 Version**: 2.2.0
* **Platform**: vue
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codesandbox.io/s/elastic-flower-64epi?fontsize=14&hidenavigation=1&theme=dark

![image](https://user-images.githubusercontent.com/7060489/80062341-109b6800-8566-11ea-9c98-cba58c828f7f.png)

![image](https://user-images.githubusercontent.com/7060489/80062377-2b6ddc80-8566-11ea-95fe-5402fee5d5e6.png)
![image](https://user-images.githubusercontent.com/7060489/80062388-358fdb00-8566-11ea-8e62-9a4ae6f6736c.png)

**Comment by lzxue** [comment]
![image](https://user-images.githubusercontent.com/4366658/80178435-c7641a80-8630-11ea-9efc-f1beb66b76d5.png)

数据类型设置有误，type json
