### ISSUE TITLE
旧版飞线效果

### ISSUE THREAD

**Issue by likeswinds** [antvis/L7#305]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

这个应该是比较旧的版本吧，飞线效果比较明显
http://antv-2018.alipay.com/zh-cn/l7/1.x/demo/gallery/citybike.html
这个是新版本的，实体线影响了飞线的效果
https://l7.antv.vision/zh/examples/gallery/animate#world
是否考虑扩展下配置，实现旧版的效果

**Comment by lzxue** [comment]
我设置了一些参数 
interval: 0.2,
trailLength: 0.5,
duration: 1
目前是拖尾效果不明显
