### ISSUE TITLE
【需求】L7 MarkerLayer能否增加一些聚合的功能

### ISSUE THREAD

**Issue by labbomb** [antvis/L7#308]
需求：1.在聚合状态下可以触发点击事件，获取当前点击下的聚合数量及数据
           2.对于MarkerLayer,除了addMarkerLayer和removeMarkerLayer，能否增加hide和show的功能
           3.在https://antv-l7.gitee.io/zh/examples/point/marker#clustermarker 中，聚合的颜色（绿色）是否能提供API进行修改
           4.能否支持点击高亮属性，设置文本功能，类似下图
![image](https://user-images.githubusercontent.com/15062456/80349876-7bb8a780-88a2-11ea-9be2-66acc9f8b45a.png)

**Comment by scxslsh** [comment]
这些功能上线了吗？1和3有没有可替代的解决方案

**Comment by labbomb** [comment]
> 这些功能上线了吗？1和3有没有可替代的解决方案
目前解决方法如下
1.监听鼠标点击，通过dom操作获取数量，监听层级，获取数据
3.直接修改css样式

**Comment by scxslsh** [comment]
> > 这些功能上线了吗？1和3有没有可替代的解决方案
> > 目前解决方法如下
> > 1.监听鼠标点击，通过dom操作获取数量，监听层级，获取数据
> > 3.直接修改css样式

目前使用了以下方案：
`const markerLayer = new MarkerLayer({
        cluster: this.cluster,
        clusterOption: {
          element: (params) => {
            console.log(params)  // marker添加extData，可以获取每个点的详细数据
            let el = document.createElement('span')
            el.innerHTML = '测试'
            el.style.cssText += 'background:#fff;padding:5px 10px;'
            el.onclick = () => {
              this.scene.setZoom(7)
            }
            return el
          },
        },
      })
      this.stations.forEach(station => {
        const { id, lng, lat } = station
        const el = this.$refs[`stationPoint${id}`][0].$el
        const marker = new Marker({
          extData: station,
          element: el,
          anchor: 'center',
        }).setLnglat({ lng, lat })
        markerLayer.addMarker(marker)
      })
      this.scene.addMarkerLayer(markerLayer)`

**Comment by labbomb** [comment]
> > > 这些功能上线了吗？1和3有没有可替代的解决方案
> > > 目前解决方法如下
> > > 1.监听鼠标点击，通过dom操作获取数量，监听层级，获取数据
> > > 3.直接修改css样式
> 
> 目前使用了以下方案：
> `const markerLayer = new MarkerLayer({ cluster: this.cluster, clusterOption: { element: (params) => { console.log(params) // marker添加extData，可以获取每个点的详细数据 let el = document.createElement('span') el.innerHTML = '测试' el.style.cssText += 'background:#fff;padding:5px 10px;' el.onclick = () => { this.scene.setZoom(7) } return el }, }, }) this.stations.forEach(station => { const { id, lng, lat } = station const el = this.$refs[`stationPoint${id}`][0].$el const marker = new Marker({ extData: station, element: el, anchor: 'center', }).setLnglat({ lng, lat }) markerLayer.addMarker(marker) }) this.scene.addMarkerLayer(markerLayer)`

可以，是一种解决方案，我还在等官方更新api呢

**Comment by lzxue** [comment]
1，3已经更新了，可以看markerlayer 的文档或者源码欢迎提PR

**Comment by scxslsh** [comment]
> 1，3已经更新了，可以看markerlayer 的文档或者源码欢迎提PR

最新的文档在哪看呢，官网好像没更新

**Comment by labbomb** [comment]
> > 1，3已经更新了，可以看markerlayer 的文档或者源码欢迎提PR
> 
> 最新的文档在哪看呢，官网好像没更新

更新了已经，你仔细找找呢

**Comment by 992572161** [comment]
可以给个更新后的连接吗？ 我这边更好有这样的需求

**Comment by lzxue** [comment]
> 可以给个更新后的连接吗？ 我这边更好有这样的需求

https://l7.antv.antgroup.com/zh/examples/component/marker/#clustermarker
