### ISSUE TITLE
[建议] 建议scene.addLayer方法支持类似mapboxgl addLayer那样可以添加图层到底图某图层之下

### ISSUE THREAD

**Issue by FanNanTx** [antvis/L7#310]
建议scene addLayer支持添加到mapbox 底图某图层之下，类似mapboxgl中的addLayer。

                                                                                                                      最后再次向伟大的你们致敬！

**Comment by lzxue** [comment]
目前 L7 和mapbox结合使用的是双canvas方案，暂时还没计划支实现L7图层放置在mapbox 之下
