### ISSUE TITLE
需求线图配置线宽度

### ISSUE THREAD

**Issue by guoliangli123** [antvis/L7#312]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

线图可否增加线size的配置，类似点图大小配置。 使用.size('data',[20, 40])设置不同线宽，暂时这样设置会报错。

**Comment by lzxue** [comment]
线图层是支持，数据映射的
demo 见 https://l7.antv.vision/zh/examples/line/isoline#isoline
