### ISSUE TITLE
文本标注是否可以增加旋转角度配置

### ISSUE THREAD

**Issue by guoliangli123** [antvis/L7#313]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

文本标注目前不支持旋转，比如某些道路河流名称，需要按照流向配置标注，希望增加旋转支持。

**Comment by lzxue** [comment]
可以先实现文本的旋转方案，但是自动跟随道路方向自动旋转会比较麻烦

**Comment by ParryQiu** [comment]
可添加地图旋转事件的监听，通过 CSS Rotate 进行同步控制旋转。
可行性是可以的，我们实现过。

**Comment by xiaogaofudao** [comment]
可以先实现 旋转配置。现在 style 里面的配置都是静态的，希望可以提供 funciton 回调，参数是遍历的值。支持自定义返回需要的格式
