### ISSUE TITLE
服务端渲染有在计划中吗？

### ISSUE THREAD

**Issue by wucangeo** [antvis/L7#315]
L7支持了大数据量的渲染与可视化，有没有考虑可以在后台渲染，能够打印出精美图幅，或者缓存为成瓦片。
技术上可以参考Mapbox GL Native：
[https://github.com/mapbox/mapbox-gl-native/blob/master/platform/node/README.md](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/node/README.md)

**Comment by lzxue** [comment]
目前侧重于Web端可视化方案

**Comment by wucangeo** [comment]
好的谢谢！
