### ISSUE TITLE
如何阻止click冒泡事件？图层、地图点击事件

### ISSUE THREAD

**Issue by houkunlin** [antvis/L7#328]
* **L7 Version**: 2.2.2 截止问题创建日期2020-05-06
* **Platform**: win10、谷歌浏览器最新版
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codesandbox.io/s/tucengdianjishijianmoupaowenti-flzb8?file=/index.js

图层鼠标事件文档：https://www.yuque.com/antv/l7/layer#8Kbjf
地图鼠标事件文档：https://www.yuque.com/antv/l7/fi19sl#d872400c

当前操作说明：给layer和scene的都添加click事件，在点击layer的时候，触发了layer的click，同时又触发了scene的click

需求、目的、目标：如何做到在点击layer的时候只触发layer的click，而不触发scene的click？

**Comment by lzxue** [comment]
目前地图事件和layer的事件是两套独立的，layer 提供了 unclick 等事件，是否能够满足需求？

**Comment by houkunlin** [comment]
> 目前地图事件和layer的事件是两套独立的，layer 提供了 unclick 等事件，是否能够满足需求？

试了一下，好像不行。在前面的 CodePen Link 地址中，我用 PolygonLayer 绘制一些 3D 图形信息，我想要点击图形，获取到图形信息，然后执行一些展示或者编辑操作，完成后再点击map、scene时隐藏这些展示或者编辑操作。
目前在 PolygonLayer 使用click事件能够获取到feature图形信息，但是同时会触发scene的click事件，也就是无法完成我上面提到的需求，在layer.click触发显示后又立即被scene.click隐藏了。
使用 PolygonLayer 的 unclick 事件时，点击图形信息无法触发事件，点击图形之外的信息才会触发事件，点击图形之外的信息会触发layer.unclick->scene.click

**Comment by lzxue** [comment]
看你描述，我觉得使用 polygon unclick 方法替代scene click方法可也满足你的。

**Comment by houkunlin** [comment]
> 看你描述，我觉得使用 polygon unclick 方法替代scene click方法可也满足你的。

@lzxue 
懂了，明白了，确实满足需求，非常感谢
