### ISSUE TITLE
Cannot read property 'fov' of undefined    

### ISSUE THREAD

**Issue by guozhenqianga** [antvis/L7#33]
版本：1.3.4，webpack+react构建
![image](https://user-images.githubusercontent.com/23112360/65007449-ccdde180-d938-11e9-8d78-def2fd44f820.png)
报错：
![image](https://user-images.githubusercontent.com/23112360/65007475-e3843880-d938-11e9-9b97-e7185bb14a57.png)
链接地址：https://www.guozhenqiang.top/dist/#/

**Comment by lzxue** [comment]
react 使用L7 可以参考demo   https://github.com/lzxue/l7_react_template

**Comment by xuyimingwork** [comment]
> react 使用L7 可以参考demo https://github.com/lzxue/l7_react_template

遇到了同样的报错，但是是在 vue 环境，可以说下这个是什么导致的报错么？
