### ISSUE TITLE
Feature Request: 能否增加高德地图的掩模

### ISSUE THREAD

**Issue by ericdong79** [antvis/L7#347]
* **L7 Version**: 2.1.15
* **Platform**: Web
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/Hansdo/pen/MWaXQBQ

你好，能否在 GaodeMap 类里增加对mask选项的支持，用于实现掩模效果？
[高德地图掩模(mask)示例](https://lbs.amap.com/api/javascript-api/example/3d/mask)
![image](https://user-images.githubusercontent.com/3775991/81631722-18e71480-943b-11ea-8cfd-40dd71943b5b.png)

**此外**，我自己试着在 `@antv\l7-maps\es\amap\map.js` 目录下修改，但奇怪的是mask并不生效。
同样的代码在一个单独引入高德SDK的html中却可以生效 (参见上方CodePen)
```
谢谢！

**Comment by lzxue** [comment]
直接子在map 配置项设置是可以生效的吧

**Comment by ericdong79** [comment]
> 直接子在map 配置项设置是可以生效的吧

请看这个codepen，我给故宫护城河内区域尝试增加了mask： https://codepen.io/Hansdo/pen/qBOKMdR
可以看到，mask的确产生了一些作用，但只是把地图上的文本标签过滤了，底图并没有被隐藏
![image](https://user-images.githubusercontent.com/3775991/81660384-451b8900-946d-11ea-81c7-1bd6d46a2aa7.png)

**Comment by lzxue** [comment]
这个是高德地图功能，跟L7没关系

**Comment by ericdong79** [comment]
> 这个是高德地图功能，跟L7没关系

这个的确是高德地图的功能，所以只是一个功能请求，如果能引入这个功能可视化的效果会更好 :)

**Comment by lzxue** [comment]
> > 这个是高德地图功能，跟L7没关系
> 
> 这个的确是高德地图的功能，所以只是一个功能请求，如果能引入这个功能可视化的效果会更好 :)
你是希望L7 的自由图层也支持mask吗。这个功能后面会增加

**Comment by amapianosa** [comment]
has it been fixed?

**Comment by 2912401452** [comment]
L7 可视化层的掩模会在 2.7.2 版本支持

**Comment by 2912401452** [comment]
https://l7.antv.vision/zh/examples/raster/basic#dem
