### ISSUE TITLE
MAPBOX是否可以做成离线使用

### ISSUE THREAD

**Issue by janxy** [antvis/L7#349]
公司是内网的，可以离线使用mapbox吗？

**Comment by lzxue** [comment]
mapbox 本身是可以的，但是需要自己提供地图服务

**Comment by janxy** [comment]
您的意思是配合foxgis-server-lite这个东西使用吗

**Comment by zy135516** [comment]
> 您的意思是配合foxgis-server-lite这个东西使用吗

遇到同样的问题，需要离线使用mapbox 请问解决了吗？
