### ISSUE TITLE
符号地图在切换缩放层级时会变成白色

### ISSUE THREAD

**Issue by ericdong79** [antvis/L7#350]
![blinking](https://user-images.githubusercontent.com/3775991/81678787-66d43a80-9484-11ea-8a06-f25402d64746.gif)

此问题在[官方示例](https://antv-l7.gitee.io/zh/examples/point/image#image) 上可以重现：鼠标滚轮在地图上滚动切换缩放大小的过程中，图片会间断地变成白色

**Comment by lzxue** [comment]
什么系统，什么浏览器

**Comment by ericdong79** [comment]
> 什么系统，什么浏览器

操作系统 Win10， 在 Chrome (81.0.4044.138) 和 Firefox 上都可以复现

**Comment by ericdong79** [comment]
今天在用别的电脑试了一下（同样的系统和浏览器）发现并没有这个问题，可能跟我本地的环境有关，先关掉了，不好意思

**Comment by xiaogaofudao** [comment]
这个不是个例，官方例子，我的也有这个问题，一模一样。win10 chrome 82 - 84 都有，其他版本浏览器没测试
