### ISSUE TITLE
希望增加 Popup 组件 mouseleave 功能

### ISSUE THREAD

**Issue by wangcongyi** [antvis/L7#358]
* **L7 Version**: 2.2.3
* **Platform**:  Win

官方demo  Popup 组件是放在 layer.on('mousemove‘）事件上 实例化一个 popup
我把 mousemove 改写成 mouseenter  是可以的
但是 我想 mouseleave 的时候 自动把 popup 删除却不好实现
因为拿不到 popup

**Comment by lzxue** [comment]
layer 有 mouseout 事件等同于mouseleave

**Comment by wangcongyi** [comment]
@lzxue 

tks  看到了文档了， 但是 popup 那就要放在外层了？
感觉写法上不太优雅
希望提供类似链式调用的写法
