### ISSUE TITLE
其他地图或不显示地图接入轨迹地图

### ISSUE THREAD

**Issue by WangTongesri** [antvis/L7#370]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

您好，项目中要求使用同一地图，看到地图仅支持高德地图和 MapBox 两种，是否可以接入其他地图？或者其他代替方法？

**Comment by lzxue** [comment]
可以使用mapbox 接入其他地图的瓦片

**Comment by WangTongesri** [comment]
您好有相关的示例代码么？
接入的瓦片要是什么样的？




------------------

&nbsp; &nbsp; &nbsp; &nbsp; 祝您
顺利！










大数据解决方案部&nbsp;王彤



Esri中国信息技术有限公司

地址：北京市朝阳区西坝河南路1号金泰大厦16层

邮编：100028

传真：010-57632299

电话：010-57632149

手机：13581787601

网址：www.esrichina.com.cn
ArcGIS在线体验中心：http://solutions.arcgisonline.cn/ 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by lzxue** [comment]
不显示地图用mapbox style设置成blank   https://l7.antv.vision/zh/examples/draw/UI#mapbox
