### ISSUE TITLE
怎么修改地图上的名称颜色或交互效果呢

### ISSUE THREAD

**Issue by zhaoyuhang123** [antvis/L7#371]
![image](https://user-images.githubusercontent.com/46439189/82199238-02a3f180-9930-11ea-86e6-4e03b4b6856c.png)
想修改这个颜色，看了文档也不知道怎么改，问下大佬有没有解决方案呢

**Comment by lzxue** [comment]
这个是高德底图图的配置，可以查看一下高德地图文档  isHotspot 配置

https://lbs.amap.com/api/javascript-api/reference/map
