### ISSUE TITLE
使用 react 组件写法 改变 lineLayer 的 shape

### ISSUE THREAD

**Issue by wangcongyi** [antvis/L7#385]
* **L7 Version**: 2.2.3
* **Platform**: win
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

```js

 <LineLayer
      source={{
      data: mapData,
      parser: { type: 'json', x: 'lng1', y: 'lat1', x1: 'longitude', y1: 'latitude' }}}
      shape={{ values: 'line' }}     ////// <<<------  
      color={{ values: '#80F4FF' }}
      size={{ values: 0.5 }}
      >
      <LayerEvent type="mouseenter" handler={showPopup} />
</LineLayer>

```

使用 react 组件的写法   lineLayer 的 shape 设置 line 的时候  
颜色和 popup 正常 当把 shape 设置为 arc 的时候 就不正常了

![x](https://user-images.githubusercontent.com/13843979/82625429-ab479f00-9c17-11ea-8a07-410300dc2440.png)
![y](https://user-images.githubusercontent.com/13843979/82625436-af73bc80-9c17-11ea-82c7-2dc8795dd890.png)

update:   shape  arc3d 也是可以的

**Comment by lzxue** [comment]
是不是因为开启了，颜色叠加  https://l7.antv.vision/zh/docs/api/react/layer   blend 设置成normal

**Comment by wangcongyi** [comment]
并没有 代码如 issues 所示

**Comment by lzxue** [comment]
> 并没有 代码如 issues 所示

你改一下配置理看看 能不能解决
```javascript
 <LineLayer options ={{blend: 'normal'}}>
```

**Comment by wangcongyi** [comment]
done  tks
