### ISSUE TITLE
高德3D楼块图层被L7.LineLayer覆盖

### ISSUE THREAD

**Issue by luguanghui** [antvis/L7#387]
项目需要高德3D楼块图层（AMap.Buildings）和动态流线效果，通过传入高德地图实例的方式，创建L7.Scene， 再创建LineLayer， 3D楼块被L7.LineLayer的流线覆盖

**Comment by lzxue** [comment]
高德地图和L7可视化层是两层canvas方案，所以一定会被盖住

**Comment by luguanghui** [comment]
已通过高德提供api AMap.Object3D.MeshLine接口实现
