### ISSUE TITLE
高德地图2.0无camerachange事件，导致无法执行相关initMap代码逻辑

### ISSUE THREAD

**Issue by wittech** [antvis/L7#402]
// 监听地图相机事件
map.on('camerachange', this.handleCameraChanged);
在2.0版本高德api中已经没有以上事件，导致L7无法升级到高德地图2.0

/**
     * 初始化底图
     */
    this.hooks.init.tapPromise('initMap', async () => {
      // 等待首次相机同步
      await new Promise((resolve) => {
        this.map.onCameraChanged((viewport: IViewport) => {
          debugger
          this.cameraService.init();
          this.cameraService.update(viewport);
          resolve();
        });
        this.map.init();
      });
  
      // this.controlService.addControls();
      // 重新绑定非首次相机更新事件
      this.map.onCameraChanged(this.handleMapCameraChanged);
      this.map.addMarkerContainer();

      // 初始化未加载的marker;
      this.markerService.addMarkers();
      this.markerService.addMarkerLayers();
      this.popupService.initPopup();
      // 地图初始化之后 才能初始化 container 上的交互
      this.interactionService.init();
      this.interactionService.on(
        InteractionEvent.Drag,
        this.addSceneEvent.bind(this),
      );
      this.logger.debug(`map ${this.id} loaded`);
    });

**Comment by lzxue** [comment]
目前还支持2.0 ,需要单独升级

**Comment by wittech** [comment]
近期有2.0的支持计划？：）

**Comment by lzxue** [comment]
目前还没开始

**Comment by 2912401452** [comment]
L7 从 2.4 版本已经支持高德JSAPI2.0，目前最新版本是 2.5.10，可以使用新版本 L7
