### ISSUE TITLE
hover过的行政区，再调用updateData数据无法被更新

### ISSUE THREAD

**Issue by lxzhu94** [antvis/L7#404]
用的是countryLayer，所有hover过的区域，都无法更新数据，只能重新初始化layer

**Comment by lzxue** [comment]
能提供复现demo吗

**Comment by lzxue** [comment]
更新了新版应该是解决了

**Comment by xiaoyuan-fe** [comment]
> 用的是countryLayer，所有hover过的区域，都无法更新数据，只能重新初始化layer
这个问题解决了吗？要是解决了可以说一下，怎么调用的updateData方法吗？我这里调用updateData方法报错
