### ISSUE TITLE
符号地图的聚合使用

### ISSUE THREAD

**Issue by jingyebuchen** [antvis/L7#407]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我在符号地图的基础上做一些聚合操作，结果有点不受我的控制，看了部分源码，可是还是不是太清楚，将最近的几个问题罗列成下。
![image](https://user-images.githubusercontent.com/41276803/84868728-b9220000-b0af-11ea-8901-eef65e33f0ab.png)
1、这种映射出来的图标，当zoom很小的时候出现这种文字text标注，有什么解决办法吗？是不是只能通过设置zoom的聚合最大最小来控制呢？
![image](https://user-images.githubusercontent.com/41276803/84869186-4bc29f00-b0b0-11ea-9f6f-732424110d1a.png)
![image](https://user-images.githubusercontent.com/41276803/84869299-6bf25e00-b0b0-11ea-8f0b-d615dff89ddd.png)
2、这种聚合情况下，用什么图标去作为聚合后的哪个图标呢，也就是为什么会用小太阳的图标作为聚合后的图标呢？
![image](https://user-images.githubusercontent.com/41276803/84870952-875e6880-b0b2-11ea-8113-fff036eb609f.png)
3、在某些情况下，做聚合的时候会出现咱们默认的一个marker图标的样式，这个是为什么呢？
4、聚合后的图标信息貌似是将properties里面的属性进行了替换，这个属性有没有办法合并而不是替换呢？（ps:官方文档中一直是用clusterOption进行说明，但是看了源码才知道是用clusterOptions,或许在这里只是在说明）
这是困扰了我几天的一些问题，感谢您能抽出宝贵的时间帮我解答疑惑，再次感谢。

**Comment by lzxue** [comment]
聚合推荐使用markerlayer 的聚合
