### ISSUE TITLE
l7引入报错问题

### ISSUE THREAD

**Issue by shenjiawei124** [antvis/L7#408]
* **L7 Version**: 2.2.14
* **Platform**: vue
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/56636993/85091620-716bb780-b21a-11ea-8629-fba4652f7401.png)

* **CodePen Link**: 

![image](https://user-images.githubusercontent.com/56636993/85091675-919b7680-b21a-11ea-94dc-24836c473f5e.png)
任意引入一个就会报如下错误
![image](https://user-images.githubusercontent.com/56636993/85091700-a5df7380-b21a-11ea-9ac3-f8d384dd0550.png)

**Comment by lzxue** [comment]
L7 本身版本没有问题，重新安装一下依赖看看

https://codesandbox.io/s/eexpv 这个示例可以看看

**Comment by shenjiawei124** [comment]
> L7本身版本没有问题，重新安装一下依赖看看
> 
> https://codesandbox.io/s/eexpv这个示例可以看看

我这边项目中还用到了F2，会不会有影响？我这边依赖也都重新装过好几次了，另外一个后台项目只用了l7就没问题，这个项目装了L7和F2
