### ISSUE TITLE
利用mqtt实时返回图标经纬度更新图标位置的时候有这样的报错。

### ISSUE THREAD

**Issue by jingyebuchen** [antvis/L7#409]
![60ae40ed8c579717b1f93b2f6992da6](https://user-images.githubusercontent.com/41276803/85226488-4c3d9b80-b40a-11ea-8b28-afa4af0a930c.png)

* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我是这样实时更新的
![d80215f865fc33754246d7a90d7220c](https://user-images.githubusercontent.com/41276803/85226548-ab9bab80-b40a-11ea-848e-81e535d302f6.png)
现象是推出五分钟到十分钟，的时侯会出现最上面的报错，可以指一个大概问题的方向吗？非常感谢。

**Comment by lzxue** [comment]
更新数据使用setData 方法 https://l7.antv.vision/zh/docs/api/layer/layer#setdata

**Comment by jingyebuchen** [comment]
> 更新数据使用setData 方法 https://l7.antv.vision/zh/docs/api/layer/layer#setdata
非常感谢您的回答，我这边尝试了setData方法也是同样的问题，我怀疑是是不是内存一直释放不掉导致的，有这种可能吗？

**Comment by jingyebuchen** [comment]
> > 更新数据使用setData 方法 https://l7.antv.vision/zh/docs/api/layer/layer#setdata
> > 非常感谢您的回答，我这边尝试了setData方法也是同样的问题，我怀疑是是不是内存一直释放不掉导致的，有这种可能吗？
https://github.com/antvis/L7/issues/409#issuecomment-647368891
和这个问题有关系吗？版本解决了吗？

**Comment by jingyebuchen** [comment]
https://github.com/antvis/L7/issues/249#issue-578985923
刚刚的链接发错了，我在实时推送数据的时候只要每次一调用setData，内存就会逐渐递增，不释放，直到内存溢出，出现上面的报错。

**Comment by jingyebuchen** [comment]
> 更新数据使用setData 方法 https://l7.antv.vision/zh/docs/api/layer/layer#setdata

![d1e7b3e935d4cf88cf4f7d6303aa2fc](https://user-images.githubusercontent.com/41276803/85348822-53aa9500-b52f-11ea-9975-40f68941aa6e.png)
