### ISSUE TITLE
符号地图中setData内存问题

### ISSUE THREAD

**Issue by jingyebuchen** [antvis/L7#412]
![0d19b6cb5552651a1ca40d28075e14d](https://user-images.githubusercontent.com/41276803/85357416-d5a4b900-b543-11ea-8097-2d2a26925747.png)

* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

      setInterval(()=>{
        for(let i = 0;i<data.length;i++){
          data[i].longitude=data[i].longitude+0.00001
          data[i].latitude=data[i].latitude+0.00001
        }
        imageLayer.setData(data)
      },100)
更新数据之后电脑gpu占用内存一直递增，直到溢出，是用法不对吗？

**Comment by jingyebuchen** [comment]
import { Scene, PointLayer } from '@antv/l7';
import { GaodeMap } from '@antv/l7-maps';

const scene = new Scene({
  id: 'map',
  map: new GaodeMap({
    pitch: 0,
    style: 'light',
    center: [ 121.434765, 31.256735 ],
    zoom: 14.83
  })
});
scene.on('loaded', () => {
  fetch(
    'https://gw.alipayobjects.com/os/basement_prod/893d1d5f-11d9-45f3-8322-ee9140d288ae.json'
  )
    .then(res => res.json())
    .then(data => {
      scene.addImage(
        '00',
        'https://gw.alipayobjects.com/zos/basement_prod/604b5e7f-309e-40db-b95b-4fac746c5153.svg'
      );
      scene.addImage(
        '01',
        'https://gw.alipayobjects.com/zos/basement_prod/30580bc9-506f-4438-8c1a-744e082054ec.svg'
      );
      scene.addImage(
        '02',
        'https://gw.alipayobjects.com/zos/basement_prod/7aa1f460-9f9f-499f-afdf-13424aa26bbf.svg'
      );
      const imageLayer = new PointLayer()
        .source(data, {
          parser: {
            type: 'json',
            x: 'longitude',
            y: 'latitude'
          }
        })
        .shape('name', [ '00', '01', '02' ])
        .size(20);
      scene.addLayer(imageLayer);
       setInterval(()=>{
        for(let i = 0;i<data.length;i++){
          data[i].longitude=data[i].longitude+0.00001
          data[i].latitude=data[i].latitude+0.00001
        }
        imageLayer.setData(data)
      },100)
    });
});
补充上符号地图示例中的测试代码

**Comment by lzxue** [comment]
用法没问题，我跟踪一下问题吧，最好在codesandbox 上提供可以运行demo

**Comment by jingyebuchen** [comment]
> 用法没问题，我跟踪一下问题吧，最好在codesandbox 上提供可以运行demo
感谢跟踪

**Comment by jingyebuchen** [comment]
> 用法没问题，我跟踪一下问题吧，最好在codesandbox 上提供可以运行demo

感谢跟踪 demo地址：https://codesandbox.io/s/polished-forest-pfw8h?file=/index.js

**Comment by jingyebuchen** [comment]
@lzxue 我看您发布了2.2.22版本，我更新了版本之后，内存问题好像还是存在呢，是需要我更改使用方式吗？
