### ISSUE TITLE
左下角L7 图标取消展示

### ISSUE THREAD

**Issue by bhabgs** [antvis/L7#413]
* **L7 Version**: 2.2.15
* **Platform**: mac - vue
在左下角展示出 L7的logo很不美观，虽然可以通过onload 或者监听删除dom元素，但是觉得L7应该有相关配置吧

**Comment by lzxue** [comment]
好好看看文档有配置项

**Comment by bhabgs** [comment]
> 好好看看文档有配置项

能不能帮忙把这个issues 删了呀😅

**Comment by bhabgs** [comment]
关闭L7 logo显示
``` ts
this.scene = new Scene({
      id: 'map',
      logoVisible: false,
     ...,
})
```

[logovisible doc](https://l7.antv.vision/zh/docs/api/scene#logovisible)

@lzxue 大佬麻烦删了这个issues吧，问题不是本人发布的。。。
