### ISSUE TITLE
Translate documentation written in chinese to english

### ISSUE THREAD

**Issue by diru1100** [antvis/L7#414]
Currently, all necessary documentation is in Chinese which may be a barrier for Non-Chinese speakers to understand this wonderful project.

I would like to translate [CONTRIBUTING.md](https://github.com/diru1100/L7/blob/master/.github/CONTRIBUTING.md) to English as a start to this transition(CONTIRBUTING_ENGLISH.md?).

**Comment by lzxue** [comment]
thanks
