### ISSUE TITLE
Popup中html上的事件触发不出来

### ISSUE THREAD

**Issue by jingyebuchen** [antvis/L7#421]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

Popup中html上的事件会被pointLayer捕获到导致自己的事件触发不出来，不知道是不是这个原因。每次点击事件会触发到pointLayer的监听事件里面，本身的事件触发不出来。下面是codesandbox里的demo地址：https://codesandbox.io/s/sharp-cloud-0zze7?file=/index.js:839-849

**Comment by lzxue** [comment]
我这边点击可以alert出来的，click 事件可能会有冲突，你可以尝试html 里面使用mousedown事件

**Comment by jingyebuchen** [comment]
> 我这边点击可以alert出来的，click 事件可能会有冲突，你可以尝试html 里面使用mousedown事件

好的，感谢您的回复，我会尝试您说的，再次感谢。

**Comment by jingyebuchen** [comment]
> 我这边点击可以alert出来的，click 事件可能会有冲突，你可以尝试html 里面使用mousedown事件
pointLayer的监听事件里面可以排除对Popup内容的监听吗？

**Comment by lzxue** [comment]
#410  fixed
