### ISSUE TITLE
热力图目前不支持动态改颜色条；另外，地图平移的时候不应该刷新，这样体验比较差，应该在zoom的时候刷新。

### ISSUE THREAD

**Issue by MonitorHao** [antvis/L7#423]
* **L7 Version**:2.2.x
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lzxue** [comment]
3D 热力图，还是2D 发一下demo链接

**Comment by MonitorHao** [comment]
> 3D 热力图，还是2D 发一下demo链接

https://antv-l7.gitee.io/zh/examples/heatmap/heatmap#heatmap3d
二三维都有，3D更明显
