### ISSUE TITLE
drawCircle可以实时监听状态更改吗？并获取更改中的数据值。

### ISSUE THREAD

**Issue by jingyebuchen** [antvis/L7#427]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

https://codesandbox.io/s/ko2jr
官方示例中draw.update也需要在编辑完圆之后鼠标松开的瞬间，才会返回update的状态。
我想要在编辑圆的过程中鼠标一直处于按下状态，圆处于编辑状态的时候，返回这个随时变化的数据，现在可以满足吗？

**Comment by lzxue** [comment]
这块的事件没有对外暴露，可以增加事件，着急使用可以 PR

**Comment by jingyebuchen** [comment]
> PR

好的，感谢回复！
