### ISSUE TITLE
L7是不是不支持除了高德和mapbox以外的底图？

### ISSUE THREAD

**Issue by itsyom** [antvis/L7#428]
L7支持除了高德和mapbox以外的底图吗？
我们有自己的地图sdk；底图想使用自己的，可视化部分使用L7，可以吗？

**Comment by lzxue** [comment]
如果是瓦片地图，可以采用mapbox 加载，如果自己引擎需要考虑扩展支持

**Comment by itsyom** [comment]
> 如果是瓦片地图，可以采用mapbox 加载，如果自己引擎需要考虑扩展支持

我们是自己的地图引擎，矢量的。如何扩展支持呢？是实现某些接口吗？有什么规范

**Comment by lzxue** [comment]
你自己地图引擎是独立开发的吗，还是基于某个开源引擎研发的。如果有定制需求，可以加钉钉群交流一下 30460926
