### ISSUE TITLE
钻取地图的例子怎么根据自己定义的数量去显示颜色

### ISSUE THREAD

**Issue by shenjiawei124** [antvis/L7#431]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/56636993/87511447-e27e7d80-c6a7-11ea-8733-dd2c680773d8.png)
这边例子里面的颜色是根据数量自动排的，我希望定义一个，比如数量在0~1000的显示一个颜色，1000~2000的显示一个颜色，按自己定义的等级去划分，这样需要怎么写？api貌似不是很详细

**Comment by lzxue** [comment]
可以join 自己的数据
color 支持字段映射，和回调函数

**Comment by LazyChun** [comment]
请问有回调函数的例子吗？我要给颜色显示加个判断。做出这种效果。
![image](https://user-images.githubusercontent.com/12028374/90236334-31f5cc00-de55-11ea-9691-fbcda82a27bc.png)


> 可以join 自己的数据
> color 支持字段映射，和回调函数

**Comment by shenjiawei124** [comment]
> 请问有回调函数的例子吗？我要给颜色显示加个判断。做出这种效果。
> ![image](https://user-images.githubusercontent.com/12028374/90236334-31f5cc00-de55-11ea-9691-fbcda82a27bc.png)
> 
> > 可以join 自己的数据
> > color 支持字段映射，和回调函数

![image](https://user-images.githubusercontent.com/56636993/90236720-ba746c80-de55-11ea-93b0-c76b5d471b8a.png)
这样去写，我是根据count字段来映射的

**Comment by LazyChun** [comment]
> > 请问有回调函数的例子吗？我要给颜色显示加个判断。做出这种效果。
> > ![image](https://user-images.githubusercontent.com/12028374/90236334-31f5cc00-de55-11ea-9691-fbcda82a27bc.png)
> > > 可以join 自己的数据
> > > color 支持字段映射，和回调函数
> 
> ![image](https://user-images.githubusercontent.com/56636993/90236720-ba746c80-de55-11ea-93b0-c76b5d471b8a.png)
> 这样去写，我是根据count字段来映射的

可以用，Thanks.
