### ISSUE TITLE
使用React组件的Layer组件，每次渲染后切换其它页面就会报错

### ISSUE THREAD

**Issue by hhmy27** [antvis/L7#434]
* **L7 Version**:  2.2.17
* **Platform**: win10
* **Mini Showcase(like screenshots)**:   ![U0EJeS.png](https://s1.ax1x.com/2020/07/15/U0EJeS.png) 
* **CodePen Link**: https://codepen.io/hhmy27/pen/KKVxrYO?editors=0010  代码几乎和官方文档上的demo一样

13号的时候在Antd Pro上使用L7的Layer组件，测试没有问题，今天再打开来看就出bug了
1. Layer组件可以成功渲染，但是上面的图标加载不出来
2. 一旦页面中渲染了Layer组件，再切换到其它页面就会报错

**Comment by lzxue** [comment]
确认一下，你现在用的哪个版本，可能是新版有问题

**Comment by hhmy27** [comment]
我重新安装了包，本地运行了一下，我现在用的是2.2.17版本的@antv/l7-react，这个版本不会出现上面的bug

这是我本地的运行结果：

* 2.2.17 版的 l7-react不会报错，但是有时候图标还是加载不出来

* 2.2.20和2.2.21版本的l7-react在我这边用都会出现上面的错误

我本地的包版本如下，按照这个版本使用不会出现错误
![image](https://user-images.githubusercontent.com/31946303/87628454-9264f100-c763-11ea-96f4-cac9e169034c.png)

似乎是新版本的l7-react会引发上面的错误

**Comment by lzxue** [comment]
我全部更新 2.2.2 版本
