### ISSUE TITLE
浏览器窗口放大时 可视化图层不能同步

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#435]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lzy110223** [comment]
同样的问题 目前有解决办法吗？我用的是React组件

**Comment by lwl666666** [comment]
同样的问题，急

**Comment by lzxue** [comment]
正在解决，为什么都有放大浏览器的需求

**Comment by lzxue** [comment]
已解决
