### ISSUE TITLE
引入10个左右L7实例会导致WebGL contexts lost

### ISSUE THREAD

**Issue by wushi666** [antvis/L7#437]
* **L7 Version**: 2.2.11
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

使用多个地图组件会加载多个webgl context，包括你们的官网示例绘制组件页面，打开多个页面也会导致地图崩溃。
报错信息有context lost，invalid render buffer format等。

**Comment by lzxue** [comment]
受webgl 限制不能超过8个
