### ISSUE TITLE
绘制功能绘制的图形偏移

### ISSUE THREAD

**Issue by wushi666** [antvis/L7#439]
* **L7 Version**: 2.2.21
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

地图加载后，如果改变窗口大小，地图大小随之改变后，这时在地图上绘制的图形，与当前鼠标位置偏移巨大，并且图形缩小。2.2.11版本并没有这个问题

**Comment by lzxue** [comment]
最新版的 L7 会有响应浏览器大小变化的吧

**Comment by lwl666666** [comment]
2.2.22版本，对body设置scale之后，地图上绘制图形的mousemove事件触发的位置会发生偏移

**Comment by lzxue** [comment]
更新新版版
