### ISSUE TITLE
scene.fitBounds方法调用报错

### ISSUE THREAD

**Issue by wushi666** [antvis/L7#440]
* **L7 Version**: 2.2.11
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

根据官网文档scene.fitBounds([112, 32, 114, 35])，输入最大最小经纬度坐标后报错，错误信息为：Invalid Object: lnglat(NaN,NaN)

**Comment by lzxue** [comment]
抱歉文档有误， scene.fitBounds([[112, 32], [114, 35]])
