### ISSUE TITLE
图层 Layer点图层符号图icon显示空白（浏览器不兼容）

### ISSUE THREAD

**Issue by goodking4** [antvis/L7#441]
图层 Layer点图层符号图icon显示空白
火狐浏览器可以正常显示，Microsoft Edge以及Chome不能正常显示
![微信图片_20200717114834](https://user-images.githubusercontent.com/27410544/87746609-95271b00-c823-11ea-91fd-f6a7aa110bac.png)
![微信图片_20200717114840](https://user-images.githubusercontent.com/27410544/87746613-96f0de80-c823-11ea-8eab-665990dc4f6e.png)
![微信图片_20200717114843](https://user-images.githubusercontent.com/27410544/87746618-98220b80-c823-11ea-957f-05b22c11b9ad.png)

**Comment by hhmy27** [comment]
同样遇到这种情况

**Comment by jinweizhiyuan** [comment]
@goodking4 这个问题解决了，我也遇到了

**Comment by 2912401452** [comment]
firefox
![image](https://user-images.githubusercontent.com/42212176/158114087-f06c9304-1cfa-46c1-a60f-df564363fe85.png)
chorme
![image](https://user-images.githubusercontent.com/42212176/158114099-3296fef1-e60f-48d6-9a30-f3952f255d36.png)
Edge
![image](https://user-images.githubusercontent.com/42212176/158114324-46085d7b-d8ac-4897-9081-f55f410bb813.png)
目前在各个浏览器的测试都是可以的，请安装新版本的 L7 看看，应该是没问题的
