### ISSUE TITLE
高层级下（18以上），同一经纬度，L7位置和mapbox位置有偏移

### ISSUE THREAD

**Issue by caelantop** [antvis/L7#448]
* **L7 Version**: 2.2.26
* **Platform**: windows
* **Mini Showcase(like screenshots)**:

![1](https://user-images.githubusercontent.com/20149400/88136177-49a5b000-cc1b-11ea-8ad8-24ec33a59de9.png)

* **CodePen Link**:   https://codepen.io/caelan/pen/xxZMENR

**Comment by lzxue** [comment]
现在怀疑是偏移坐标系的问题，在高的缩放等级有误差

**Comment by caelanChan** [comment]
@lzxue 请问有解决的方法吗？

**Comment by qianzhangsheng** [comment]
![image](https://user-images.githubusercontent.com/1262247/114729163-50102500-9d72-11eb-86df-c9a372521793.png)
底图是天地图，发现也会偏移

**Comment by zoumingyin** [comment]
我也遇到这个问题，求大佬解决。

**Comment by lvisei** [comment]
fixed https://github.com/antvis/L7/pull/2416

**Comment by zoumingyin** [comment]
暂时无法回复，请电话联系。
