### ISSUE TITLE
绘制组件

### ISSUE THREAD

**Issue by onlymaple** [antvis/L7#450]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by onlymaple** [comment]
1、绘制组件中，绘制结束双击完成的时候，会有重复的数据返回；
2、绘制组件完成后，麻烦添加个选中事件

**Comment by lzxue** [comment]
问1 ： 重复数据返回是指 返回数据里有重复的图形？

**Comment by onlymaple** [comment]
![image](https://user-images.githubusercontent.com/12403826/88650745-93026d80-d0fb-11ea-8b8a-0b01f50fcad2.png)
绘画线段的时候，只有两个点的线段，双击结束，会返回重复的数组（应该只有两条数据的数组，返回了N条）

**Comment by lzxue** [comment]
这几个我看一下，

**Comment by onlymaple** [comment]
好的，谢谢，麻烦了
