### ISSUE TITLE
 regl 对象销毁问题,数据频繁更新减少内存占用

### ISSUE THREAD

**Issue by jingyebuchen** [antvis/L7#451]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

@lzxue 我看您完善了这个功能之后，发布了2.2.22版本，我更新了版本之后，内存问题好像还是存在呢，是需要我更改使用方式吗？

**Comment by lzxue** [comment]
现在修复之后，频繁销毁内存会稳定下来

**Comment by jingyebuchen** [comment]
> 现在修复之后，频繁销毁内存会稳定下来
> 你当时这个demo https://codesandbox.io/s/polished-forest-pfw8h?file=/index.js 下测试内存比较稳定
感谢您的回复。
![image](https://user-images.githubusercontent.com/41276803/88260679-6fa08280-ccf7-11ea-8442-a235f3f64d06.png)
再次测试这个GPU进程内存占用空间还是会递增，直至页面崩溃报错。

**Comment by lzxue** [comment]
![image](https://user-images.githubusercontent.com/4366658/88275186-894dc400-cd0f-11ea-9920-01a8d4ba037c.png)
我在这个地方看的

**Comment by jingyebuchen** [comment]
嗯嗯在电脑任务管理器中看内存确实会有释放，但是浏览器中的任务管理器GPU进程占用大小一直不会释放，一直在增加，直到超出内存大小，页面崩溃。

**Comment by songtang0** [comment]
我的也是，调用scene.addImage之后，定时器添加textarea纹理贴图，然后内存一直递增，直到溢出，然后wewbgl丢失上下文，地图就没了
