### ISSUE TITLE
中国地图气泡图  拖动一下浏览器窗口会一直触发resize事件

### ISSUE THREAD

**Issue by pangpang007** [antvis/L7#452]
* **L7 Version**: 2.2.26
* **Platform**: windows
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/29764139/88388164-883b9600-cde6-11ea-87ca-495ae0398319.png)
![image](https://user-images.githubusercontent.com/29764139/88388181-94275800-cde6-11ea-9539-f05dde12da5d.png)

**Comment by lzxue** [comment]
一直都在resize吗？

**Comment by pangpang007** [comment]
主动触发一次resize，就会一直调用自定义的回调函数

**Comment by pangpang007** [comment]
@lzxue   麻烦问下最近有看过这个问题么

**Comment by lzxue** [comment]
> @lzxue 麻烦问下最近有看过这个问题么

最好提供在线复现的demo, 我这边没有复现，先更新一下最新版本看看
