### ISSUE TITLE
3d填充图加载性能问题

### ISSUE THREAD

**Issue by jingyebuchen** [antvis/L7#453]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

您好，这个问题可能会让您难以回答，但我是在我使用l7的过程中确实遇到了，试了几种方式都不太理想，所有提一个问题，希望能够得到官方的解答。加载3d填充图的时候首次加载速度对用户的印象或者使用感受尤为重要。
我在官网示例基础上打开codesandbox首次加载大概需要8s左右，这是我的测试地址：https://codesandbox.io/s/blissful-goldberg-72we8?file=/index.js:804-912
我在官网的示例上直接用上面的代码测试首次加载大概需要4s左右：https://l7.antv.vision/zh/examples/polygon/3d这是官网地址，只是将最后scene.addLayer(layer);修改成了 console.log(new Date()); scene.addLayer(layer);console.log(new Date());
我在vue工程中也仿照示例测试了一下首次加载也是8s左右，这是测试地址：https://codesandbox.io/s/vue-l7-gih77?file=/src/components/HelloWorld.vue:1112-1214
这差出来几秒钟的加载时间让我很困扰，所以我想问官网示例做了特殊的性能加载处理吗？我也希望能够达到官网的加载速度，提前感谢抽出宝贵的时间回复了。

**Comment by jingyebuchen** [comment]
> * **L7 Version**:
> * **Platform**:
> * **Mini Showcase(like screenshots)**:
> * **CodePen Link**:
> 
> 您好，这个问题可能会让您难以回答，但我是在我使用l7的过程中确实遇到了，试了几种方式都不太理想，所有提一个问题，希望能够得到官方的解答。加载3d填充图的时候首次加载速度对用户的印象或者使用感受尤为重要。
> 我在官网示例基础上打开codesandbox首次加载大概需要8s左右，这是我的测试地址：https://codesandbox.io/s/blissful-goldberg-72we8?file=/index.js:804-912
> 我在官网的示例上直接用上面的代码测试首次加载大概需要4s左右：[https://l7.antv.vision/zh/examples/polygon/3d这是官网地址，只是将最后scene.addLayer(layer);修改成了](https://l7.antv.vision/zh/examples/polygon/3d%E8%BF%99%E6%98%AF%E5%AE%98%E7%BD%91%E5%9C%B0%E5%9D%80%EF%BC%8C%E5%8F%AA%E6%98%AF%E5%B0%86%E6%9C%80%E5%90%8Escene.addLayer(layer);%E4%BF%AE%E6%94%B9%E6%88%90%E4%BA%86) console.log(new Date()); scene.addLayer(layer);console.log(new Date());
> 我在vue工程中也仿照示例测试了一下首次加载也是8s左右，这是测试地址：https://codesandbox.io/s/vue-l7-gih77?file=/src/components/HelloWorld.vue:1112-1214
> 这差出来几秒钟的加载时间让我很困扰，所以我想问官网示例做了特殊的性能加载处理吗？我也希望能够达到官网的加载速度，提前感谢抽出宝贵的时间回复了。

抱歉，准确的说，上面所说的不能是首次加载速度，是平均加载速度，首次加载速度可能会更长一点。

**Comment by lzxue** [comment]
官网没有做特殊处理的，你可以加钉钉群，找我私聊一下

**Comment by jingyebuchen** [comment]
我发送了一封邮件给您，您方便提供一下群地址吗

**Comment by jingyebuchen** [comment]
> 官网没有做特殊处理的，你可以加钉钉群，找我私聊一下

@lzxue

**Comment by lzxue** [comment]
> > 官网没有做特殊处理的，你可以加钉钉群，找我私聊一下
> 
> @lzxue
30460926

**Comment by jingyebuchen** [comment]
> > > 官网没有做特殊处理的，你可以加钉钉群，找我私聊一下
> > 
> > 
> > @lzxue
> > 30460926
好的收到
