### ISSUE TITLE
react的Popup组件，怎样添加自定义的事件？

### ISSUE THREAD

**Issue by jiaicon** [antvis/L7#456]
`
<Popup lnglat={popupInfo.lnglat}>
              <ul
                style={{
                  margin: 0,
                }}
                className={styles.popup}
              >
                <ArrowUpOutlined onClick={this.handleChange} />
                <li className={styles.unit_name}>{popupInfo.feature.unit}</li>
              </ul>
</Popup>
`

我在popup中想自定义按钮，但是点击的时候handleChange事件似乎不触发，

**Comment by lzxue** [comment]
目前click 事件和底图事件有些冲突，你可以尝试使用一下mousedown

**Comment by jiaicon** [comment]
使用onMouseDown也触发不了，我是在react组件上使用的。

**Comment by lzxue** [comment]
之前测试是可以的

**Comment by jiaicon** [comment]
```
popupInfo && (
            <Popup lnglat={popupInfo.lnglat}>
              <ul
                style={{
                  margin: 0,
                }}
                className={styles.popup}
              >
                <ArrowUpOutlined className={styles.close} onMouseDown={this.handleChange} />
                <li>更新时间：{popupInfo.feature.update_time}</li>
              </ul>
            </Popup>
          )
```
我是这样测试的，您可以看下

**Comment by yuanhan1890** [comment]
我也遇到了这个问题，可能事件在capture过程中被阻止了？
有一个临时方案是只利用popup的锚点，使用antd里的tooltip（或其他相同原理的组件）将你的vdom mount到其他节点;
```
const content = (
  <ul
    style={{
      margin: 0,
    }}
    className={styles.popup}
  >
    <ArrowUpOutlined className={styles.close} onMouseDown={this.handleChange} />
    <li>更新时间：{popupInfo.feature.update_time}</li>
  </ul>
);

<Popup lnglat={popupInfo.lnglat}>
  <Tooltip visible title={content} overlayClassname="用以清除tooltip样式的类名">
    <div>
  </Tooltip>
</Popup>
```

**Comment by jiaicon** [comment]
这个想法可以的，自己可以实现一个类似tooltip的组件，动态控制位置

**Comment by lzxue** [comment]
> 这个想法可以的，自己可以实现一个类似tooltip的组件，动态控制位置

https://github.com/antvis/L7/blob/master/packages/component/src/popup.ts#L211 这里添加了stopPropagation 设置，在 非react 下是可以。但是使用react组件的话就需要关闭这个设置，我增加一个配置项，在react 关闭这个配置

**Comment by jiaicon** [comment]
> > 这个想法可以的，自己可以实现一个类似tooltip的组件，动态控制位置
> 
> https://github.com/antvis/L7/blob/master/packages/component/src/popup.ts#L211 这里添加了stopPropagation 设置，在 非react 下是可以。但是使用react组件的话就需要关闭这个设置，我增加一个配置项，在react 关闭这个配置

这个会什么时候发布版本呢，不知道我这边产品上线前能不能加上
