### ISSUE TITLE
钻取地图如何设置只显示省区域，不显示全国

### ISSUE THREAD

**Issue by aiiua** [antvis/L7#457]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lzxue** [comment]
目前还不支持，你可以详细描述一下使用场景

**Comment by aiiua** [comment]
![image](https://user-images.githubusercontent.com/8858433/88609628-31201480-d0b7-11ea-92ba-25f19bf81134.png)
现在我们要做宁夏的一个人口统计的展示，可以下钻到市县区查看市县区下人口的情况～

**Comment by lzxue** [comment]
cityLayer 是可以通过updateData 进行更新不同的市
