### ISSUE TITLE
钻取地图怎么更改默认触发事件

### ISSUE THREAD

**Issue by RuaghLiu** [antvis/L7#458]
DrillDownLayer 提供默认提供通过Layer的交互事件，实现上钻下钻的交互，默认点击当前图层(click)向下钻取，双击非地图区域(undblclick)向上钻取。你可以更改默认交互的的触发事件。通过也可以更改默认的交互行为。

这个怎么修改的

**Comment by lzxue** [comment]
看文档有trigerEvent 配置项，同时也可以完全自定义根据需求调用drillup、drilldown 方法

**Comment by RuaghLiu** [comment]
Cannot read property 'features' of undefined
我试了下drilldown这个方法结果报这个错 是要更新插件了吗


> 看文档有trigerEvent 配置项，同时也可以完全自定义根据需求调用drillup、drilldown 方法

**Comment by lzxue** [comment]
不需要更新，默认的下钻也是调用的这个方法
