### ISSUE TITLE
在IE11下，位置发生偏移

### ISSUE THREAD

**Issue by MrGuoPF** [antvis/L7#460]
* **L7 Version**:2.2.19
* **Platform**:Windows
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
![image](https://user-images.githubusercontent.com/29505871/88770775-e1257880-d1b0-11ea-84ac-dfde618c8357.png)

(内部虚拟机项目，只能用手机拍)
IE11下，渲染了一张中国地图，增加了鼠标移入该省份显示该省份相关信息功能，在google能正常显示，IE下，鼠标移入地图下方才能显示相关信息（图中鼠标位置，激活了对应青蓝色的省份）

**Comment by lzxue** [comment]
应该是CSS的问题，新版本这块有改动，尝试安装2.2.28最新版本看看
