### ISSUE TITLE
react组件中 AMapScene plugin无效?

### ISSUE THREAD

**Issue by hyyqcweb** [antvis/L7#464]
* **L7 Version**: 2.2.28
* **Platform**: Windows
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

```
  map={{
          center: ...,
          plugin: ['AMap.MapType'],
          pitch: 0,
          zoom: 12,
        }}
```
plugin无法生效?

**Comment by hyyqcweb** [comment]
```
<AMapScene
        map={{
          center: [120.78524, 30.68865],
          plugin: ['AMap.MapType'],
          pitch: 0,
          zoom: 12,
        }}
        option={{ logoVisible: false }}
      />
```
此为完整代码

**Comment by hehu321** [comment]
同样遇到相同问题

**Comment by hyyqcweb** [comment]
@hehu321 这个问题解决了吗, 官方好像不太活跃

**Comment by lzxue** [comment]
我看一下

**Comment by hyyqcweb** [comment]
> > ```
> > <AMapScene
> >         map={{
> >           center: [120.78524, 30.68865],
> >           plugin: ['AMap.MapType'],
> >           pitch: 0,
> >           zoom: 12,
> >         }}
> >         option={{ logoVisible: false }}
> >       />
> > ```
> > 
> > 
> > 此为完整代码
> 
> 添加完了应该需要实例化一下吧，提供一个在线复现demo

实例化? 有演示的demo吗

**Comment by hehu321** [comment]
解决了,在plugin设置之后需要实例化一下就业了
```js

```

> @hehu321 这个问题解决了吗, 官方好像不太活跃

需要实例化一下上面添加的只是注册这个插件,可以在onSceneLoaded方法中通过scene.map获取到地图实例然后调用它的addControl方法将插件添加到地图
```js
<AMapScene
        map={{
          center: [120.78524, 30.68865],
          plugin: ['AMap.MapType'],
          pitch: 0,
          zoom: 12,
        }}
        option={{ logoVisible: false }}
       onSceneLoaded={(scene) => {
         var type= new AMap.MapType({
           defaultType:0 //使用2D地图
        });
        scene.map.addControl(type);
       }}
      />
```

**Comment by hyyqcweb** [comment]
> 解决了,在plugin设置之后需要实例化一下就业了
> 
> > @hehu321 这个问题解决了吗, 官方好像不太活跃
> 
> 需要实例化一下上面添加的只是注册这个插件,可以在onSceneLoaded方法中通过scene.map获取到地图实例然后调用它的addControl方法将插件添加到地图
> 
> ```js
> <AMapScene
>         map={{
>           center: [120.78524, 30.68865],
>           plugin: ['AMap.MapType'],
>           pitch: 0,
>           zoom: 12,
>         }}
>         option={{ logoVisible: false }}
>        onSceneLoaded={(scene) => {
>          var type= new AMap.MapType({
>            defaultType:0 //使用2D地图
>         });
>         scene.map.addControl(type);
>        }}
>       />
> ```

nice, 很棒~
