### ISSUE TITLE
移动端地图标签问题

### ISSUE THREAD

**Issue by shenjiawei124** [antvis/L7#466]
* **L7 Version**:2.2.7
* **Platform**: vue
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![5904bfb50e6d931ee723febb4437179](https://user-images.githubusercontent.com/56636993/89157123-93d54c80-d59e-11ea-894e-cd67f6f7413a.png)

1.在微信浏览器内需要双击才会展示出标签
2.同机型iphone x ios12系统双击无效果，ios13的可以

**Comment by lzxue** [comment]
更新成最新版本看看

**Comment by shenjiawei124** [comment]
> 更新成最新版本看看

已经更新成2.2.28的版本，ios12双击还是无效

**Comment by lzxue** [comment]
后面问题解决了吗？应该是事件兼容性的问题？

**Comment by shenjiawei124** [comment]
> 后面问题解决了吗？应该是事件兼容性的问题？

暂时还没有解决，公司有的一些测试机，ios12都是无效，应该是点击事件的兼容问题吧
