### ISSUE TITLE
L7-行政区域-填充图-api-excel文档下载后中文乱码

### ISSUE THREAD

**Issue by amen943** [antvis/L7#467]
网页地址：https://l7.antv.vision/zh/examples/district/basic/API

-
![1596441241(1)](https://user-images.githubusercontent.com/49328213/89159232-cd5b8700-d5a1-11ea-9489-b0bc46a22ed1.jpg)
浏览器：Microsoft Edge 版本 85.0.564.18 (官方内部版本) beta (64 位)
![1596441440(1)](https://user-images.githubusercontent.com/49328213/89159415-0a277e00-d5a2-11ea-8348-0edc9112477a.jpg)

**Comment by lzxue** [comment]
用文本编辑器打开
