### ISSUE TITLE
Popup组件是否有鼠标移出消失?

### ISSUE THREAD

**Issue by pkaq** [antvis/L7#468]
Popup组件是否有鼠标移出消失?

另外, 感觉文档好像好久不更新了 里面很多链接404 还有一些示例里调用的方法和属性在文档里也没有

**Comment by lzxue** [comment]
监听 mouseout 事件处理popup 消失问题。
文档的链接404 问题，可以贴一下链接，我会及时修改

**Comment by pkaq** [comment]
比如 scene文档里找不到  scene.addPopup(popup); 的api
pop的文档里找不到 remove

**Comment by pkaq** [comment]
自定义 Marker -> Marker 文档 404
