### ISSUE TITLE
layer组件使用自定义marker图片时，地图缩放或者移动图片会消失

### ISSUE THREAD

**Issue by jiaicon** [antvis/L7#469]
![微信截图_20200804102341](https://user-images.githubusercontent.com/34124517/89246164-13195d80-d63d-11ea-8235-06698722d72d.png)
像图片上的，消失掉了，这个是什么原因？

**Comment by lzxue** [comment]
这个是pointlayer 添加图片吧？感觉是兼容问题

**Comment by xiaogaofudao** [comment]
这个问题一直存在，一直闪白色

**Comment by jiaicon** [comment]
> 这个是pointlayer 添加图片吧？感觉是兼容问题

应该不是，这个是文档上的例子，公司的电脑都这样，应该是使用PointLayer的原因

**Comment by lzxue** [comment]
> 这个问题一直存在，一直闪白色

应该是浮点数的问题，这个问题新版修复了
