### ISSUE TITLE
[需求] PointLayer的偏移支持和飞线的个性化支持

### ISSUE THREAD

**Issue by pkaq** [antvis/L7#470]
真实场景描述

1.目前要做一个航空大屏, 需要在若干机场城市添加 circle 类型的涟漪圆点和一个自定义图标, 但是PointLayer不支持偏移导致两者会重叠在一起, 实际期望图片在圆点上面, 虽然可以通过自定义 marker间接实现, 但是自定义marker好像又不支持geojson 导致要搞两份数据出来.

1.城市之间的飞线要添加飞机图标,好像目前也只能通过自定义marker的形式去计算经纬度添加

期望可以支持PointLayer的偏移量 飞线自定义(不限于设定图标\飞线渐变颜色(支持style自定义)))等

希望可以尽快像 echarts 一样强大

**Comment by lzxue** [comment]
偏移这块比较好加，如果有些可以提PR ，我会指导如何实现

**Comment by pkaq** [comment]
好的, 我发现写法竟然跟 mapbox 一样 所以我...........
