### ISSUE TITLE
DrillDownLayer 的data应该是什么格式的？怎么使用？

### ISSUE THREAD

**Issue by LazyChun** [antvis/L7#471]
![image](https://user-images.githubusercontent.com/12028374/89506442-b022f480-d7fd-11ea-92b5-7da669266644.png)
我觉得doc应该写几个列子，让人知道这个data的用处已经它的格式应该是怎样的。

**Comment by lzxue** [comment]
https://l7.antv.vision/zh/examples/district/basic   和这个demo一样的，jsone格式

**Comment by LazyChun** [comment]
data与provinceData的区别是什么？还有我把provinceData格式的数据放在data里，没有任何效果，并没有把value赋值进去。  我现在是想实现一个功能，统计各省市的人数，然后根据人数多少来决定各省市颜色的深浅，我给provinceData添加value后可以正常看到value,但是给cityData添加后，钻取进去后没有value这个属性。很奇怪。

**Comment by AlingChen** [comment]
> https://l7.antv.vision/zh/examples/district/basic 和这个demo一样的，jsone格式

这个示例没有啊？？
