### ISSUE TITLE
网格热力图将shape设置为3D属性时，不会绘制出layer

### ISSUE THREAD

**Issue by yeastone** [antvis/L7#472]
* **L7 Version**:  2.2.28
* **Platform**: mac 
* **Mini Showcase(like screenshots)**:
为啥coverage设为1了正方形之间还会有缝，蜂窝形就不会有缝。
![image](https://user-images.githubusercontent.com/65276724/89507326-edd44d00-d7fe-11ea-9337-8e4124583448.png)
![image](https://user-images.githubusercontent.com/65276724/89507378-004e8680-d7ff-11ea-9b87-6843c16c3ae6.png)

* **CodePen Link**:[https://codesandbox.io/s/charming-grass-1mz0f](https://codesandbox.io/s/charming-grass-1mz0f)

**Comment by lzxue** [comment]
grid布局好像有bug 我检查一下
