### ISSUE TITLE
请问如何给钻取地图的城市与县区赋值？

### ISSUE THREAD

**Issue by LazyChun** [antvis/L7#473]
我现在需要给省 市 区加一个特定value属性，省可以直接这样加
![image](https://user-images.githubusercontent.com/12028374/89605698-c46bfd80-d8a0-11ea-975a-488b5fac4994.png)

![image](https://user-images.githubusercontent.com/12028374/89605715-cafa7500-d8a0-11ea-83f5-a2e1839cc7c4.png)
![image](https://user-images.githubusercontent.com/12028374/89606085-bb2f6080-d8a1-11ea-8bc1-d262221791dc.png)

但 市 和区的数据加了 无效。

![image](https://user-images.githubusercontent.com/12028374/89605974-7acfe280-d8a1-11ea-8fe6-8a836fc7c597.png)

![image](https://user-images.githubusercontent.com/12028374/89605988-84594a80-d8a1-11ea-9929-10cb4754d4b4.png)

![image](https://user-images.githubusercontent.com/12028374/89606225-09dcfa80-d8a2-11ea-9893-8db26e4e4066.png)

**Comment by LazyChun** [comment]
难道市和区的赋值方法和省不一样吗？

**Comment by lzxue** [comment]
是一样的

**Comment by LazyChun** [comment]
版本2.2.11是正常的。

**Comment by lzxue** [comment]
> 版本2.2.11是正常的。

能提供个demo吗，我复现一下

**Comment by timewaitsnoone** [comment]
[复现步骤见#442](https://github.com/antvis/L7/issues/442)
