### ISSUE TITLE
莫名奇妙的8PX

### ISSUE THREAD

**Issue by pkaq** [antvis/L7#474]
![lALPDh0cMqrZxOfNAz_NBXA_1392_831](https://user-images.githubusercontent.com/4537450/89631565-86d49800-d8d3-11ea-9a50-4562f2c76a66.png)

页面只有一个 div, 宽高都是 100 , 
不知道这蜜汁8px哪来的 渲染完会向右偏移8px 并且导致页面宽高都出现滚动条
如果强行修改 .amap-container 向左偏移回来 -8px 那么 页面的marker并不会偏移 就导致跟实际坐标点无法对齐

求解

**Comment by pkaq** [comment]
![1](https://user-images.githubusercontent.com/4537450/89632167-5c370f00-d8d4-11ea-87b1-e643bb246adf.png)
![3](https://user-images.githubusercontent.com/4537450/89632169-5d683c00-d8d4-11ea-9133-b3e3d4c973c6.png)

难道是我的打开方式有问题吗

**Comment by lzxue** [comment]
body 的margin 吧

**Comment by pkaq** [comment]
```
html, body {
  margin: 0;
}
```
 指定了这个解决了 但仍然不知道哪来的8px 也没有地方指定这 8px
