### ISSUE TITLE
create webgl failed!

### ISSUE THREAD

**Issue by QAQ1002** [antvis/L7#475]
![微信截图_20200810092419](https://user-images.githubusercontent.com/69441659/89746253-50716580-daeb-11ea-8788-86f8d489858f.png)
有一定概率会出现这个错误，刷新就好了，不知道是什么问题，官方大大知道吗？

**Comment by lzxue** [comment]
是不是频繁创建 L7 实例没有销毁导致的？

**Comment by QAQ1002** [comment]
> 是不是频繁创建 L7 实例没有销毁导致的？

很多时候是第一次进入的时候出现的，应该只创建了一次，

**Comment by lzxue** [comment]
这种一般是浏览器或系统兼容性的问题
