### ISSUE TITLE
怎么禁止缩放和禁止拖动，文档找了好久也没找到

### ISSUE THREAD

**Issue by shoestrong** [antvis/L7#478]
* **L7 Version**: 2.2.10
* **Platform**: PC
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

怎么禁止缩放和禁止拖动，文档找了好久也没找到

**Comment by lzxue** [comment]
可以参考一下 mapbox 或高德地图 的 Map配置项 有相关配置，后面L7文档会补充这块的的文档

**Comment by 97Yates05** [comment]
> 可以参考一下 mapbox 或高德地图 的 Map配置项 有相关配置，后面L7文档会补充这块的的文档

既然都回答了，那就顺带回答一下多好，一句参考带过。。这意思l7是基于mapbox和高德地图改的吗

**Comment by andy7076** [comment]
我也是把所有文档读了一遍也没找到。

**Comment by iamdhj** [comment]
网上搜了半天才找到设置方法，通过关键字搜索源码才发现文档有说明，建议文档增加关键字注释
[setMapStatus 设置地图状态](https://l7.antv.vision/zh/docs/api/scene#setmapstatus-%E8%AE%BE%E7%BD%AE%E5%9C%B0%E5%9B%BE%E7%8A%B6%E6%80%81)
