### ISSUE TITLE
路径图json值含义

### ISSUE THREAD

**Issue by Fyee** [antvis/L7#481]
开发者你好，官方示例的路径图中json参数里面path对应的第1、2个参数是坐标，那第三个参数是用来做什么的，这个参数要根据什么来定义？
我尝试把第三个参数都换成了0，路径图的样式都发生了改变
官方的demo地址：<https://antv-l7.gitee.io/zh/examples/line/path#bus_light>
官方的模拟数据地址：<https://gw.alipayobjects.com/os/basement_prod/ee07641d-5490-4768-9826-25862e8019e1.json>
```json
path: [
      [
        103.7857052,
        1.4378292,
        0
      ]
]
```

**Comment by lzxue** [comment]
第三个字段一般是高度字段，在L7 里面没有做处理，正常不会影响显示效果，样式改有截图说明吗

**Comment by Fyee** [comment]
谢谢，我重新试了一下，第三个字段改了之后没有影响，应该是之前改错了其他参数的值，谢谢回复
