### ISSUE TITLE
钻取地图在IE上无法显示

### ISSUE THREAD

**Issue by timewaitsnoone** [antvis/L7#484]
钻取地图在IE上无法显示，官网中的实例在IE中就无法显示，包括React组件有同样的问题，IE常见版本都试过了。

**Comment by timewaitsnoone** [comment]
大佬！求助一下 @lzxue

**Comment by lzxue** [comment]
有没有报错，或者提供一个简单的在线demo 我看一下

**Comment by timewaitsnoone** [comment]
[L7官网实例](https://l7.antv.vision/zh/examples/district/basic)在IE中就打不开，IE版本11，Win10系统，现象为不显示，console报错信息如图。
![l7IE不显示问题](https://user-images.githubusercontent.com/22412289/90362812-090f4a00-e094-11ea-877d-cd59f60cbec6.PNG)

**Comment by timewaitsnoone** [comment]
console报错信息：Unhandled promise rejection SyntaxError

**Comment by lzxue** [comment]
> console报错信息：Unhandled promise rejection SyntaxError

官网不支持IE，如果IE 使用L7  需要增加 polyfill.js 具体可以看这里的 demo https://github.com/antvis/L7/tree/master/packages/l7/demo
