### ISSUE TITLE
需求：PointLayer 追加数据

### ISSUE THREAD

**Issue by fengluhome** [antvis/L7#485]
我这有个需求，更新数据每次用setData() , 导致图层全部更新,页面效果不自然，能不能增加pushData()方法，谢谢

**Comment by lzxue** [comment]
没有这样的方法，你可以一次加载所有数据，用filter 方法过滤数据，或者用color 控制透明度实现，color 方法会更快

**Comment by fengluhome** [comment]
哦哦 ，非常感谢，思路很赞。
