### ISSUE TITLE
钻取地图怎么获取当前点击了什么区域？就靠 SceneEvent 的 handler 来判断？？？？？？？

### ISSUE THREAD

**Issue by redblue9771** [antvis/L7#489]
* **L7 Version**: latest
* **Platform**: windows 10
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

当下钻或者上钻的时候，我需要根据点击的区域来触发不同的动作如何实现？？？？？？

**Comment by lzxue** [comment]
自定义动作，自己按需调用 drilldown , drillup方法

**Comment by redblue9771** [comment]
> 自定义动作，自己按需调用 drilldown , drillup方法

也没解决问题呀，自定义也要知道点了哪

**Comment by lzxue** [comment]
> > 自定义动作，自己按需调用 drilldown , drillup方法
> 
> 也没解决问题呀，自定义也要知道点了哪
你可以配置触发的事件

drillDownTriggerEvent 向下钻取的触发事件 ⛔customTrigger 为 true 时不生效
drillUpTriggleEvent 向上钻取的触发事件 ⛔customTrigger 为 true 时不生效


你也可也取到对应的 provincelayer,citylayer  添加事件

**Comment by lzxue** [comment]
> > 自定义动作，自己按需调用 drilldown , drillup方法
> 
> 也没解决问题呀，自定义也要知道点了哪
你可以配置触发的事件

drillDownTriggerEvent 向下钻取的触发事件 ⛔customTrigger 为 true 时不生效
drillUpTriggleEvent 向上钻取的触发事件 ⛔customTrigger 为 true 时不生效


你也可也取到对应的 provincelayer,citylayer  添加事件

**Comment by LazyChun** [comment]
这个问题楼主解决了吗？

**Comment by LazyChun** [comment]
我有一套解决方案，就是有点非主流。  在popup的时候，把当前省市信息给一个变量，然后监听点击的时候，使用这个变量。 大概就是这样。 我经过测试没有问题。
const initDrillMap = ({ setCity, provinceData, cityData, drill }) => {
  let currentState = {};
  const scene = new Scene({
    id: "drillMap",
    map: new Mapbox({
      center: [116.2825, 39.9],
      pitch: 0,
      style: "blank",
      zoom: 3,
      minZoom: 3,
      maxZoom: 10
    })
  });
  scene.on("loaded", () => {
    drill = new DrillDownLayer(scene, {
      data: [],
      depth: 1,
      drillDepth: 1,
      provinceData,
      cityData,
      joinBy: ["adcode", "adcode"],

      fill: {
        color: {
          field: "value",
          values: count => {
            if (count <= 0) {
              return "white";
            } else if (count > 0 && count < 20) {
              return "#feedde";
            } else if (count > 20 && count <= 100) {
              return "#fdd0a2";
            } else if (count > 100 && count <= 500) {
              return "#fdae6b";
            } else if (count > 500 && count <= 1000) {
              return "#fd8d3c";
            } else if (count > 1000 && count <= 10000) {
              return "#e6550d";
            } else if (count > 10000) {
              return "#a63603";
            }
          }
        }
      },
      popup: {
        enable: true,
        Html: props => {
          currentState = props;
          console.log("props_______", props);
          return `<span>${props.NAME_CHN} <br> 扫码次数: ${props.value}</span>`;
        }
      }
    });
  });
  scene.on("click", parms => {
    // 如果点击的是城市 进入热力地图
    if (currentState && currentState.level === "city") {
      setCity(currentState);
      currentState = null;
    }
  });
  scene.on("mousemove", handle => {
    currentState = null;
  });
};

![image](https://user-images.githubusercontent.com/12028374/91009570-6d418900-e613-11ea-8b84-f6fa003997ec.png)

**Comment by redblue9771** [comment]
> > > 自定义动作，自己按需调用 drilldown , drillup方法
> > 
> > 
> > 也没解决问题呀，自定义也要知道点了哪
> > 你可以配置触发的事件
> 
> drillDownTriggerEvent 向下钻取的触发事件 ⛔customTrigger 为 true 时不生效
> drillUpTriggleEvent 向上钻取的触发事件 ⛔customTrigger 为 true 时不生效
> 
> 你也可也取到对应的 provincelayer,citylayer 添加事件

不懂，我怎么取到对应的-。- 能取到就没这个问题了

**Comment by redblue9771** [comment]
> 我有一套解决方案，就是有点非主流。 在popup的时候，把当前省市信息给一个变量，然后监听点击的时候，使用这个变量。 大概就是这样。 我经过测试没有问题。
> const initDrillMap = ({ setCity, provinceData, cityData, drill }) => {
> let currentState = {};
> const scene = new Scene({
> id: "drillMap",
> map: new Mapbox({
> center: [116.2825, 39.9],
> pitch: 0,
> style: "blank",
> zoom: 3,
> minZoom: 3,
> maxZoom: 10
> })
> });
> scene.on("loaded", () => {
> drill = new DrillDownLayer(scene, {
> data: [],
> depth: 1,
> drillDepth: 1,
> provinceData,
> cityData,
> joinBy: ["adcode", "adcode"],
> 
> ```
>   fill: {
>     color: {
>       field: "value",
>       values: count => {
>         if (count <= 0) {
>           return "white";
>         } else if (count > 0 && count < 20) {
>           return "#feedde";
>         } else if (count > 20 && count <= 100) {
>           return "#fdd0a2";
>         } else if (count > 100 && count <= 500) {
>           return "#fdae6b";
>         } else if (count > 500 && count <= 1000) {
>           return "#fd8d3c";
>         } else if (count > 1000 && count <= 10000) {
>           return "#e6550d";
>         } else if (count > 10000) {
>           return "#a63603";
>         }
>       }
>     }
>   },
>   popup: {
>     enable: true,
>     Html: props => {
>       currentState = props;
>       console.log("props_______", props);
>       return `<span>${props.NAME_CHN} <br> 扫码次数: ${props.value}</span>`;
>     }
>   }
> });
> ```
> 
> });
> scene.on("click", parms => {
> // 如果点击的是城市 进入热力地图
> if (currentState && currentState.level === "city") {
> setCity(currentState);
> currentState = null;
> }
> });
> scene.on("mousemove", handle => {
> currentState = null;
> });
> };
> 
> ![image](https://user-images.githubusercontent.com/12028374/91009570-6d418900-e613-11ea-8b84-f6fa003997ec.png)

但是我是在大屏触摸屏上，可能不触发 popup，头疼~

**Comment by lzxue** [comment]
DrillDownLayer.cityLayer.on('click',()=>{})不可以吗

**Comment by redblue9771** [comment]
> cityLayer

不行-。-，给个例子呗

**Comment by redblue9771** [comment]
@LazyChun https://github.com/lzxue/yiqingditu 我从楼上老哥的仓库看到一个例子，虽然有点小复杂

**Comment by redblue9771** [comment]
放弃了

**Comment by LazyChun** [comment]
> 放弃了

哎 ，这个框架的文档信息太少了。。。

**Comment by LazyChun** [comment]
> > 我有一套解决方案，就是有点非主流。 在popup的时候，把当前省市信息给一个变量，然后监听点击的时候，使用这个变量。 大概就是这样。 我经过测试没有问题。
> > const initDrillMap = ({ setCity, provinceData, cityData, drill }) => {
> > let currentState = {};
> > const scene = new Scene({
> > id: "drillMap",
> > map: new Mapbox({
> > center: [116.2825, 39.9],
> > pitch: 0,
> > style: "blank",
> > zoom: 3,
> > minZoom: 3,
> > maxZoom: 10
> > })
> > });
> > scene.on("loaded", () => {
> > drill = new DrillDownLayer(scene, {
> > data: [],
> > depth: 1,
> > drillDepth: 1,
> > provinceData,
> > cityData,
> > joinBy: ["adcode", "adcode"],
> > ```
> >   fill: {
> >     color: {
> >       field: "value",
> >       values: count => {
> >         if (count <= 0) {
> >           return "white";
> >         } else if (count > 0 && count < 20) {
> >           return "#feedde";
> >         } else if (count > 20 && count <= 100) {
> >           return "#fdd0a2";
> >         } else if (count > 100 && count <= 500) {
> >           return "#fdae6b";
> >         } else if (count > 500 && count <= 1000) {
> >           return "#fd8d3c";
> >         } else if (count > 1000 && count <= 10000) {
> >           return "#e6550d";
> >         } else if (count > 10000) {
> >           return "#a63603";
> >         }
> >       }
> >     }
> >   },
> >   popup: {
> >     enable: true,
> >     Html: props => {
> >       currentState = props;
> >       console.log("props_______", props);
> >       return `<span>${props.NAME_CHN} <br> 扫码次数: ${props.value}</span>`;
> >     }
> >   }
> > });
> > ```
> > 
> > 
> > });
> > scene.on("click", parms => {
> > // 如果点击的是城市 进入热力地图
> > if (currentState && currentState.level === "city") {
> > setCity(currentState);
> > currentState = null;
> > }
> > });
> > scene.on("mousemove", handle => {
> > currentState = null;
> > });
> > };
> > ![image](https://user-images.githubusercontent.com/12028374/91009570-6d418900-e613-11ea-8b84-f6fa003997ec.png)
> 
> 但是我是在大屏触摸屏上，可能不触发 popup，头疼~

刚刚试了一下，用我这种方法，在触屏上使用没有问题。  popup还是有触发的。 用的华为Matepad Pro测试的。

**Comment by Hanxiaobo** [comment]
文档写的太垃圾了，浪费时间。。。

**Comment by wujinjinBill** [comment]
和 popup 并列写drillDownEvent  drillUpEvent  可以获取想要的内容如下：
(整理自己功能代码时，竟然不记得从哪里找到的这个方法，困惑中。。。可能是看源码扒出来的)
popup:{
},
drillDownEvent: props => {
   const areaName= props.NAME_CHN
   const areaCode= props.adcode
  debugger
},
drillUpEvent: props => {
  debugger
}
