### ISSUE TITLE
地图的CountryLayer构造的实例，调用updateData方法无法更新地图现有数据

### ISSUE THREAD

**Issue by henryyohn** [antvis/L7#492]
* **L7 Version**: 2.2.33
* **Platform**: chrome  84.0.4147.135 64位
* **Mini Showcase(like screenshots)**
我的一个vue项目用了下面内容，初始化地图后，获取服务器数据在调用updateDat(serveData, joinBy)无法更新地图的数据
```
import { Scene } from "@antv/l7";
import { CountryLayer } from "@antv/l7-district";
import { Mapbox } from "@antv/l7-maps";

```
<img width="891" alt="截屏2020-08-25 下午11 13 14" src="https://user-images.githubusercontent.com/37692583/91193680-f4812080-e729-11ea-9430-e338092f7b84.png">
<img width="864" alt="截屏2020-08-25 下午11 13 48" src="https://user-images.githubusercontent.com/37692583/91193689-f9de6b00-e729-11ea-8d49-15de75796285.png">
<img width="868" alt="截屏2020-08-25 下午11 14 01" src="https://user-images.githubusercontent.com/37692583/91193706-fcd95b80-e729-11ea-85f7-e133e9799f04.png">

* **CodePen Link**:
主要代码和下面（你们的demo）的一样，我是用的CountryLayer构造函数返回的实例调用的updateData()方法，没有catch任何错误，但是地图数据不会更新。
https://codesandbox.io/s/zen-franklin-e7z8z?file=/index.js

**Comment by lzxue** [comment]
目前应该只是更新了，填充图，气泡图数据没用更新，我修复一下

**Comment by Teachers-Tony** [comment]
// 我在源码中找到这个方法，你用这个方法来更新数据
`
this.scene.updateDistrict(adcode, newData, joinByField);
`
