### ISSUE TITLE
钻取地图 全局颜色配置 在市级地图、县级地图不生效

### ISSUE THREAD

**Issue by BiuBiuHs** [antvis/L7#496]
![image](https://user-images.githubusercontent.com/24862392/91516064-28706780-e91d-11ea-9949-6097836d2df4.png)

 https://codesandbox.io/s/competent-glade-1q94u?file=/index.js
钻取地图 全局颜色配置 在市级地图、县级地图没有生效 ，显示黑白配色

**Comment by lzxue** [comment]
URL 不对没有保存。重新发一下

**Comment by BiuBiuHs** [comment]
https://codesandbox.io/s/competent-glade-1q94u?file=/index.js

> URL 不对没有保存。重新发一下

https://codesandbox.io/s/competent-glade-1q94u?file=/index.js

**Comment by BiuBiuHs** [comment]
> URL 不对没有保存。重新发一下

drillDepth 设置为0 地图也可以下钻 图表显示空白
![image](https://user-images.githubusercontent.com/24862392/91556822-eddeed00-e965-11ea-8aa7-170201415e86.png)

**Comment by lzxue** [comment]
为什么设置depth 为0 ，depth 最小是1.

我现在看demo,下钻是有颜色的 
![image](https://user-images.githubusercontent.com/4366658/91788619-3b49ab80-ec3f-11ea-86b2-a661c0784cb9.png)

**Comment by BiuBiuHs** [comment]
> 为什么设置depth 为0 ，depth 最小是1.
> 
> 我现在看demo,下钻是有颜色的
> ![image](https://user-images.githubusercontent.com/4366658/91788619-3b49ab80-ec3f-11ea-86b2-a661c0784cb9.png)

![image](https://user-images.githubusercontent.com/24862392/91788962-1d307b00-ec40-11ea-93d6-4cf397b7d443.png)
api文档中写着有 0啊 
颜色的问题 我发现是 数据的数值 相同时 默认填充了黑色 不是我预先设置的颜色数组当中的颜色

**Comment by BiuBiuHs** [comment]
mapBox 绘制底图 style 设置blank  行政区划数据 是从https://github.com/antvis/L7/blob/master/packages/boundary/src/config.ts
这个文件当中取的 我怎么将这部分行政区划 数据 本地化 呢？
可以在外部更改配置吗？

**Comment by lzxue** [comment]
> mapBox 绘制底图 style 设置blank 行政区划数据 是从https://github.com/antvis/L7/blob/master/packages/boundary/src/config.ts
> 这个文件当中取的 我怎么将这部分行政区划 数据 本地化 呢？
> 可以在外部更改配置吗？
可以的，有方法的 这块没有全面开放

**Comment by thelaurelyy** [comment]
hello，请教这个问题后面是如何解决的：数据的数值 相同时 默认填充了黑色 不是我预先设置的颜色数组当中的颜色？
期待回复，谢谢！~

**Comment by lvisei** [comment]
@thelaurelyy 给个复现链接，看看是不是使用错误问题，不过现在也没有维护 l7-distrct 了，建议切换 L7plot 行政地图

**Comment by thelaurelyy** [comment]
@lvisei   宁好~  复现地址在这里：https://codesandbox.io/s/antv-l7-di-tu-forked-4658sj?file=/index.js
demo中可以看到：当data中只有一条数据或者所有数据值相同时，区域就会变成黑色

--------------------------------------------------------

谢谢大佬，L7plot 行政地图已经在切换中了，不过也遇到了一些问题，比如：
tooltip.customContent 想要使用JSX （现在仅支持 string | HTMLElement）~

**Comment by lvisei** [comment]
> @lvisei 宁好~ 复现地址在这里：[codesandbox.io/s/antv-l7-di-tu-forked-4658sj?file=/index.js](https://codesandbox.io/s/antv-l7-di-tu-forked-4658sj?file=/index.js) demo中可以看到：当data中只有一条数据或者所有数据值相同时，区域就会变成黑色
> 
> 谢谢大佬，L7plot 行政地图已经在切换中了，不过也遇到了一些问题所以没那么快，比如： tooltip.customContent 想要使用JSX （现在仅支持 string | HTMLElement）~

JSX 可以用 react createPortal 🚀
@thelaurelyy

**Comment by thelaurelyy** [comment]
使用  react createPortal  应该在哪里预留容器呢？ 能否提供简单举例，谢谢回复~  @lvisei

**Comment by lvisei** [comment]
> 使用 react createPortal 应该在哪里预留容器呢？ 能否提供简单举例，谢谢回复~ @lvisei

```jsx
customContent (title: string, items: TooltipListItem[]) {
	  const container = document.createElement('div');
	  const portal = ReactDOM.createPortal(<div>{JSON.stringify(items)}</div>, container);
	  ReactDOM.render(portal, container);
	  return container;
}
```

@thelaurelyy

**Comment by thelaurelyy** [comment]
@lvisei 很抱歉，由于历史项目依赖l7-distrct，因此请教您一个问题：
地图区域中，当data只有一条数据或者所有数据值相同时，区域渲染是黑色的，如果想改成自定义的主题色应该怎么办呢？

复现地址：https://codesandbox.io/s/antv-l7-di-tu-forked-4658sj?file=/index.js
