### ISSUE TITLE
react版本的图层顺序是不是有问题

### ISSUE THREAD

**Issue by jiaicon** [antvis/L7#498]
![image](https://user-images.githubusercontent.com/34124517/91534147-9d569800-e943-11ea-84a9-a0304d07e85d.png)
看图上，marker在popup上面
![image](https://user-images.githubusercontent.com/34124517/91534297-ddb61600-e943-11ea-92e8-daeec39c3621.png)
我的代码
`
import React, { useState } from 'react';
import { AMapScene, Marker, Popup } from '@antv/l7-react';

const Index = () => {
  const [showPopup, setShowPopup] = useState(false);

  const onSceneLoaded = scene => {
    scene.on('click', e => {
      console.log(`[${e.lnglat.lng}, ${e.lnglat.lat}]`)
    });
  };

  const onMarkerLoaded = marker => {
    marker.on('click', () => {
      setShowPopup(true);
    })
  };

  return (
    <AMapScene
      map={{
        center: [116.397473, 39.908692],
        pitch: 0,
        zoom: 16,
        style: 'light',
      }}
      style={{
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
      }}
      onSceneLoaded={onSceneLoaded}
    >
      {
        showPopup && <Popup
          option={{offsets: [0, 40]}}
          lnglat={[116.397473, 39.908692]}
        >
          <div>这里是popup</div>
        </Popup>
      }
      <Marker
        lnglat={[116.397473, 39.908692]}
        onMarkerLoaded={onMarkerLoaded}
      />
      <Marker
        lnglat={[116.39743, 39.909713]}
      />
    </AMapScene>
  )
};

export default Index;
`

**Comment by lzxue** [comment]
这块统一修改
