### ISSUE TITLE
使用DrillDownLayer下钻，如何根据上级数据重新填充下级颜色

### ISSUE THREAD

**Issue by HowieZhan** [antvis/L7#499]
使用’DrillDownLayer‘从全国下钻至省级后，需要根据省级数据重新调整颜色覆盖‘fill’及添加省级独有的‘Control’。目前需要一个下钻后的方法入口。

**Comment by lzxue** [comment]
可以配置省级的数据数据，citydata

**Comment by lzxue** [comment]
看一下这个 https://github.com/antvis/L7/blob/master/stories/District/Layer/drillDown.tsx

**Comment by HowieZhan** [comment]
嗯...
http://kyt.gk2823.com/map_v1
各省所含数量越多颜色越深，进入其中一个省就根据城市所含数量越多颜色越深；
比如进入广东，会发现颜色依旧只会按全国的算导致颜色分布不明显。所以我需要一个入口去重新加载fill中的color
根据您给的实例链接怎么去改？

**Comment by lzxue** [comment]
每个层级 可以设置单独颜色渲染配置 
https://l7.antv.vision/zh/docs/api/district/drilldown#layeroption
