### ISSUE TITLE
官网demo在codesandbox中无法打开

### ISSUE THREAD

**Issue by arkee11** [antvis/L7#500]
[COVID-19 地图](https://l7.antv.vision/zh/examples/react/covid)
我想在demo上进行改动，但是codesandbox无法打开这些demo。
![image](https://user-images.githubusercontent.com/57891228/91787905-8662bf00-ec3d-11ea-972b-a7e63bb4093b.png)

**Comment by lzxue** [comment]
先在官网调试吧，sandbox 需要改一下写法
