### ISSUE TITLE
钻取地图的事件支持以及气泡图鼠标移入问题

### ISSUE THREAD

**Issue by hcy0622** [antvis/L7#501]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

1. 钻取地图可以提供事件支持吗，比如点击或移入某个省或市，文档上没有找到对应的事件响应
2. 气泡图的popup的html片段在鼠标移入时经常出不来，感觉不是很精确
3. 下钻深度可以再往下1级吗

**Comment by lzxue** [comment]
1. 可以取到单独layer监听，https://l7.antv.vision/zh/docs/api/district/drilldown#provincelayer
2.最好提供一个简单复现的demo
3.街道级的下钻吗？

**Comment by hcy0622** [comment]
1. 可以提供一个demo吗，我看这个属性好像是私有的
2. 应该是我这里布局的问题，重新弄了一个环境之后正常了
3. 就是可以下钻到具体的某一个区 / 县，类似高德那个行政区下钻

**Comment by lzxue** [comment]
> 1. 可以提供一个demo吗，我看这个属性好像是私有的
> 2. 应该是我这里布局的问题，重新弄了一个环境之后正常了
> 3. 就是可以下钻到具体的某一个区 / 县，类似高德那个行政区下钻

可以下钻到县的啊，省市县下钻都可以的
