### ISSUE TITLE
官方的L7地图vue的例子为什么会报错 “禁止多种API加载方式混用”

### ISSUE THREAD

**Issue by SummerGC** [antvis/L7#504]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by yeastone** [comment]
+10086我也遇到了

**Comment by lzxue** [comment]
高德地图加载好像有问题，我跟进一下

**Comment by SummerGC** [comment]
> 高德地图加载好像有问题，我跟进一下

我们项目最近在用这个组件 结果发现一直在报错  之前引用的时候是没问题的

**Comment by lzxue** [comment]
都是 Vue 的项目吗

**Comment by lzxue** [comment]
L7  更新了高德地图API的加载方式，Vue模板项目 由于在 index.html 文件也引入 高德地图API，导致API 重复引入，如果已有项目可以删除引用。模板我也会更新一下。
