### ISSUE TITLE
antv中marker和popup重叠问题

### ISSUE THREAD

**Issue by baiyangzhengxin** [antvis/L7#506]
antv/l7中 地图  2.2.20版本的marker和popup重叠是没有问题的，popup覆盖在marker上面，但是2.2.30之后的版本marker是覆盖在popup上面的，希望能够修复

**Comment by lzxue** [comment]
> antv/l7中 地图 2.2.20版本的marker和popup重叠是没有问题的，popup覆盖在marker上面，但是2.2.30之后的版本marker是覆盖在popup上面的，希望能够修复

2.2.34 已经修复了，之前的版本应该是高德地图有问题，mapbox 没有问题

**Comment by pursuelu** [comment]
![9KF7W%(O0BZ5(959%JFC{Q9](https://github.com/antvis/L7/assets/16470378/b5758b5d-b70e-4055-b383-add7dfdce279)
