### ISSUE TITLE
LineLayer设置了.shape('line')时，Source的parser解析coordinates数据时会将第二个点坐标丢失

### ISSUE THREAD

**Issue by yeastone** [antvis/L7#507]
* **L7 Version**:2.2.35
* **Platform**:Mac OS
* **Mini Showcase(like screenshots)**:
三个点只会画一条线段
![image](https://user-images.githubusercontent.com/65276724/92107305-2411e600-ee18-11ea-97d9-c5db1e4361fb.png)
这种情况下是画两条线段
![image](https://user-images.githubusercontent.com/65276724/92107410-502d6700-ee18-11ea-907d-8e1ac99ca297.png)
https://codesandbox.io/s/affectionate-euler-lvudu?fontsize=14&hidenavigation=1&theme=dark
* **CodePen Link**:
https://codesandbox.io/s/affectionate-euler-lvudu?fontsize=14&hidenavigation=1&theme=dark

在2.2.28版本中是好的。
.shape('line')这样设置时特有
https://l7.antv.vision/zh/examples/gallery/basic#arcCircle
这个demo的shape设置为line就显示不出来了!!!!

**Comment by lzxue** [comment]
@elaine1234 这个可以看一下

**Comment by ParryQiu** [comment]
明天我来看下。

**Comment by lzxue** [comment]
点去重方法已经优化
