### ISSUE TITLE
PointLayer中配置了cluster:true，最终聚合后的数据会缺失一部分

### ISSUE THREAD

**Issue by jingyebuchen** [antvis/L7#508]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

复现demo地址：https://codesandbox.io/s/recursing-lumiere-b46im?file=/index.js

**Comment by ParryQiu** [comment]
测试了下，在 mapbox 下渲染是正常的。
https://codepen.io/parryqiu/pen/abNVwRw

**Comment by jingyebuchen** [comment]
> 测试了下，在 mapbox 下渲染是正常的。
> https://codepen.io/parryqiu/pen/abNVwRw
确实是这样。
https://github.com/antvis/L7/blob/6ff115ddb5950a1a0186ca23f853a953583213fd/packages/source/src/source.ts#L90中的this.extent是根据原始数据取的范围；https://github.com/antvis/L7/pull/170/commits/31446172fc76637adb10b9ddbc9c0e71f1fc13b2中的viewBBox是视野范围。getClusters这个方法中的第一个参数是数据范围还是视野范围，这个有影响吗？
![image](https://user-images.githubusercontent.com/41276803/92326307-b10ca780-f083-11ea-8457-d7a837a76bc2.png)
因为当我尝试在这里修改参数的时候，貌似返回的数据是正常的。

**Comment by zchuhui** [comment]
啊，我也遇到这个问题 。。。。
