### ISSUE TITLE
样例预览有bug

### ISSUE THREAD

**Issue by qiuqiui** [antvis/L7#51]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

chrome 75.0.3770.142 浏览器预览L7的样例都会报这个错误，同时示例图加载不出来
![image](https://user-images.githubusercontent.com/29109885/67837015-06edf600-fb29-11e9-8a55-e42b4de37776.png)

**Comment by lzxue** [comment]
这个问题，一般是网络的问题，
其他用户也出现过

> 我之前 也出现了这种情况，火狐能显示高德得3d地图，谷歌 浏览器就不能，卸载重装也不行，后来  把 谷歌浏览器 重置 就可以了
