### ISSUE TITLE
绘制组件bug

### ISSUE THREAD

**Issue by Liisp** [antvis/L7#510]
官方绘制组件Demo([https://l7.antv.vision/zh/examples/draw/UI#amap]())出现多个bug：
1、绘制线、多边形、圆出现错乱、消失现象。
2、绘制完编辑出现错乱编辑现象。
3、无法删除绘制。
![image](https://user-images.githubusercontent.com/50945549/92346596-ccb59380-f0ff-11ea-8a71-286aa62a5889.png)

![L7绘制组件bug](https://user-images.githubusercontent.com/50945549/92353481-ff1cbc00-f112-11ea-8cf7-a6bd40218450.gif)

**Comment by zchuhui** [comment]
除了了这里，LineLayer 也有问题，更新包，没有提升版本，都出现了这个问题。在绘制线的时候，回出现标点缺失！
比如本该绘制一个正方形的线，绘制后就会损失一个节点，导致只有三条线。

**Comment by yanyu510** [comment]
新版本已修复
