### ISSUE TITLE
行政区划图可以支持标注可数据映射嘛，或者其它方法实现

### ISSUE THREAD

**Issue by webpawn** [antvis/L7#514]
![image](https://user-images.githubusercontent.com/45424583/92478321-93227c80-f214-11ea-896e-46e47ce47990.png)

* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lzxue** [comment]
这种自定义的希望获取到数据之后，通过markers实现
