### ISSUE TITLE
偶尔会报错 Error: @postConstruct error in class PostProcessor: (regl) invalid render buffer format

### ISSUE THREAD

**Issue by jiaicon** [antvis/L7#519]
![Snipaste_2020-09-14_10-13-13](https://user-images.githubusercontent.com/34124517/93036606-ea8c7680-f672-11ea-9cda-e7812c2db8ce.png)

**Comment by lzxue** [comment]
什么场景，是地图频繁刷新吗？

**Comment by jiaicon** [comment]
> 什么场景，是地图频繁刷新吗？

对，还有一个高德js加载的错误，也会出现

**Comment by wufenfen** [comment]
多次切换的时候，会出现。比较常见。
