### ISSUE TITLE
Feature request: 是否有考虑抽离核心渲染器，支持各个地图类库的 CanvasLayer？

### ISSUE THREAD

**Issue by sakitam-fdd** [antvis/L7#52]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

是否有考虑抽离核心渲染器，支持各个地图类库的 CanvasLayer？目前如果直接创建 dom 元素的方式会直接覆盖掉原始地图图层，我看到 next 分支相关的新架构貌似目前还没有计划抽离这一块。

**Comment by lzxue** [comment]
新架构定义了地图服务接口，可以扩展其他第三方地图，你说的支持地图类库的canvaslayer 是再叠加一层

**Comment by sakitam-fdd** [comment]
@lzxue 类似高德的这个[API](https://lbs.amap.com/api/javascript-api/example/selflayer/canvaslayer)，相当于是将l7作为其他地图的一个图层，这样的好处是可以管理到L7与原始底图图层的层级关系，不过可能跟L7的定位不太一致:joy:

**Comment by lzxue** [comment]
@sakitam-fdd 后面有计划跟高德打通的
