### ISSUE TITLE
setDOMContent 二次点击后报错 Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by laijinxian** [antvis/L7#520]
通过 pointLayer.on 方法 设置Popup, 在不点击气泡的情况下没问题， 当你点击气泡后，后面就报错再也弹不出Popup了； 后面一直报错 Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

**Comment by lzxue** [comment]
提供一下复现demo

**Comment by laijinxian** [comment]
```
pointLayer.on('mousemove', e => {
          const popup = new Popup({
            offsets: [ 0, 0 ],
            closeButton: false
          })
            .setLnglat(e.lngLat)
            .setDOMContent(document.querySelector('.details'))
          scene.addPopup(popup);
        });
```
鼠标移入没有问题Popup能正常显示；但是点击气泡后，document.querySelector('.details') 就变成undefined了， 就报上面那个错了， 后面每次点击都报错了；

用 ref 的方式就没有问题，不会出现上面的问题；

**Comment by lzxue** [comment]
document.querySelector('.details') 为什么要这操作(react?)，是不是没有取到dom, 如果是react 看看l7-react 如何实现的

**Comment by laijinxian** [comment]
刚开始的演练时候没引入框架 ......；原生JS 跑的

**Comment by laijinxian** [comment]
用的vue.......

**Comment by lzxue** [comment]
具体什么问题还清楚，上面写法不推荐

**Comment by laijinxian** [comment]
@lzxue ：  new PointLayer({})； 支持自定义 animate 动画么？ 比如呼吸动画； 而不是默认水波纹动画

例子： https://l7.antv.vision/zh/examples/point/bubble#world

**Comment by laijinxian** [comment]
@lzxue  通过 ref 取节点的方式没问题了； 谢谢！ 初期没引框架预演续期， 用的是原生js

**Comment by laijinxian** [comment]
通过 ref 取节点的方式没问题了； 谢谢！ 初期没引框架预演需求， 用的是原生js

**Comment by laijinxian** [comment]
已解决
