### ISSUE TITLE
PointLayer 支持自定义 animate 动画么

### ISSUE THREAD

**Issue by laijinxian** [antvis/L7#521]
new PointLayer({}) 气泡图动画； 支持自定义 animate 动画么？ 比如呼吸动画等； 而不是默认水波纹动画

例子： https://l7.antv.vision/zh/examples/point/bubble#world

**Comment by lzxue** [comment]
目前不支持，需要基于源码定制

**Comment by guoliangli123** [comment]
呼吸动画请问有没有解决方案呢？源码定制有点难以下手。
