### ISSUE TITLE
填充图显示问题，渲染过程中会有跳动

### ISSUE THREAD

**Issue by webpawn** [antvis/L7#523]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

[官网示例](https://antv-l7.gitee.io/zh/examples/district/basic#china_map_2)
如上官网示例所示，地图加载时会有跳动的现象

**Comment by dinglei19** [comment]
@webpawn 跳动的原因应该是CountryLayer默认是autoFit:true,这会导致初始化行政区划图层时会自动计算中心点和zoom层级，可以尝试将autoFit设为false, 就可以以scene设置的center和zoom为准了，或者将scene的center和zoom设置为autoFit: true一致

**Comment by webpawn** [comment]
![image](https://user-images.githubusercontent.com/45424583/93312122-69331080-f839-11ea-9d6f-8576c9572885.png)
按图上调整后可以使用了
