### ISSUE TITLE
请问L7-react离线部署有详细的方案吗

### ISSUE THREAD

**Issue by lansebingqilin** [antvis/L7#524]
我使用高德地图底图，内网使用就无法访问了，看到文档介绍Mapbox可以支持离线，但百度一番没有找到相应的方案

**Comment by dinglei19** [comment]
@lansebingqilin 你需要的时mapbox离线部署的方案，应该和L7的关系不是很大，mapbox离线部署推荐使用mbtiles发布，比较方便。

**Comment by lzxue** [comment]
离线需要自己提供数据
