### ISSUE TITLE
如何修改光标样式？

### ISSUE THREAD

**Issue by daxiaolaogui** [antvis/L7#526]
想再特定的情况下把光标从小手改为箭头。例如监听mouseenter事件

mapbox的方法map.getCanvas().style.cursor = 'pointer‘  似乎在L7中无法使用。

即使是传入外部实例，在外部实例的map上使用map.getCanvas().style.cursor = 'pointer‘似乎可以生效但是无法显示。表面上依旧是触摸的小手状态。再改map.getCanvas().style.position= 'relative‘可以生效，但是加载到scene层上的其他图层就会消失。

再scene的style里似乎也不支持修改这一属性。

请教一下如何修改

**Comment by daxiaolaogui** [comment]
尝试过禁用地图交互，禁用后光标依旧是小手

**Comment by Randysheng** [comment]
通过 CSS 设置样式应该可以解决把。设置 `.amap-container {
  cursor: pointer !important;
}`
不知你是否尝试过这种办法没。希望你找到办法解决了

**Comment by daxiaolaogui** [comment]
> 通过 CSS 设置样式应该可以解决把。设置 `.amap-container { cursor: pointer !important; }`
> 不知你是否尝试过这种办法没。希望你找到办法解决了

我是想在特定的事件下改变他的光标的，有什么方法改变css？用了常规的方法无效。

**Comment by daxiaolaogui** [comment]
已经解决，通过设置pointerEvents样式得以修改

**Comment by xingming2020** [comment]
> 已经解决，通过设置pointerEvents样式得以修改

可否提供demo？设置map.getCanvas().style.pointerEvents后无任何效果
