### ISSUE TITLE
Popup使用setDOMContent添加Dom报错

### ISSUE THREAD

**Issue by lansebingqilin** [antvis/L7#528]
![image](https://user-images.githubusercontent.com/35915720/93956335-89585780-fd84-11ea-8952-d9370baf7b96.png)
报错代码：const popup = new Popup({
                offsets: [ 0, 20 ]
              }).setDOMContent(<div>1111</div>)
            

报错信息：
![image](https://user-images.githubusercontent.com/35915720/93956904-beb17500-fd85-11ea-8102-565d2bb37610.png)

popup源码：
![image](https://user-images.githubusercontent.com/35915720/93957003-ec96b980-fd85-11ea-9813-0ed1c2980bc0.png)

这边尝试加{}、尝试react函数组件，依然不行

**Comment by lzxue** [comment]
你的用法不对，

Popup 中使用react 组件 参照 https://github.com/antvis/L7-react/blob/master/src/component/Popup.tsx
