### ISSUE TITLE
如何使用HighMaps的地图数据做个填充图？

### ISSUE THREAD

**Issue by luckymore** [antvis/L7#529]
* **L7 Version**: latest
* **Platform**: 版本 85.0.4183.121（正式版本） （64 位） 
* **CodePen Link**: https://codesandbox.io/s/mystifying-framework-kq3zt

例如：Indonesia 的 [Geojson](https://code.highcharts.com.cn/mapdata/countries/id/id-all.geo.json)，在 HighCharts.js 中的[使用](https://jshare.com.cn/mapdata/CN4fQa?map=countries/id/id-all)，但放到 `antv/L7` 中，layer 就乱了。<del>（不好意思问这种使用问题，可实在不会用o(╥﹏╥)o）</del>
![image](https://user-images.githubusercontent.com/5390013/94245141-6d071700-ff4c-11ea-9267-4ea88992e4a8.png)

**Comment by lzxue** [comment]
坐标系不一样，L7 只支持经纬度坐标系

**Comment by luckymore** [comment]
@lzxue 其他地图数据去哪里取，比如美国的州数据，https://l7.antv.vision/zh/examples/polygon/fill#usa

**Comment by luckymore** [comment]
我用的这个 https://github.com/superpikar/indonesia-geojson/blob/master/indonesia.geojson
但是不知道有没有一种找用经纬度坐标表示地图数据的平台😢

**Comment by lzxue** [comment]
你可以下载 QGIS 软件转一下坐标使用，将数据拖入QGIS，然后另存为，坐标改成 wgs84 4326


![20201009170125](https://user-images.githubusercontent.com/4366658/95564252-1bcd4c00-0a51-11eb-860c-853a4826c896.jpg)
