### ISSUE TITLE
绘制UI组件画出的图形可否支持自定义事件？

### ISSUE THREAD

**Issue by EricChen047** [antvis/L7#530]

**Comment by loong-chen-cn** [comment]
目前只支持create, update, delete 事件，绘制完后也无法拿到layer对象，也就无法给layer增加事件，只能拿到绘制后的GeoJSON，无法对接其他业务逻辑。如果考虑用GeoJSON再生成一个layer的话，但是绘制的layer却无法隐藏，所以感觉逻辑很不好处理，谢谢。

**Comment by lzxue** [comment]
可也增加的 目前仓库单独维护 https://github.com/antvis/L7-draw  有需求也可以提PR

**Comment by loong-chen-cn** [comment]
> 可也增加的 目前仓库单独维护 https://github.com/antvis/L7-draw 有需求也可以提PR

好的，谢谢

**Comment by 2912401452** [comment]
推荐使用 L7Draw3.0
https://antv.vision/L7Draw/
