### ISSUE TITLE
行政区划标准地图中，如何写click点击事件

### ISSUE THREAD

**Issue by EricHan0723** [antvis/L7#532]
文档中并没有详细说明在行政区划中如果点击省份地图，click等事件回调写在哪里，希望有文档可以参考

同为antv下的产品，G2Plot明显文档更清晰，希望改进

**Comment by lzxue** [comment]
通过对应的layer去监听  https://l7.antv.vision/zh/docs/api/district/baselayer#filllayer

**Comment by EricHan0723** [comment]
希望能在行政区划地图示例代码中增加对应的样例代码

**Comment by lzxue** [comment]
> 希望能在行政区划地图示例代码中增加对应的样例代
后面会增加,这里写个示例
```javascript
 const chinaLayer = new CountryLayer();
chinaLayer.fillLayer.on('click',(e)=>{

})


```
