### ISSUE TITLE
图层active(true)以后select(true)无效

### ISSUE THREAD

**Issue by wxfqf** [antvis/L7#534]
使用版本 2.2.37

1,  图层active(true)以后select(true)无效
2.setActive(1,{color:'red'}) 颜色无效，setSelect(1,{color:'red'})颜色有效

**Comment by wxfqf** [comment]
setActive(1,{color:'red'}) 在源码BaseLayer.js中setActive方法中this.hooks.beforeSelect.call修改为this.hooks.beforeHighlight.call后颜色有效

**Comment by lzxue** [comment]
先关闭 active 在开启select 可以吗

**Comment by susiwen8** [comment]
Fix in 2.7
