### ISSUE TITLE
L7提供下钻到区县，新的行政区域数据需要怎么加载

### ISSUE THREAD

**Issue by TwoPens** [antvis/L7#538]
new DrillDownLayer后，怎么监听下钻和上钻，然后怎么更新geo数据

**Comment by lzxue** [comment]
这个需要自定义数据了, 可以参考这个https://github.com/antvis/L7-boundary/blob/master/src/config.ts

**Comment by TwoPens** [comment]
> 这个需要自定义数据了, 可以参考这个https://github.com/antvis/L7-boundary/blob/master/src/config.ts
我引入的填充地图的示例，没有 L7-boundary这个资源。现在需要引入这个依赖？还是，可以直接使用 DrillDownLayer from '@antv/l7-district'

**Comment by cashZhang27** [comment]
请问有计划更新版本时将行政区域数据更新到最新么？

**Comment by 2912401452** [comment]
现在应该是最新的，同时也可以使用 L7Plot 的行政区划
