### ISSUE TITLE
LineLayer能否绘制渐变线？文档没找到？

### ISSUE THREAD

**Issue by pkaq** [antvis/L7#541]
LineLayer能否绘制渐变线？文档没找到？

**Comment by yu-tou** [comment]
认领下，我试试能不能实现

**Comment by 2912401452** [comment]
线渐变的功能已经实现 [https://l7.antv.vision/zh/docs/api/layer/line_layer/linelayer#%E8%AE%BE%E7%BD%AE%E6%B8%90%E5%8F%98%E8%89%B2](url)
