### ISSUE TITLE
地图拖拽、移动时，CPU内存占用超多，

### ISSUE THREAD

**Issue by jiaicon** [antvis/L7#542]
![image](https://user-images.githubusercontent.com/34124517/96662505-13461100-1381-11eb-9ad9-9be5b010fccf.png)

**Comment by ParryQiu** [comment]
调试网页性能应该用 Chrome 的调试工具具体看某一个页面，抓取内存等快照，而不是直接看整个 Chrome 的进程。
这样才能更加精准地定位问题。

**Comment by yu-tou** [comment]
注意下自己的用法，是否为每个元素创建了一个 layer，cpu 飙高很可能是因为这个，另外就是自定义 marker 过多，自定义marker基于 dom 渲染，性能很差
