### ISSUE TITLE
如何实现渐变填充地图

### ISSUE THREAD

**Issue by wayingCode** [antvis/L7#548]
如下效果
![image](https://user-images.githubusercontent.com/5735933/97654713-83017d80-1a9e-11eb-8cd6-78de9945e92c.png)

**Comment by ParryQiu** [comment]
感谢您向我们反馈问题。

1. 提交问题前，请先阅读 https://antv.alipay.com/zh-cn/g2/3.x/index.html 上的文档。
2. 我们推荐如果是小问题（错别字修改，小的 bug fix）直接提交 PR。
3. 如果是一个新需求，请提供：详细需求描述，最好是有伪代码实现。
4. 如果是一个 BUG，请提供：复现步骤，错误日志以及相关配置，并尽量填写下面的模板中的条目。
5. 如果可以，请提供尽可能精简的 CodePen 链接，可使用 CodePen 模板 https://codepen.io/leungwensen/pen/WXJgox，方便我们排查问题。
6. 扩展阅读：[如何向开源项目提交无法解答的问题](https://zhuanlan.zhihu.com/p/25795393)

**Comment by lzxue** [comment]
目前不支持，一个区块内的颜色渐变
