### ISSUE TITLE
HeatmapLayer的react组件报错

### ISSUE THREAD

**Issue by CathyLX** [antvis/L7#550]
https://antv-l7.gitee.io/zh/examples/heatmap/heatmap 将官网这个例子改成react组件，报错

![image](https://user-images.githubusercontent.com/12692270/98093395-dae71c80-1ec2-11eb-9596-8970d720d1d8.png)

![image](https://user-images.githubusercontent.com/12692270/98093200-9491bd80-1ec2-11eb-878c-50bda79f61c5.png)

**Comment by sebastianandreasson** [comment]
I'm having the same issue as above, is there any documentation on how to use the Heatmaplayer with react?

**Comment by yzg1025** [comment]
size的写法有问题，你这个场景应该使用这样的写法
![image](https://user-images.githubusercontent.com/44477805/118352376-b7004400-b593-11eb-8321-ff5639b36e17.png)
