### ISSUE TITLE
点图层(PointLayer)、线图层(LineLayer) 怎么设置高度？

### ISSUE THREAD

**Issue by StarryAn** [antvis/L7#552]
* **L7 Version**: 2.2
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lzxue** [comment]
点图层，目前不支持高度设置，
线图层可以通过size设置 [0,10] 第一个数字表示宽度，第二个表示高度。 https://l7.antv.vision/zh/examples/line/path

**Comment by StarryAn** [comment]
> 点图层，目前不支持高度设置，
> 线图层可以通过size设置 [0,10] 第一个数字表示宽度，第二个表示高度。 https://l7.antv.vision/zh/examples/line/path

面状3D填充的高度和线的高度是一样的高度吗？我把一个多边形拉高之后，给线也设置高度，怎么不匹配

**Comment by lzxue** [comment]
目前不支持

**Comment by 2912401452** [comment]
现在可以使用 raisingHeight 参数配置点、线、面的高度，写法可以参考下面的 demo
https://l7.antv.vision/zh/examples/polygon/3d/#floatMap

**Comment by guoliangli123** [comment]
我的代码如下
`const layer = new PointLayer({ zIndex: 3 })
        .source(points, {
          parser: {
            type: 'json',
            x: 'lng',
            y: 'lat'
          }
        })
        .shape('circle')
        .color('#f00')
        .size('value', v => 15 + 15 * v)
        .style({
          strokeWidth: 3,
          stroke: '#0ff', // 描边颜色
          strokeWidth: 0.2, // 描边宽度
          // raisingHeight: 800000 + 150000 + 10000,
        });
        this.scene.addLayer(layer);`
不设置高度时，可以看到点图层。
![image](https://user-images.githubusercontent.com/12670391/190575719-5a85eebd-1a0c-42ca-9653-1c118da0d9a9.png)
但是设置了高度后
`const layer = new PointLayer({ zIndex: 3 })
        .source(points, {
          parser: {
            type: 'json',
            x: 'lng',
            y: 'lat'
          }
        })
        .shape('circle')
        .color('#f00')
        .size('value', v => 15 + 15 * v)
        .style({
          strokeWidth: 3,
          stroke: '#0ff', // 描边颜色
          strokeWidth: 0.2, // 描边宽度
          raisingHeight: 800000 + 150000 + 10000,
        });
        this.scene.addLayer(layer);`
点图层看不到了，是代码的问题吗？
![image](https://user-images.githubusercontent.com/12670391/190576004-9c310c06-5a73-4887-9c79-36ea0ff423a0.png)

**Comment by guoliangli123** [comment]
> 现在可以使用 raisingHeight 参数配置点、线、面的高度，写法可以参考下面的 demo https://l7.antv.vision/zh/examples/polygon/3d/#floatMap

我按照官方的写法，但是好像只有文字标注起作用了。

**Comment by StarryAn** [comment]
收到，谢谢，越来越强大

DFGK-安帅奇


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/L7"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月25日(星期一) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [antvis/L7] 点图层(PointLayer)、线图层(LineLayer) 怎么设置高度？ (#552)





 
现在可以使用 raisingHeight 参数配置点、线、面的高度，写法可以参考下面的 demo
 https://l7.antv.vision/zh/examples/polygon/3d/#floatMap

**Comment by Yuki-Zhao** [comment]
请问height和raisingHeight是有什么区别？
效果不一样，是否是因为单位不同？
