### ISSUE TITLE
CityLayer Popup  渲染太频繁， 不支持防抖方式

### ISSUE THREAD

**Issue by laijinxian** [antvis/L7#553]
```
L7 Version: 2.2.37:
Platform: CityLayer Popup信息框
Mini Showcase(like screenshots):
CodePen Link: 官方列子 中国地图（市地图）https://antv-l7.gitee.io/zh/examples/district/basic#city
```
**Popup 实时渲染太频繁， html结构多的会卡顿；**
**在官方例子上加防抖，渲染出问题， 页面popup内容显示undefined**
**CityLayer Popup 是否支持 setDOMContent 方式添加popup**
**有别的方法对popup优化么**

![1604742892(1)](https://user-images.githubusercontent.com/30945933/98438085-83df8280-2122-11eb-96d7-07d311c3ef95.jpg)

代码如下：
```
if (timer) clearTimeout(timer)
   timer = setTimeout(() => {
      return `<span>${props.NAME_CHN}:</span><span>${props.pop}</span>`;
   }, 200)
```
**求解**

**Comment by lzxue** [comment]
会增加 throttle机制
