### ISSUE TITLE
行政地图钻取DrillDownLayer是否有加载完成事件

### ISSUE THREAD

**Issue by snake11am** [antvis/L7#557]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

行政地图钻取DrillDownLayer是否有加载完成事件，scene.on('loaded', () => {layer.current = new DrillDownLayer(scene, {})})要过几秒
layer.current才能使用，DrillDownLayer是否有加载完成事件

**Comment by lzxue** [comment]
目前没有可以增加一下

**Comment by liuvigongzuoshi** [comment]
@snake11am  **建议使用新版[行政区域 ](https://l7.antv.vision/zh/docs/api/district/start)，使用[案例](https://l7.antv.vision/zh/examples/choropleth/drill#order-drill)**

### 使用方式

1. 按图表方式

```js
import { Choropleth } from '@antv/l7plot';

const choropleth = new Choropleth('container', options);
```

2. 按场景方式

```js
import { Scene, Mapbox } from '@antv/l7';
import { Choropleth } from '@antv/l7plot';

const scene = new Scene({
  id: 'container',
  map: new Mapbox({
    style: 'light',
    center: [102.447303, 37.753574],
    zoom: 5,
  }),
});

const choropleth = new Choropleth(options);

scene.on('loaded', () => {
  choropleth.addToScene(scene);
});
```

### API

Choropleth 具体 API 文档移步 [L7Plot 官网](https://l7plot.antv.vision/zh/docs/api/plots/choropleth)。
