### ISSUE TITLE
VUE 下使用L7的行政区划-气泡填充

### ISSUE THREAD

**Issue by Liamqin** [antvis/L7#560]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

vue-cli 搭建的vue，运行示例后  只显示中国地图的描边，没有图层，并且控制台报一下错误。 react环境下正常运行
 Cannot read property 'getBoundingClientRect' of undefined

**Comment by lzxue** [comment]
没有设置地图初始化 dom 吧
