### ISSUE TITLE
线能否实现3d坡度效果，比如上高速时从下到上

### ISSUE THREAD

**Issue by HWTsang** [antvis/L7#568]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by 2912401452** [comment]
已经在新版本中支持、请安装 L7 新版本 >=  2.5.56
` fetch(
        'https://gw.alipayobjects.com/os/bmw-prod/65589ef3-7f1d-440f-ba5d-86b03ee6ba7e.json',
      )
        .then((res) => res.json())
        .then((data) => {
          const layer = new LineLayer({})
            .source(data)
            .size(1)
            .shape('line')
            .style({
              vertexHeightScale: 30,
            })
            .color('#ccc');

          scene.addLayer(layer);
        });`
![4050AD45-5050-4683-8539-EF2C6FD9A5BD](https://user-images.githubusercontent.com/42212176/142161866-e4093bec-0455-4a39-b991-08374aa6ab97.png)
