### ISSUE TITLE
图片图层支持SVG

### ISSUE THREAD

**Issue by linziguan** [antvis/L7#570]
图片图层可以支持SVG图片吗？

**Comment by lzxue** [comment]
支持的但是也会转换成 Png

**Comment by linziguan** [comment]
本想是，如果用SVG矢量图，在使用pitch时，不会产生锯齿。或者说有没有更好的办法（将一张平面图（如室内），放在L7上，并设置pitch，不会产生锯齿？）

**Comment by linziguan** [comment]
还有，L7的钉钉二维码过期了，扫不出来。
