### ISSUE TITLE
下钻地图 描边不生效

### ISSUE THREAD

**Issue by Bigredorange** [antvis/L7#574]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by Bigredorange** [comment]
[http://chuantu.xyz/t6/741/1606909304x1033348159.png](url)
官方省级下钻实例加入属性layerOption配置描边无效
[https://l7.antv.vision/zh/examples/district/drill#drill_down_province](url)
layerOption: {
      provinceStroke: '#ff0000',
      cityStroke: '#FF00000'
    },
请问如何设置描边，谢谢了。

**Comment by zjdesj** [comment]
province: {
    provinceStroke: '#ff0000',
    cityStroke: '#FF00000'
},
