### ISSUE TITLE
CountryLayer使用updateData只有初始化时生效，无法动态更新数据

### ISSUE THREAD

**Issue by chen515024** [antvis/L7#575]
* **L7 Version**:2.3.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://codesandbox.io/s/cocky-aryabhata-8itye?file=/src/App.vue

![image](https://user-images.githubusercontent.com/27874954/100976558-ac6c6800-357a-11eb-96ea-42ed6d894216.png)
![image](https://user-images.githubusercontent.com/27874954/100976617-c27a2880-357a-11eb-9526-c89ed34fb8e5.png)
![image](https://user-images.githubusercontent.com/27874954/100976583-b68e6680-357a-11eb-83c0-b8fe2a52968f.png)
![image](https://user-images.githubusercontent.com/27874954/100976662-d02fae00-357a-11eb-9a45-044307f2bfa9.png)
![image](https://user-images.githubusercontent.com/27874954/100976682-d887e900-357a-11eb-93b2-9c226015e698.png)
以上的图是第一次加载时的状态和数据以及点击按钮切换时的数据和状态，监听了数据的变化，每次都会触发，但是updateData方法好像没有把页面的效果做修改，数据变更了，但是界面上显示的还是一样。
想要使用codesandbox做个demo但是好像我使用的包有问题？😓
![image](https://user-images.githubusercontent.com/27874954/100977083-6f54a580-357b-11eb-9489-a40b4a9c09e2.png)

**Comment by ShoutongLiu** [comment]
解决了吗？我也遇到同样的问题
