### ISSUE TITLE
有没有什么办法可以让自定义的marker点或图片，可以平铺在地图上，随地图缩放旋转？

### ISSUE THREAD

**Issue by jiaicon** [antvis/L7#578]
![image](https://user-images.githubusercontent.com/34124517/101117341-bdbc7f80-3621-11eb-827b-ceb38c3c2619.png)
类似这种的，贴在地图上的，

**Comment by ParryQiu** [comment]
需要通过自定义层绘制，也就是 geojson 的数据来绘制。
https://l7.antv.vision/zh/examples/point/bubble#point

**Comment by jiaicon** [comment]
> 需要通过自定义层绘制，也就是 geojson 的数据来绘制。
> https://l7.antv.vision/zh/examples/point/bubble#point

这个是不能自定义样式的，我这边是想自定义icon，添加一些动效。

**Comment by wanyanyan** [comment]
监听地图的旋转、倾斜事件，根据旋转角度用css同步Marker的形状

**Comment by lzxue** [comment]
目前Marker 是正对屏幕的，不支持平铺

**Comment by lzxue** [comment]
平铺使用 pointlayer
