### ISSUE TITLE
内网隔离环境实现mapbox本地化的问题

### ISSUE THREAD

**Issue by wjcool520** [antvis/L7#579]
* **L7 Version**:2.3.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://codepen.io/wjcool520/pen/RwGrxrE

根据您们提供的L7使用mapbox本地化的demo进行研究编写后，发现source里面的底图无法载入
载入底图的方式采用TMS的瓦片png,采用Tomcat搭建本地服务器后放置其中

因为您们的demo中没有具体的source引用本地底图的案例，所以想了解：
1.source中本地化瓦片图的引用方法
2.TMS瓦片图的编号格式是否和通用的zxy相同
3.如果方便可否提供实例和瓦片资源包

**Comment by yksdjx** [comment]
mapbox-gl 2.0 之后 协议改了会强制调accessToken接口，离线使用话推荐使用V1.13.1
