### ISSUE TITLE
关于L7离线使用的问题

### ISSUE THREAD

**Issue by lujunpeng** [antvis/L7#582]
* **L7 Version**:"^4.0.15"
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

地图服务本地化
1.加载第三方底图，栅格瓦片图层做底图，如天地图，高德，google的栅格瓦片都可以
2.下载opensteetmap 矢量瓦片地图做底图
3.自己业务数据发布底图服务，或者矢量瓦片服务。

这里还有个更完备的解决方案
 https://jingsam.github.io/foxgis-server-lite/#/

官方文档里面离线使用提到的更完备的解决方案，我自己搭了服务但是怎么配合L7进行使用？
现在我只能做到两个分开使用，没办法做到地图联动。

    const map = new window.mapboxgl.Map({
        container: 'map',
        style: 'http://localhost:1234/api/styles/world',
        center: [103.86536517143006, 36.60943236225276],
        zoom: 3.802,
        attributionControl: false,
        hash: false,
    })

      map.addControl(new window.mapboxgl.NavigationControl())
      map.addControl(new window.mapboxgl.FullscreenControl())
      map.addControl(new window.mapboxgl.ScaleControl())

      const scene = new Scene({
        id: 'map',
        map: new Mapbox({
          pitch: 0,
          style: 'blank',
          center: [103.86536517143006, 36.60943236225276],
          zoom: 3.802,
          token: 'xxxx',
        }),

**Comment by wanyanyan** [comment]
只要有离线地图就可以离线使用啊
`
const scene = new Scene({
    id: 'map',
    map: new Mapbox({
      pitch: 0,
      style: 'http://localhost:1234/api/styles/world',
      center: [103.86536517143006, 36.60943236225276],
      zoom: 3.802
    })
`

**Comment by lujunpeng** [comment]
> 只要有离线地图就可以离线使用啊
> 
> ```js
> const scene = new Scene({
>   id: 'map',
>   map: new Mapbox({
>     pitch: 0,
>     style: 'http://localhost:1234/api/styles/world',
>     center: [103.86536517143006, 36.60943236225276],
>     zoom: 3.802
>   })
> })
> ```

试了一下确实可以，谢了

**Comment by thelaurelyy** [comment]
请教离线地图服务是指什么，单纯的地图数据还是需要加载静态资源，比如图片样式等

**Comment by zy135516** [comment]
> > 只要有离线地图就可以离线使用啊
> > ```js
> > const scene = new Scene({
> >   id: 'map',
> >   map: new Mapbox({
> >     pitch: 0,
> >     style: 'http://localhost:1234/api/styles/world',
> >     center: [103.86536517143006, 36.60943236225276],
> >     zoom: 3.802
> >   })
> > })
> > ```
> 
> 试了一下确实可以，谢了

请问这样就直接加载出离线地图了吗？包括样式。我是用此方式会报错mapbox-gl.js:31 GET http://localhost:8080/api/tilesets/admin/tilejson 404 (Not Found)

**Comment by lyyh** [comment]
请问在哪里能下载离线地图样式文件
