### ISSUE TITLE
ol 里面 能使用L7吗？

### ISSUE THREAD

**Issue by lzp0070007** [antvis/L7#586]
openlayers api里面 能使用L7吗？有没有demo？谢谢

**Comment by lzxue** [comment]
目前不支持

**Comment by hawkhu** [comment]
> 目前不支持

打算研究一下OpenLayers适配到L7上面当底图使用，需要关注那些模块？

**Comment by xForMe** [comment]
@lzxue  目前支持openlayer吗？ ，我看2020.12 月份已经关了，是可以了？
