### ISSUE TITLE
有没有提供一个方法主动触发resize事件重新渲染图层

### ISSUE THREAD

**Issue by xiaogaofudao** [antvis/L7#589]
遇到一个Bug。当前页面拖动改变窗口大小可以触发图层重新渲染。但是离开页面进去其他页面，在其他页面改变窗口大小，再返回当前页面，l7 渲染的图层不能自动重新渲染。页面路由切换 vue router + keepalive

**Comment by xiaogaofudao** [comment]
现在是否有，或者提供一个主动触发图层重绘的 方法

**Comment by lzxue** [comment]
重新渲染可以调用render

**Comment by xiaogaofudao** [comment]
@lzxue 重新调用 render 并不能重新适应新窗口，能否暴漏下主动resize方法呢
