### ISSUE TITLE
l7 不兼容vite

### ISSUE THREAD

**Issue by aixinaxc** [antvis/L7#590]
在基于vue3采用vite时，l7会报错导致项目无法启动：
[vite] Dep optimization failed with error:
Could not load assert (imported by node_modules\merge-json-schemas\index.js): ENOENT: no such file or directory, open 'D:\project\vvue3\assert'
[Error: Could not load assert (imported by node_modules\merge-json-schemas\index.js): ENOENT: no such file or directory, open 'D:\project\vvue3\assert']

**Comment by lzxue** [comment]
少安装依赖了吧

**Comment by aixinaxc** [comment]
> 
> 
> 少安装依赖了吧

安装G2和其他包可以正常使用启动，安装完L7就会报哪个错。

**Comment by lzxue** [comment]
看错误是没有这个 assert 依赖

**Comment by gk-shi** [comment]
我在使用 vue 3 + vite 的情况下也碰到类似问题：

```javascript
import { computed, defineComponent, onMounted, ref } from 'vue'
// es6 引入
import { Scene, PointLayer, Popup } from '@antv/l7'
import { GaodeMap } from '@antv/l7-maps'

import { useRouter } from 'vue-router'


// cdn 引入
// const { Scene, PointLayer, Popup, GaodeMap } = L7

export default defineComponent({
  name: 'Travel',
  setup () {
    console.log('scene -- ', Scene)

    return {}
  }
})
```

用第一种 import 方法引入 @antv/l7 的相关模块的时候，会报错说找不到模块，继而致使 vue 的路由无法解析。
但是从 @antv/l7-maps 引入的 GaodeMap 却是可以使用的。

用第二种 cdn 的方式的话，就能正常使用模块的功能了。

**Comment by Beipy** [comment]
同求vite初始化实例报错

**Comment by yzStrive** [comment]
> 同求vite初始化实例报错

使用 `@antv/l7/lib/index` / `@antv/l7-maps/lib/index`

**Comment by Beipy** [comment]
> > 同求vite初始化实例报错
> 
> 使用 `@antv/l7/lib/index` / `@antv/l7-maps/lib/index`

打包后地图页面无法打开。也不报错

**Comment by lzxue** [comment]
vite 问题解决安装最新版本 2.5.8， 示例可以参照 https://github.com/lc06/vite_antv-L7 ，有的用户反馈vite.confg不需要配置 swc 也可以。

**Comment by candy-Tong** [comment]
### 

> 参照 https://github.com/lc06/vite_antv-L7 ，有的用户反馈vite.confg不需要配置 swc 也可以。

这个例子，试了一下，已经是 build 不成功了的，报错如下：
![image](https://user-images.githubusercontent.com/20377280/144693391-7f51a4eb-37cb-4c2c-a4c0-443848231093.png)
