### ISSUE TITLE
行政区划地图开启label后与文本标注发送冲突，导致文字显示错误

### ISSUE THREAD

**Issue by wckgo** [antvis/L7#591]
* **L7 Version**: "@antv/l7": "^2.3.1", "@antv/l7-district": "^2.2.46",
* **Platform**: chrome
* **Mini Showcase(like screenshots)**:
![图片](https://user-images.githubusercontent.com/33270942/102034700-aa679c00-3df9-11eb-9109-00707c7c87d4.png)
* **CodePen Link**:

行政区划地图开启label，且设置文本标注的fontWeight，就会发送冲突，导致文字显示错误

**Comment by 2912401452** [comment]
推荐使用 L7Plot
https://l7plot.antv.vision/
