### ISSUE TITLE
Pylogon绘制后缩放导致图层坐标偏移

### ISSUE THREAD

**Issue by q127981** [antvis/L7#592]
如图：默认绘制出来的样子
![图片](https://user-images.githubusercontent.com/31874319/102058291-40b3b600-3e2a-11eb-8d6e-20711793b485.png)

当改变鼠标滚动改变缩放视图后，覆盖多边形位置发生了偏移。如何才能不管怎么缩放，都不偏移？
![图片](https://user-images.githubusercontent.com/31874319/102058441-75277200-3e2a-11eb-960b-31dd5003521f.png)
![图片](https://user-images.githubusercontent.com/31874319/102058463-7ce71680-3e2a-11eb-9507-500cd0b2d29c.png)

**Comment by lzxue** [comment]
能不能提供一个复现demo

**Comment by q127981** [comment]
感谢您的关注，demo已发送附件





guanzhiqiang@aliyun.com
 
发件人： @thinkinggis
发送时间： 2020-12-15 10:01
收件人： antvis/L7
抄送： q127981; Author
主题： Re: [antvis/L7] Pylogon绘制后缩放导致图层坐标偏移 (#592)
能不能提供一个复现demo

**Comment by q127981** [comment]
[](url)

**Comment by q127981** [comment]
怎么close了  我点错了么。。。
