### ISSUE TITLE
Pylogon绘制后缩放导致图层坐标偏移

### ISSUE THREAD

**Issue by q127981** [antvis/L7#594]
之前点错了  close了。 
原地址：https://github.com/antvis/L7/issues/592

复现的demo 链接: https://pan.baidu.com/s/1tqya589__e5cbUsCQyITkw 提取码: w8vt 

@lzxue

**Comment by dai-siki** [comment]
我也是偏移，还挺大的
![image](https://user-images.githubusercontent.com/18674462/180941813-2c9d80bb-6cab-4b43-8a30-a839c544e504.png)

**Comment by dai-siki** [comment]
画的图层直接偏到地图外面去了
![image](https://user-images.githubusercontent.com/18674462/180942274-8d5b6cb0-7854-4aa4-b251-c505222e0c62.png)

**Comment by dai-siki** [comment]
sorry,我这个问题，是因为地图根元素加了padding导致的，去掉就好了

**Comment by lvisei** [comment]
fixed https://github.com/antvis/L7/pull/2416
