### ISSUE TITLE
气泡图中使用updateData方法的时候报错

### ISSUE THREAD

**Issue by xiaoyuan-fe** [antvis/L7#596]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/27466516/102314960-489c6300-3fae-11eb-9528-b53072ac3595.png)

**Comment by xiaoyuan-fe** [comment]
"@antv/l7": "^2.3.1",
    "@antv/l7-district": "^2.2.46",

**Comment by lxfu1** [comment]
@xiaoyuan-fe 这个什么时候可以修复？

**Comment by lxfu1** [comment]
@lzxue 这个什么时候可以修复？

**Comment by yanyu510** [comment]
layer.updateData(ProvinceData2) 改成下面写法试试
layer.on('loaded', e=> {
          layer.updateData(ProvinceData2)
      })

**Comment by 2912401452** [comment]
推荐换成 L7Plot
https://l7plot.antv.vision/zh/docs/api/plots/choropleth
