### ISSUE TITLE
怎么样配置可以不显示南海？

### ISSUE THREAD

**Issue by xiaoyuan-fe** [antvis/L7#598]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by xiaoyuan-fe** [comment]
显示附图就可以

**Comment by lzxue** [comment]
南海是数据驱动显示的，不支持关闭

**Comment by drafish** [comment]
我也有这个需求诶

**Comment by linlinNB** [comment]
所以大佬们，没有显示附图的选项是吗？ @xiaoyuan-fe @drafish
