### ISSUE TITLE
DrillDownLayer配置joinBy:['NAME_CHN', "name"]为什么数据在popup里面Html获取props.value是undefined

### ISSUE THREAD

**Issue by MrArky** [antvis/L7#599]
`
import { MapboxScene } from "@antv/l7-react";
import { DrillDownLayer } from '@antv/l7-district';
const SceneView: React.FC = () => {

     // const mian = useRef(null);
    const [provinceData, setProvinceData] = useState([
        {
            name: '湖南省',
            code: 430000,
            value: 36425.78
        },
        {
            name: '江西省',
            code: 360000,
            value: 21984.78
        },
        {
            name: '四川省',
            code: 510000,
            value: 40678.13
        },
    ]);
    return <MapboxScene
        map={{
            center: [116.2825, 39.9],
            pitch: 1,
            style: 'blank',
            zoom: 3,
            minZoom: 0,
            maxZoom: 10
        }}
        onSceneLoaded={(scene) => {
            new DrillDownLayer(scene, {
                provinceData: provinceData,
                cityData: [
                    // {
                    //     name: '郫都区',
                    //     value: 17881.12
                    // },
                ],
                countyData: [],
                // viewStart: 'Country',
                // viewEnd: 'City',
                joinBy: ['NAME_CHN', "name"],
                depth: 0,
                fill: {
                    color: {
                        field: 'value',
                        values: (args)=>{
                            return ['#fee5d9', '#fcae91', '#fb6a4a', '#de2d26', '#a50f15']
                        }
                    },
                    style: {
                        opacity: 1
                    }
                },
                province: {
                    joinBy: ['NAME_CHN', "name"],
                },
                popup: {
                    enable: true,
                    Html: props => {
                        console.log(props);
                        return `<span>${props.NAME_CHN}:</span><span>${props.value ? props.value : 0}</span>`;
                    }
                },
            });
        }}
        children={
            <>
                <div style={{ padding: "24px 0 0 24px", color: "rgba(0, 0, 0, 0.45)" }}>
                    入员分布情况
                </div>
            </>
        }
    />
}
`

**Comment by lwrench** [comment]
hello 请问你解决了吗

**Comment by MrArky** [comment]
> hello 请问你解决了吗

popup: {
                    enable: true,
                    Html: props => {
                        let num: any = data?.filter(i => i.province == props.NAME_CHN || i.city == props.NAME_CHN || i.county == props.NAME_CHN).map(i => i.users.length).reduce((x, y) => x + y, 0);
                        return `<span>${props.NAME_CHN}:</span><span>${num}</span>`;
                    }
                },
这个办法虽然蠢了一点，不过可以暂时解决问题。但是如果出现有名字相同的市或者县，就比较尴尬。

**Comment by lwrench** [comment]
感谢

**Comment by MrArky** [comment]
> 改provinceData，cityData，countyData 为 ProvinceData，CityData，CountyData 即可

靠谱

**Comment by MrArky** [comment]
> > 改provinceData，cityData，countyData 为 ProvinceData，CityData，CountyData 即可
> 
> 靠谱

已经试过了，可行，在此关闭。
