### ISSUE TITLE
现在有正式版了吗

### ISSUE THREAD

**Issue by llsshh1985** [antvis/L7#6]
请问现在L7有正式版了吗？试用修改了几个在线的例子，发现文档不太好用。Scene方法中的getLayers()和getLayers到底有什么区别，用removeLayer方法移除getLayers()获取的Layer图层没有移除掉。目前也没有类似clear的方法。

比起G2，我可以把L7放入自己的项目中吗？还是还能当玩具玩玩，等正式版发布？

**Comment by lzxue** [comment]
npm 版本一直再更新，可以更新使用，一些bug已经修复了。可以把L7放在自己的项目中使用，同时遇到问题，欢迎提issue我们会及时修复。
