### ISSUE TITLE
能不能完善一下官网的文档？

### ISSUE THREAD

**Issue by sjmlsxp** [antvis/L7#600]
官网文档太多语焉不详的地方，真的很难猜。
比如
> 视觉编码方法
可视化编码是将数据转换为可视形式的过程，L7 目前支持形状，大小，颜色 3 种视觉通道，你可以指定数据字段，为不同要素设置不同的图形属性。

size(value） 传入数字常量，如  pointLayer.size(20)

这里的常量20是指宽20px吗？ 可不可以指定高呢？

不仅如此，还有很多404……
有点难用啊

**Comment by lzxue** [comment]
404 的欢迎指出会尽快修复

**Comment by sjmlsxp** [comment]
404非常多，指不尽啊
你们自己翻一翻啊

**Comment by yqcs** [comment]
为什么我npm install @antv/l7安装的是2.3.5版本的，也就是1系列的。而官网都是2系列了。。。怎么安装2系...
