### ISSUE TITLE
DrillDownLayer fill 颜色不对

### ISSUE THREAD

**Issue by wangjunhong** [antvis/L7#601]
我自定义了颜色，但是颜色都是错的，怎么才能根据我设置的颜色来设置地图颜色
![image](https://user-images.githubusercontent.com/19639929/102569749-ff205500-4120-11eb-91f2-239ce858abd6.png)

**Comment by lzxue** [comment]
颜色怎么配置的？代码贴全一点？

**Comment by wangjunhong** [comment]
![微信图片_20201221154805](https://user-images.githubusercontent.com/19639929/102752107-02774300-43a4-11eb-8146-b50c73bc59a5.png)
上传传图片没成功，如果我设置了一种颜色是对的，如果是多种就不对

**Comment by wangjunhong** [comment]
案例地址  https://antv-l7.gitee.io/zh/examples/district/drill#drill_down_province
描述 第四行 colors 第一个改成#0f0,但是取色结果是#4EFB05

**Comment by chengchao1** [comment]
设置的颜色透明度会变（比如：设置颜色为白色，会变成灰色），这个bug啥时间解决啊

**Comment by chengchao1** [comment]
![image](https://user-images.githubusercontent.com/13247228/106767397-c8bd7b80-6675-11eb-93e2-e5cb9e2599f8.png)
可以这样重现

**Comment by liuvigongzuoshi** [comment]
**建议使用新版[行政区域 ](https://l7.antv.vision/zh/docs/api/district/start)，使用[案例](https://l7.antv.vision/zh/examples/choropleth/drill#order-drill)**

### 使用方式

1. 按图表方式

```js
import { Choropleth } from '@antv/l7plot';

const choropleth = new Choropleth('container', options);
```

2. 按场景方式

```js
import { Scene, Mapbox } from '@antv/l7';
import { Choropleth } from '@antv/l7plot';

const scene = new Scene({
  id: 'container',
  map: new Mapbox({
    style: 'light',
    center: [102.447303, 37.753574],
    zoom: 5,
  }),
});

const choropleth = new Choropleth(options);

scene.on('loaded', () => {
  choropleth.addToScene(scene);
});
```

### API

Choropleth 具体 API 文档移步 [L7Plot 官网](https://l7plot.antv.vision/zh/docs/api/plots/choropleth)。
