### ISSUE TITLE
mapbox的center配置无效

### ISSUE THREAD

**Issue by drafish** [antvis/L7#603]
我想只展示中国地图，不展示南海。但这好像不行，我看 @xiaoyuan-fe 同学已经提了[issue](https://github.com/antvis/L7/issues/598)。

所以我想退而求其次，把地图放大点，通过调整地图中心点把南海遮盖掉。但是center配置又不生效。我看了官网给的[demo](https://l7.antv.vision/zh/examples/district/basic#china_map_2)，直接改demo中的center配置也是不生效的。

**Comment by lzxue** [comment]
关闭autofit

**Comment by drafish** [comment]
> 关闭autofit

亲测有效，感谢大佬，问题完美解决👍

**Comment by luoxiao-supermap** [comment]
遇到同样的问题， 请问autofit是怎么配置的
