### ISSUE TITLE
使用高德地图做地图，报错，提示map.setContainer is not a function

### ISSUE THREAD

**Issue by lvhaiboimufe** [antvis/L7#605]
地图可以正确现实出来，但是控制台会报错

![微信截图_20201223105557](https://user-images.githubusercontent.com/46703271/102954040-9ca6ca80-450d-11eb-9677-3b49e9e82b21.png)
![微信截图_20201223105731](https://user-images.githubusercontent.com/46703271/102954044-9fa1bb00-450d-11eb-881d-b3ccaf6ebdef.png)
![微信截图_20201223105628](https://user-images.githubusercontent.com/46703271/102954045-a03a5180-450d-11eb-836a-1279a95a691f.png)
![微信截图_20201223105652](https://user-images.githubusercontent.com/46703271/102954046-a0d2e800-450d-11eb-8616-2bb296b7c125.png)
![微信截图_20201223105723](https://user-images.githubusercontent.com/46703271/102954048-a16b7e80-450d-11eb-90e2-b2bc3d9b8c0b.png)

**Comment by cherislive** [comment]
> 为了统一不同底图之前的接口差异 L7 在 scene 层对 map 的方法做了统一，因此一些地图的操作方法可以通过 scene 调用这样，切换不同底图时保证表现一致。

这里已经不能用高德的API了，不晓得暴露这个map有何用，啥都干不了！！！

![image](https://user-images.githubusercontent.com/7383097/103840291-305ec600-50cc-11eb-89e5-113354d3fb82.png)

**Comment by ParryQiu** [comment]
一些其他地图引擎，如 mapbox，获取到 map 对象的意义还是很大的。
