### ISSUE TITLE
IE11下，layer图层的click事件，获取的事件对象中的地图对象和实际区域对应不上，存在偏移

### ISSUE THREAD

**Issue by creed36** [antvis/L7#606]
* **L7 Version**:2.3.3
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

使用 PolygonLayer创建图层，并添加click事件监听，想在监听中获取地图区域信息，用的是demo里的世界地图数据，chrome下能准确获取鼠标点击位置的国家元素，ie11有严重的偏移，无法正常获取对应位置的国家信息。
this.SceneObj = new Scene({
        id: 'mapBox',
        logoVisible: false,
        preserveDrawingBuffer: false,
        map: new Mapbox({
          pitch: 0,
          style: 'blank',
          center: [13.441, 53.618],
          zoom: 1.1499683683569812
        })
      });
const layer = new PolygonLayer({
          autoFit: true
        })
        .source(worldMapData)
        .scale('midTotal', {
          type: 'quantile'
        })
        .color('midTotal', (midTotal) => {
          console.log('midTotal', midTotal)
          // 通过回调函数
          if (midTotal > 50) {
            return '#0050B3';
          } else if (midTotal > 0) {
            return '#69C0FF';
          } else {
            return '#E5E9F7';
          }
        })
        .shape('fill')
        .style({
          opacity: 0.9
        }).select(true);
layer.on('click', ev => {
        console.log('mousedown', ev.feature)
        let itemData = ev.feature.properties}）

**Comment by lzxue** [comment]
这个问题记得已经修复了
