### ISSUE TITLE
CountryLayer 怎么隐藏label 啊，我调用了updateLayerAttribute 方法，报错了，也不起作用。还有basicLayer 中的setOption 也不起作用呀

### ISSUE THREAD

**Issue by guizhichao** [antvis/L7#609]
![image](https://user-images.githubusercontent.com/24600605/103334853-eebb9300-4aad-11eb-9e06-ff8bec54456e.png)

    countryMap.updateLayerAttribute('label', 'color', 'red')
    const options = countryMap.getOptions();
    options.label.opacity = 0;
    countryMap.setOption(options)
    const labelLayer = countryMap.getLayer('label');
    labelLayer.hide();
这些也不起作用呢，求救呀

**Comment by 2912401452** [comment]
获取到 Layer 后使用 layer.hide() 方法
