### ISSUE TITLE
layer在updateData的时候是否应该触发init函数

### ISSUE THREAD

**Issue by Qinmei** [antvis/L7#619]
当我的数据量很大的时候，比如说50M，这个时候每次更新数据都要先下载然后再加载，为了用户友好，需要加一些loading的提示，但是从代码来看，init函数似乎只在第一次加载的时候触发， 后续的更新都不触发，那就无法精准判断是否layer绘制完成，目前只能销毁重建，但是这个开销就有点大了

个人觉得对于大量数据的图表还是多加一些回调函数来方便外部了解加载的情况

https://github.com/antvis/L7/blob/899fb397b08b5775292cd4b81c70cb8b1759e926/packages/layers/src/core/BaseLayer.ts#L451

**Comment by lzxue** [comment]
如果数据量大可以考虑，重新创建图层
