### ISSUE TITLE
animate能和color或者size一样根据数值来调整参数吗

### ISSUE THREAD

**Issue by yeastone** [antvis/L7#624]

**Comment by 2912401452** [comment]
可以的
[https://l7.antv.vision/zh/examples/gallery/animate#world](url)

**Comment by xiezzz** [comment]
链接失效 没找到设置方法

**Comment by xiezzz** [comment]
> 可以的 [https://l7.antv.vision/zh/examples/gallery/animate#world](url)

链接失效 没找到设置的api
