### ISSUE TITLE
使用高德自定义地图样式不起作用

### ISSUE THREAD

**Issue by DZTZ** [antvis/L7#625]
map: new GaodeMap({
        center: [121.757628, 31.111472],
        pitch: 0,
        // style: "dark",
        // style: "amap://styles/darkblue",
        style: "amap://styles/aac3249a3a642031f993e55a0723d630", //我的高德自定义样式的id
        zoom: 8.5,
      }),

请问改如何正确的设置？

**Comment by DZTZ** [comment]
已解决，需要加入 高德地图的 key 
 map: new GaodeMap({
        center: [121.757628, 31.111472],
        pitch: 0,
        style: "amap://styles/aac3249a3a642031f993e55a0723d630",
        zoom: 8.5,
        type: "amap", // 这个type = amap 也叫 加上  
        token: "xxxx你的keyxxx" // 这里加入 高德地图的key
      }),

**Comment by yangruoxu** [comment]
> 
> 
> 已解决，需要加入 高德地图的 key
> map: new GaodeMap({
> center: [121.757628, 31.111472],
> pitch: 0,
> style: "amap://styles/aac3249a3a642031f993e55a0723d630",
> zoom: 8.5,
> type: "amap", // 这个type = amap 也要 加上
> token: "xxxx你的keyxxx" // 这里加入 高德地图的key
> }),

你是在js上面吗？我在js上遇到了同样的问题，加入token以后依旧没办法解决

**Comment by DZTZ** [comment]
> > 已解决，需要加入 高德地图的 key
> > map: new GaodeMap({
> > center: [121.757628, 31.111472],
> > pitch: 0,
> > style: "amap://styles/aac3249a3a642031f993e55a0723d630",
> > zoom: 8.5,
> > type: "amap", // 这个type = amap 也要 加上
> > token: "xxxx你的keyxxx" // 这里加入 高德地图的key
> > }),
> 
> 你是在js上面吗？我在js上遇到了同样的问题，加入token以后依旧没办法解决

你的 key 可能申请错了
![image](https://user-images.githubusercontent.com/46846745/106561338-7429db80-6563-11eb-9059-7d0f95befdf5.png)
