### ISSUE TITLE
L7地图设置为style: 'dark'时，加载地图时会有一段时间的闪白，才能渲染出黑色版地图

### ISSUE THREAD

**Issue by EricHan0723** [antvis/L7#626]
请问这个问题有可以解决的方法吗？刚开始加载时的一瞬间闪白问题

**Comment by wxfqf** [comment]
高德地图的问题吧，可以用css解决 .amap-maps { background: rgb(30, 42, 76) !important;}

**Comment by wxfqf** [comment]
> 请问这个问题有可以解决的方法吗？刚开始加载时的一瞬间闪白问题

高德地图的问题吧，可以用css解决 .amap-maps { background: rgb(30, 42, 76) !important;}

**Comment by EricHan0723** [comment]
好的，感谢，可以了
