### ISSUE TITLE
行政区域中，怎样选择坐标系，现在mapbox下使用的应该是高德的坐标系，区域填充的不准确。

### ISSUE THREAD

**Issue by jiaicon** [antvis/L7#630]
应该是坐标系不同导致数据位置不准确，可不可以排查下

**Comment by 2912401452** [comment]
行政区划现在默认使用的数据是高德的数据，目前还没有提供 mapbox 坐标下的数据，可以自己指定更新数据
[https://github.com/antvis/L7-boundary](url)
![image](https://user-images.githubusercontent.com/42212176/147028753-130e8c53-4559-4fcd-b5ef-7f43d8948182.png)
