### ISSUE TITLE
地图的高度是怎么定的啊？

### ISSUE THREAD

**Issue by sym233** [antvis/L7#637]
想把地图塞到antd layout content里面
地图外面用div height 100%包一层
地图的canvas只有一半高
地图容器确实有height 100%，antv logo也在该在的左下角
但是怎么让地图canvas填满content
除了用css设置高度为px还能怎么解决

截图
![image](https://user-images.githubusercontent.com/10321547/106916000-a85af300-6741-11eb-843c-ebb4321ad472.png)

codesandbox https://codesandbox.io/s/silly-jang-16rik

"@antv/l7": "^2.3.7",
"@antv/l7-maps": "^2.3.7",
"@antv/l7-react": "^2.3.0",

**Comment by lzxue** [comment]
可以设置成 100VH
