### ISSUE TITLE
2.3.2 - 2.3.7 版本不支持 IE 11，需要将版本降低到 2.2.12 才兼容 IE 11

### ISSUE THREAD

**Issue by qkr-noone** [antvis/L7#643]
* **L7 Version**: 2.3.2-2.3.7
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

在项目中的依赖包@antv/l7  2.3.2 - 2.3.7 版本下，查看编译生成的 dist 文件，存在箭头函数 "=>"；将版本降低到 2.2.12 后，dist文件的 l7.js 不存在箭头函数 "=>" 兼容 IE11。
l7 下有多个依赖包，依赖包也需要将版本降低到 2.2.12。
如果仅仅 "@antv/l7": "2.2.12"，l7 的相关依赖包不是2.2.12；
则可以将依赖包 锁住
"@antv/l7": "2.2.12",
    "@antv/l7-component": "2.2.12",
    "@antv/l7-core": "2.2.12",
    "@antv/l7-district": "2.2.12",
    "@antv/l7-layers": "2.2.12",
    "@antv/l7-maps": "2.2.12",
    "@antv/l7-react": "2.2.12",
    "@antv/l7-renderer": "2.2.12",
    "@antv/l7-scene": "2.2.12",
    "@antv/l7-source": "2.2.12",
(package-lock 记得清除对应的高版本下载地址)

**Comment by lzxue** [comment]
检查一下最新版本的是不纯在 箭头函数的
