### ISSUE TITLE
l7-react CustomControl组件销毁报错

### ISSUE THREAD

**Issue by wisdomsuper** [antvis/L7#647]
- [x] I have searched the [issues](https://github.com/antvis/l7/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angry-mayer-5h3b0)

### Steps to reproduce
打开重现链接，点击按钮“点我消失”，页面报错

| Environment | Info |
|---|---|
| l7 | 2.3.9 |
| System | - |
| Browser | - |

---
CustomControl 只覆盖了Control.onAdd，没有复写Control.onRemove导致

**Comment by lzxue** [comment]
多谢指出问题 可以多提PR  https://github.com/antvis/L7-React

**Comment by 2912401452** [comment]
问题已经在 "@antv/l7-react": "^2.3.2" 版本修复
