### ISSUE TITLE
技术支持服务群，钉钉扫码，显示群二维码过期了

### ISSUE THREAD

**Issue by tobemaster56** [antvis/L7#648]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

https://antv-l7.gitee.io/zh/docs/api/l7#%E6%8A%80%E6%9C%AF%E6%94%AF%E6%8C%81%E6%9C%8D%E5%8A%A1%E7%BE%A4，技术支持服务群，钉钉扫码，显示群二维码过期了

**Comment by lzxue** [comment]
搜索群号加入：30460926
