### ISSUE TITLE
pointLayer 点击事件不友好，基本处于不起作用状态

### ISSUE THREAD

**Issue by liujingjingg** [antvis/L7#650]
![image](https://user-images.githubusercontent.com/33412221/110587108-2af62880-81ae-11eb-80e9-4c1a14d37241.png)

点击不灵敏，水波纹形态下似乎只有点击到水波纹才会执行click 动作
active 方法同上，高亮并不灵敏。
部分代码如下：

const scene = new Scene({
id: 'map',
map: new GaodeMap({
pitch: 0,
style: mode === 'inner' ? '' : 'dark',
center: [105, 30],
zoom: 3.8,
}),
logoVisible: false,
});
const pointLayer = new PointLayer({})
.source(newData, {
parser: {
type: 'json',
x: 'x',
y: 'y',
},
})
.shape('circle')
.active(true)
.select(true)
.animate(true)
.size('value', (value) => {
return getMapConfValue(otherParams, 'size', value);
})
.color('value', (value) => {
return getMapConfValue(otherParams, 'color', value);
})
.style({
opacity: 0.5,
strokeWidth: 0,
}).on('click', (ev) => {
console.log('map')
})
scene.addLayer(pointLayer);

**Comment by lzxue** [comment]
可以关注看一下，动画情况的拾取 @2912401452
