### ISSUE TITLE
按照官方文档操作出现致命级别bug

### ISSUE THREAD

**Issue by lvqi0724** [antvis/L7#653]
1. npm i @antv/l7-react
2. import { LineLayer, AMapScene } from '@antv/l7-react';
3. Module not found: Can't resolve '@antv/l7' in 'C:\Users\Admin\Desktop\ReactVideo\my-app\node_modules\@antv\l7- 
   react\es\component'

**Comment by lvqi0724** [comment]
官方人呢  呜呜  都没人维护了  呜呜呜 怪不得有bug 呜呜呜

**Comment by lzxue** [comment]
没有安装L7

遂宁刘德华 ***@***.***> 于2021年3月29日周一 下午10:11写道：
