### ISSUE TITLE
LineLayer arc3d 现在支持起点终点相反的两条数据，绘制成两条线吗。以后会支持吗

### ISSUE THREAD

**Issue by guonanci** [antvis/L7#656]
我稍微看了看LineLayer arc3d的绘制源码，看不太懂，请问现在支持绘制成弧度不同的两条线吗。2d呢

可以复现：
https://l7.antv.vision/zh/examples/gallery/animate#world2
修改一下Demo，在第40行（几行注释上方）添加如下代码：
```js
const reverse1 = {coord: [flydata[0].coord[1],flydata[0].coord[0]]}
flydata.length=5
flydata.push(reverse1)
console.log(flydata)
  ```
有6条数据却只显示5条线（数组第一项和最后一项起点终点相反）。

* **L7 Version**:2.3.9
* **Platform**:MacOS11.2.3
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lzxue** [comment]
会考虑做个新feature实现，弧线区别不同方向

**Comment by lzxue** [comment]
3D  弧线无法区分方向的，2D 的是可以的
