### ISSUE TITLE
选中Mapbox图层后，外层有一圈蓝色的选中标示，请问这个可以去除吗

### ISSUE THREAD

**Issue by CrazyGriferman** [antvis/L7#657]
如图所示，请问这个外面的蓝边有办法去除吗？
![image](https://user-images.githubusercontent.com/51702723/111990635-68fc3080-8b4e-11eb-9779-fae0504dfc5b.png)

**Comment by lzxue** [comment]
这个蓝边可也通过CSS样式去重
