### ISSUE TITLE
vite2.0 运行 build 命令打包后，L7 出现 require is not defined 错误

### ISSUE THREAD

**Issue by moxuanluo** [antvis/L7#659]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

使用的L7 版本为2.3.9，vite版本为2.0.0 
参照官方文档引入 L7后，本地运行没有问题，但是打包上线后，出现 require is not defined 的问题。
打包后的js中出现 require("load-styles") 
打包配置的使用的是默认的配置，

请问需要如何修改？

**Comment by Ynewtime** [comment]
参考: https://www.jianshu.com/p/b000b18c42da

**Comment by Ynewtime** [comment]
上面方案适用于 Snowpack，针对 Vite2，可以通过修改 index.html 规避：

```html
<body>
  <div id="root"></div>
  <script>
    function require() {
      return function (css) {
        var style = document.createElement('style')
        style.appendChild(document.createTextNode(css))
        document.head.appendChild(style)
      }
    }
  </script>
  <script type="module" src="/src/main.tsx"></script>
</body>
```

**Comment by dinfer** [comment]
可以解决, 但是在只用PolygonLayer加载图层的时候还是报错.

vendor.b9ca2b22.js:formatted:80382 Uncaught (in promise) Error: No matching bindings found for serviceIdentifier: Symbol(ILayerPlugin)

![image](https://user-images.githubusercontent.com/11496403/117791128-92972580-b27c-11eb-8d4b-0ca6c40b2b5a.png)

**Comment by lzxue** [comment]
是否可也提供个在线的项目模板

**Comment by lzxue** [comment]
> 可以解决, 但是在只用PolygonLayer加载图层的时候还是报错.
> 
> vendor.b9ca2b22.js:formatted:80382 Uncaught (in promise) Error: No matching bindings found for serviceIdentifier: Symbol(ILayerPlugin)
> 
> ![image](https://user-images.githubusercontent.com/11496403/117791128-92972580-b27c-11eb-8d4b-0ca6c40b2b5a.png)

可以尝试直接全局引用CDN 版本的

**Comment by dinfer** [comment]
> > 可以解决, 但是在只用PolygonLayer加载图层的时候还是报错.
> > vendor.b9ca2b22.js:formatted:80382 Uncaught (in promise) Error: No matching bindings found for serviceIdentifier: Symbol(ILayerPlugin)
> > ![image](https://user-images.githubusercontent.com/11496403/117791128-92972580-b27c-11eb-8d4b-0ca6c40b2b5a.png)
> 
> 可以尝试直接全局引用CDN 版本的

谢谢, 有尝试过, 问题出现在打包模式上.如果使用script module, 没法从global获取L7对象

**Comment by lzxue** [comment]
vite 问题解决安装最新版本 2.5.8， 示例可以参照 https://github.com/lc06/vite_antv-L7 ，有的用户反馈vite.confg不需要配置 swc 也可以。

**Comment by lzxue** [comment]
> 上面方案适用于 Snowpack，针对 Vite2，可以通过修改 index.html 规避：
> 
> ```
> <body>
>   <div id="root"></div>
>   <script>
>     function require() {
>       return function (css) {
>         var style = document.createElement('style')
>         style.appendChild(document.createTextNode(css))
>         document.head.appendChild(style)
>       }
>     }
>   </script>
>   <script type="module" src="/src/main.tsx"></script>
> </body>
> ```

snowpack 打包问题已解决，2.5.8版本
