### ISSUE TITLE
No English Instructions

### ISSUE THREAD

**Issue by brettforbes** [antvis/L7#660]
I really like the capability of your software, but unfortunately using it carries too much risk as there are no instructions in English. I wish you had English documentation for all of your packages

In general, packages written in another language need an English copy of the manual and api defintions, or the package is only usable by those who can speak the language. Your package looks really great, but it is unusable by >half of the worlds population, since there is no English translation

You should put in the very small effort required to translate your manuals into English. Seriously, this is mostly automated so it should be very easy.

Instead you have a great product that is completely unusable, how sad!!!!
Great looking product, completely useless documentation

**Comment by 2912401452** [comment]
we will provide it as soon as possible!
