### ISSUE TITLE
如何在mapbox地图实例上，LineLayer设置了高度后，缩放地图，线条并不会拉伸保持原有设定的距离。

### ISSUE THREAD

**Issue by vanness30214** [antvis/L7#661]
[地址](https://l7.antv.vision/zh/examples/gallery/basic#bus_dark)
如何在mapbox地图实例上，LineLayer设置了高度后，缩放地图，线条并不会拉伸保持原有设定的距离。

在GaodeMap地图实例上并不会出现设置高度后，缩放地图，线条高度随地图缩放而拉伸高度
* **L7 Version**:2.3.9
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by vanness30214** [comment]
//GaodeMap  并不会拉伸高度

import { Scene, LineLayer } from '@antv/l7';
import { GaodeMap  } from '@antv/l7-maps';

const scene = new Scene({
  id: 'map',
  map: new GaodeMap ({
    center: [ 116.3956, 39.9392 ],
    pitch: 0,
    zoom: 10,
    rotation: 0,
    style: 'dark'
  })
});
scene.on('loaded', () => {
  fetch(
    'https://gw.alipayobjects.com/os/basement_prod/0d2f0113-f48b-4db9-8adc-a3937243d5a3.json'
  )
    .then(res => res.json())
    .then(data => {
      const layer = new LineLayer({})
        .source(data)
        .size([1.5,300000])
        .shape('line')
        .color('标准名称', [ '#5B8FF9', '#5CCEA1', '#F6BD16' ]);
      scene.addLayer(layer);
    });
});

**Comment by vanness30214** [comment]
//Mapbox 会随缩放拉伸高度，不能保持原有设定固定高度
import { Scene, LineLayer } from '@antv/l7';
import { Mapbox } from '@antv/l7-maps';

const scene = new Scene({
  id: 'map',
  map: new Mapbox({
    center: [ 116.3956, 39.9392 ],
    pitch: 0,
    zoom: 10,
    rotation: 0,
    style: 'dark'
  })
});
scene.on('loaded', () => {
  fetch(
    'https://gw.alipayobjects.com/os/basement_prod/0d2f0113-f48b-4db9-8adc-a3937243d5a3.json'
  )
    .then(res => res.json())
    .then(data => {
      const layer = new LineLayer({})
        .source(data)
        .size([1.5,60])
        .shape('line')
        .color('标准名称', [ '#5B8FF9', '#5CCEA1', '#F6BD16' ]);
      scene.addLayer(layer);
    });
});

**Comment by lzxue** [comment]
你是想要和高德地图一样的效果吗？

**Comment by vanness30214** [comment]
是的

**Comment by vanness30214** [comment]
> 你是想要和高德地图一样的效果吗？

是的

**Comment by 2912401452** [comment]
在 L7 2.5 版本中将会修复
