### ISSUE TITLE
地图块PolygonLayer高亮的时候，能否联动周围的LineLayer高亮？目前地图块高亮的时候，周围的边框线没有高亮

### ISSUE THREAD

**Issue by lumia2046** [antvis/L7#663]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lzxue** [comment]
目前默认的active 高亮只能修改颜色，线高亮需要新增一个图层处理高亮
