### ISSUE TITLE
请问L7，是基于mapbox.js 哪个版本做的？

### ISSUE THREAD

**Issue by q77322708** [antvis/L7#667]
最新的mapbox的版本好像是2.3版本。
请问，L7是基于mapbox哪个版本号的？

**Comment by 2912401452** [comment]
1.2.1

**Comment by ShareQiu1994** [comment]
@2912401452  未来是否计划采用mapbox 2.x + ? mapbox改动挺多，加入了很多新特性  mapboxgl主流已经转向mapbox2.x +
