### ISSUE TITLE
关于new PolygonLayer().source(data) 问题求助

### ISSUE THREAD

**Issue by TabCrazy** [antvis/L7#668]
* **L7 Version**: 2.x
* **Platform**: 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codesandbox.io/s/clever-rhodes-d2t7t?file=/index.js

官方提供是示例：3D填充图
https://l7.antv.vision/zh/examples/polygon/3d#polygon

其中只有深圳地区，有3D建筑物。
如果我需要全国地区有3D建筑物，有2个问题麻烦请教下？
1、new PolygonLayer().source(data)，中的data数据，如何 生成 或 哪里可以找到已经生成好的 全国3D建筑物数据？
2、全国渲染3D建筑物的情况下，是否会卡顿比较严重，解决卡顿是否有好的指导意见？

打扰各位大神们了，希望能有大神能给出一些指导意见。非常感谢！

**Comment by 2912401452** [comment]
1、目前还没有官方提供数据的入口，只能自己提供
2、同时渲染全国范围的数据造成卡顿的情况暂时没有办法解决
