### ISSUE TITLE
官方文档关于钻取地图 DrillDownLayer 的 drillUp 使用方法有错误

### ISSUE THREAD

**Issue by changexbc** [antvis/L7#677]
* **L7 Version**:2.3.10
* **Platform**: macOS 10.15.2
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

在[官方文档](https://antv-l7.gitee.io/zh/docs/api/district/drilldown#drilldown) 中介绍的`drillUp`的使用方法为 `drillLayer.drillUp(['110100'])`，源码中实际`drillUp`方法只能传递 `Province` `Country` `Region`字符串。

![image](https://user-images.githubusercontent.com/8199684/117428117-57cd7e80-af58-11eb-8ba9-8c53824bd0e8.png)

![image](https://user-images.githubusercontent.com/8199684/117428208-6fa50280-af58-11eb-8984-d2344c62b3cb.png)

**Comment by lzxue** [comment]
最新版本已修复
