### ISSUE TITLE
视角变化是否能添加过度动画

### ISSUE THREAD

**Issue by coloz** [antvis/L7#678]
使用setRotation、setPitch会直接变到指定角度，没有动画效果，显得太突兀的，希望能添加动画，可以参考maptalks的api，添加一个animateTo的方法。

**Comment by coloz** [comment]
https://maptalks.org/examples/en/animation/map-flyto/

**Comment by lzxue** [comment]
有mapbox 底图是有的

**Comment by coloz** [comment]
> 有mapbox 底图是有的

@lzxue 国内项目，用mapbox貌似不合规

**Comment by 2912401452** [comment]
L7新版本高德2.0底图模式，支持镜头动画
