### ISSUE TITLE
@antv/l7-react生成中国地图时如何修改国界线的样式

### ISSUE THREAD

**Issue by WGH-TEE** [antvis/L7#680]
使用的版本：@antv/l7-react: "^2.3.0",
JSX部分代码：
![image](https://user-images.githubusercontent.com/72968036/117926943-1c51fc00-b32c-11eb-80af-9e88f5144e79.png)

翻遍了文档，只找到了使用组件CountryLayer时支持配置国界样式。
那么像我这样不用CountryLayer组件的话，该如何改变国界的样式呢。
望大神给予解答。谢谢。

**Comment by lzxue** [comment]
和linelayer 方法一样，比如shape 可以行政，可以参考 线的demo
