### ISSUE TITLE
scene与map的div层偏移？

### ISSUE THREAD

**Issue by 13kay** [antvis/L7#681]
在用R+htmlwigets做L7的封装，但是渲染出来发现scene与map的div层有偏移
L7 2.3.10，高德map

在IDE中（chrome下）渲染的效果，正常
![4](https://user-images.githubusercontent.com/394134/118259918-4fd78680-b4e4-11eb-887b-736365254b36.png)
在chrome中打开之后，两个div层没对齐
![1](https://user-images.githubusercontent.com/394134/118259926-5239e080-b4e4-11eb-8ec2-ab903009b1d6.png)
取消top属性
![3](https://user-images.githubusercontent.com/394134/118259921-5108b380-b4e4-11eb-8ea1-ef4dbb044738.png)
调整top属性对齐
![2](https://user-images.githubusercontent.com/394134/118259922-51a14a00-b4e4-11eb-8fd6-f5710b535cdb.png)

**Comment by lzxue** [comment]
container 的css 定位可以用绝对定位处理
