### ISSUE TITLE
Mapbox invalid access token error

### ISSUE THREAD

**Issue by sanjeev-unomok** [antvis/L7#686]
* **L7 Version**: 2.2.141
* **Platform**: linux,ubuntu 20.04.2
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codesandbox.io/s/r3tz3

Map box API call giving error of unauthorized access token

Request URL:- https://api.mapbox.com/styles/v1/zcxduo/ck241p6413s0b1cpayzldv7x7?access_token=pk.eyJ1IjoibHp4dWUiLCJhIjoiYnhfTURyRSJ9.Ugm314vAKPHBzcPmY1p4KQ

![Screenshot from 2021-05-19 13-28-42](https://user-images.githubusercontent.com/73215636/118786577-9431a080-b8af-11eb-822a-530ebed395b6.png)

because of this map is not loading, please fix this.

antv-l7 :- ^2.2.41
antvl7 :- ^2.2.41

Platform :- Linux, ubuntu 20.04

code sandbox link :- https://codesandbox.io/s/r3tz3

**Comment by lzxue** [comment]
需要自己注册mapboxtoken

**Comment by sanjeev-unomok** [comment]
> 需要自己注册mapboxtoken

In which file I have to change?
