### ISSUE TITLE
Popup 组件的click事件会触发底下的 PolygonLayer 的click事件

### ISSUE THREAD

**Issue by zstiu** [antvis/L7#692]
* **L7 Version**: 2.3.10
* **Platform**: win10, chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我用 PolygonLayer 的click 事件来控制Popup的展示，但是在Popup组件中点击时，总会触发底下的PolygonLayer 的click事件。

而且我在Popup组件的option中发现有stopPropagation这个属性，把它设置为true也不是一样的会触发。

**Comment by 2912401452** [comment]
新版本会处理事件冲突

**Comment by 2912401452** [comment]
请安装 L7 最新版本
