### ISSUE TITLE
pointlayer 文字标注图层，通过回调函数，返回文本时，使用换行符会压盖

### ISSUE THREAD

**Issue by KelseyYau** [antvis/L7#693]
* **L7 Version**:  2.2.38
* **Platform**: window 10 chrome  90
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/28589663/119754434-15ea8500-bed3-11eb-811a-23ae7e9282cb.png)
![image](https://user-images.githubusercontent.com/28589663/119754470-27339180-bed3-11eb-80f1-eafb2967aa37.png)

**Comment by lzxue** [comment]
目前还不支持换行
