### ISSUE TITLE
PointLayer 怎么配合Ant Design Avatar组件使用?

### ISSUE THREAD

**Issue by 6ok** [antvis/L7#696]
PointLayer 怎么配合Ant Design Avatar组件使用?

需求，将会员头像显示到地图上

**Comment by 6ok** [comment]
add.image方法就这两个参数，不能修改图片样式吗
![image](https://user-images.githubusercontent.com/56467036/120078224-f9bc3300-c0e0-11eb-85ad-f447d57852a6.png)

**Comment by lzxue** [comment]
图片不能添加样式，你希望添加圆角这样的样式？

**Comment by 6ok** [comment]
> 图片不能添加样式，你希望添加圆角这样的样式？

对或者开放一个reactdom

**Comment by lzxue** [comment]
dom 要使用marker 来做，pointLayer不支持

**Comment by 6ok** [comment]
@lzxue 
marker 有没有 autofit 功能
