### ISSUE TITLE
自定义 layer 和 WMTS layer 处理

### ISSUE THREAD

**Issue by jhgrrewq** [antvis/L7#697]
* **L7 Version**: 2.3.9
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

对于用户自定义 layer 有没有对应 api ，还有对于 wmts 数据怎么处理，在 l7 基础上创建 wmts layer 的能否提供一些思路？

**Comment by jhgrrewq** [comment]
@lzxue @lifesinger @afc163 @RaoHai

**Comment by lzxue** [comment]
wmts layer 可以用地图能力，通过瓦片图层实现

**Comment by jhgrrewq** [comment]
'wmts layer 可以用地图能力，通过瓦片图层实现'  比如是本身用的是高德地图实例，用原本高德地图的 layer 添加 wmts 吗，如果用的是 mapbox 地图实例，用 mapbox 地图的 layer 添加 wmts 吗 @lzxue

**Comment by lzxue** [comment]
mapbox Tile raster 瓦片可以看一下

**Comment by jhgrrewq** [comment]
l7 本身已经有 raster 类型的 source，是不是可以将 wmts 服务获取的每个瓦片在对应 bounds 进行纹理贴图 @lzxue
