### ISSUE TITLE
Layer、Layer 插件、后处理效果配置项校验服务设计

### ISSUE THREAD

**Issue by xiaoiver** [antvis/L7#70]
### 问题背景

用户在使用 L7 的 Scene/Layer API 时，由于参数配置项众多难免会误传。需要在运行时通过校验提前发现并给出友好的提示。

另外由于 L7 允许用户自定义 Layer、Layer 插件、后处理效果，规范化参数配置项也能提升易用性和质量。

这方面 Webpack 做的很好，使用 [schema-utils](https://github.com/webpack/schema-utils) 基于 JSON Schema 对 Plugin 和 Loader 进行校验。如果传入了错误的配置项，会给出友好的提示：
```
Invalid configuration object. MyPlugin has been initialised using a configuration object that does not match the API schema.
 - configuration.optionName should be a integer.
```

### 方案设计

需要考虑以下场景及注意事项：
* L7 内部 Scene、Layer、Layer 插件、后处理效果直接使用该服务，校验传入的配置项
* 对于用户自定义 Layer、插件、后处理效果提供简单友好方式接入，例如通过重载基类方法定义自定义组件配置项的 schema
* 校验失败立刻中断后续处理（Layer 初始化），并在控制台给出友好提示
* 校验时机除了初始化，在 Layer 属性更新时同样需要进行

在具体实现上，和 Webpack 一样，我们也选择 [ajv](https://github.com/epoberezkin/ajv) 作为 JSON Schema 校验器。

JSON Schema 描述十分直观，例如描述 Layer 拾取高亮相关的配置项 Schema：
```javascript
export default {
  properties: {
    // 开启拾取
    enablePicking: {
      type: 'boolean',
    },
    // 开启高亮
    enableHighlight: {
      type: 'boolean',
    },
    // 高亮颜色：例如 [0, 0, 1, 1] 或者 '#ffffff'
    highlightColor: {
      oneOf: [
        {
          type: 'array',
          items: {
            type: 'number',
            minimum: 0,
            maximum: 1,
          },
        },
        {
          type: 'string',
        },
      ],
    },
  },
};
```

### API

通过 `configService` 引用，作为一个全局服务在全局容器中完成绑定。

同一类 Layer 只需要注册一个校验器：
```typescript
registerLayerConfigSchemaValidator(layerName: string, schema: object): void;
validateLayerConfig(layerName: string, data: object): { valid: boolean; errorText: string; };
```

### 使用方法

主要考虑自定义场景下的使用方法，内置实现使用方法几乎一致。

#### Layer 子类配置项 Schema

Layer 子类（用户自定义 Layer 一样）可以通过重载 `getConfigSchema()` 方法定义自身的特有属性。例如 `PolygonLayer` 需要定义透明度：

```javascript
protected getConfigSchema() {
  return {
    properties: {
      opacity: {
        type: 'number',
        minimum: 0,
        maximum: 1,
      },
    },
  };
}
```

### TODO

待补充自定义 Layer 插件、后处理效果 使用方法。

**Comment by lzxue** [comment]
ajv 单个包体积太大,不适合Web端使用
