### ISSUE TITLE
怎么指定高德地图SDK版本

### ISSUE THREAD

**Issue by spike-bepop** [antvis/L7#704]
SDK版本号：![image](https://user-images.githubusercontent.com/26076008/121280669-41c12e00-c909-11eb-94b7-c5c0cecfe674.png)

使用的是l7-react中的AMapScene组件

本地加载的版本是1.4.15
![image](https://user-images.githubusercontent.com/26076008/121280966-b85e2b80-c909-11eb-9ee0-5218da6f825d.png)

发到测试环境后加载的是2.0版本
![image](https://user-images.githubusercontent.com/26076008/121281194-1d198600-c90a-11eb-9fa6-eb8344989606.png)

AMapScene文档中没找到设置SDK版本的地方

根据文档上引入 [GaodeMapV1](https://l7.antv.vision/zh/docs/api/map)来指定版本 根本没`export GaodeMapV1`
![image](https://user-images.githubusercontent.com/26076008/121280884-9369b880-c909-11eb-91e7-f3e1148101ef.png)

目前本地使用@antv/l7-district中的DrillDownLayer组件能够正常加载，测试环境地图一片空白，怀疑是SDK版本导致的，但是console里没有任何报错，麻烦看看什么问题

**Comment by 2912401452** [comment]
在项目中使用的时候可以锁定版本号，^的写法会默认升级的最新的小版本
"@antv/l7": "2.3.10",
 "@antv/l7-maps": "2.3.10",

**Comment by spike-bepop** [comment]
锁版本之后解决了
