### ISSUE TITLE
[l7-district]DrillDownLayer 手动调用drillDown方法报错

### ISSUE THREAD

**Issue by spike-bepop** [antvis/L7#706]
[codesandbox链接](https://codesandbox.io/s/hungry-grothendieck-d0d86?file=/index.js)

看源码是drillState的问题

**Comment by liuvigongzuoshi** [comment]
@spike-bepop 

使用最新的行政区域下钻 [L7Plot Choropleth](https://l7plot.antv.vision/zh/docs/api/plots/choropleth)，使用[方式](https://l7.antv.vision/zh/examples/choropleth/drill#order-drill)，旧版 DrillDownLayer 不再提供维护
