### ISSUE TITLE
LineLayer 被 CountLayer 覆盖问题，调整zIndex无用

### ISSUE THREAD

**Issue by WumaCoder** [antvis/L7#712]
* **L7 Version**:2.4.3
* **Platform**:mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/39021696/123016652-abf3cb80-d3fd-11eb-912e-072dd3e307ed.png)

**Comment by WumaCoder** [comment]
![image](https://user-images.githubusercontent.com/39021696/123017842-ff671900-d3ff-11eb-9b38-3aca87fdf044.png)

**Comment by 2912401452** [comment]
感谢发现问题，会尽快修复！

**Comment by 2912401452** [comment]
let lineLayer = new LineLayer({zIndex: 3, blend: 'normal'})
线图层 arc、arc3d 默认的叠加模式不是 normal，需要调整一下叠加模式！
