### ISSUE TITLE
Vue3.0 实例有吗？

### ISSUE THREAD

**Issue by Beipy** [antvis/L7#713]
L7的vue3.0初始化实例有吗？跪求实例

**Comment by Beipy** [comment]
自己已解决

**Comment by GiottoLLL** [comment]
请问可以分享一下吗？

**Comment by lzxue** [comment]
> 请问可以分享一下吗？

https://codesandbox.io/s/l7-vue3-ufhc1?file=/src/App.vue

**Comment by GiottoLLL** [comment]
> > 请问可以分享一下吗？
> 
> https://codesandbox.io/s/l7-vue3-ufhc1?file=/src/App.vue

非常感谢
