### ISSUE TITLE
Error: Uncaught SyntaxError: Unexpected token '!'

### ISSUE THREAD

**Issue by pieterbergmans** [antvis/L7#722]
I'm trying to get L7 running in my create-react-app.  My steps so far are:

1. I installed L7 with...
```npm i @antv/l7-react``` 

2. I imported it into my react app with...
```import { LineLayer, AMapScene } from '@antv/l7-react';```

The error I get is...

```Uncaught SyntaxError: Unexpected token '!'```

I have react 17.0.2 installed.

**Comment by lzxue** [comment]
you can see this demo https://l7.antv.vision/zh/examples/react/covid/#covid_column
