### ISSUE TITLE
`L7` 文档似乎有个多余的文案，但国内镜像版本文档正常

### ISSUE THREAD

**Issue by hocko333** [antvis/L7#723]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

### 截图对比
![image](https://user-images.githubusercontent.com/45919606/126035120-401a8c15-9456-4b93-8075-6b3e649edb2c.png)
![image](https://user-images.githubusercontent.com/45919606/126035130-087a4421-fc97-4706-84ae-0afde5a4042f.png)

**Comment by 2912401452** [comment]
官网已更新
