### ISSUE TITLE
高德地图插件

### ISSUE THREAD

**Issue by curly210102** [antvis/L7#726]
* **L7 Version**: 2.5.0
* **Platform**: MacOS Big Sur Version 11.4， Edge Version 90.0.818.66

### 现象描述
[React 的 AmapScene 组件的文档](https://antv-l7.gitee.io/zh/docs/api/react/scene#map-option)表明可以配置 `plugin` 属性来使用高德地图插件，然而并没有效果。

### 原因
原因在于 `GaodeMap` 使用的 amap-jsapi-loader 只是下载 plugin 相关的源码，并不会自动应用

### 疑问

猜想 L7 的设计是借助 amap-jsapi-loader 下载 plugin 代码，对高德地图插件的应用需要使用者在 `scene loaded` 钩子中借助 `scene.map` 自定义。例如

``` ts
const scene = new Scene({
  id: 'map',
  map: new GaodeMap({
    style: 'light',
    pitch: 0,
    center: [107.054293, 35.246265],
    zoom: 4.056,
    plugin: [
      'AMap.ToolBar'
    ],
  }),
});
scene.on('loaded', () => {
  const plugin = new (window.AMap as typeof AMap & {
    [key: string]: any;
  })['ToolBar']();
  const map = scene.map as AMap.Map;
  map.addControl(plugin);
});
```

如果插件的使用确实是这样的，我想我能在文档里加一下使用说明和演示代码。

**Comment by lzxue** [comment]
这块确实没有细致研究过，欢迎为L7贡献代码

**Comment by wudadadaju** [comment]
![image](https://user-images.githubusercontent.com/24884926/137063855-fad3bb85-6d82-4482-91e2-0b3d0ae1f50d.png)
我使用您的解决方案，编译报错不知道为啥呢 @curly210102

**Comment by curly210102** [comment]
目测是因为用的 js 而非 ts，

``` js
scene.on('loaded', () => {
  const plugin = new AMap['ToolBar']();
  const map = scene.map;
  map.addControl(plugin);
});
```
<img width="668" alt="Screen Shot 2021-10-13 at 1 16 18 PM" src="https://user-images.githubusercontent.com/76864176/137071569-168dbf8e-164d-4f25-a719-48198a43fa7c.png">

**Comment by wudadadaju** [comment]
> 目测是因为用的 js 而非 ts
> 
> <img alt="Screen Shot 2021-10-13 at 1 16 18 PM" width="668" src="https://user-images.githubusercontent.com/76864176/137071569-168dbf8e-164d-4f25-a719-48198a43fa7c.png">
> 
> js 代码如下
> 
> ```js
> scene.on('loaded', () => {
>   const plugin = new AMap['ToolBar']();
>   const map = scene.map;
>   map.addControl(plugin);
> });
> ```

感谢大佬指点。。
但是为啥我这个还是有问题呢，像是amap里面没有这个工具一样
![image](https://user-images.githubusercontent.com/24884926/137072708-4e8410d4-1898-40fc-acda-6ae9abf1a4b6.png)

![image](https://user-images.githubusercontent.com/24884926/137072742-eaa52c71-45de-4612-b463-a290f68f167a.png)

**Comment by curly210102** [comment]
AMap 并不是 @antv/l7-maps 导出的对象，而是 `window.AMap`

**Comment by 2912401452** [comment]
高德插件的使用可以参考官网文档和demo
https://l7.antv.vision/zh/docs/api/amapPlugin/plugin
https://l7.antv.vision/zh/examples/amapPlugin/bus#busStop
