### ISSUE TITLE
【合法性咨询】外网线上使用是否需要申请审图号

### ISSUE THREAD

**Issue by liangyuqi** [antvis/L7#727]
用了你们的[填充地图](https://l7.antv.vision/zh/examples/district/basic#china_map_2), 

没有审图号 上线使用的话，会有法律风险吗

万一出事了 是L7承担责任，还是我承担 呀，期待解答🙏

**Comment by 2912401452** [comment]
审图号需要一图一审，L7 只是提供了能力，需要你们自己去审批

**Comment by AndyXGWang** [comment]
您好， 咨询下， L7有 基础的地图组件 有审图号吗？ 在官网文档上没有看到， 所以咨询下

thanks
