### ISSUE TITLE
vite+ts项目引入l7报错TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by fgxpf** [antvis/L7#729]
TypeError: Super expression must either be null or a function
    at _inherits (inherits.js:4)
    at BlurHPass.ts:12
    at BlurHPass.ts:50

import { Scene } from '@antv/l7'
import { Mapbox } from '@antv/l7-maps'

直接导入l7的模块就报错，可以正常导入其他依赖包，大佬们求解

"dependencies": {
    "@antv/l7": "^2.4.4",
    "@antv/l7-maps": "^2.4.4",
    "vue": "^3.0.5",
    "vue-router": "4"
  }

**Comment by sodatea** [comment]
参见 https://github.com/vitejs/vite/issues/4391#issuecomment-890542537

是因为循环引用的问题。

**Comment by fgxpf** [comment]
> 参见 [vitejs/vite#4391 (comment)](https://github.com/vitejs/vite/issues/4391#issuecomment-890542537)
> 
> 是因为循环引用的问题。

感谢！

**Comment by GiottoLLL** [comment]
是否需要重新打开并向开发者报告这个问题呢？

**Comment by lc06** [comment]
这个问题目前开发者已经解决了，方案是：
1. 升级@antv/l7到2.5.7以上，然后改一下vite 配置就行了
2. 修改vite配置文件vite.config.js: 
`import { defineConfig } from "vite";
import swc from "rollup-plugin-swc"; //注意添加rollup-plugin-swc，@swc/core这两个依赖
import vue from "@vitejs/plugin-vue";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    swc({
      jsc: {
        parser: {
          syntax: "typescript",
          // tsx: true, // If you use react
          dynamicImport: true,
          decorators: true,
        },
        target: "es2021",
        transform: {
          decoratorMetadata: true,
        },
      },
    })
  ],
  esbuild: false,
});
`

**Comment by GiottoLLL** [comment]
> 这个问题目前开发者已经解决了，方案是：
> 
> 1. 升级@antv/l7到2.5.7以上，然后改一下vite 配置就行了
> 2. 修改vite配置文件vite.config.js:
> 
> ```js
> import { defineConfig } from "vite";
> import swc from "rollup-plugin-swc"; //注意添加rollup-plugin-swc，@swc/core这两个依赖
> import vue from "@vitejs/plugin-vue";
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [
>     vue(),
>     swc({
>       jsc: {
>         parser: {
>           syntax: "typescript",
>           // tsx: true, // If you use react
>           dynamicImport: true,
>           decorators: true,
>         },
>         target: "es2021",
>         transform: {
>           decoratorMetadata: true,
>         },
>       },
>     })
>   ],
>   esbuild: false,
> });
> ```
> 
> > 具体可参考：https://github.com/lc06/vite_antv-L7

好的，非常感谢
