### ISSUE TITLE
下钻地图市区描边怎么设置

### ISSUE THREAD

**Issue by git-zh** [antvis/L7#736]
下钻地图 DrillDownLayer （l7-district）
省的为
province: {
  provinceStrokeWidth: 1
} 是起作用的
请问 市、区描边怎么设置，或者有没有统一配置的地方

**Comment by lzxue** [comment]
对应 city，county里面设置

**Comment by git-zh** [comment]
设置了， 像这样，但是下钻到省后没起作用
city: {
        cityStrokeWidth: 1
      }

**Comment by lzxue** [comment]
city: {
strokeWidth: 1
}

**Comment by git-zh** [comment]
好的，谢谢

**Comment by thelaurelyy** [comment]
@lzxue 请问你使用此配置有生效吗？我试了一下好像还是不行

city: {
strokeWidth: 1
}

**Comment by git-zh** [comment]
可以的

**Comment by thelaurelyy** [comment]
好的，谢谢

**Comment by thelaurelyy** [comment]
好的，谢谢
