### ISSUE TITLE
引入Loca2.0可视化API后, L7自有图层发生偏移

### ISSUE THREAD

**Issue by wyl1201** [antvis/L7#741]
* **L7 Version**:  2.5.7
* **Platform**:   Window10 Chrome 版本 92.0.4515.131（正式版本） （64 位）
* **Mini Showcase(like screenshots)**: ![image](https://user-images.githubusercontent.com/29521491/128672414-cb57fd09-3f1e-49a3-976f-100db7f5fa42.png)
* **CodeSanbox Link**: https://codesandbox.io/s/l7-loca-mxr99

问题描叙: 
 项目引入高德新出的Loca2.0可视化API后, 做贴地点效果, 同样的坐标, 使用Loca创建的图层, 点的位置正确,  使用L7, PointLayer创建的图层位置偏移

引入Loca
```jsx
const TrafficPointLayer = (props) => {
  const scene = useSceneValue()
  useEffect(() => {
    const Loca = window.Loca
    const loca = new Loca.Container({ map: scene.map })
    var breath = new Loca.ScatterLayer({
      zIndex: 121,
    })
    breath.setSource(
      new Loca.GeoJSONSource({
        data: top10,
      })
    )
    breath.setStyle({
      unit: "px",
      size: [50, 50],
      texture:
        "https://a.amap.com/Loca/static/loca-v2/demos/images/breath_red.png",
      animate: true,
      duration: 1000,
    })
    loca.add(breath)
    loca.animate.start()
  }, [])
  return null
}
```

**Comment by 2912401452** [comment]
目前没有做 与 Loca 的混合兼容，后续也没有这个计划
