### ISSUE TITLE
L7是内置了高德地图么,可以结合其它第三方地图使用吗

### ISSUE THREAD

**Issue by HaoAurora** [antvis/L7#747]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lzxue** [comment]
目前只支持两种mapbox 和高德

**Comment by yanyu510** [comment]
maptalks支持 https://github.com/yanyu510/L7/tree/maptalks，可以参考下

**Comment by zhounewz** [comment]
？

**Comment by zhounewz** [comment]
可以结合第三方地图试用吗？

**Comment by 2912401452** [comment]
目前还不支持
