### ISSUE TITLE
2.5.9版本包没有编译es版本只有lib包，导致ts找不到类型定义

### ISSUE THREAD

**Issue by bluehymn** [antvis/L7#748]
* **L7 Version**: v2.5.9
* **Platform**: 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

@antv/l7-xxxx几个包都有这个问题

![image](https://user-images.githubusercontent.com/15361704/130023176-c48c4d54-5b77-4dd9-84be-f2d9276c7594.png)

**Comment by lzxue** [comment]
已经回滚到2.5.8

**Comment by GiottoLLL** [comment]
> 已经回滚到2.5.8

2.5.8 @antv/l7的lib里的declaration声明文件全没了
![image](https://user-images.githubusercontent.com/39177802/130413444-079d803d-a769-488f-9458-f567a74cad83.png)
