### ISSUE TITLE
行政区域图 destroy 后内存依然不减

### ISSUE THREAD

**Issue by xiecg** [antvis/L7#751]
行政区域图 destroy 后内存依然不减

* **L7 Version**:2.5.8
* **Platform**: macOS Big Sur 11.4
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codesandbox.io/s/muddy-leaf-ubc59

我这边每次是把  Scene 和 CountryLayer 销毁掉的

第一次加载，仅有73MB

<img width="683" alt="start" src="https://user-images.githubusercontent.com/10857932/130431859-ddfc253e-cd70-48ea-bd57-a88bf6d1868b.png">

销毁再加载重复了 20 次，内存来到了 300 MB，在 windows 平台表现上更夸张，

<img width="668" alt="end" src="https://user-images.githubusercontent.com/10857932/130432174-d2256a53-f552-4416-9ebb-f3645e9332d3.png">

**Comment by 2912401452** [comment]
感谢提出问题，内存泄漏的问题已经在 L7 2.6.7 版本修复
[https://codesandbox.io/s/dazzling-napier-78soq?file=/index.js](url)
ps：一般 scene 不会被销毁
