### ISSUE TITLE
如何使用天地图

### ISSUE THREAD

**Issue by YC725968** [antvis/L7#752]
如何使用将天地图换为天地图，有Api吗

**Comment by lzxue** [comment]
只能使用天地图的瓦片地图

**Comment by YC725968** [comment]
你好，有具体例子吗？

**Comment by Randysheng** [comment]
我的解决方法：采用[传入高德地图实例](https://antv-l7.gitee.io/zh/docs/api/map#%E4%BC%A0%E5%85%A5%E9%AB%98%E5%BE%B7%E5%9C%B0%E5%9B%BE%E5%AE%9E%E4%BE%8B)的方式创建地图。
那么剩下的问题就是：高德如何加载天地图了? 在网上搜一下吧，一堆文章。
希望能帮到你。
