### ISSUE TITLE
查遍所有的文档都没看到这个data 格式，哪位大神告知？

### ISSUE THREAD

**Issue by AlingChen** [antvis/L7#755]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/11454349/131614180-0996ea60-c822-4543-bfa0-a694ecdf43da.png)

**Comment by 2912401452** [comment]
这是内置的数据，暂时不支持自定义传入
