### ISSUE TITLE
L7流向图线条流动效果异常bug

### ISSUE THREAD

**Issue by changeiot** [antvis/L7#757]
* **L7 Version**:
* **Platform**: Chrome 93.0.4577.63（正式版本） （64 位）
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/43211867/131951531-cb65b670-d173-4de6-92f9-6706e4dc9e11.png)

* **CodePen Link**:

复现步骤： 
1. 打开官方示例网站 https://antv-l7.gitee.io/zh/examples/gallery/animate#world2 ，
![image](https://user-images.githubusercontent.com/43211867/131947164-fdd6a634-80f1-4b87-aa18-3c31706a9ae0.png)
2. 如上图，修改worldLine中的size为足够宽时，流向图的流动效果被地图边界遮挡。

3. 另外，本官方示例中，世界地图图层worldFill图层配置被注释，并且没有绘制在地图上。如下图所示，
![image](https://user-images.githubusercontent.com/43211867/131947507-59d8ceed-9174-4867-933f-7784f3778a24.png)
。而当正确加入并绘制这个图层后，流向线条流动效果会被地图完全遮挡

**Comment by 2912401452** [comment]
混合模式改一下就行
const flyLine = new LineLayer({blend: 'normal'})

**Comment by changeiot** [comment]
经过调整混合模式，问题已解决，谢谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 晚上7:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [antvis/L7] L7流向图线条流动效果异常bug (#757)





 
混合模式改一下就行
 const flyLine = new LineLayer({blend: 'normal'})
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
