### ISSUE TITLE
“L7-District”在QQ浏览器中的使用错误

### ISSUE THREAD

**Issue by xaisdk** [antvis/L7#759]
在QQ浏览器中使用“L7-District”组件中的“CountryLayer”或者“WorldLayer”会报一个这样的错误：
在填充图示例中打开codesandbox即可复现.

Error linking program with vertex shader, "https://hxh8d.csb.app/node_modules/@antv/l7-renderer/es/regl/ReglModel.js:106:24", and fragment shader "https://hxh8d.csb.app/node_modules/@antv/l7-renderer/es/regl/ReglModel.js:106:24"
Could not pack varying v_distance
Note: Additional non-conformant packing restrictions are enforced on D3D9.

**Comment by 1021683053** [comment]
跟我碰到的问题一样

**Comment by 2912401452** [comment]
升级 2.5.13 版本看看
