### ISSUE TITLE
L7 使用 LineLayer 再 win7 上会报错: Additional non-conformant packing restrictions are enforced on D3D9.

### ISSUE THREAD

**Issue by 1021683053** [antvis/L7#761]
![image](https://user-images.githubusercontent.com/7711802/132462086-b7d1c2af-9866-4f47-9cdb-2cfe25d8ccc5.png)
![image](https://user-images.githubusercontent.com/7711802/132475035-1c83f717-8262-42b2-b050-2781295b458f.png)

![image](https://user-images.githubusercontent.com/7711802/132475012-82685cab-9272-435a-811f-5094f4d038b5.png)

**Comment by 2912401452** [comment]
var gl = document.createElement('canvas').getContext('webgl')
gl.getParameter(gl.MAX_VARYING_VECTORS)
浏览器控制台执行一下看看

**Comment by 1021683053** [comment]
> ument.createElement('canvas').getContext('webgl')
> gl.getParameter(gl.MAX_VARYING_VECTORS)
> 浏览器控制台执行一下看看
应该跟这个 issue 一样的问题
https://github.com/antvis/L7/issues/759

**Comment by 2912401452** [comment]
2.5.13 版本已经优化
