### ISSUE TITLE
@antv/l7-map 没有发布UMD 包

### ISSUE THREAD

**Issue by 1021683053** [antvis/L7#764]
![image](https://user-images.githubusercontent.com/7711802/132939395-893a47d2-30c8-4114-8594-f1f8a3f0888c.png)

**Comment by 2912401452** [comment]
https://unpkg.com/@antv/l7@2.5.14/dist/l7.js

**Comment by 2912401452** [comment]
l7 的 cdn 包含了所有的其他依赖
