### ISSUE TITLE
AMapSceneV2不支持style为blank，内部的popup不支持跟随地图拖动而移动

### ISSUE THREAD

**Issue by simplast** [antvis/L7#770]
如题

**Comment by 2912401452** [comment]
在2.5.25 版本测试后并没有发现你提出的问题，请提供在复现案例，或安装 L7 最新版本

**Comment by simplast** [comment]
> 在2.5.25 版本测试后并没有发现你提出的问题，请提供在复现案例，或安装 L7 最新版本

https://l7.antv.vision/zh/examples/react/layer#marker 进去后把AMapScene改成AMapSceneV2，style改成blank就看到问题了

**Comment by 2912401452** [comment]
不要直接在官网修改，由于高德 JSAPI 的限制，直接切换高德地图地图的版本会报错
![A6D462AB-7CD5-46BD-8CD4-FA64929F7469](https://user-images.githubusercontent.com/42212176/134791769-e5882194-6a09-447a-9276-0a777366bc62.png)
自己在工程中引用地图的时候就选 AMapSceneV2 就不会报错了
![BBF5946E-2390-4765-B4E1-E31F8296C0B5](https://user-images.githubusercontent.com/42212176/134791807-c2c69848-5737-46fd-9a5e-4b2b00e69723.png)

**Comment by simplast** [comment]
我项目是没有报错，但是用v2，这个popup不能跟随我拖拽地图而移动，它就一直固定在那里

**Comment by simplast** [comment]
> 不要直接在官网修改，由于高德 JSAPI 的限制，直接切换高德地图地图的版本会报错
> ![A6D462AB-7CD5-46BD-8CD4-FA64929F7469](https://user-images.githubusercontent.com/42212176/134791769-e5882194-6a09-447a-9276-0a777366bc62.png)
> 自己在工程中引用地图的时候就选 AMapSceneV2 就不会报错了
> ![BBF5946E-2390-4765-B4E1-E31F8296C0B5](https://user-images.githubusercontent.com/42212176/134791807-c2c69848-5737-46fd-9a5e-4b2b00e69723.png)

升级到新版本后，应该是我umi缓存导致的，清空后就没问题了，popup可以跟随用户拖拽，但是地图的style为blank还是不生效
