### ISSUE TITLE
DEMO填充地图/中国地图省级中的标注数据json数据错误

### ISSUE THREAD

**Issue by EricHan0723** [antvis/L7#773]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

DEMO示例中的填充地图/中国地图省级中的标注数据json中，关于香港和澳门的标注位置（包括标题位置和填充地图的边缘位置）与地图实际位置之间的差异有点大，尤其是澳门

**Comment by EricHan0723** [comment]
https://gw.alipayobjects.com/os/bmw-prod/c4a6aa9d-8923-4193-a695-455fd8f6638c.json ，这个是demo中的json链接

**Comment by 2912401452** [comment]
这个 demo 的数据只适用于全国视角，为了避免文字的遮盖所以对一些文字的位置做了偏移，在高缩放等级下需要更新部分点位的数据
