### ISSUE TITLE
使用高德地图时 panBy 方法存在问题

### ISSUE THREAD

**Issue by wtzeng1** [antvis/L7#785]
* **L7 Version**: @antv/l7-maps@2.5.25
* **Platform**: -
* **Mini Showcase(like screenshots)**: [相关源码](https://github.com/antvis/L7/blob/0bcc822cdd5e7bace35ea60b427e54e4da73d2b8/packages/maps/src/amap/map.ts#L233)
* **CodePen Link**: -
1. 源码中 `panBy` 和 `panTo` 一样都调用的是高德地图实例的 `panTo` 方法
2. 高德地图v1 中 `panBy` 的参数不是一个数组([link](https://lbs.amap.com/api/javascript-api/reference/map))，需要改参数传递方式

**Comment by 2912401452** [comment]
已经在 2.5.28 版本修复这个问题
