### ISSUE TITLE
如何进行目标地点的搜索

### ISSUE THREAD

**Issue by wudadadaju** [antvis/L7#794]
* **L7 Version**:2.0
* **Platform**:vue
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

不知道如何使用高德地图的搜索功能，或者说咱们L7里面是否支持地点的搜索？

**Comment by 2912401452** [comment]
需要使用高德地图的插件，官网会尽快补充相关 demo

**Comment by 2912401452** [comment]
高德插件的使用可以参考官网文档和demo
https://l7.antv.vision/zh/docs/api/amapPlugin/plugin
https://l7.antv.vision/zh/examples/amapPlugin/bus#busStop

**Comment by shining-data** [comment]
> 高德插件的使用可以参考官网文档和demo https://l7.antv.vision/zh/docs/api/amapPlugin/plugin https://l7.antv.vision/zh/examples/amapPlugin/bus#busStop

mapbox 离线模式，是否能支持搜索呢
