### ISSUE TITLE
能否支持MVT数据标准的大数据可视化？

### ISSUE THREAD

**Issue by wucangeo** [antvis/L7#80]
简单看了一下示例和代码，目前是通过请求json(geojson)数据然后进行可视化渲染的。
这种方式可能无法做到真正的“大数据”，因为大量的数据如果通过http的单个请求，可能会超过10M或者更大。
如果能够支持原生MVT数据标准的大数据可视化，可视化的内容可以配置property字段，就可以做到分层级的大数据可视化了。
希望考虑。感谢！

**Comment by lzxue** [comment]
后面会做，但是目前来看优先级没那么高

**Comment by wucangeo** [comment]
那就太棒了！感谢回复。  @lzxue
