### ISSUE TITLE
Marker不提供拖动事件吗？

### ISSUE THREAD

**Issue by 17797776321** [antvis/L7#802]
![image](https://user-images.githubusercontent.com/20875342/137720472-0a5d7922-ade8-4619-9e11-68bc252c1e6e.png)
如图所示！高德地图的Marker是有一个dragend事件。请问L7的Marker不支持监听拖拽事件吗，文档好像并没有这个事件的接口？有什么办法实现这个功能吗？

**Comment by lzxue** [comment]
需要拖动Maker 改变位置吗？

**Comment by Nikkolast88** [comment]
+1，有实现方法嘛？

**Comment by lvisei** [comment]
https://l7.antv.antgroup.com/api/component/marker

![image](https://github.com/antvis/L7/assets/26923747/6bfd1731-a02d-441c-a0f1-a6d6705b6b28)
