### ISSUE TITLE
航向图（平面) 示例的小飞机变形了很奇怪, 如何修改能保持不变的形状?

### ISSUE THREAD

**Issue by hudson-dong** [antvis/L7#805]
* **L7 Version**:2.5.35
* **Platform**:react
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

[航向图(平面)](https://l7.antv.vision/zh/examples/gallery/animate#plane_animate2)

**Comment by 2912401452** [comment]
目前纹理在动画模式下还有待优化，会尽快进行优化

**Comment by 2912401452** [comment]
线图层的纹理动画以及在 2.6.3 版本优化，请更新版本
