### ISSUE TITLE
高德2.0下无法使用l7

### ISSUE THREAD

**Issue by ILHQ** [antvis/L7#821]
"@antv/l7": "^2.5.45",
    "@antv/l7-maps": "^2.5.45",
高德2.0下无法使用l7
切换到高德1.4.15版本可以正常使用
官方文档上的示例也无法运行https://l7.antv.vision/zh/examples/tutorial/map#amapInstance

**Comment by 2912401452** [comment]
`
import { PointLayer, Scene } from '@antv/l7';
import { GaodeMap, GaodeMapV2 } from '@antv/l7-maps';
import AMapLoader from '@amap/amap-jsapi-loader';
import * as React from 'react';
export default class Amap2demo_instance extends React.Component {
  // @ts-ignore
  private scene: Scene;

  public componentWillUnmount() {
    this.scene.destroy();
  }

  public async componentDidMount() {
    // const AMAP_API_KEY: string = '15cd8a57710d40c9b7c0e3cc120f1200';
    // const AMAP_VERSION: string = '1.4.15';
    const AMAP_API_KEY: string = 'ff533602d57df6f8ab3b0fea226ae52f';
    const AMAP_VERSION: string = '2.0';

    AMapLoader.load({
      key: AMAP_API_KEY, // 申请好的Web端开发者Key，首次调用 load 时必填
      version: AMAP_VERSION, // 指定要加载的 JSAPI 的版本，缺省时默认为 1.4.15
      // plugins: plugin, // 需要使用的的插件列表，如比例尺'AMap.Scale'等
    }).then((AMap) => {
      const map = new AMap.Map('map', {
        viewMode: '3D',
        pitch: 0,
        mapStyle: 'amap://styles/darkblue',
        center: [121.435159, 31.256971],
        zoom: 14.89,
        minZoom: 10,
      });

      const scene = new Scene({
        id: 'map',
        map: new GaodeMapV2({
          mapInstance: map,
        }),
      });

      this.scene = scene;

      scene.on('loaded', () => {
        fetch(
          'https://gw.alipayobjects.com/os/basement_prod/893d1d5f-11d9-45f3-8322-ee9140d288ae.json',
        )
          .then((res) => res.json())
          .then((data) => {
            const pointLayer = new PointLayer()
              .source(data, {
                parser: {
                  type: 'json',
                  x: 'longitude',
                  y: 'latitude',
                },
              })
              .shape('name', [
                'circle',
                'triangle',
                'square',
                'pentagon',
                'hexagon',
                'octogon',
                'hexagram',
                'rhombus',
                'vesica',
              ])
              .size('unit_price', [10, 25])
              .color('name', [
                '#5B8FF9',
                '#5CCEA1',
                '#5D7092',
                '#F6BD16',
                '#E86452',
              ])
              .style({
                opacity: 0.3,
                strokeWidth: 2,
              });
            scene.addLayer(pointLayer);
          });
      });
    });
  }

  public render() {
    return (
      <>
        <div
          id="map"
          style={{
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
          }}
        />
      </>
    );
  }
}

`
![DC333651-85E6-4A69-B7C1-F9E7F3E51B0A](https://user-images.githubusercontent.com/42212176/143521213-5f9e1a2f-9677-426a-ba7d-370151ea7216.png)


不要在运行中的 demo 中动态切换地图版本，高德 SDK 本身不支持
