### ISSUE TITLE
 'HeatMapLayer' is not exported from '@antv/l7'.

### ISSUE THREAD

**Issue by jerryyyq** [antvis/L7#822]
* **L7 Version**:   2.5.45
* **Platform**: react_create_app   react version is  17.0.1
* **Mini Showcase(like screenshots)**:   'HeatMapLayer' is not exported from '@antv/l7'.
* **CodePen Link**:    import { HeatMapLayer } from "@antv/l7";

import { HeatMapLayer } from "@antv/l7";

npm start 时，报：Attempted import error: 'HeatMapLayer' is not exported from '@antv/l7'.

**Comment by susiwen8** [comment]
It's `HeatmapLayer`, not `HeatMapLayer`
