### ISSUE TITLE
对于各个layer的调用能否提供一些 react 的例子

### ISSUE THREAD

**Issue by jerryyyq** [antvis/L7#823]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

对于各个layer的调用能否提供一些 react 的例子， 例如；WorldLayer   HeatmapLayer 等等......

**Comment by 2912401452** [comment]
目前已经发布了 L7React 专门的站点，可以在里面查看更多关于 L7React 的 demo
https://antv.vision/L7-react/

**Comment by susiwen8** [comment]
或者使用 ant-design-charts
https://charts.ant.design/
