### ISSUE TITLE
图层超出父容器且无法缩小显示

### ISSUE THREAD

**Issue by jerryyyq** [antvis/L7#825]
* **L7 Version**:   2.5.45
* **Platform**: react   17.0.1
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: 

`
    componentDidMount() {
        const scene = new Scene({
            id: "hot_map",
            logoVisible: false,
            map: new Mapbox({
                pitch: 0,
                style: "dark",
                center: [116.2825, 39.9],
                zoom: 0,
                minZoom: 0,
                maxZoom: 24
            })
        });

        scene.on('loaded', () => {
            this.worldLayer = new WorldLayer(scene, {
                data: [],
                fill: {
                    color: {
                        field: 'NAME_CHN',
                        values: [
                            '#feedde',
                            '#fdd0a2',
                            '#fdae6b',
                            '#fd8d3c',
                            '#e6550d',
                            '#a63603'
                        ]
                    }
                },
                stroke: '#ccc',
                label: {
                    enable: true,
                    textAllowOverlap: false,
                    field: 'NAME_CHN'
                },
                popup: {
                    enable: false,
                    Html: props => {
                        return `<span>${props.NAME_CHN}</span>`;
                    }
                }
            });
        });

        console.log("scene.getSize() = ", scene.getSize())
        console.log("scene.getContainer() = ", scene.getContainer())
        
        this.scene = scene;        
    }

    render() {
               ......
                <Layout.Content key="1" >
                    <h2>数据检索</h2>
                    <div className="Content">
                    <Row>
                        <Col span={6}>
                            <div id="hot_map" style={{ margin:0, width:'100%', height:0, paddingBottom:'100%'}}>
                                {''}
                            </div>
               ......
`

**Comment by 2912401452** [comment]
WorldLayer 暂时不支持 fitBounds 方法，会及时完善，感谢提出问题🙏

**Comment by 2912401452** [comment]
可以使用 worldLayer.fillLayer.fitBounds()
