### ISSUE TITLE
@antv/l7-district 无法离线使用

### ISSUE THREAD

**Issue by HallGold** [antvis/L7#831]
下载了@antv/l7-district包之后 在内网环境 会默认请求https://gw.alipayobjects.com/os/bmw-prod/516b2703-d692-44e6-80dd-b3f5df0186e7.bin  这个地址，请问城市区域的地图必须联网使用吗？

**Comment by HallGold** [comment]
> 下载了@antv/l7-district包之后 在内网环境 会默认请求https://gw.alipayobjects.com/os/bmw-prod/516b2703-d692-44e6-80dd-b3f5df0186e7.bin 这个地址，请问城市区域的地图必须联网使用吗？  用的是市及地图

**Comment by lkxing** [comment]
请问这个问题解决了吗

**Comment by HallGold** [comment]
> 问这个问题解决了吗

别人都不理你，我改用echarts的地图了

**Comment by 2912401452** [comment]
支持配置数据源 https://github.com/antvis/L7-boundary
import { setDataConfig } from '@antv/l7-district';
setDataConfig({
  country: {
    CHN: {
      1: {
        // 设置省级地图
        fill: {
          type: 'pbf', // 支持pbf 和 geojson  pbf 进行了数据压缩，减少数据量
          url:
            'https://gw.alipayobjects.com/os/bmw-prod/47af6305-062e-454f-9e8a-55e0808b2b7a.bin',
        },
      },
    },
  },
});

**Comment by 2912401452** [comment]
替换资源地址
