### ISSUE TITLE
TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by jerryyyq** [antvis/L7#836]
* **L7 Version**:  2.5.45
* **Platform**:  react  17.0.1
* **Mini Showcase(like screenshots)**:    
* **CodePen Link**:

代码：
```js
import { WorldLayer } from '@antv/l7-district';
import { MapboxScene } from '@antv/l7-react';

                            <MapboxScene option={{logoVisible: false}} map={{
                                style: 'light',
                                center: [112, 20],
                                token: '',
                            }}>
                                <WorldLayer key={'2'} data={[]} fill={{color:{
                                        field: 'NAME_CHN',
                                        values: ['#feedde','#fdd0a2','#fdae6b','#fd8d3c','#e6550d','#a63603']
                                    }}} stroke={'#ccc'} label={{
                                        enable: true,
                                        textAllowOverlap: false,
                                        field: 'NAME_CHN'
                                    }} popup={{
                                        enable: false,
                                        Html: props => {
                                            return `<span>${props.NAME_CHN}</span>`;
                                        }
                                    }}
                                />
                            </MapboxScene>
```

错误栈：
`
TypeError: Cannot call a class as a function
_classCallCheck
node_modules/@antv/l7-district/es/layer/world.js:25
  22 | 
  23 | function _arrayWithHoles(arr) { if (Array.isArray(arr)) return arr; }
  24 | 
> 25 | function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
  26 | 
  27 | function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }
  28 | 
View compiled
WorldLayer
node_modules/@antv/l7-district/es/layer/world.js:59
  56 | 
  57 | var option = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
  58 | 
> 59 | _classCallCheck(this, WorldLayer);
     | ^  60 | 
  61 | _this = _super.call(this, scene, option);
  62 | 
View compiled
renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js:14985
  14982 |   }
  14983 | }
  14984 | 
> 14985 | var children = Component(props, secondArg); // Check if there was a render phase update
        | ^  14986 | 
  14987 | if (didScheduleRenderPhaseUpdateDuringThisPass) {
  14988 |   // Keep rendering in a loop for as long as render phase updates continue to
View compiled
mountIndeterminateComponent
node_modules/react-dom/cjs/react-dom.development.js:17811
  17808 | 
  17809 |   setIsRendering(true);
  17810 |   ReactCurrentOwner$1.current = workInProgress;
> 17811 |   value = renderWithHooks(null, workInProgress, Component, props, context, renderLanes);
        | ^  17812 |   setIsRendering(false);
  17813 | } // React DevTools reads this flag.
  17814 | 
View compiled
beginWork
node_modules/react-dom/cjs/react-dom.development.js:19049
  19046 | switch (workInProgress.tag) {
  19047 |   case IndeterminateComponent:
  19048 |     {
> 19049 |       return mountIndeterminateComponent(current, workInProgress, workInProgress.type, renderLanes);
        | ^  19050 |     }
  19051 | 
  19052 |   case LazyComponent:
View compiled
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js:3945
  3942 | function callCallback() {
  3943 |   didCall = true;
  3944 |   restoreAfterDispatch();
> 3945 |   func.apply(context, funcArgs);
       | ^  3946 |   didError = false;
  3947 | } // Create a global error event handler. We use this to capture the value
  3948 | // that was thrown. It's possible that this error handler will fire more
View compiled
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:3994
  3991 | // errors, it will trigger our global error handler.
  3992 | 
  3993 | evt.initEvent(evtType, false, false);
> 3994 | fakeNode.dispatchEvent(evt);
       | ^  3995 | 
  3996 | if (windowEventDescriptor) {
  3997 |   Object.defineProperty(window, 'event', windowEventDescriptor);
View compiled
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:4056
  4053 | function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {
  4054 |   hasError = false;
  4055 |   caughtError = null;
> 4056 |   invokeGuardedCallbackImpl$1.apply(reporter, arguments);
  4057 | }
  4058 | /**
  4059 |  * Same as invokeGuardedCallback, but instead of returning an error, it stores
View compiled
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js:23964
  23961 | } // Run beginWork again.
  23962 | 
  23963 | 
> 23964 | invokeGuardedCallback(null, beginWork, null, current, unitOfWork, lanes);
        | ^  23965 | 
  23966 | if (hasCaughtError()) {
  23967 |   var replayError = clearCaughtError(); // `invokeGuardedCallback` sometimes sets an expando `_suppressLogging`.
View compiled
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js:22776
  22773 | 
  22774 | if ( (unitOfWork.mode & ProfileMode) !== NoMode) {
  22775 |   startProfilerTimer(unitOfWork);
> 22776 |   next = beginWork$1(current, unitOfWork, subtreeRenderLanes);
        | ^  22777 |   stopProfilerTimerIfRunningAndRecordDelta(unitOfWork, true);
  22778 | } else {
  22779 |   next = beginWork$1(current, unitOfWork, subtreeRenderLanes);
View compiled
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js:22707
  22704 | function workLoopSync() {
  22705 |   // Already timed out, so perform work without checking if we need to yield.
  22706 |   while (workInProgress !== null) {
> 22707 |     performUnitOfWork(workInProgress);
  22708 |   }
  22709 | }
  22710 | 
View compiled
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js:22670
  22667 | 
  22668 | do {
  22669 |   try {
> 22670 |     workLoopSync();
        | ^  22671 |     break;
  22672 |   } catch (thrownValue) {
  22673 |     handleError(root, thrownValue);
View compiled
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js:22293
  22290 |   }
  22291 | } else {
  22292 |   lanes = getNextLanes(root, NoLanes);
> 22293 |   exitStatus = renderRootSync(root, lanes);
        | ^  22294 | }
  22295 | 
  22296 | if (root.tag !== LegacyRoot && exitStatus === RootErrored) {
View compiled
(anonymous function)
node_modules/react-dom/cjs/react-dom.development.js:11327
  11324 |     var callback = _queue[i];
  11325 | 
  11326 |     do {
> 11327 |       callback = callback(_isSync2);
        | ^  11328 |     } while (callback !== null);
  11329 |   }
  11330 | });
View compiled
unstable_runWithPriority
node_modules/scheduler/cjs/scheduler.development.js:646
  643 | currentPriorityLevel = priorityLevel;
  644 | 
  645 | try {
> 646 |   return eventHandler();
      | ^  647 | } finally {
  648 |   currentPriorityLevel = previousPriorityLevel;
  649 | }
View compiled
runWithPriority$1
node_modules/react-dom/cjs/react-dom.development.js:11276
  11273 | 
  11274 | function runWithPriority$1(reactPriorityLevel, fn) {
  11275 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);
> 11276 |   return Scheduler_runWithPriority(priorityLevel, fn);
  11277 | }
  11278 | function scheduleCallback(reactPriorityLevel, callback, options) {
  11279 |   var priorityLevel = reactPriorityToSchedulerPriority(reactPriorityLevel);
View compiled
flushSyncCallbackQueueImpl
node_modules/react-dom/cjs/react-dom.development.js:11322
  11319 | try {
  11320 |   var _isSync2 = true;
  11321 |   var _queue = syncQueue;
> 11322 |   runWithPriority$1(ImmediatePriority$1, function () {
        | ^  11323 |     for (; i < _queue.length; i++) {
  11324 |       var callback = _queue[i];
  11325 | 
View compiled
flushSyncCallbackQueue
node_modules/react-dom/cjs/react-dom.development.js:11309
  11306 |     Scheduler_cancelCallback(node);
  11307 |   }
  11308 | 
> 11309 |   flushSyncCallbackQueueImpl();
  11310 | }
  11311 | 
  11312 | function flushSyncCallbackQueueImpl() {
View compiled
scheduleUpdateOnFiber
node_modules/react-dom/cjs/react-dom.development.js:21893
  21890 |       // without immediately flushing it. We only do this for user-initiated
  21891 |       // updates, to preserve historical behavior of legacy mode.
  21892 |       resetRenderTimer();
> 21893 |       flushSyncCallbackQueue();
        | ^  21894 |     }
  21895 |   }
  21896 | } else {
View compiled
dispatchAction
node_modules/react-dom/cjs/react-dom.development.js:16139
  16136 |       }
  16137 |     }
  16138 | 
> 16139 |     scheduleUpdateOnFiber(fiber, lane, eventTime);
  16140 |   }
  16141 | }
  16142 | 
View compiled
Scene.<anonymous>
node_modules/@antv/l7-react/es/component/MapScene/MapboxScene.js:46
  43 |   map: new Mapbox(map)
  44 | }));
  45 | sceneInstance.on('loaded', function () {
> 46 |   setScene(sceneInstance);
     | ^  47 | 
  48 |   if (onSceneLoaded) {
  49 |     onSceneLoaded(sceneInstance);
View compiled
Scene.emit
node_modules/eventemitter3/index.js:180
  177 | if (listeners.once) this.removeListener(event, listeners.fn, undefined, true);
  178 | 
  179 | switch (len) {
> 180 |   case 1: return listeners.fn.call(listeners.context), true;
      | ^  181 |   case 2: return listeners.fn.call(listeners.context, a1), true;
  182 |   case 3: return listeners.fn.call(listeners.context, a1, a2), true;
  183 |   case 4: return listeners.fn.call(listeners.context, a1, a2, a3), true;
View compiled
Scene._callee5$
src/services/scene/SceneService.ts:323
  320 |   this.layerService.initLayers();
  321 |   this.controlService.addControls();
  322 |   this.loaded = true;
> 323 |   this.emit('loaded');
      | ^  324 |   this.inited = true;
  325 | }
  326 | 
View compiled
`

**Comment by 2912401452** [comment]
用错了
[https://codesandbox.io/s/yngez?file=/App.jsx](url)
![image](https://user-images.githubusercontent.com/42212176/143520769-010d51f8-7443-41e0-a8b0-da6818b4694f.png)
