### ISSUE TITLE
地图无法跟随父元素容器大小进行自适应适配

### ISSUE THREAD

**Issue by weishisi** [antvis/L7#849]
## 版本信息
    "@antv/l7": "^2.5.54",
    "@antv/l7-district": "^2.3.11",
    "@antv/l7-maps": "^2.5.54",
    "@antv/l7-react": "^2.3.6",
## 问题
  使用 AMapScene react组件 + CountryLayer构造函数开发中国地图。Amapscene设置初始 zoom 值，当设置的地图的父元素div 缩小后，中国地图不会随着父元素自适应缩小，会被容器遮盖，显示不全。只能通过鼠标滚轮修改 zoom 值实现适配。

## 目的
中国地图 countrylayer 可以随着父元素的大小进行自适应放大缩小。

## 复现代码
![image](https://user-images.githubusercontent.com/34361947/143188071-d505b943-deb2-4cab-9690-934a5655fdd3.png)

 
![image](https://user-images.githubusercontent.com/34361947/143189091-ffa66c8d-7c58-4bf1-9dc7-657b6714073d.png)

**Comment by 2912401452** [comment]
layer 图层存在 fitBounds 方法，在修改容器的大小的时候可以配合使用
[https://l7.antv.vision/zh/docs/api/layer/layer#fitbounds](url)
