### ISSUE TITLE
修改中心经纬度，地图并不适配

### ISSUE THREAD

**Issue by jerryyyq** [antvis/L7#852]
* **L7 Version**: 2.5.45
* **Platform**: react 17.0.1
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:  https://codesandbox.io/s/yngez?file=/App.jsx

 const scene = new Scene({
      id: 'world',
      map: new Mapbox({
        center: [116.2825, 69.9],

修改了这个中心点坐标无效，地图并不会将这个坐标移动到显示区域的中心。

**Comment by 2912401452** [comment]
你不是你的地图层级太小了

**Comment by 2912401452** [comment]
![image](https://user-images.githubusercontent.com/42212176/143538217-a393c311-1780-4c5e-b304-f9b13b8f9b83.png)
这些问题到群里问吧
