### ISSUE TITLE
线图层绑定图片纹理，动画移动过程中会被压缩大小，需要不被压缩大小，是否有解决方案？

### ISSUE THREAD

**Issue by youpinyao** [antvis/L7#856]
https://l7.antv.vision/zh/docs/api/layer/layer#为图层绑定纹理

// 首先在全局加载图片资源
scene.addImage(
  'plane',
  'https://gw.alipayobjects.com/zos/bmw-prod/0ca1668e-38c2-4010-8568-b57cb33839b9.svg',
);

const layer = new LineLayer({
  blend: 'normal',
})
  .source(data, {
    parser: {
      type: 'json',
      x: 'lng1',
      y: 'lat1',
      x1: 'lng2',
      y1: 'lat2',
    },
  })
  .size(25)
  .shape('arc')
  .texture('plane') // 为图层绑定纹理
  .color('#8C1EB2')
  .style({
    lineTexture: true, // 开启线的贴图功能
    iconStep: 30, // 设置贴图纹理的间距
    textureBlend: 'replace', // 设置纹理混合方式，默认值为 normal，可选值有 normal/replace 两种
  });

**Comment by 2912401452** [comment]
目前线图层的纹理动画还未优化

**Comment by 2912401452** [comment]
后续会进行优化

**Comment by 2912401452** [comment]
线图层的纹理动画以及在 2.6.3 版本优化，请更新版本
