### ISSUE TITLE
希望可以添加后期发光特效和高斯模糊

### ISSUE THREAD

**Issue by jinxiangqiang** [antvis/L7#861]
https://lbsyun.baidu.com/solutions/mapvdata
百度GL中的BloomEffect、BrightEffect、SparkLayer、WallTripLayer，地图的边缘能局部高斯模糊等效果，提升科技感

**Comment by 2912401452** [comment]
后期特效的添加已经在计划中，会尽快开发上线

**Comment by 2912401452** [comment]
目前 L7 已经支持 后处理流程
https://github.com/antvis/L7/blob/master/stories/MultiPassRenderer/components/Bloom.tsx
关于 bloom 的写法可以参考这个demo
