### ISSUE TITLE
BUG: 图层触发的事件跟图层设置的zIndex无关，只跟插入图层先后顺序有关。

### ISSUE THREAD

**Issue by Viin-zx** [antvis/L7#863]
复现demo地址： https://github.com/Viin-zx/bug-demo

前端框架： vue3+vue-cli
高德版本： v2
l7版本：2.5.57

![image](https://user-images.githubusercontent.com/19523605/144778486-703c666b-07ea-44b0-b194-90e96c83f22c.png)

有多个图层元素重叠的情况，想触发图层的事件，始终只会触发后插入scene的layer事件，即使前面插入的图层zIndex等级更高。

**Comment by 2912401452** [comment]
感谢提出问题，会尽快修复

**Comment by 2912401452** [comment]
已经在 2.6.4 版本修复

**Comment by Viin-zx** [comment]
好的，多谢。

**Comment by Viin-zx** [comment]
@2912401452 升级到2.6.4后图层 contextmenu 事件没用了。。。还是那个demo，麻烦看下。

**Comment by 2912401452** [comment]
是不是没有初始化完成就注册监听了，我刚试了试没有问题
`    scene.on('loaded', () => {  
      scene.addLayer(linelayer);  
      scene.addLayer(layer);  
      scene.on('contextmenu', () => {console.log('contextmenu')})  
    });`

**Comment by Viin-zx** [comment]
@2912401452  
![image](https://user-images.githubusercontent.com/19523605/144957623-958b172a-05a6-4301-a0fc-7e1b37472ae5.png)
没有哦，我更新了下demo，是在loaded中执行的这个方法，所有click事件都有用，contextmenu没用。请确认下node_modules中l7版本是否为2.6.4

**Comment by Viin-zx** [comment]
@2912401452 请问下这个问题确认了么。

**Comment by Viin-zx** [comment]
@2912401452 请问下这个问题确认了么。

**Comment by 2912401452** [comment]
![image](https://user-images.githubusercontent.com/42212176/161364307-6357b9aa-eeab-4e3f-9f2f-8c66db46fede.png)

**Comment by 2912401452** [comment]
换成新版本看看
