### ISSUE TITLE
BUG：图层contextmenu事件无效。

### ISSUE THREAD

**Issue by Viin-zx** [antvis/L7#874]
复现demo地址： https://github.com/Viin-zx/bug-demo

前端框架： vue3+vue-cli
高德版本： v2
l7版本：2.6.4

所有click事件都有用，contextmenu没用。

![image](https://user-images.githubusercontent.com/19523605/145530762-43f8a4cb-e3f8-47a6-83c5-7f9acd6a73f6.png)

**Comment by 2912401452** [comment]
感谢提出问题，会尽快修复！

**Comment by 2912401452** [comment]
问题已经在 2.6.16 版本修复
