### ISSUE TITLE
react 组件如何实现居中偏移

### ISSUE THREAD

**Issue by zhugeliange** [antvis/L7#876]
如题：需求是按照指定位置居中，而不是默认的屏幕中间居中。且随着窗口大小缩放，居中位置始终不变。
例如：https://docs.mapbox.com/mapbox-gl-js/example/offset-vanishing-point-with-padding
实际上我想要的就是某个点基于右半边60%屏幕居中，但是地图内容是基于100%屏幕的
🙏

**Comment by 2912401452** [comment]
可以使用 setCenter 方法，传入   padding 参数，相关使用 demo 后续会在官网补充
  public setCenter(lnglat: [number, number], options?: ICameraOptions): void {
    if (options?.padding) {
      const padding = toPaddingOptions(options.padding);
      const px = this.lngLatToPixel(lnglat);
      const offsetPx = [
        (padding.right - padding.left) / 2,
        (padding.bottom - padding.top) / 2,
      ];
      const newCenter = this.pixelToLngLat([
        px.x + offsetPx[0],
        px.y + offsetPx[1],
      ]);
      this.map.setCenter([newCenter.lng, newCenter.lat]);
    } else {
      this.map.setCenter(lnglat);
    }
  }

**Comment by 2912401452** [comment]
可以参考这个案例
https://l7.antv.vision/zh/examples/point/bubble#point
