### ISSUE TITLE
ant 钻取地图可以实现3d效果吗 就是稍微倾斜点有点立体的

### ISSUE THREAD

**Issue by zhangle1** [antvis/L7#880]

**Comment by liuvigongzuoshi** [comment]
@zhangle1 

L7Plot 的行政区域图下钻目前不支持 3D 效果，已提上[日程 ](https://github.com/antvis/L7Plot/projects/1#card-74564324)

https://l7plot.antv.vision/zh/examples/choropleth/drill#order-drill
