### ISSUE TITLE
图层zIndex属性，只是图层的层级发生改变，事件无法随着图层改变？如何解决呢

### ISSUE THREAD

**Issue by 909559792** [antvis/L7#885]
图层zIndex属性，只是图层的层级发生改变，事件无法随着图层改变？如何解决呢

**Comment by 2912401452** [comment]
zIndex 只是改变图层的绘制顺序，和事件的触发逻辑无关
事件的触发只和实际选择的图层有关，以鼠标事件为例，底层以鼠标落点拾取到的像素值相关
