### ISSUE TITLE
生产环境报错：No matching bindings found for serviceIdentifier: Symbol(ILayerPlugin)

### ISSUE THREAD

**Issue by zhxqc** [antvis/L7#895]
"@antv/l7": "2.6.24",
"@antv/l7-district": "2.3.12",
"@antv/l7-maps": "2.6.24",
"vue": "3.2.26",
"vite": "2.5.10",

使用vite官方推荐ssr框架 https://github.com/vitejs/vite/tree/main/packages/playground/ssr-vue

SSR项目，引入语法如下
![image](https://user-images.githubusercontent.com/35363368/147217615-43f6e31c-6eaa-49f1-a13a-ecd01e7525a6.png)

本地调试正常，生产环境报错
![image](https://user-images.githubusercontent.com/35363368/147218032-40670407-0ce9-413f-a8f5-8409d1844e3d.png)

**Comment by 2912401452** [comment]
L7 暂时不支持 ssr
