### ISSUE TITLE
Scene.off 移除事件监听不生效

### ISSUE THREAD

**Issue by junpengc** [antvis/L7#897]
* **L7 Version**: v2.6.18
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

Scene.off 移除事件监听不生效

**Comment by 2912401452** [comment]
可以提供 demo 吗？

**Comment by junpengc** [comment]
const onClick = console.log

scene.on('click',onClick)
scene.off('click',onClick)

就最简单的用例，只要注册了就删不掉 ;(

**Comment by 2912401452** [comment]
https://codesandbox.io/s/83l1w?file=/index.js
测试中是生效的，你看看是不是错了
