### ISSUE TITLE
希望提供多种南海诸岛的显示方式。

### ISSUE THREAD

**Issue by compasss** [antvis/L7#905]
现在南海都是显示在下方，没法调整。希望提供配置调整南海的显示位置。或者支持自己传入geojson数据。

**Comment by liuvigongzuoshi** [comment]
https://l7plot.antv.vision/zh/examples/gallery#category-%E8%A1%8C%E6%94%BF%E5%8C%BA%E5%9F%9F

https://l7plot.antv.vision/zh/docs/api/plots/choropleth

@compasss
