### ISSUE TITLE
文档麻烦不完整，麻烦补全下呢

### ISSUE THREAD

**Issue by zhounewz** [antvis/L7#940]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

文件位置： dev-docs/PixelPickingEngine.md
代码行数： 117
![image](https://user-images.githubusercontent.com/16400882/149754332-3bc7baa9-8270-4669-ac16-83104b507dd5.png)

**Comment by 2912401452** [comment]
你好，这一块确实缺失了，请问你是想要做什么呢？
