### ISSUE TITLE
地图示例未包含钓鱼岛部分

### ISSUE THREAD

**Issue by iota9star** [antvis/L7#948]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

详见最新图表示例

**Comment by susiwen8** [comment]
请问是哪一个示例

**Comment by iota9star** [comment]
![image](https://user-images.githubusercontent.com/21272154/150932549-3023ca29-e182-4ece-a7f0-fb3ab63a4129.png)

世界地图中国

**Comment by susiwen8** [comment]
谢谢反馈，我们替换下数据

**Comment by lzxue** [comment]
数据被简化掉了

**Comment by iota9star** [comment]
@lzxue 那算问题吗

**Comment by lzxue** [comment]
> @lzxue 那算问题吗

算，马上更新一下数据

**Comment by iota9star** [comment]
好的

**Comment by 2912401452** [comment]
官网数据已经更新，感谢提出问题！
