### ISSUE TITLE
PointLayer下开启cluster聚合 配置  clusterOptions 聚合失效

### ISSUE THREAD

**Issue by tagore-cai** [antvis/L7#949]
https://l7.antv.vision/zh/examples/point/cluster#cluster2
添加配置  clusterOptions: { maxZoom: 12 }
![image](https://user-images.githubusercontent.com/21003678/150937963-d43eb028-1188-4515-8c4c-e9c3b5626ad7.png)

`import { Scene, PointLayer, Source } from '@antv/l7';
import { GaodeMap } from '@antv/l7-maps';

const scene = new Scene({
  id: 'map',
  map: new GaodeMap({
    center: [ 120.19382669582967, 30.258134 ],
    pitch: 0,
    style: 'dark',
    zoom: 3
  })
});
scene.on('loaded', () => {
  fetch('https://gw.alipayobjects.com/os/bmw-prod/87e40417-a5da-4fdb-8313-c796ea15f982.csv')
    .then(res => res.text())
    .then(data => {
      const dataSource = new Source(data, {
        parser: {
          type: 'csv',
          x: 'lng',
          y: 'lat'

        },
        cluster: true,
        clusterOptions: { maxZoom: 12 }
      });
      const pointLayer = new PointLayer({
        autoFit: true
      })
        .source(dataSource)
        .shape('circle')
        .scale('point_count', {
          type: 'quantile'
        })
        .size('point_count', [ 5, 10, 15, 20, 25 ])
        .active(true)
        .color('rgb(73,167,86)')
        .style({
          opacity: 1,
          strokeWidth: 1,
          stroke: '#fff'
        });

      // 聚合图标注
      const pointLayerText = new PointLayer({
        autoFit: false
      })
        .source(dataSource)
        .shape('point_count', 'text')
        .size(15)
        .active(true)
        .color('#fff')
        .style({
          opacity: 1,
          strokeWidth: 0,
          stroke: '#fff'

        });

      scene.addLayer(pointLayer);
      scene.addLayer(pointLayerText);
    });
});
`

**Comment by tagore-cai** [comment]
![image](https://user-images.githubusercontent.com/21003678/150943848-c536839c-4d99-4a6f-9e2d-89b500cf626d.png)

**Comment by lzxue** [comment]
> ![image](https://user-images.githubusercontent.com/21003678/150943848-c536839c-4d99-4a6f-9e2d-89b500cf626d.png)

应该是这里的问题，在看
