### ISSUE TITLE
官网示例点击就崩溃。

### ISSUE THREAD

**Issue by yhyddr** [antvis/L7#95]
**Platform**:
MacOS 
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/32089134/69687718-e355a580-10fe-11ea-9915-d389772524a3.png)

* **重现**:
https://l7.antv.vision/zh/examples/gallery/basic#normal

无法响应点击，重复刷新返回崩溃页面。

**Comment by lzxue** [comment]
这几个数据量有点大，可能导致卡死，针对这个demo我们优化一下。
