### ISSUE TITLE
请问怎么设置点图层中点密集后高亮的颜色？

### ISSUE THREAD

**Issue by javacoderxxp** [antvis/L7#96]
* **L7 Version**: 2.0.beta
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
点图层中点密集后高亮的颜色？
或者怎么取消高亮？统一纯色点渲染
enableHighlight: false,无效

**Comment by lzxue** [comment]
交互这块 功能文档再补充中，很快就上线

**Comment by lzxue** [comment]
你的意思是blend效果吧，这个只有shape为normal时有马上会开放配置项目

**Comment by lzxue** [comment]
https://l7.antv.vision/zh/docs/api/layer/layer/#blend 
layer blend 配置项
