### ISSUE TITLE
PolygonLayer color 如果设置颜色有透明，active设置的颜色 会自动继承 color中的透明的

### ISSUE THREAD

**Issue by chengchao1** [antvis/L7#961]
import { GaodeMap, Scene, LineLayer, PolygonLayer, Marker } from "@antv/l7";
................
![image](https://user-images.githubusercontent.com/13247228/153817003-b7ff6735-7aa7-4e61-a4f9-dd12cdfa4ec7.png)

鼠标hover时，显示的颜色不是纯红色，带有透明度

**Comment by 2912401452** [comment]
目前的计算逻辑是这样的

**Comment by chengchao1** [comment]
请问这个后续会改吗？我认为不能直接继承吧，如果直接继承hover/select 无法高亮显示选中区域。

**Comment by Yanhua67** [comment]
最近也遇到了这个需求。请后续出了解决方案吗
