### ISSUE TITLE
是否有关于MarkerLayer 如何配置clusterOption 的文档。

### ISSUE THREAD

**Issue by brave1126** [antvis/L7#969]
* **L7 Version**:2.7.12
* **Platform**: macos
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

是否有关于MarkerLayer 如何配置clusterOption 的文档。
项目需要聚合marker，在合适的zoom显示原始的marker。
<img width="700" alt="image" src="https://user-images.githubusercontent.com/34409806/154445620-3fbbc220-b4a5-430e-82a1-edaa27e73d3a.png">
官网提供的文档使用方式不是很明确。

**Comment by 2912401452** [comment]
相关文档后续会补充，感谢反馈

**Comment by 992572161** [comment]
请问这块文档更新了吗？刚好我也遇到了类似的需求

**Comment by lzxue** [comment]
可以 通过 minZoom,maxZoom 设置
