### ISSUE TITLE
vite打包报错

### ISSUE THREAD

**Issue by cshenger** [antvis/L7#973]
项目使用vite 和 l7 打包之后运行文件提示

> Cannot read properties of undefined (reading 'Graph')

![image](https://user-images.githubusercontent.com/5855865/154689260-215e4274-8140-4311-b61c-5d17ab55063f.png)
![image](https://user-images.githubusercontent.com/5855865/154689282-d7eb474a-46a8-413d-b2fa-0dac8a914582.png)
这个graphlib指的就是这个
![image](https://user-images.githubusercontent.com/5855865/154689312-80b7df13-fe61-4405-8ce4-96a292d20e62.png)
但是graphlib获取不到，所以后面的程序就报错了，想问下有没有大神碰到过这个问题，还望赐教，谢谢。

**Comment by lzxue** [comment]
这个好像不是L7内部引用,L7 vite问题可以搜一下 L7 issue
