### ISSUE TITLE
pointLayer可以修改方向吗？

### ISSUE THREAD

**Issue by GKLL** [antvis/L7#974]
可以提供pointLayer修改方向的方法吗？
需求是动态获取到的经纬度计算了方向，但是不能设置方向

**Comment by lzxue** [comment]
图标旋转？

**Comment by GKLL** [comment]
> 

是的，定义一个shape为image 的pointLayer，然后根据经纬度算出了旋转角度，但是设置不了这个点的旋转

**Comment by 2912401452** [comment]
已经列到计划中，后续会添加

**Comment by 2912401452** [comment]
已经支持了，请使用新版本的 L7，使用可以参考下面的 demo
[https://l7.antv.vision/zh/examples/point/image/#fillimage](url)
