### ISSUE TITLE
animate无法设置false取消动画

### ISSUE THREAD

**Issue by wanghongrui** [antvis/L7#975]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/13774829/154887609-11dbd8c2-81db-4529-b871-6fc183fe1d67.png)

* **CodePen Link**: https://codesandbox.io/s/pyjqj9?file=/index.js

animate方法没有效果

**Comment by 2912401452** [comment]
目前需要重新构建 pointLayer，不支持这样的写法

**Comment by wanghongrui** [comment]
后续有计划通过方法实现吗？之前有没有实现过，我记得之前我是用这种方式控制的，但最近客户反馈说有问题我才发现的

**Comment by 2912401452** [comment]
目前还没有计划
