### ISSUE TITLE
采用mapbox底图, 能否进行底图的切换

### ISSUE THREAD

**Issue by malinlin809** [antvis/L7#98]
L7 Version: 2.0.beta
Platform:
Mini Showcase(like screenshots):
CodePen Link:
请问采用mapbox作为底图, 能否实现底图的切换, 例如从mapbox的街道图切换至卫星图, 谢谢

**Comment by lzxue** [comment]
调用scene.setMapStyle 方法，等同于mapbox 的 setStyle方法

**Comment by lzxue** [comment]
https://l7.antv.vision/zh/docs/api/scene/#setmapstyle
